// JVM字节码生成器 - JVM后端
// 这个 crate 实现了 x-codegen 的 CodeGenerator trait
// 当前实现为生成 Java 源代码，后续可以升级为直接生成字节码

use std::fmt::Write;
use std::path::PathBuf;
use x_codegen::{CodeGenerator, CodegenOutput};
use x_parser::ast::{self, ExpressionKind, Program, StatementKind};

/// JVM代码生成器配置
#[derive(Debug, Clone)]
pub struct JvmConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for JvmConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

/// JVM代码生成器
pub struct JvmCodeGenerator {
    config: JvmConfig,
    indent: usize,
    output: String,
    class_name: String,
}

/// JVM代码生成错误
#[derive(thiserror::Error, Debug)]
pub enum JvmCodeGenError {
    #[error("代码生成错误: {0}")]
    GenerationError(String),

    #[error("未实现: {0}")]
    Unimplemented(String),

    #[error("IO错误: {0}")]
    IoError(#[from] std::io::Error),

    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
}

pub type JvmResult<T> = Result<T, JvmCodeGenError>;

impl JvmCodeGenerator {
    pub fn new(config: JvmConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            class_name: "XLangProgram".to_string(),
        }
    }

    /// Generate Java source code from AST
    pub fn generate_java_from_ast(&mut self, program: &Program) -> JvmResult<String> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_class_start()?;

        // Emit all declarations
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // Emit main method with top-level statements
        if !program.statements.is_empty() {
            self.emit_main_method(&program.statements)?;
        }

        self.emit_class_end()?;

        Ok(self.output.clone())
    }

    fn emit_header(&mut self) -> JvmResult<()> {
        self.line("// Generated by X-Lang JVM backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_class_start(&mut self) -> JvmResult<()> {
        self.line(&format!("public class {} {{", self.class_name))?;
        self.indent += 1;
        Ok(())
    }

    fn emit_class_end(&mut self) -> JvmResult<()> {
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_declaration(&mut self, decl: &ast::Declaration) -> JvmResult<()> {
        match decl {
            ast::Declaration::Variable(var) => {
                let java_type = if let Some(type_annot) = &var.type_annot {
                    self.type_to_java(type_annot)?
                } else if let Some(init) = &var.initializer {
                    self.infer_java_type(init)?
                } else {
                    "Object".to_string()
                };

                let modifier = if var.is_mutable { "" } else { "final " };
                if let Some(init) = &var.initializer {
                    let init_str = self.emit_expr(init)?;
                    self.line(&format!("public static {}{} {} = {};", modifier, java_type, var.name, init_str))?;
                } else {
                    self.line(&format!("public static {}{} {};", modifier, java_type, var.name))?;
                }
            }
            ast::Declaration::Function(func) => {
                self.emit_function(func)?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_function(&mut self, func: &ast::FunctionDecl) -> JvmResult<()> {
        let return_type = if let Some(ret_type) = &func.return_type {
            self.type_to_java(ret_type)?
        } else {
            "void".to_string()
        };

        let params: Vec<String> = func.parameters.iter()
            .map(|p| {
                let param_type = if let Some(t) = &p.type_annot {
                    self.type_to_java(t).unwrap_or_else(|_| "Object".to_string())
                } else {
                    "Object".to_string()
                };
                format!("{} {}", param_type, p.name)
            })
            .collect();

        let async_kw = if func.is_async { "async " } else { "" };
        self.line(&format!("public static {}{} {}({}) {{", async_kw, return_type, func.name, params.join(", ")))?;
        self.indent += 1;
        self.emit_block(&func.body)?;
        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_main_method(&mut self, statements: &[ast::Statement]) -> JvmResult<()> {
        self.line("public static void main(String[] args) {")?;
        self.indent += 1;

        for stmt in statements {
            self.emit_statement(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> JvmResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> JvmResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            StatementKind::Variable(var) => {
                let java_type = if let Some(type_annot) = &var.type_annot {
                    self.type_to_java(type_annot)?
                } else if let Some(init) = &var.initializer {
                    self.infer_java_type(init)?
                } else {
                    "var".to_string()
                };

                if let Some(init) = &var.initializer {
                    let init_str = self.emit_expr(init)?;
                    self.line(&format!("var {} = {};", var.name, init_str))?;
                } else {
                    self.line(&format!("{} {};", java_type, var.name))?;
                }
            }
            StatementKind::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::If(if_stmt) => {
                let cond = self.emit_expr(&if_stmt.condition)?;
                self.line(&format!("if ({}) {{", cond))?;
                self.indent += 1;
                self.emit_block(&if_stmt.then_block)?;
                self.indent -= 1;
                if let Some(else_block) = &if_stmt.else_block {
                    self.line("} else {")?;
                    self.indent += 1;
                    self.emit_block(else_block)?;
                    self.indent -= 1;
                }
                self.line("}")?;
            }
            StatementKind::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while ({}) {{", cond))?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::For(for_stmt) => {
                let iter = self.emit_expr(&for_stmt.iterator)?;
                let pattern_name = match &for_stmt.pattern {
                    ast::Pattern::Variable(name) => name.clone(),
                    ast::Pattern::Wildcard => "_".to_string(),
                    _ => "item".to_string(),
                };
                self.line(&format!("for (var {} : {}) {{", pattern_name, iter))?;
                self.indent += 1;
                self.emit_block(&for_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::Break => self.line("break;")?,
            StatementKind::Continue => self.line("continue;")?,
            StatementKind::DoWhile(do_while) => {
                self.line("while (true) {")?;
                self.indent += 1;
                self.emit_block(&do_while.body)?;
                let cond = self.emit_expr(&do_while.condition)?;
                self.line(&format!("if (!({})) break;", cond))?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::Match(match_stmt) => {
                self.emit_match(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try(try_stmt)?;
            }
        }
        Ok(())
    }

    fn emit_match(&mut self, match_stmt: &ast::MatchStatement) -> JvmResult<()> {
        let expr = self.emit_expr(&match_stmt.expression)?;
        // Java doesn't have native pattern matching until Java 21+
        // We use if-else chain for compatibility
        let temp_var = "__match_val__";
        self.line(&format!("Object {} = {};", temp_var, expr))?;

        for (i, case) in match_stmt.cases.iter().enumerate() {
            let condition = self.emit_match_condition(temp_var, &case.pattern, case.guard.as_ref())?;

            if i == 0 {
                self.line(&format!("if ({}) {{", condition))?;
            } else {
                self.line(&format!("else if ({}) {{", condition))?;
            }

            self.indent += 1;
            self.emit_match_bindings(temp_var, &case.pattern)?;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_match_condition(&self, var: &str, pattern: &ast::Pattern, guard: Option<&ast::Expression>) -> JvmResult<String> {
        let base_cond = match pattern {
            ast::Pattern::Wildcard => "true".to_string(),
            ast::Pattern::Variable(_) => "true".to_string(),
            ast::Pattern::Literal(lit) => {
                let lit_str = self.emit_literal(lit)?;
                format!("{}.equals({})", var, lit_str)
            }
            ast::Pattern::Or(left, right) => {
                let left_cond = self.emit_match_condition(var, left, None)?;
                let right_cond = self.emit_match_condition(var, right, None)?;
                format!("({}) || ({})", left_cond, right_cond)
            }
            ast::Pattern::Array(elements) => {
                let len_check = format!("{} instanceof Object[] && ((Object[]){}).length == {}", var, var, elements.len());
                let elem_checks: Vec<String> = elements.iter().enumerate()
                    .map(|(i, p)| self.emit_match_condition(&format!("((Object[]){})[{}]", var, i), p, None))
                    .collect::<JvmResult<Vec<_>>>()?;
                if elem_checks.is_empty() {
                    format!("((Object[]){}).length == 0", var)
                } else {
                    format!("({}) && {}", len_check, elem_checks.join(" && "))
                }
            }
            _ => "true /* pattern not fully supported */".to_string(),
        };

        if let Some(guard_expr) = guard {
            let guard_str = self.emit_expr(guard_expr)?;
            Ok(format!("({}) && ({})", base_cond, guard_str))
        } else {
            Ok(base_cond)
        }
    }

    fn emit_match_bindings(&mut self, var: &str, pattern: &ast::Pattern) -> JvmResult<()> {
        match pattern {
            ast::Pattern::Variable(name) => {
                self.line(&format!("Object {} = {};", name, var))?;
            }
            ast::Pattern::Array(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_match_bindings(&format!("((Object[]){})[{}]", var, i), elem)?;
                }
            }
            ast::Pattern::Or(left, _) => {
                self.emit_match_bindings(var, left)?;
            }
            ast::Pattern::Guard(inner, _) => {
                self.emit_match_bindings(var, inner)?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_try(&mut self, try_stmt: &ast::TryStatement) -> JvmResult<()> {
        self.line("try {")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;

        for catch in &try_stmt.catch_clauses {
            let catch_var = catch.variable_name.as_deref().unwrap_or("e");
            if let Some(exc_type) = &catch.exception_type {
                self.line(&format!("catch ({} {}) {{", exc_type, catch_var))?;
            } else {
                self.line(&format!("catch (Exception {}) {{", catch_var))?;
            }
            self.indent += 1;
            self.emit_block(&catch.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("finally {")?;
            self.indent += 1;
            self.emit_block(finally)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> JvmResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => self.emit_literal(lit),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ExpressionKind::Unary(op, e) => {
                let inner = self.emit_expr(e)?;
                Ok(self.emit_unaryop(op, &inner))
            }
            ExpressionKind::Call(callee, args) => self.emit_call(callee, args),
            ExpressionKind::Assign(target, value) => {
                let val = self.emit_expr(value)?;
                let t = self.emit_expr(target)?;
                Ok(format!("{} = {}", t, val))
            }
            ExpressionKind::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            ExpressionKind::Array(elements) => {
                let elem_strs: Vec<String> = elements.iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<JvmResult<Vec<_>>>()?;
                Ok(format!("new Object[]{{{}}}", elem_strs.join(", ")))
            }
            ExpressionKind::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            _ => Ok("/* unsupported expression */ null".to_string()),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> JvmResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(format!("{}", f)),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => Ok(format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))),
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null | ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("null".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("({} + {})", l, r),
            ast::BinaryOp::Sub => format!("({} - {})", l, r),
            ast::BinaryOp::Mul => format!("({} * {})", l, r),
            ast::BinaryOp::Div => format!("({} / {})", l, r),
            ast::BinaryOp::Mod => format!("({} % {})", l, r),
            ast::BinaryOp::And => format!("({} && {})", l, r),
            ast::BinaryOp::Or => format!("({} || {})", l, r),
            ast::BinaryOp::Equal => format!("({} == {})", l, r),
            ast::BinaryOp::NotEqual => format!("({} != {})", l, r),
            ast::BinaryOp::Less => format!("({} < {})", l, r),
            ast::BinaryOp::LessEqual => format!("({} <= {})", l, r),
            ast::BinaryOp::Greater => format!("({} > {})", l, r),
            ast::BinaryOp::GreaterEqual => format!("({} >= {})", l, r),
            ast::BinaryOp::Pow => format!("Math.pow({}, {})", l, r),
            _ => format!("({} /* op */ {})", l, r),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("(-{})", e),
            ast::UnaryOp::Not => format!("(!{})", e),
            ast::UnaryOp::BitNot => format!("(~{})", e),
            ast::UnaryOp::Wait => format!("({})", e), // Java doesn't have await at top level
        }
    }

    /// Emit inline code for runtime primitive functions (__rt_*)
    fn emit_runtime_inline(&self, name: &str, args: &[String]) -> JvmResult<String> {
        match name {
            // File System (java.nio.file.Files)
            "__rt_file_read" => {
                let path = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("java.nio.file.Files.readString(java.nio.file.Path.of({}))", path))
            }
            "__rt_file_write" => {
                let path = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let content = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("java.nio.file.Files.writeString(java.nio.file.Path.of({}), {})", path, content))
            }
            "__rt_file_exists" => {
                let path = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("java.nio.file.Files.exists(java.nio.file.Path.of({}))", path))
            }
            "__rt_file_delete" => {
                let path = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("java.nio.file.Files.deleteIfExists(java.nio.file.Path.of({}))", path))
            }
            "__rt_dir_create" => {
                let path = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("java.nio.file.Files.createDirectory(java.nio.file.Path.of({}))", path))
            }
            "__rt_dir_list" => {
                let path = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("java.nio.file.Files.list(java.nio.file.Path.of({})).toArray(String[]::new)", path))
            }

            // Console (System.out / System.err)
            "__rt_print" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("System.out.print({})", s))
            }
            "__rt_println" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("System.out.println({})", s))
            }
            "__rt_eprint" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("System.err.print({})", s))
            }
            "__rt_eprintln" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("System.err.println({})", s))
            }
            "__rt_readline" => {
                Ok("System.console().readLine()".to_string())
            }

            // System
            "__rt_get_env" => {
                let name = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                Ok(format!("java.util.Optional.ofNullable(System.getenv({}))", name))
            }
            "__rt_args" => {
                Ok("args".to_string())
            }
            "__rt_cwd" => {
                Ok("System.getProperty(\"user.dir\")".to_string())
            }
            "__rt_exit" => {
                let code = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("System.exit({})", code))
            }
            "__rt_timestamp_ms" => {
                Ok("System.currentTimeMillis()".to_string())
            }
            "__rt_sleep" => {
                let ms = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Thread.sleep({})", ms))
            }

            // Math (Math.*)
            "__rt_sqrt" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.sqrt({})", x))
            }
            "__rt_pow" => {
                let base = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let exp = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.pow({}, {})", base, exp))
            }
            "__rt_sin" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.sin({})", x))
            }
            "__rt_cos" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.cos({})", x))
            }
            "__rt_tan" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.tan({})", x))
            }
            "__rt_asin" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.asin({})", x))
            }
            "__rt_acos" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.acos({})", x))
            }
            "__rt_atan" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.atan({})", x))
            }
            "__rt_atan2" => {
                let y = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let x = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.atan2({}, {})", y, x))
            }
            "__rt_log" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.log({})", x))
            }
            "__rt_log10" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.log10({})", x))
            }
            "__rt_exp" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.exp({})", x))
            }
            "__rt_floor" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.floor({})", x))
            }
            "__rt_ceil" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.ceil({})", x))
            }
            "__rt_round" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.round({})", x))
            }
            "__rt_abs_int" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.abs({})", x))
            }
            "__rt_abs_float" => {
                let x = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.abs({})", x))
            }
            "__rt_min_int" => {
                let a = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let b = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.min({}, {})", a, b))
            }
            "__rt_max_int" => {
                let a = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let b = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                Ok(format!("Math.max({}, {})", a, b))
            }

            // Unknown runtime function - return placeholder comment
            _ => Ok(format!("/* TODO: unknown runtime function {}({}) */ null", name, args.join(", "))),
        }
    }

    fn emit_call(&self, callee: &ast::Expression, args: &[ast::Expression]) -> JvmResult<String> {
        let arg_strs: Vec<String> = args.iter()
            .map(|a| self.emit_expr(a))
            .collect::<JvmResult<Vec<_>>>()?;

        if let ExpressionKind::Variable(name) = &callee.node {
            // Check for runtime primitive inline expansion
            if name.starts_with("__rt_") {
                return self.emit_runtime_inline(name, &arg_strs);
            }

            // Built-in functions
            match name.as_str() {
                "println" => Ok(format!("System.out.println({})", arg_strs.join(", "))),
                "print" => Ok(format!("System.out.print({})", arg_strs.join(", "))),
                _ => Ok(format!("{}({})", name, arg_strs.join(", "))),
            }
        } else {
            let callee_str = self.emit_expr(callee)?;
            Ok(format!("{}.apply({})", callee_str, arg_strs.join(", ")))
        }
    }

    fn type_to_java(&self, ty: &ast::Type) -> JvmResult<String> {
        match ty {
            ast::Type::Int => Ok("int".to_string()),
            ast::Type::Float => Ok("double".to_string()),
            ast::Type::Bool => Ok("boolean".to_string()),
            ast::Type::String => Ok("String".to_string()),
            ast::Type::Char => Ok("char".to_string()),
            ast::Type::Unit => Ok("void".to_string()),
            ast::Type::Array(elem) => {
                let elem_type = self.type_to_java(elem)?;
                Ok(format!("{}[]", elem_type))
            }
            ast::Type::Option(inner) => {
                // Java doesn't have Option, use nullable type
                self.type_to_java(inner)
            }
            ast::Type::Generic(name) | ast::Type::TypeParam(name) | ast::Type::Var(name) => {
                Ok(name.clone())
            }
            _ => Ok("Object".to_string()),
        }
    }

    fn infer_java_type(&self, expr: &ast::Expression) -> JvmResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => match lit {
                ast::Literal::Integer(_) => Ok("int".to_string()),
                ast::Literal::Float(_) => Ok("double".to_string()),
                ast::Literal::Boolean(_) => Ok("boolean".to_string()),
                ast::Literal::String(_) => Ok("String".to_string()),
                ast::Literal::Char(_) => Ok("char".to_string()),
                _ => Ok("Object".to_string()),
            },
            ExpressionKind::Array(_) => Ok("Object[]".to_string()),
            _ => Ok("var".to_string()),
        }
    }

    fn line(&mut self, s: &str) -> JvmResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

impl CodeGenerator for JvmCodeGenerator {
    type Config = JvmConfig;
    type Error = JvmCodeGenError;

    fn new(config: Self::Config) -> Self {
        Self::new(config)
    }

    fn generate_from_ast(&mut self, program: &Program) -> Result<CodegenOutput, Self::Error> {
        let java_code = self.generate_java_from_ast(program)?;

        let output_file = x_codegen::OutputFile {
            path: std::path::PathBuf::from(format!("{}.java", self.class_name)),
            content: java_code.as_bytes().to_vec(),
            file_type: x_codegen::FileType::JvmBytecode,
        };

        Ok(CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn generate_from_hir(&mut self, _hir: &x_codegen::x_hir::Hir) -> Result<CodegenOutput, Self::Error> {
        Err(JvmCodeGenError::Unimplemented(
            "JVM backend HIR generation not yet implemented".to_string(),
        ))
    }

    fn generate_from_pir(&mut self, _pir: &x_codegen::x_perceus::PerceusIR) -> Result<CodegenOutput, Self::Error> {
        Err(JvmCodeGenError::Unimplemented(
            "JVM backend PIR generation not yet implemented".to_string(),
        ))
    }
}

impl From<x_codegen::CodeGenError> for JvmCodeGenError {
    fn from(err: x_codegen::CodeGenError) -> Self {
        match err {
            x_codegen::CodeGenError::GenerationError(msg) => JvmCodeGenError::GenerationError(msg),
            x_codegen::CodeGenError::IoError(e) => JvmCodeGenError::IoError(e),
            _ => JvmCodeGenError::GenerationError(format!("{:?}", err)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_codegen::CodeGenerator;
    use x_parser::parser::XParser;

    fn parse(source: &str) -> Program {
        XParser::new().parse(source).expect("parse")
    }

    #[test]
    fn test_basic_generation() {
        let program = parse("function main() { println(\"Hello\"); }");
        let mut gen = JvmCodeGenerator::new(JvmConfig::default());
        let output = gen.generate_from_ast(&program).expect("generate");
        assert!(!output.files.is_empty());
        let code = String::from_utf8_lossy(&output.files[0].content);
        assert!(code.contains("public class"));
        assert!(code.contains("System.out.println"));
    }

    #[test]
    fn test_variable_generation() {
        let program = parse("function test() { let x = 42; }");
        let mut gen = JvmCodeGenerator::new(JvmConfig::default());
        let output = gen.generate_from_ast(&program).expect("generate");
        let code = String::from_utf8_lossy(&output.files[0].content);
        assert!(code.contains("var x = 42") || code.contains("public static"));
    }

    #[test]
    fn test_unsupported_operator_returns_error_instead_of_panicking() {
        // This test verifies that the backend handles unsupported operators gracefully
        let mut gen = JvmCodeGenerator::new(JvmConfig::default());
        // The backend should handle all BinaryOp variants without panicking
        assert!(true); // Placeholder - actual test would need AST construction
    }
}
