// JavaScript/TypeScript生成器 - JS/TS后端
// 这个 crate 实现了 x-codegen 的 CodeGenerator trait

use std::fmt::Write;
use std::path::PathBuf;
use x_codegen::{CodeGenerator, CodegenOutput};
use x_parser::ast::{self, Program as AstProgram};

/// JavaScript/TypeScript代码生成器配置
#[derive(Debug, Clone)]
pub struct JavaScriptConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
    pub target_language: TargetLanguage,
}

impl Default for JavaScriptConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            target_language: TargetLanguage::JavaScript,
        }
    }
}

/// 目标语言类型
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum TargetLanguage {
    JavaScript,
    TypeScript,
}

/// JavaScript/TypeScript代码生成器
pub struct JavaScriptCodeGenerator {
    config: JavaScriptConfig,
    indent: usize,
    output: String,
}

impl JavaScriptCodeGenerator {
    pub fn new(config: JavaScriptConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    /// 从AST生成JavaScript代码
    pub fn generate_js_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> Result<String, JavaScriptCodeGenError> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;

        // 首先处理所有顶层声明
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // 然后处理顶层语句
        if !program.statements.is_empty() {
            self.line("// 顶层代码")?;
            self.line("(function() {")?;
            self.indent += 1;
            for stmt in &program.statements {
                self.emit_statement(stmt)?;
            }
            self.indent -= 1;
            self.line("})();")?;
        }

        Ok(self.output.clone())
    }

    fn emit_header(&mut self) -> Result<(), JavaScriptCodeGenError> {
        self.line("// Generated by X-Lang JavaScript backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_declaration(&mut self, decl: &ast::Declaration) -> Result<(), JavaScriptCodeGenError> {
        match decl {
            ast::Declaration::Variable(v) => {
                self.emit_var_decl(v)?;
                self.line("")?;
            }
            ast::Declaration::Function(f) => {
                self.emit_function(f)?;
                self.line("")?;
            }
            ast::Declaration::Class(c) => {
                self.emit_class(c)?;
                self.line("")?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_var_decl(&mut self, v: &ast::VariableDecl) -> Result<(), JavaScriptCodeGenError> {
        let keyword = if v.is_mutable { "let" } else { "const" };
        let init = if let Some(expr) = &v.initializer {
            format!(" = {}", self.emit_expr(expr)?)
        } else {
            String::new()
        };
        self.line(&format!("{} {}{};", keyword, v.name, init))?;
        Ok(())
    }

    fn emit_function(&mut self, f: &ast::FunctionDecl) -> Result<(), JavaScriptCodeGenError> {
        let params = f
            .parameters
            .iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");

        if f.is_async {
            self.line(&format!("async function {}({}) {{", f.name, params))?;
        } else {
            self.line(&format!("function {}({}) {{", f.name, params))?;
        }
        self.indent += 1;
        self.emit_block(&f.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_class(&mut self, c: &ast::ClassDecl) -> Result<(), JavaScriptCodeGenError> {
        if let Some(ext) = &c.extends {
            self.line(&format!("class {} extends {} {{", c.name, ext))?;
        } else {
            self.line(&format!("class {} {{", c.name))?;
        }
        self.indent += 1;

        for member in &c.members {
            match member {
                ast::ClassMember::Field(f) => {
                    let init = if let Some(expr) = &f.initializer {
                        format!(" = {}", self.emit_expr(expr)?)
                    } else {
                        String::new()
                    };
                    self.line(&format!("{}{};", f.name, init))?;
                }
                ast::ClassMember::Method(m) => {
                    let params = m
                        .parameters
                        .iter()
                        .map(|p| p.name.clone())
                        .collect::<Vec<_>>()
                        .join(", ");
                    if m.is_async {
                        self.line(&format!("async {}({}) {{", m.name, params))?;
                    } else {
                        self.line(&format!("{}({}) {{", m.name, params))?;
                    }
                    self.indent += 1;
                    self.emit_block(&m.body)?;
                    self.indent -= 1;
                    self.line("}")?;
                }
                ast::ClassMember::Constructor(ctor) => {
                    let params = ctor
                        .parameters
                        .iter()
                        .map(|p| p.name.clone())
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.line(&format!("constructor({}) {{", params))?;
                    self.indent += 1;
                    self.emit_block(&ctor.body)?;
                    self.indent -= 1;
                    self.line("}")?;
                }
            }
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> Result<(), JavaScriptCodeGenError> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> Result<(), JavaScriptCodeGenError> {
        match stmt {
            ast::Statement::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            ast::Statement::Variable(v) => {
                self.emit_var_decl(v)?;
            }
            ast::Statement::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            ast::Statement::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            ast::Statement::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while ({}) {{", cond))?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            ast::Statement::For(for_stmt) => {
                let iter = self.emit_expr(&for_stmt.iterator)?;
                let pat = self.emit_pattern(&for_stmt.pattern)?;
                self.line(&format!("for (const {} of {}) {{", pat, iter))?;
                self.indent += 1;
                self.emit_block(&for_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> Result<(), JavaScriptCodeGenError> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if ({}) {{", cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;
        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }
        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> Result<String, JavaScriptCodeGenError> {
        match expr {
            ast::Expression::Literal(lit) => self.emit_literal(lit),
            ast::Expression::Variable(name) => Ok(name.clone()),
            ast::Expression::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ast::Expression::Unary(op, expr) => {
                let e = self.emit_expr(expr)?;
                Ok(self.emit_unaryop(op, &e))
            }
            ast::Expression::Call(callee, args) => self.emit_call(callee, args),
            ast::Expression::Assign(target, value) => self.emit_assign(target, value),
            ast::Expression::Array(elements) => self.emit_array_literal(elements),
            ast::Expression::Dictionary(pairs) => self.emit_dict_literal(pairs),
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            ast::Expression::If(cond, then_e, else_e) => {
                let c = self.emit_expr(cond)?;
                let t = self.emit_expr(then_e)?;
                let e = self.emit_expr(else_e)?;
                Ok(format!("({} ? {} : {})", c, t, e))
            }
            ast::Expression::Lambda(params, _body) => {
                let param_str = params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                Ok(format!("({}) => {{ /* TODO */ }}", param_str))
            }
            ast::Expression::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            _ => Ok("/* unsupported expression */ null".to_string()),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> Result<String, JavaScriptCodeGenError> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(format!("{}", f)),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null => Ok("null".to_string()),
            ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("undefined".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("({} + {})", l, r),
            ast::BinaryOp::Sub => format!("({} - {})", l, r),
            ast::BinaryOp::Mul => format!("({} * {})", l, r),
            ast::BinaryOp::Div => format!("({} / {})", l, r),
            ast::BinaryOp::Mod => format!("({} % {})", l, r),
            ast::BinaryOp::Equal => format!("({} === {})", l, r),
            ast::BinaryOp::NotEqual => format!("({} !== {})", l, r),
            ast::BinaryOp::Less => format!("({} < {})", l, r),
            ast::BinaryOp::LessEqual => format!("({} <= {})", l, r),
            ast::BinaryOp::Greater => format!("({} > {})", l, r),
            ast::BinaryOp::GreaterEqual => format!("({} >= {})", l, r),
            ast::BinaryOp::And => format!("({} && {})", l, r),
            ast::BinaryOp::Or => format!("({} || {})", l, r),
            ast::BinaryOp::Pow => format!("Math.pow({}, {})", l, r),
            _ => format!("({} {} {})", l, "/* unsupported */", r),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("(-{})", e),
            ast::UnaryOp::Not => format!("(!{})", e),
            ast::UnaryOp::BitNot => format!("(~{})", e),
            ast::UnaryOp::Wait => format!("(await {})", e),
        }
    }

    fn emit_call(
        &self,
        callee: &ast::Expression,
        args: &[ast::Expression],
    ) -> Result<String, JavaScriptCodeGenError> {
        // 检查内置函数
        if let ast::Expression::Variable(name) = callee {
            let arg_strs: Vec<String> = args
                .iter()
                .map(|a| self.emit_expr(a))
                .collect::<Result<Vec<_>, _>>()?;
            return Ok(self.emit_builtin_or_call(name, &arg_strs));
        }
        let callee_str = self.emit_expr(callee)?;
        let arg_strs: Vec<String> = args
            .iter()
            .map(|a| self.emit_expr(a))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
    }

    fn emit_builtin_or_call(&self, name: &str, args: &[String]) -> String {
        match name {
            "print" | "println" => {
                if args.len() == 1 {
                    format!("console.log({})", args[0])
                } else {
                    "console.log()".to_string()
                }
            }
            "to_string" => format!("String({})", args.first().map(|s| s.as_str()).unwrap_or("")),
            "len" => format!("{}.length", args.first().map(|s| s.as_str()).unwrap_or("")),
            _ => format!("{}({})", name, args.join(", ")),
        }
    }

    fn emit_assign(
        &self,
        target: &ast::Expression,
        value: &ast::Expression,
    ) -> Result<String, JavaScriptCodeGenError> {
        let val = self.emit_expr(value)?;
        match target {
            ast::Expression::Variable(name) => Ok(format!("({} = {})", name, val)),
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("({}.{} = {})", o, field, val))
            }
            _ => {
                let t = self.emit_expr(target)?;
                Ok(format!("({} = {})", t, val))
            }
        }
    }

    fn emit_array_literal(
        &self,
        elements: &[ast::Expression],
    ) -> Result<String, JavaScriptCodeGenError> {
        let elem_strs: Vec<String> = elements
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(format!("[{}]", elem_strs.join(", ")))
    }

    fn emit_dict_literal(
        &self,
        pairs: &[(ast::Expression, ast::Expression)],
    ) -> Result<String, JavaScriptCodeGenError> {
        let mut parts = Vec::new();
        for (k, v) in pairs {
            let key_str = self.emit_expr(k)?;
            let val_str = self.emit_expr(v)?;
            parts.push(format!("{}: {}", key_str, val_str));
        }
        Ok(format!("{{{}}}", parts.join(", ")))
    }

    fn emit_pattern(&self, pat: &ast::Pattern) -> Result<String, JavaScriptCodeGenError> {
        match pat {
            ast::Pattern::Wildcard => Ok("_".to_string()),
            ast::Pattern::Variable(name) => Ok(name.clone()),
            ast::Pattern::Literal(lit) => self.emit_literal(lit),
            _ => Ok("/* pattern */".to_string()),
        }
    }

    fn line(&mut self, s: &str) -> Result<(), JavaScriptCodeGenError> {
        for _ in 0..self.indent {
            write!(self.output, "  ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

impl CodeGenerator for JavaScriptCodeGenerator {
    type Config = JavaScriptConfig;
    type Error = JavaScriptCodeGenError;

    fn new(config: Self::Config) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    fn generate_from_ast(&mut self, program: &AstProgram) -> Result<CodegenOutput, Self::Error> {
        let _js_code = self.generate_js_from_ast(program)?;
        Ok(CodegenOutput {
            files: vec![],
            dependencies: vec![],
        })
    }

    fn generate_from_hir(&mut self, _hir: &x_codegen::x_hir::Hir) -> Result<CodegenOutput, Self::Error> {
        Err(JavaScriptCodeGenError::Unimplemented(
            "JavaScript/TypeScript backend not yet implemented".to_string(),
        ))
    }

    fn generate_from_pir(&mut self, _pir: &x_codegen::x_perceus::PerceusIR) -> Result<CodegenOutput, Self::Error> {
        Err(JavaScriptCodeGenError::Unimplemented(
            "JavaScript/TypeScript backend not yet implemented".to_string(),
        ))
    }
}

/// JavaScript/TypeScript代码生成错误
#[derive(thiserror::Error, Debug)]
pub enum JavaScriptCodeGenError {
    #[error("代码生成错误: {0}")]
    GenerationError(String),

    #[error("未实现: {0}")]
    Unimplemented(String),

    #[error("IO错误: {0}")]
    IoError(#[from] std::io::Error),

    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
}

impl From<x_codegen::CodeGenError> for JavaScriptCodeGenError {
    fn from(err: x_codegen::CodeGenError) -> Self {
        match err {
            x_codegen::CodeGenError::GenerationError(msg) => {
                JavaScriptCodeGenError::GenerationError(msg)
            }
            x_codegen::CodeGenError::IoError(e) => JavaScriptCodeGenError::IoError(e),
            _ => JavaScriptCodeGenError::GenerationError(format!("{:?}", err)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_codegen::CodeGenerator;

    fn parse(source: &str) -> AstProgram {
        x_parser::parser::XParser::new()
            .parse(source)
            .expect("parse")
    }

    #[test]
    fn generate_empty_program_has_header() {
        let program = parse("");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let js = gen.generate_js_from_ast(&program).expect("generate");
        assert!(js.contains("Generated by X-Lang JavaScript backend"));
        assert!(js.contains("DO NOT EDIT"));
    }

    #[test]
    fn generate_function_emits_function() {
        let program = parse("function main() { println(\"hi\") }");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let js = gen.generate_js_from_ast(&program).expect("generate");
        assert!(js.contains("function main()"));
        assert!(js.contains("console.log"));
    }

    #[test]
    fn generate_variable_emits_const_or_let() {
        let program = parse("let x = 1;");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let js = gen.generate_js_from_ast(&program).expect("generate");
        assert!(js.contains("const x = 1") || js.contains("let x = 1"));
    }

    #[test]
    fn generate_from_ast_trait_returns_ok_with_files() {
        let program = parse("function f() {}");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let out = gen.generate_from_ast(&program).expect("generate_from_ast");
        assert!(out.files.is_empty());
    }

    #[test]
    fn generate_from_hir_returns_unimplemented() {
        use std::collections::HashMap;
        use x_codegen::x_hir::{Hir, HirTypeEnv};

        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let hir = Hir {
            module_name: "test".to_string(),
            declarations: vec![],
            statements: vec![],
            type_env: HirTypeEnv {
                variables: HashMap::new(),
                functions: HashMap::new(),
                types: HashMap::new(),
            },
        };
        let err = gen.generate_from_hir(&hir).expect_err("unimplemented");
        let msg = err.to_string();
        assert!(msg.contains("未实现") || msg.contains("Unimplemented") || msg.contains("not yet implemented"));
    }

    #[test]
    fn generate_from_pir_returns_unimplemented() {
        use x_codegen::x_perceus::{PerceusIR, ReuseAnalysis};

        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let pir = PerceusIR {
            functions: vec![],
            global_ops: vec![],
            reuse_analysis: ReuseAnalysis {
                reuse_pairs: vec![],
                estimated_savings: 0,
            },
        };
        let err = gen.generate_from_pir(&pir).expect_err("unimplemented");
        let msg = err.to_string();
        assert!(msg.contains("未实现") || msg.contains("not yet implemented"));
    }

    #[test]
    fn error_display_generation_error() {
        let e = JavaScriptCodeGenError::GenerationError("test".to_string());
        assert!(e.to_string().contains("代码生成错误"));
        assert!(e.to_string().contains("test"));
    }

    #[test]
    fn error_display_unimplemented() {
        let e = JavaScriptCodeGenError::Unimplemented("foo".to_string());
        assert!(e.to_string().contains("未实现"));
        assert!(e.to_string().contains("foo"));
    }
}
