// JavaScript/TypeScript生成器 - JS/TS后端
// 这个 crate 实现了 x-codegen 的 CodeGenerator trait

use std::fmt::Write;
use std::path::PathBuf;
use x_codegen::{CodeGenerator, CodegenOutput};
use x_parser::ast::{self, ExpressionKind, Program as AstProgram, StatementKind};

/// JavaScript/TypeScript代码生成器配置
#[derive(Debug, Clone)]
pub struct JavaScriptConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
    pub target_language: TargetLanguage,
}

impl Default for JavaScriptConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            target_language: TargetLanguage::JavaScript,
        }
    }
}

/// 目标语言类型
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum TargetLanguage {
    JavaScript,
    TypeScript,
}

/// JavaScript/TypeScript代码生成器
pub struct JavaScriptCodeGenerator {
    config: JavaScriptConfig,
    indent: usize,
    output: String,
}

impl JavaScriptCodeGenerator {
    pub fn new(config: JavaScriptConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    /// 从AST生成JavaScript代码
    pub fn generate_js_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> Result<String, JavaScriptCodeGenError> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;

        // 首先处理所有顶层声明
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // 然后处理顶层语句
        if !program.statements.is_empty() {
            self.line("// 顶层代码")?;
            self.line("(function() {")?;
            self.indent += 1;
            for stmt in &program.statements {
                self.emit_statement(stmt)?;
            }
            self.indent -= 1;
            self.line("})();")?;
        }

        Ok(self.output.clone())
    }

    fn emit_header(&mut self) -> Result<(), JavaScriptCodeGenError> {
        self.line("// Generated by X-Lang JavaScript backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_declaration(&mut self, decl: &ast::Declaration) -> Result<(), JavaScriptCodeGenError> {
        match decl {
            ast::Declaration::Variable(v) => {
                self.emit_var_decl(v)?;
                self.line("")?;
            }
            ast::Declaration::Function(f) => {
                self.emit_function(f)?;
                self.line("")?;
            }
            ast::Declaration::Class(c) => {
                self.emit_class(c)?;
                self.line("")?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_var_decl(&mut self, v: &ast::VariableDecl) -> Result<(), JavaScriptCodeGenError> {
        let keyword = if v.is_mutable { "let" } else { "const" };
        let init = if let Some(expr) = &v.initializer {
            format!(" = {}", self.emit_expr(expr)?)
        } else {
            String::new()
        };
        self.line(&format!("{} {}{};", keyword, v.name, init))?;
        Ok(())
    }

    fn emit_function(&mut self, f: &ast::FunctionDecl) -> Result<(), JavaScriptCodeGenError> {
        let params = f
            .parameters
            .iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");

        if f.is_async {
            self.line(&format!("async function {}({}) {{", f.name, params))?;
        } else {
            self.line(&format!("function {}({}) {{", f.name, params))?;
        }
        self.indent += 1;
        self.emit_block(&f.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_class(&mut self, c: &ast::ClassDecl) -> Result<(), JavaScriptCodeGenError> {
        if let Some(ext) = &c.extends {
            self.line(&format!("class {} extends {} {{", c.name, ext))?;
        } else {
            self.line(&format!("class {} {{", c.name))?;
        }
        self.indent += 1;

        for member in &c.members {
            match member {
                ast::ClassMember::Field(f) => {
                    let init = if let Some(expr) = &f.initializer {
                        format!(" = {}", self.emit_expr(expr)?)
                    } else {
                        String::new()
                    };
                    self.line(&format!("{}{};", f.name, init))?;
                }
                ast::ClassMember::Method(m) => {
                    let params = m
                        .parameters
                        .iter()
                        .map(|p| p.name.clone())
                        .collect::<Vec<_>>()
                        .join(", ");
                    if m.is_async {
                        self.line(&format!("async {}({}) {{", m.name, params))?;
                    } else {
                        self.line(&format!("{}({}) {{", m.name, params))?;
                    }
                    self.indent += 1;
                    self.emit_block(&m.body)?;
                    self.indent -= 1;
                    self.line("}")?;
                }
                ast::ClassMember::Constructor(ctor) => {
                    let params = ctor
                        .parameters
                        .iter()
                        .map(|p| p.name.clone())
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.line(&format!("constructor({}) {{", params))?;
                    self.indent += 1;
                    self.emit_block(&ctor.body)?;
                    self.indent -= 1;
                    self.line("}")?;
                }
            }
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> Result<(), JavaScriptCodeGenError> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> Result<(), JavaScriptCodeGenError> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            StatementKind::Variable(v) => {
                self.emit_var_decl(v)?;
            }
            StatementKind::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            StatementKind::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while ({}) {{", cond))?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::For(for_stmt) => {
                let iter = self.emit_expr(&for_stmt.iterator)?;
                let pat = self.emit_pattern(&for_stmt.pattern)?;
                self.line(&format!("for (const {} of {}) {{", pat, iter))?;
                self.indent += 1;
                self.emit_block(&for_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::Match(match_stmt) => {
                self.emit_match(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try(try_stmt)?;
            }
            StatementKind::Break => {
                self.line("break;")?;
            }
            StatementKind::Continue => {
                self.line("continue;")?;
            }
            StatementKind::DoWhile(do_while) => {
                self.line("while (true) {")?;
                self.indent += 1;
                self.emit_block(&do_while.body)?;
                let cond = self.emit_expr(&do_while.condition)?;
                self.line(&format!("if (!({})) break;", cond))?;
                self.indent -= 1;
                self.line("}")?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> Result<(), JavaScriptCodeGenError> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if ({}) {{", cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;
        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }
        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> Result<String, JavaScriptCodeGenError> {
        match &expr.node {
            ExpressionKind::Literal(lit) => self.emit_literal(lit),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ExpressionKind::Unary(op, e) => {
                let inner = self.emit_expr(e)?;
                Ok(self.emit_unaryop(op, &inner))
            }
            ExpressionKind::Call(callee, args) => self.emit_call(callee, args),
            ExpressionKind::Assign(target, value) => self.emit_assign(target, value),
            ExpressionKind::Array(elements) => self.emit_array_literal(elements),
            ExpressionKind::Dictionary(pairs) => self.emit_dict_literal(pairs),
            ExpressionKind::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            ExpressionKind::If(cond, then_e, else_e) => {
                let c = self.emit_expr(cond)?;
                let t = self.emit_expr(then_e)?;
                let e = self.emit_expr(else_e)?;
                Ok(format!("({} ? {} : {})", c, t, e))
            }
            ExpressionKind::Lambda(params, body) => {
                let param_str = params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                // Generate lambda body as an IIFE-like expression
                let body_str = self.emit_lambda_body(body)?;
                Ok(format!("({}) => {{ {} }}", param_str, body_str))
            }
            ExpressionKind::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            _ => Ok("/* unsupported expression */ null".to_string()),
        }
    }

    /// Generate lambda body statements as a string
    fn emit_lambda_body(&self, block: &ast::Block) -> Result<String, JavaScriptCodeGenError> {
        let mut body_parts = Vec::new();
        for stmt in &block.statements {
            let stmt_str = self.emit_lambda_stmt(stmt)?;
            body_parts.push(stmt_str);
        }
        Ok(body_parts.join(" "))
    }

    /// Generate a single statement for use in lambda body
    fn emit_lambda_stmt(&self, stmt: &ast::Statement) -> Result<String, JavaScriptCodeGenError> {
        match &stmt.node {
            StatementKind::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    Ok(format!("return {};", e))
                } else {
                    Ok("return;".to_string())
                }
            }
            StatementKind::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                Ok(format!("{};", e))
            }
            StatementKind::Variable(v) => {
                let keyword = if v.is_mutable { "let" } else { "const" };
                if let Some(init) = &v.initializer {
                    let init_str = self.emit_expr(init)?;
                    Ok(format!("{} {} = {};", keyword, v.name, init_str))
                } else {
                    Ok(format!("{} {};", keyword, v.name))
                }
            }
            StatementKind::If(if_stmt) => {
                let cond = self.emit_expr(&if_stmt.condition)?;
                let then_str = self.emit_lambda_body(&if_stmt.then_block)?;
                let mut result = format!("if ({}) {{ {} }}", cond, then_str);
                if let Some(else_block) = &if_stmt.else_block {
                    let else_str = self.emit_lambda_body(else_block)?;
                    result = format!("{} else {{ {} }}", result, else_str);
                }
                Ok(result)
            }
            _ => Ok("/* unsupported statement */".to_string()),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> Result<String, JavaScriptCodeGenError> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(format!("{}", f)),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null => Ok("null".to_string()),
            ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("undefined".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("({} + {})", l, r),
            ast::BinaryOp::Sub => format!("({} - {})", l, r),
            ast::BinaryOp::Mul => format!("({} * {})", l, r),
            ast::BinaryOp::Div => format!("({} / {})", l, r),
            ast::BinaryOp::Mod => format!("({} % {})", l, r),
            ast::BinaryOp::Equal => format!("({} === {})", l, r),
            ast::BinaryOp::NotEqual => format!("({} !== {})", l, r),
            ast::BinaryOp::Less => format!("({} < {})", l, r),
            ast::BinaryOp::LessEqual => format!("({} <= {})", l, r),
            ast::BinaryOp::Greater => format!("({} > {})", l, r),
            ast::BinaryOp::GreaterEqual => format!("({} >= {})", l, r),
            ast::BinaryOp::And => format!("({} && {})", l, r),
            ast::BinaryOp::Or => format!("({} || {})", l, r),
            ast::BinaryOp::Pow => format!("Math.pow({}, {})", l, r),
            _ => format!("({} {} {})", l, "/* unsupported */", r),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("(-{})", e),
            ast::UnaryOp::Not => format!("(!{})", e),
            ast::UnaryOp::BitNot => format!("(~{})", e),
            ast::UnaryOp::Wait => format!("(await {})", e),
        }
    }

    fn emit_call(
        &self,
        callee: &ast::Expression,
        args: &[ast::Expression],
    ) -> Result<String, JavaScriptCodeGenError> {
        // 检查内置函数
        if let ExpressionKind::Variable(name) = &callee.node {
            let arg_strs: Vec<String> = args
                .iter()
                .map(|a| self.emit_expr(a))
                .collect::<Result<Vec<_>, _>>()?;
            return Ok(self.emit_builtin_or_call(name, &arg_strs));
        }
        let callee_str = self.emit_expr(callee)?;
        let arg_strs: Vec<String> = args
            .iter()
            .map(|a| self.emit_expr(a))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
    }

    fn emit_builtin_or_call(&self, name: &str, args: &[String]) -> String {
        // Check for runtime primitives starting with __rt_
        if name.starts_with("__rt_") {
            match self.emit_runtime_inline(name, args) {
                Ok(code) => return code,
                Err(_) => return format!("/* unknown runtime function: {} */ null", name),
            }
        }

        match name {
            "print" | "println" => {
                if args.len() == 1 {
                    format!("console.log({})", args[0])
                } else {
                    "console.log()".to_string()
                }
            }
            "to_string" => format!("String({})", args.first().map(|s| s.as_str()).unwrap_or("")),
            "len" => format!("{}.length", args.first().map(|s| s.as_str()).unwrap_or("")),
            _ => format!("{}({})", name, args.join(", ")),
        }
    }

    /// Emit inline code for runtime primitives (__rt_* functions)
    pub fn emit_runtime_inline(&self, name: &str, args: &[String]) -> Result<String, JavaScriptCodeGenError> {
        let code = match name {
            // Console functions
            "__rt_print" => {
                if args.is_empty() {
                    "console.log()".to_string()
                } else {
                    format!("console.log({})", args[0])
                }
            }
            "__rt_println" => {
                if args.is_empty() {
                    "console.log()".to_string()
                } else {
                    format!("console.log({})", args[0])
                }
            }
            "__rt_eprint" => {
                if args.is_empty() {
                    "console.error()".to_string()
                } else {
                    format!("console.error({})", args[0])
                }
            }
            "__rt_eprintln" => {
                if args.is_empty() {
                    "console.error()".to_string()
                } else {
                    format!("console.error({})", args[0])
                }
            }
            "__rt_readline" => {
                // Simplified placeholder - readline requires async/callback in Node.js
                "((function() { throw new Error('readline requires async handling'); })())".to_string()
            }

            // Math functions
            "__rt_sqrt" => format!("Math.sqrt({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_pow" => {
                let base = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let exp = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                format!("Math.pow({}, {})", base, exp)
            }
            "__rt_sin" => format!("Math.sin({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_cos" => format!("Math.cos({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_tan" => format!("Math.tan({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_asin" => format!("Math.asin({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_acos" => format!("Math.acos({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_atan" => format!("Math.atan({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_atan2" => {
                let y = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let x = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                format!("Math.atan2({}, {})", y, x)
            }
            "__rt_log" => format!("Math.log({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_log2" => format!("Math.log2({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_log10" => format!("Math.log10({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_exp" => format!("Math.exp({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_floor" => format!("Math.floor({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_ceil" => format!("Math.ceil({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_round" => format!("Math.round({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_trunc" => format!("Math.trunc({})", args.first().map(|s| s.as_str()).unwrap_or("0")),
            "__rt_abs_int" | "__rt_abs_float" => {
                format!("Math.abs({})", args.first().map(|s| s.as_str()).unwrap_or("0"))
            }
            "__rt_min_int" => {
                let a = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let b = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                format!("Math.min({}, {})", a, b)
            }
            "__rt_max_int" => {
                let a = args.get(0).map(|s| s.as_str()).unwrap_or("0");
                let b = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                format!("Math.max({}, {})", a, b)
            }

            // Node.js File System functions
            "__rt_file_read" => {
                let path = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("require('fs').readFileSync({}, 'utf8')", path)
            }
            "__rt_file_write" => {
                let path = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let content = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("require('fs').writeFileSync({}, {})", path, content)
            }
            "__rt_file_exists" => {
                let path = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("require('fs').existsSync({})", path)
            }
            "__rt_file_delete" => {
                let path = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("require('fs').unlinkSync({})", path)
            }
            "__rt_dir_create" => {
                let path = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("require('fs').mkdirSync({}, {{ recursive: true }})", path)
            }
            "__rt_dir_list" => {
                let path = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("require('fs').readdirSync({})", path)
            }
            "__rt_dir_exists" => {
                let path = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("require('fs').existsSync({})", path)
            }

            // Node.js System functions
            "__rt_get_env" => {
                let name = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("process.env[{}]", name)
            }
            "__rt_args" => "process.argv".to_string(),
            "__rt_cwd" => "process.cwd()".to_string(),
            "__rt_exit" => {
                let code = args.first().map(|s| s.as_str()).unwrap_or("0");
                format!("process.exit({})", code)
            }
            "__rt_timestamp_ms" => "Date.now()".to_string(),
            "__rt_sleep" => {
                let ms = args.first().map(|s| s.as_str()).unwrap_or("0");
                format!(
                    "((function() {{ const end = Date.now() + {}; while (Date.now() < end) {{}} }})())",
                    ms
                )
            }

            // String functions
            "__rt_str_len" => {
                let s = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.length", s)
            }
            "__rt_str_concat" => {
                let a = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let b = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("({} + {})", a, b)
            }
            "__rt_str_eq" => {
                let a = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let b = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("({} === {})", a, b)
            }
            "__rt_str_contains" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let substr = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.includes({})", s, substr)
            }
            "__rt_str_starts_with" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let prefix = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.startsWith({})", s, prefix)
            }
            "__rt_str_ends_with" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let suffix = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.endsWith({})", s, suffix)
            }
            "__rt_str_substring" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let start = args.get(1).map(|s| s.as_str()).unwrap_or("0");
                let len = args.get(2).map(|s| s.as_str()).unwrap_or("0");
                format!("{}.substring({}, {} + {})", s, start, start, len)
            }
            "__rt_str_split" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let sep = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.split({})", s, sep)
            }
            "__rt_str_replace" => {
                let s = args.get(0).map(|s| s.as_str()).unwrap_or("\"\"");
                let from = args.get(1).map(|s| s.as_str()).unwrap_or("\"\"");
                let to = args.get(2).map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.replaceAll({}, {})", s, from, to)
            }
            "__rt_str_to_lower" => {
                let s = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.toLowerCase()", s)
            }
            "__rt_str_to_upper" => {
                let s = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.toUpperCase()", s)
            }
            "__rt_str_trim" => {
                let s = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!("{}.trim()", s)
            }
            "__rt_int_to_str" => {
                let n = args.first().map(|s| s.as_str()).unwrap_or("0");
                format!("String({})", n)
            }
            "__rt_float_to_str" => {
                let f = args.first().map(|s| s.as_str()).unwrap_or("0");
                format!("String({})", f)
            }
            "__rt_str_to_int" => {
                let s = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!(
                    "((function() {{ const n = parseInt({}, 10); return isNaN(n) ? null : n; }})())",
                    s
                )
            }
            "__rt_str_to_float" => {
                let s = args.first().map(|s| s.as_str()).unwrap_or("\"\"");
                format!(
                    "((function() {{ const f = parseFloat({}); return isNaN(f) ? null : f; }})())",
                    s
                )
            }

            // Unknown runtime function
            _ => return Err(JavaScriptCodeGenError::GenerationError(
                format!("Unknown runtime function: {}", name)
            )),
        };

        Ok(code)
    }

    fn emit_assign(
        &self,
        target: &ast::Expression,
        value: &ast::Expression,
    ) -> Result<String, JavaScriptCodeGenError> {
        let val = self.emit_expr(value)?;
        match &target.node {
            ExpressionKind::Variable(name) => Ok(format!("({} = {})", name, val)),
            ExpressionKind::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("({}.{} = {})", o, field, val))
            }
            _ => {
                let t = self.emit_expr(target)?;
                Ok(format!("({} = {})", t, val))
            }
        }
    }

    fn emit_array_literal(
        &self,
        elements: &[ast::Expression],
    ) -> Result<String, JavaScriptCodeGenError> {
        let elem_strs: Vec<String> = elements
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(format!("[{}]", elem_strs.join(", ")))
    }

    fn emit_dict_literal(
        &self,
        pairs: &[(ast::Expression, ast::Expression)],
    ) -> Result<String, JavaScriptCodeGenError> {
        let mut parts = Vec::new();
        for (k, v) in pairs {
            let key_str = self.emit_expr(k)?;
            let val_str = self.emit_expr(v)?;
            parts.push(format!("{}: {}", key_str, val_str));
        }
        Ok(format!("{{{}}}", parts.join(", ")))
    }

    fn emit_pattern(&self, pat: &ast::Pattern) -> Result<String, JavaScriptCodeGenError> {
        match pat {
            ast::Pattern::Wildcard => Ok("_".to_string()),
            ast::Pattern::Variable(name) => Ok(name.clone()),
            ast::Pattern::Literal(lit) => self.emit_literal(lit),
            ast::Pattern::Array(elements) => {
                let elem_strs: Vec<String> = elements.iter()
                    .map(|e| self.emit_pattern(e))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(format!("[{}]", elem_strs.join(", ")))
            }
            ast::Pattern::Tuple(elements) => {
                let elem_strs: Vec<String> = elements.iter()
                    .map(|e| self.emit_pattern(e))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(format!("[{}]", elem_strs.join(", ")))
            }
            ast::Pattern::Or(left, _) => self.emit_pattern(left),
            ast::Pattern::Guard(inner, _) => self.emit_pattern(inner),
            _ => Ok("_".to_string()),
        }
    }

    fn emit_match(&mut self, match_stmt: &ast::MatchStatement) -> Result<(), JavaScriptCodeGenError> {
        let expr = self.emit_expr(&match_stmt.expression)?;
        let temp_var = "__match_val__";
        self.line(&format!("const {} = {};", temp_var, expr))?;

        for (i, case) in match_stmt.cases.iter().enumerate() {
            let condition = self.emit_match_condition(temp_var, &case.pattern, case.guard.as_ref())?;

            if i == 0 {
                self.line(&format!("if ({}) {{", condition))?;
            } else {
                self.line(&format!("else if ({}) {{", condition))?;
            }

            self.indent += 1;
            self.emit_match_bindings(temp_var, &case.pattern)?;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_match_condition(&self, var: &str, pattern: &ast::Pattern, guard: Option<&ast::Expression>) -> Result<String, JavaScriptCodeGenError> {
        let base_cond = match pattern {
            ast::Pattern::Wildcard => "true".to_string(),
            ast::Pattern::Variable(_) => "true".to_string(),
            ast::Pattern::Literal(lit) => {
                let lit_str = self.emit_literal(lit)?;
                format!("{} === {}", var, lit_str)
            }
            ast::Pattern::Array(elements) => {
                let len_check = format!("Array.isArray({}) && {}.length === {}", var, var, elements.len());
                let elem_checks: Vec<String> = elements.iter().enumerate()
                    .map(|(i, p)| self.emit_match_condition(&format!("{}[{}]", var, i), p, None))
                    .collect::<Result<Vec<_>, _>>()?;
                if elem_checks.is_empty() {
                    format!("{}.length === 0", var)
                } else {
                    format!("({}) && {}", len_check, elem_checks.join(" && "))
                }
            }
            ast::Pattern::Or(left, right) => {
                let left_cond = self.emit_match_condition(var, left, None)?;
                let right_cond = self.emit_match_condition(var, right, None)?;
                format!("({}) || ({})", left_cond, right_cond)
            }
            ast::Pattern::Guard(inner, cond_expr) => {
                let inner_cond = self.emit_match_condition(var, inner, None)?;
                let guard_cond = self.emit_expr(cond_expr)?;
                format!("({}) && ({})", inner_cond, guard_cond)
            }
            _ => format!("true /* pattern not fully supported */"),
        };

        if let Some(guard_expr) = guard {
            let guard_str = self.emit_expr(guard_expr)?;
            Ok(format!("({}) && ({})", base_cond, guard_str))
        } else {
            Ok(base_cond)
        }
    }

    fn emit_match_bindings(&mut self, var: &str, pattern: &ast::Pattern) -> Result<(), JavaScriptCodeGenError> {
        match pattern {
            ast::Pattern::Variable(name) => {
                self.line(&format!("const {} = {};", name, var))?;
            }
            ast::Pattern::Array(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_match_bindings(&format!("{}[{}]", var, i), elem)?;
                }
            }
            ast::Pattern::Tuple(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_match_bindings(&format!("{}[{}]", var, i), elem)?;
                }
            }
            ast::Pattern::Or(left, _) => {
                self.emit_match_bindings(var, left)?;
            }
            ast::Pattern::Guard(inner, _) => {
                self.emit_match_bindings(var, inner)?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_try(&mut self, try_stmt: &ast::TryStatement) -> Result<(), JavaScriptCodeGenError> {
        self.line("try {")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.indent -= 1;

        for catch in &try_stmt.catch_clauses {
            let catch_var = catch.variable_name.as_deref().unwrap_or("error");
            self.line(&format!("catch ({}) {{", catch_var))?;
            self.indent += 1;
            self.emit_block(&catch.body)?;
            self.indent -= 1;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("} finally {")?;
            self.indent += 1;
            self.emit_block(finally)?;
            self.indent -= 1;
        }

        self.line("}")?;
        Ok(())
    }

    fn line(&mut self, s: &str) -> Result<(), JavaScriptCodeGenError> {
        for _ in 0..self.indent {
            write!(self.output, "  ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

impl CodeGenerator for JavaScriptCodeGenerator {
    type Config = JavaScriptConfig;
    type Error = JavaScriptCodeGenError;

    fn new(config: Self::Config) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    fn generate_from_ast(&mut self, program: &AstProgram) -> Result<CodegenOutput, Self::Error> {
        let _js_code = self.generate_js_from_ast(program)?;
        Ok(CodegenOutput {
            files: vec![],
            dependencies: vec![],
        })
    }

    fn generate_from_hir(&mut self, _hir: &x_codegen::x_hir::Hir) -> Result<CodegenOutput, Self::Error> {
        Err(JavaScriptCodeGenError::Unimplemented(
            "JavaScript/TypeScript backend not yet implemented".to_string(),
        ))
    }

    fn generate_from_pir(&mut self, _pir: &x_codegen::x_perceus::PerceusIR) -> Result<CodegenOutput, Self::Error> {
        Err(JavaScriptCodeGenError::Unimplemented(
            "JavaScript/TypeScript backend not yet implemented".to_string(),
        ))
    }
}

/// JavaScript/TypeScript代码生成错误
#[derive(thiserror::Error, Debug)]
pub enum JavaScriptCodeGenError {
    #[error("代码生成错误: {0}")]
    GenerationError(String),

    #[error("未实现: {0}")]
    Unimplemented(String),

    #[error("IO错误: {0}")]
    IoError(#[from] std::io::Error),

    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
}

impl From<x_codegen::CodeGenError> for JavaScriptCodeGenError {
    fn from(err: x_codegen::CodeGenError) -> Self {
        match err {
            x_codegen::CodeGenError::GenerationError(msg) => {
                JavaScriptCodeGenError::GenerationError(msg)
            }
            x_codegen::CodeGenError::IoError(e) => JavaScriptCodeGenError::IoError(e),
            _ => JavaScriptCodeGenError::GenerationError(format!("{:?}", err)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_codegen::CodeGenerator;

    fn parse(source: &str) -> AstProgram {
        x_parser::parser::XParser::new()
            .parse(source)
            .expect("parse")
    }

    #[test]
    fn generate_empty_program_has_header() {
        let program = parse("");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let js = gen.generate_js_from_ast(&program).expect("generate");
        assert!(js.contains("Generated by X-Lang JavaScript backend"));
        assert!(js.contains("DO NOT EDIT"));
    }

    #[test]
    fn generate_function_emits_function() {
        let program = parse("function main() { println(\"hi\") }");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let js = gen.generate_js_from_ast(&program).expect("generate");
        assert!(js.contains("function main()"));
        assert!(js.contains("console.log"));
    }

    #[test]
    fn generate_variable_emits_const_or_let() {
        let program = parse("let x = 1;");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let js = gen.generate_js_from_ast(&program).expect("generate");
        assert!(js.contains("const x = 1") || js.contains("let x = 1"));
    }

    #[test]
    fn generate_from_ast_trait_returns_ok_with_files() {
        let program = parse("function f() {}");
        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let out = gen.generate_from_ast(&program).expect("generate_from_ast");
        assert!(out.files.is_empty());
    }

    #[test]
    fn generate_from_hir_returns_unimplemented() {
        use std::collections::HashMap;
        use x_codegen::x_hir::{Hir, HirTypeEnv, HirPerceusInfo};

        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let hir = Hir {
            module_name: "test".to_string(),
            declarations: vec![],
            statements: vec![],
            type_env: HirTypeEnv {
                variables: HashMap::new(),
                functions: HashMap::new(),
                types: HashMap::new(),
            },
            perceus_info: HirPerceusInfo::default(),
        };
        let err = gen.generate_from_hir(&hir).expect_err("unimplemented");
        let msg = err.to_string();
        assert!(msg.contains("未实现") || msg.contains("Unimplemented") || msg.contains("not yet implemented"));
    }

    #[test]
    fn generate_from_pir_returns_unimplemented() {
        use x_codegen::x_perceus::{PerceusIR, ReuseAnalysis};

        let mut gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());
        let pir = PerceusIR {
            functions: vec![],
            global_ops: vec![],
            reuse_analysis: ReuseAnalysis {
                reuse_pairs: vec![],
                estimated_savings: 0,
            },
        };
        let err = gen.generate_from_pir(&pir).expect_err("unimplemented");
        let msg = err.to_string();
        assert!(msg.contains("未实现") || msg.contains("not yet implemented"));
    }

    #[test]
    fn error_display_generation_error() {
        let e = JavaScriptCodeGenError::GenerationError("test".to_string());
        assert!(e.to_string().contains("代码生成错误"));
        assert!(e.to_string().contains("test"));
    }

    #[test]
    fn error_display_unimplemented() {
        let e = JavaScriptCodeGenError::Unimplemented("foo".to_string());
        assert!(e.to_string().contains("未实现"));
        assert!(e.to_string().contains("foo"));
    }

    // Tests for emit_runtime_inline

    #[test]
    fn runtime_inline_console_functions() {
        let gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());

        // print and println
        let result = gen.emit_runtime_inline("__rt_print", &["\"hello\"".to_string()]).unwrap();
        assert_eq!(result, "console.log(\"hello\")");

        let result = gen.emit_runtime_inline("__rt_println", &["\"world\"".to_string()]).unwrap();
        assert_eq!(result, "console.log(\"world\")");

        let result = gen.emit_runtime_inline("__rt_eprint", &["\"error\"".to_string()]).unwrap();
        assert_eq!(result, "console.error(\"error\")");

        let result = gen.emit_runtime_inline("__rt_eprintln", &["\"error\"".to_string()]).unwrap();
        assert_eq!(result, "console.error(\"error\")");

        // Empty args
        let result = gen.emit_runtime_inline("__rt_print", &[]).unwrap();
        assert_eq!(result, "console.log()");
    }

    #[test]
    fn runtime_inline_math_functions() {
        let gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());

        let result = gen.emit_runtime_inline("__rt_sqrt", &["16".to_string()]).unwrap();
        assert_eq!(result, "Math.sqrt(16)");

        let result = gen.emit_runtime_inline("__rt_pow", &["2".to_string(), "8".to_string()]).unwrap();
        assert_eq!(result, "Math.pow(2, 8)");

        let result = gen.emit_runtime_inline("__rt_sin", &["x".to_string()]).unwrap();
        assert_eq!(result, "Math.sin(x)");

        let result = gen.emit_runtime_inline("__rt_cos", &["x".to_string()]).unwrap();
        assert_eq!(result, "Math.cos(x)");

        let result = gen.emit_runtime_inline("__rt_tan", &["x".to_string()]).unwrap();
        assert_eq!(result, "Math.tan(x)");

        let result = gen.emit_runtime_inline("__rt_atan2", &["y".to_string(), "x".to_string()]).unwrap();
        assert_eq!(result, "Math.atan2(y, x)");

        let result = gen.emit_runtime_inline("__rt_floor", &["3.7".to_string()]).unwrap();
        assert_eq!(result, "Math.floor(3.7)");

        let result = gen.emit_runtime_inline("__rt_ceil", &["3.2".to_string()]).unwrap();
        assert_eq!(result, "Math.ceil(3.2)");

        let result = gen.emit_runtime_inline("__rt_round", &["3.5".to_string()]).unwrap();
        assert_eq!(result, "Math.round(3.5)");

        let result = gen.emit_runtime_inline("__rt_trunc", &["3.9".to_string()]).unwrap();
        assert_eq!(result, "Math.trunc(3.9)");

        let result = gen.emit_runtime_inline("__rt_abs_int", &["-5".to_string()]).unwrap();
        assert_eq!(result, "Math.abs(-5)");

        let result = gen.emit_runtime_inline("__rt_min_int", &["a".to_string(), "b".to_string()]).unwrap();
        assert_eq!(result, "Math.min(a, b)");

        let result = gen.emit_runtime_inline("__rt_max_int", &["a".to_string(), "b".to_string()]).unwrap();
        assert_eq!(result, "Math.max(a, b)");
    }

    #[test]
    fn runtime_inline_file_system_functions() {
        let gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());

        let result = gen.emit_runtime_inline("__rt_file_read", &["\"file.txt\"".to_string()]).unwrap();
        assert_eq!(result, "require('fs').readFileSync(\"file.txt\", 'utf8')");

        let result = gen.emit_runtime_inline("__rt_file_write", &["\"file.txt\"".to_string(), "\"content\"".to_string()]).unwrap();
        assert_eq!(result, "require('fs').writeFileSync(\"file.txt\", \"content\")");

        let result = gen.emit_runtime_inline("__rt_file_exists", &["\"file.txt\"".to_string()]).unwrap();
        assert_eq!(result, "require('fs').existsSync(\"file.txt\")");

        let result = gen.emit_runtime_inline("__rt_file_delete", &["\"file.txt\"".to_string()]).unwrap();
        assert_eq!(result, "require('fs').unlinkSync(\"file.txt\")");

        let result = gen.emit_runtime_inline("__rt_dir_create", &["\"mydir\"".to_string()]).unwrap();
        assert_eq!(result, "require('fs').mkdirSync(\"mydir\", { recursive: true })");

        let result = gen.emit_runtime_inline("__rt_dir_list", &["\"mydir\"".to_string()]).unwrap();
        assert_eq!(result, "require('fs').readdirSync(\"mydir\")");

        let result = gen.emit_runtime_inline("__rt_dir_exists", &["\"mydir\"".to_string()]).unwrap();
        assert_eq!(result, "require('fs').existsSync(\"mydir\")");
    }

    #[test]
    fn runtime_inline_system_functions() {
        let gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());

        let result = gen.emit_runtime_inline("__rt_get_env", &["\"PATH\"".to_string()]).unwrap();
        assert_eq!(result, "process.env[\"PATH\"]");

        let result = gen.emit_runtime_inline("__rt_args", &[]).unwrap();
        assert_eq!(result, "process.argv");

        let result = gen.emit_runtime_inline("__rt_cwd", &[]).unwrap();
        assert_eq!(result, "process.cwd()");

        let result = gen.emit_runtime_inline("__rt_exit", &["1".to_string()]).unwrap();
        assert_eq!(result, "process.exit(1)");

        let result = gen.emit_runtime_inline("__rt_timestamp_ms", &[]).unwrap();
        assert_eq!(result, "Date.now()");

        let result = gen.emit_runtime_inline("__rt_sleep", &["1000".to_string()]).unwrap();
        assert!(result.contains("Date.now() + 1000"));
    }

    #[test]
    fn runtime_inline_string_functions() {
        let gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());

        let result = gen.emit_runtime_inline("__rt_str_len", &["s".to_string()]).unwrap();
        assert_eq!(result, "s.length");

        let result = gen.emit_runtime_inline("__rt_str_concat", &["a".to_string(), "b".to_string()]).unwrap();
        assert_eq!(result, "(a + b)");

        let result = gen.emit_runtime_inline("__rt_str_eq", &["a".to_string(), "b".to_string()]).unwrap();
        assert_eq!(result, "(a === b)");

        let result = gen.emit_runtime_inline("__rt_str_contains", &["s".to_string(), "\"sub\"".to_string()]).unwrap();
        assert_eq!(result, "s.includes(\"sub\")");

        let result = gen.emit_runtime_inline("__rt_str_starts_with", &["s".to_string(), "\"pre\"".to_string()]).unwrap();
        assert_eq!(result, "s.startsWith(\"pre\")");

        let result = gen.emit_runtime_inline("__rt_str_ends_with", &["s".to_string(), "\"suf\"".to_string()]).unwrap();
        assert_eq!(result, "s.endsWith(\"suf\")");

        let result = gen.emit_runtime_inline("__rt_str_substring", &["s".to_string(), "0".to_string(), "5".to_string()]).unwrap();
        assert_eq!(result, "s.substring(0, 0 + 5)");

        let result = gen.emit_runtime_inline("__rt_str_split", &["s".to_string(), "\",\"".to_string()]).unwrap();
        assert_eq!(result, "s.split(\",\")");

        let result = gen.emit_runtime_inline("__rt_str_replace", &["s".to_string(), "\"a\"".to_string(), "\"b\"".to_string()]).unwrap();
        assert_eq!(result, "s.replaceAll(\"a\", \"b\")");

        let result = gen.emit_runtime_inline("__rt_str_to_lower", &["s".to_string()]).unwrap();
        assert_eq!(result, "s.toLowerCase()");

        let result = gen.emit_runtime_inline("__rt_str_to_upper", &["s".to_string()]).unwrap();
        assert_eq!(result, "s.toUpperCase()");

        let result = gen.emit_runtime_inline("__rt_str_trim", &["s".to_string()]).unwrap();
        assert_eq!(result, "s.trim()");

        let result = gen.emit_runtime_inline("__rt_int_to_str", &["42".to_string()]).unwrap();
        assert_eq!(result, "String(42)");

        let result = gen.emit_runtime_inline("__rt_float_to_str", &["3.14".to_string()]).unwrap();
        assert_eq!(result, "String(3.14)");

        let result = gen.emit_runtime_inline("__rt_str_to_int", &["\"42\"".to_string()]).unwrap();
        assert!(result.contains("parseInt(\"42\", 10)"));

        let result = gen.emit_runtime_inline("__rt_str_to_float", &["\"3.14\"".to_string()]).unwrap();
        assert!(result.contains("parseFloat(\"3.14\")"));
    }

    #[test]
    fn runtime_inline_unknown_function_returns_error() {
        let gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());

        let result = gen.emit_runtime_inline("__rt_unknown_func", &[]);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("Unknown runtime function"));
    }

    #[test]
    fn emit_builtin_or_call_handles_runtime_functions() {
        let gen = JavaScriptCodeGenerator::new(JavaScriptConfig::default());

        // Test that __rt_ functions are handled by emit_runtime_inline
        let result = gen.emit_builtin_or_call("__rt_sqrt", &["16".to_string()]);
        assert_eq!(result, "Math.sqrt(16)");

        let result = gen.emit_builtin_or_call("__rt_args", &[]);
        assert_eq!(result, "process.argv");

        // Test that unknown __rt_ functions return a placeholder comment
        let result = gen.emit_builtin_or_call("__rt_unknown", &[]);
        assert!(result.contains("unknown runtime function"));
    }
}
