//! x86-64 汇编生成器
//!
//! 支持 NASM 语法（Linux/macOS）和 MASM 语法（Windows）。
//!
//! # 支持的 ABI
//!
//! - System V AMD64 ABI (Linux/macOS) - NASM 语法
//! - Microsoft x64 ABI (Windows) - MASM 语法 (ml64)
//!
//! # 示例输出 (NASM)
//!
//! ```nasm
//! global main
//! main:
//!     push rbp
//!     mov rbp, rsp
//!     sub rsp, 32
//!     ; ... function body ...
//!     mov rsp, rbp
//!     pop rbp
//!     ret
//! ```
//!
//! # 示例输出 (MASM)
//!
//! ```masm
//! .code
//! PUBLIC main
//! main:
//!     push rbp
//!     mov rbp, rsp
//!     sub rsp, 32
//!     ; ... function body ...
//!     mov rsp, rbp
//!     pop rbp
//!     ret
//! ```

use std::collections::HashMap;
use std::fmt::Write;

use crate::{escape_assembly_string, NativeError, NativeResult, TargetArch, TargetOS};
use x_lir as lir;

use super::{AssemblyGenerator, AssemblyContext, GlobalInfo};

/// 汇编语法类型
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum AssemblySyntax {
    /// NASM 语法（Linux/macOS）
    Nasm,
    /// MASM 语法（Windows/ml64）
    Masm,
}

/// x86-64 汇编生成器
pub struct X86_64AssemblyGenerator {
    /// 目标操作系统
    os: TargetOS,
    /// 汇编语法
    syntax: AssemblySyntax,
    /// 输出缓冲区
    output: String,
    /// 当前缩进级别
    indent: usize,
    /// 标签计数器
    label_counter: usize,
    /// 字符串字面量表
    string_literals: HashMap<String, String>,
    /// 全局变量表
    globals: HashMap<String, GlobalInfo>,
    /// 局部变量栈偏移
    local_offsets: HashMap<String, i32>,
    /// 当前栈帧大小
    stack_size: usize,
    /// 当前函数名
    current_function: String,
    /// 循环标签栈 - (continue_label, break_label) for each nested loop
    loop_labels: Vec<(String, String)>,
    /// 字段偏移表 - field name -> calculated offset with alignment
    field_offsets: HashMap<String, usize>,
}

impl X86_64AssemblyGenerator {
    /// 创建新的 x86-64 汇编生成器
    pub fn new(os: TargetOS) -> Self {
        let syntax = match os {
            TargetOS::Windows => AssemblySyntax::Masm,
            TargetOS::Linux | TargetOS::MacOS => AssemblySyntax::Nasm,
        };

        Self {
            os,
            syntax,
            output: String::new(),
            indent: 0,
            label_counter: 0,
            string_literals: HashMap::new(),
            globals: HashMap::new(),
            local_offsets: HashMap::new(),
            stack_size: 0,
            current_function: String::new(),
            loop_labels: Vec::new(),
            field_offsets: HashMap::new(),
        }
    }

    /// 清空生成器状态
    pub fn clear(&mut self) {
        self.output.clear();
        self.indent = 0;
        self.label_counter = 0;
        self.string_literals.clear();
        self.globals.clear();
        self.local_offsets.clear();
        self.stack_size = 0;
        self.current_function.clear();
        self.loop_labels.clear();
        self.field_offsets.clear();
    }

    /// 生成唯一标签名
    fn new_label(&mut self, prefix: &str) -> String {
        let label = format!("L_{}_{}", prefix, self.label_counter);
        self.label_counter += 1;
        label
    }

    /// 输出一行汇编
    fn emit_line(&mut self, line: &str) -> NativeResult<()> {
        writeln!(self.output, "{}{}", "    ".repeat(self.indent), line)?;
        Ok(())
    }

    /// 输出原始文本（无缩进）
    fn emit_raw(&mut self, text: &str) -> NativeResult<()> {
        writeln!(self.output, "{}", text)?;
        Ok(())
    }

    /// 生成内存操作数语法
    /// MASM: qword ptr [rbp-8]
    /// NASM: qword [rbp-8]
    fn mem_operand(&self, size: &str, offset: i32) -> String {
        match self.syntax {
            AssemblySyntax::Masm => format!("{} ptr [rbp-{}]", size, offset),
            AssemblySyntax::Nasm => format!("{} [rbp-{}]", size, offset),
        }
    }

    /// 生成简单内存操作数语法（无大小前缀，用于寄存器操作）
    /// MASM: qword ptr [rbp-8]
    /// NASM: [rbp-8]
    fn mem_operand_simple(&self, offset: i32) -> String {
        match self.syntax {
            AssemblySyntax::Masm => format!("qword ptr [rbp-{}]", offset),
            AssemblySyntax::Nasm => format!("[rbp-{}]", offset),
        }
    }

    /// 生成汇编头部
    fn emit_header(&mut self) -> NativeResult<()> {
        self.emit_raw("; Generated by X Compiler Native Backend")?;
        match self.syntax {
            AssemblySyntax::Masm => {
                self.emit_raw("; Target: x86_64-pc-windows-msvc (MASM)")?;
            }
            AssemblySyntax::Nasm => {
                self.emit_raw("; Target: x86_64-unknown-linux-gnu (NASM)")?;
            }
        }
        self.emit_raw("")?;
        Ok(())
    }

    /// 生成数据段
    fn emit_data_section(&mut self) -> NativeResult<()> {
        if self.string_literals.is_empty() && self.globals.is_empty() {
            return Ok(());
        }

        // 克隆数据以避免借用冲突
        let string_literals: Vec<(String, String)> = self
            .string_literals
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        let globals: Vec<(String, GlobalInfo)> = self
            .globals
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();

        match self.syntax {
            AssemblySyntax::Nasm => {
                // NASM 语法
                self.emit_raw("section .rodata")?;
                for (literal, label) in &string_literals {
                    self.emit_raw(&format!("{}:", label))?;
                    self.emit_raw(&format!("    db \"{}\", 0", escape_assembly_string(literal)))?;
                }
                self.emit_raw("")?;

                if !globals.is_empty() {
                    self.emit_raw("section .data")?;
                    for (name, info) in &globals {
                        self.emit_raw(&format!("{}:", name))?;
                        self.emit_raw(&format!("    resb {}", info.size))?;
                    }
                    self.emit_raw("")?;
                }
            }
            AssemblySyntax::Masm => {
                // MASM 语法
                self.emit_raw(".const")?;
                for (literal, label) in &string_literals {
                    self.emit_raw(&format!("{} BYTE \"{}\", 0", label, escape_assembly_string(literal)))?;
                }
                self.emit_raw("")?;

                if !globals.is_empty() {
                    self.emit_raw(".data")?;
                    for (name, info) in &globals {
                        self.emit_raw(&format!("{} BYTE {} DUP (?)", name, info.size))?;
                    }
                    self.emit_raw("")?;
                }
            }
        }
        Ok(())
    }

    /// 收集字符串字面量和全局变量
    fn collect_literals_and_globals(&mut self, lir: &lir::Program) -> NativeResult<()> {
        for decl in &lir.declarations {
            match decl {
                lir::Declaration::Global(global) => {
                    let size = self.type_size(&global.type_);
                    self.globals.insert(
                        global.name.clone(),
                        GlobalInfo {
                            size,
                            initialized: global.initializer.is_some(),
                            align: self.type_align(&global.type_),
                        },
                    );
                }
                lir::Declaration::Function(func) => {
                    self.collect_string_literals(&func.body)?;
                }
                lir::Declaration::Struct(strct) => {
                    // Calculate field offsets with proper alignment
                    let mut current_offset = 0;
                    let mut max_alignment = 1;

                    for field in &strct.fields {
                        let align = self.type_align(&field.type_);
                        max_alignment = max_alignment.max(align);

                        // Align current offset to field alignment requirement
                        if current_offset % align != 0 {
                            current_offset += align - (current_offset % align);
                        }

                        // Store offset - first occurrence wins (matches existing comment)
                        if !self.field_offsets.contains_key(&field.name) {
                            let size = self.type_size(&field.type_);
                            self.field_offsets.insert(field.name.clone(), current_offset);
                            current_offset += size;
                        }
                    }

                    // Align total struct size
                    if current_offset % max_alignment != 0 {
                        current_offset += max_alignment - (current_offset % max_alignment);
                    }
                }
                lir::Declaration::Class(cls) => {
                    // Calculate field offsets with proper alignment - same as struct
                    let mut current_offset = 0;
                    let mut max_alignment = 1;

                    for field in &cls.fields {
                        let align = self.type_align(&field.type_);
                        max_alignment = max_alignment.max(align);

                        // Align current offset to field alignment requirement
                        if current_offset % align != 0 {
                            current_offset += align - (current_offset % align);
                        }

                        // Store offset - first occurrence wins
                        if !self.field_offsets.contains_key(&field.name) {
                            let size = self.type_size(&field.type_);
                            self.field_offsets.insert(field.name.clone(), current_offset);
                            current_offset += size;
                        }
                    }

                    // Align total class size
                    if current_offset % max_alignment != 0 {
                        current_offset += max_alignment - (current_offset % max_alignment);
                    }
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// 从语句块收集字符串字面量
    fn collect_string_literals(&mut self, block: &lir::Block) -> NativeResult<()> {
        for stmt in &block.statements {
            self.collect_stmt_strings(stmt)?;
        }
        Ok(())
    }

    /// 从语句收集字符串字面量
    fn collect_stmt_strings(&mut self, stmt: &lir::Statement) -> NativeResult<()> {
        use lir::Statement;
        match stmt {
            Statement::Expression(expr) => self.collect_expr_strings(expr),
            Statement::Variable(var) => {
                if let Some(init) = &var.initializer {
                    self.collect_expr_strings(init)
                } else {
                    Ok(())
                }
            }
            Statement::If(if_stmt) => {
                self.collect_expr_strings(&if_stmt.condition)?;
                self.collect_stmt_strings(&if_stmt.then_branch)?;
                if let Some(else_branch) = &if_stmt.else_branch {
                    self.collect_stmt_strings(else_branch)?;
                }
                Ok(())
            }
            Statement::While(while_stmt) => {
                self.collect_expr_strings(&while_stmt.condition)?;
                self.collect_stmt_strings(&while_stmt.body)
            }
            Statement::Return(Some(expr)) => self.collect_expr_strings(expr),
            Statement::Compound(block) => self.collect_string_literals(block),
            _ => Ok(()),
        }
    }

    /// 从表达式收集字符串字面量
    fn collect_expr_strings(&mut self, expr: &lir::Expression) -> NativeResult<()> {
        use lir::{Expression, Literal};
        match expr {
            Expression::Literal(Literal::String(s)) => {
                if !self.string_literals.contains_key(s) {
                    let label = format!("LC{}", self.string_literals.len());
                    self.string_literals.insert(s.clone(), label);
                }
                Ok(())
            }
            Expression::Unary(_, e) => self.collect_expr_strings(e),
            Expression::Binary(_, left, right) => {
                self.collect_expr_strings(left)?;
                self.collect_expr_strings(right)
            }
            Expression::Call(func, args) => {
                self.collect_expr_strings(func)?;
                for arg in args {
                    self.collect_expr_strings(arg)?;
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }

    /// 生成代码段
    fn emit_text_section(&mut self, lir: &lir::Program) -> NativeResult<()> {
        // 收集本地定义的函数名
        let local_functions: std::collections::HashSet<&str> = lir.declarations
            .iter()
            .filter_map(|decl| {
                if let lir::Declaration::Function(func) = decl {
                    Some(func.name.as_str())
                } else {
                    None
                }
            })
            .collect();

        match self.syntax {
            AssemblySyntax::Nasm => {
                // NASM 语法 - 声明外部函数
                self.emit_raw("; External functions")?;
                if !local_functions.contains("printf") { self.emit_raw("extern printf")?; }
                if !local_functions.contains("puts") { self.emit_raw("extern puts")?; }
                if !local_functions.contains("malloc") { self.emit_raw("extern malloc")?; }
                if !local_functions.contains("free") { self.emit_raw("extern free")?; }
                if !local_functions.contains("println") { self.emit_raw("extern println")?; }
                if !local_functions.contains("print") { self.emit_raw("extern print")?; }
                if !local_functions.contains("exit") { self.emit_raw("extern exit")?; }
                self.emit_raw("")?;
                self.emit_raw("section .text code")?;
            }
            AssemblySyntax::Masm => {
                // MASM 语法
                // 注意：External functions 在需要时由调用代码生成，不需要预声明
                self.emit_raw(".code")?;
            }
        }

        for decl in &lir.declarations {
            if let lir::Declaration::Function(func) = decl {
                self.emit_function(func)?;
            }
        }

        // MASM 需要结束代码段
        if self.syntax == AssemblySyntax::Masm {
            self.emit_raw("END")?;
        }

        Ok(())
    }

    /// 生成函数
    fn emit_function(&mut self, func: &lir::Function) -> NativeResult<()> {
        self.stack_size = 0;
        self.local_offsets.clear();
        self.current_function = func.name.clone();

        // 函数标签
        if func.name == "main" {
            match self.syntax {
                AssemblySyntax::Nasm => {
                    self.emit_raw(&format!("global {}", func.name))?;
                }
                AssemblySyntax::Masm => {
                    self.emit_raw(&format!("PUBLIC {}", func.name))?;
                }
            }
        }
        self.emit_raw(&format!("{}:", func.name))?;

        // 函数序言
        self.emit_line("push rbp")?;
        self.emit_line("mov rbp, rsp")?;

        // 分配栈空间
        let stack_alloc_label = self.new_label("stack_alloc");
        self.emit_line(&format!("sub rsp, 0  ; {}", stack_alloc_label))?;

        // 保存被调用者保存的寄存器
        let callee_saved = vec!["rbx", "r12", "r13", "r14", "r15"];
        for reg in &callee_saved {
            self.emit_line(&format!("push {}", reg))?;
        }

        // 处理参数
        let arg_regs = if self.os.uses_system_v_abi() {
            vec!["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
        } else {
            vec!["rcx", "rdx", "r8", "r9"]
        };

        for (i, param) in func.parameters.iter().enumerate() {
            if i < arg_regs.len() {
                self.local_offsets.insert(param.name.clone(), ((i + 1) * 8) as i32);
                self.emit_line(&format!("mov {}, {}", self.mem_operand_simple(((i + 1) * 8) as i32), arg_regs[i]))?;
            }
        }

        // 生成函数体
        self.emit_block(&func.body)?;

        // 函数尾声
        let epilogue_label = format!("L_{}_epilogue", func.name);
        self.emit_raw(&format!("{}:", epilogue_label))?;

        for reg in callee_saved.iter().rev() {
            self.emit_line(&format!("pop {}", reg))?;
        }

        self.emit_line("mov rsp, rbp")?;
        self.emit_line("pop rbp")?;
        self.emit_line("ret")?;
        self.emit_raw("")?;

        Ok(())
    }

    /// 生成语句块
    fn emit_block(&mut self, block: &lir::Block) -> NativeResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    /// 生成语句
    fn emit_statement(&mut self, stmt: &lir::Statement) -> NativeResult<()> {
        use lir::{BinaryOp, Statement};
        match stmt {
            Statement::Expression(expr) => {
                self.emit_expr(expr)?;
            }
            Statement::Variable(var) => {
                self.stack_size += 8;
                let offset = self.stack_size as i32;
                self.local_offsets.insert(var.name.clone(), offset);

                if let Some(init) = &var.initializer {
                    self.emit_expr(init)?;
                    self.emit_line(&format!("mov {}, rax", self.mem_operand_simple(offset)))?;
                } else {
                    self.emit_line(&format!("mov {}, 0", self.mem_operand("qword", offset)))?;
                }
            }
            Statement::Return(Some(expr)) => {
                self.emit_expr(expr)?;
                self.emit_line("mov rsp, rbp")?;
                self.emit_line("pop rbp")?;
                self.emit_line("ret")?;
            }
            Statement::Return(None) => {
                self.emit_line("xor rax, rax")?;
                self.emit_line("mov rsp, rbp")?;
                self.emit_line("pop rbp")?;
                self.emit_line("ret")?;
            }
            Statement::If(if_stmt) => {
                let else_label = self.new_label("else");
                let end_label = self.new_label("endif");

                self.emit_expr(&if_stmt.condition)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", else_label))?;

                self.emit_statement(&if_stmt.then_branch)?;
                self.emit_line(&format!("jmp {}", end_label))?;

                self.emit_raw(&format!("{}:", else_label))?;
                if let Some(else_branch) = &if_stmt.else_branch {
                    self.emit_statement(else_branch)?;
                }
                self.emit_raw(&format!("{}:", end_label))?;
            }
            Statement::While(while_stmt) => {
                let start_label = self.new_label("while_start"); // continue jumps here (recheck condition)
                let end_label = self.new_label("while_end");   // break jumps here

                // Push to label stack for break/continue
                self.loop_labels.push((start_label.clone(), end_label.clone()));

                self.emit_raw(&format!("{}:", start_label))?;
                self.emit_expr(&while_stmt.condition)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", end_label))?;

                self.emit_statement(&while_stmt.body)?;
                self.emit_line(&format!("jmp {}", start_label))?;

                self.emit_raw(&format!("{}:", end_label))?;

                // Pop from stack
                self.loop_labels.pop();
            }
            Statement::DoWhile(do_while) => {
                let start_label = self.new_label("do_start");
                let cond_label = self.new_label("do_cond");
                let end_label = self.new_label("do_end");

                // continue -> go to condition check (then back to start if condition true)
                // break -> exit to end_label
                self.loop_labels.push((cond_label.clone(), end_label.clone()));

                self.emit_raw(&format!("{}:", start_label))?;

                self.indent += 1;
                self.emit_statement(&do_while.body)?;
                self.emit_line(&format!("jmp {}", cond_label))?;
                self.indent -= 1;

                self.emit_raw(&format!("{}:", cond_label))?;
                self.emit_expr(&do_while.condition)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jnz {}", start_label))?;

                self.emit_raw(&format!("{}:", end_label))?;

                // Pop from stack
                self.loop_labels.pop();
            }
            Statement::For(for_stmt) => {
                let start_label = self.new_label("for_start");
                let end_label = self.new_label("for_end");
                // continue -> go to condition check (then loop if true)
                // break -> exit to end_label

                // initializer
                if let Some(init) = &for_stmt.initializer {
                    self.emit_statement(init)?;
                }

                // Push to label stack
                self.loop_labels.push((start_label.clone(), end_label.clone()));

                self.emit_raw(&format!("{}:", start_label))?;

                // condition check
                self.indent += 1;
                if let Some(cond) = &for_stmt.condition {
                    self.emit_expr(cond)?;
                    self.emit_line("test rax, rax")?;
                    self.emit_line(&format!("jz {}", end_label))?;
                }

                // loop body
                self.emit_statement(&for_stmt.body)?;

                // increment
                if let Some(inc) = &for_stmt.increment {
                    self.emit_expr(inc)?;
                }

                self.emit_line(&format!("jmp {}", start_label))?;
                self.indent -= 1;

                self.emit_raw(&format!("{}:", end_label))?;

                // Pop from stack
                self.loop_labels.pop();
            }
            Statement::Compound(block) => {
                self.emit_block(block)?;
            }
            Statement::Break => {
                // break jumps to the current loop's break target
                if let Some((_continue_label, break_label)) = self.loop_labels.last() {
                    self.emit_line(&format!("jmp {}", break_label))?;
                } else {
                    self.emit_line("; TODO: break outside loop")?;
                }
            }
            Statement::Continue => {
                // continue jumps to the current loop's continue target (condition check / loop start)
                if let Some((continue_label, _break_label)) = self.loop_labels.last() {
                    self.emit_line(&format!("jmp {}", continue_label))?;
                } else {
                    self.emit_line("; TODO: continue outside loop")?;
                }
            }
            Statement::Empty => {}
            _ => {
                // 其他语句类型的简化处理
                self.emit_line(&format!("; TODO: {:?}", std::mem::discriminant(stmt)))?;
            }
        }
        Ok(())
    }

    /// 生成表达式
    fn emit_expr(&mut self, expr: &lir::Expression) -> NativeResult<()> {
        use lir::{BinaryOp, Expression, Literal, UnaryOp};
        match expr {
            Expression::Literal(lit) => self.emit_literal(lit)?,
            Expression::Variable(name) => {
                if let Some(offset) = self.local_offsets.get(name) {
                    self.emit_line(&format!("mov rax, {}", self.mem_operand_simple(*offset)))?;
                } else if self.globals.contains_key(name) {
                    self.emit_line(&format!("mov rax, [{}]", name))?;
                } else {
                    return Err(NativeError::CodegenError(format!(
                        "Undefined variable: {}",
                        name
                    )));
                }
            }
            Expression::Unary(op, e) => {
                self.emit_expr(e)?;
                match op {
                    UnaryOp::Minus => {
                        self.emit_line("neg rax")?;
                    }
                    UnaryOp::BitNot => {
                        self.emit_line("not rax")?;
                    }
                    UnaryOp::Not => {
                        self.emit_line("test rax, rax")?;
                        self.emit_line("setz al")?;
                        self.emit_line("movzx rax, al")?;
                    }
                    _ => {}
                }
            }
            Expression::Binary(op, left, right) => {
                self.emit_binary(*op, left, right)?;
            }
            Expression::Call(func, args) => {
                self.emit_call(func, args)?;
            }
            Expression::Assign(target, value) => {
                self.emit_expr(value)?;
                match target.as_ref() {
                    Expression::Variable(name) => {
                        if let Some(offset) = self.local_offsets.get(name) {
                            self.emit_line(&format!("mov {}, rax", self.mem_operand_simple(*offset)))?;
                        } else if self.globals.contains_key(name) {
                            self.emit_line(&format!("mov [{}], rax", name))?;
                        }
                    }
                    Expression::Dereference(ptr) => {
                        self.emit_expr(ptr)?;
                        self.emit_line("mov [rax], rax")?;
                    }
                    Expression::Member(obj, field) => {
                        self.emit_expr(obj)?;
                        // 查找结构体字段偏移
                        if let Some(&offset) = self.field_offsets.get(field) {
                            if offset > 0 {
                                self.emit_line(&format!("add rax, {}", offset))?;
                            }
                            self.emit_line("mov [rax], rax")?;
                        } else {
                            // Field not found - assume offset 0
                            self.emit_line("mov [rax], rax")?;
                        }
                    }
                    Expression::PointerMember(obj, field) => {
                        self.emit_expr(obj)?;
                        self.emit_line("mov rax, [rax]")?;
                        // 查找结构体字段偏移
                        if let Some(&offset) = self.field_offsets.get(field) {
                            if offset > 0 {
                                self.emit_line(&format!("add rax, {}", offset))?;
                            }
                            self.emit_line("mov [rax], rax")?;
                        } else {
                            // Field not found - assume offset 0
                            self.emit_line("mov [rax], rax")?;
                        }
                    }
                    Expression::Index(arr, idx) => {
                        self.emit_expr(arr)?;
                        self.emit_line("mov rcx, rax")?;
                        self.emit_expr(idx)?;
                        self.emit_line("shl rax, 3")?; // 假设 8 字节元素
                        self.emit_line("add rcx, rax")?;
                        self.emit_line("mov [rcx], rax")?;
                    }
                    _ => {
                        self.emit_line("; TODO: complex assign target")?;
                    }
                }
            }
            Expression::AssignOp(op, target, value) => {
                // 处理如 +=, -= 等复合赋值
                self.emit_expr(target)?;
                self.emit_line("push rax")?;
                self.emit_expr(value)?;
                self.emit_line("mov rcx, rax")?;
                self.emit_line("pop rax")?;
                match op {
                    BinaryOp::Add => self.emit_line("add rax, rcx")?,
                    BinaryOp::Subtract => self.emit_line("sub rax, rcx")?,
                    BinaryOp::Multiply => self.emit_line("imul rax, rcx")?,
                    BinaryOp::Divide => {
                        self.emit_line("cqo")?;
                        self.emit_line("idiv rcx")?;
                    }
                    BinaryOp::Modulo => {
                        self.emit_line("cqo")?;
                        self.emit_line("idiv rcx")?;
                        self.emit_line("mov rax, rdx")?;
                    }
                    BinaryOp::BitAnd => self.emit_line("and rax, rcx")?,
                    BinaryOp::BitOr => self.emit_line("or rax, rcx")?,
                    BinaryOp::BitXor => self.emit_line("xor rax, rcx")?,
                    BinaryOp::LeftShift => self.emit_line("shl rax, cl")?,
                    BinaryOp::RightShift => self.emit_line("shr rax, cl")?,
                    BinaryOp::RightShiftArithmetic => self.emit_line("sar rax, cl")?,
                    _ => self.emit_line("; TODO: unsupported assign op")?,
                }
                // 存回目标
                match target.as_ref() {
                    Expression::Variable(name) => {
                        if let Some(offset) = self.local_offsets.get(name) {
                            self.emit_line(&format!("mov {}, rax", self.mem_operand_simple(*offset)))?;
                        }
                    }
                    _ => {}
                }
            }
            Expression::SizeOf(ty) => {
                let size = self.type_size(ty);
                self.emit_line(&format!("mov rax, {}", size))?;
            }
            Expression::SizeOfExpr(expr) => {
                // SizeOfExpr - since LIR Expression doesn't carry type info,
                // we default to 8 bytes (pointer size on x86_64)
                let _ = expr;
                self.emit_line("mov rax, 8")?;
            }
            Expression::AlignOf(ty) => {
                let align = self.type_align(ty);
                self.emit_line(&format!("mov rax, {}", align))?;
            }
            Expression::Ternary(cond, then, else_) => {
                let else_label = self.new_label("ternary_else");
                let end_label = self.new_label("ternary_end");

                self.emit_expr(cond)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", else_label))?;

                self.emit_expr(then)?;
                self.emit_line(&format!("jmp {}", end_label))?;

                self.emit_raw(&format!("{}:", else_label))?;
                self.emit_expr(else_)?;

                self.emit_raw(&format!("{}:", end_label))?;
            }
            Expression::Cast(ty, expr) => {
                self.emit_expr(expr)?;
                // Basic casting between integer types is handled implicitly
                // since everything is in rax as 64-bit. For floating point we'd need
                // proper instructions, but this handles the common case.
                let _ = ty;
            }
            Expression::AddressOf(expr) => {
                match expr.as_ref() {
                    Expression::Variable(name) => {
                        if let Some(offset) = self.local_offsets.get(name) {
                            self.emit_line(&format!("lea rax, [rbp-{}]", offset))?;
                        }
                    }
                    _ => self.emit_expr(expr)?,
                }
            }
            Expression::Dereference(expr) => {
                self.emit_expr(expr)?;
                self.emit_line("mov rax, [rax]")?;
            }
            Expression::Index(arr, idx) => {
                self.emit_expr(arr)?;
                self.emit_line("push rax")?;
                self.emit_expr(idx)?;
                self.emit_line("mov rcx, rax")?;
                self.emit_line("pop rax")?;
                self.emit_line("shl rcx, 3")?; // 假设 8 字节元素
                self.emit_line("add rax, rcx")?;
                self.emit_line("mov rax, [rax]")?;
            }
            Expression::Member(obj, field) => {
                self.emit_expr(obj)?;
                // 查找结构体字段偏移 - 简单实现，假设第一个同名字段
                if let Some(&offset) = self.field_offsets.get(field) {
                    if offset > 0 {
                        self.emit_line(&format!("add rax, {}", offset))?;
                    }
                    self.emit_line("mov rax, [rax]")?;
                } else {
                    // Field not found - assume offset 0 (TODO: proper error handling)
                    self.emit_line("mov rax, [rax]")?;
                }
            }
            Expression::PointerMember(obj, field) => {
                self.emit_expr(obj)?;
                self.emit_line("mov rax, [rax]")?;
                // 查找结构体字段偏移
                if let Some(&offset) = self.field_offsets.get(field) {
                    if offset > 0 {
                        self.emit_line(&format!("add rax, {}", offset))?;
                    }
                    self.emit_line("mov rax, [rax]")?;
                } else {
                    // Field not found - assume offset 0
                    self.emit_line("mov rax, [rax]")?;
                }
            }
            Expression::Comma(exprs) => {
                for expr in exprs.iter() {
                    self.emit_expr(expr)?;
                }
            }
            Expression::Parenthesized(expr) => {
                self.emit_expr(expr)?;
            }
            Expression::InitializerList(_) => {
                self.emit_line("; TODO: initializer list")?;
            }
            Expression::CompoundLiteral(_, _) => {
                self.emit_line("; TODO: compound literal")?;
            }
            _ => {
                self.emit_line("; TODO: unsupported expression type")?;
            }
        }
        Ok(())
    }

    /// 生成字面量
    fn emit_literal(&mut self, lit: &lir::Literal) -> NativeResult<()> {
        use lir::Literal;
        match lit {
            Literal::Integer(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::UnsignedInteger(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::Long(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::UnsignedLong(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::LongLong(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::UnsignedLongLong(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::Bool(b) => {
                self.emit_line(&format!("mov rax, {}", if *b { 1 } else { 0 }))?;
            }
            Literal::Float(f) => {
                // 浮点数需要特殊处理，简化为整数
                self.emit_line(&format!("mov rax, {}", *f as i64))?;
            }
            Literal::Double(f) => {
                self.emit_line(&format!("mov rax, {}", *f as i64))?;
            }
            Literal::String(s) => {
                if let Some(label) = self.string_literals.get(s) {
                    self.emit_line(&format!("lea rax, [rel {}]", label))?;
                }
            }
            Literal::Char(c) => {
                self.emit_line(&format!("mov rax, {}", *c as i64))?;
            }
            Literal::NullPointer => {
                self.emit_line("xor rax, rax")?;
            }
        }
        Ok(())
    }

    /// 生成二元运算
    fn emit_binary(&mut self, op: lir::BinaryOp, left: &lir::Expression, right: &lir::Expression) -> NativeResult<()> {
        use lir::BinaryOp;

        self.emit_expr(left)?;
        self.emit_line("push rax")?;
        self.emit_expr(right)?;
        self.emit_line("mov rcx, rax")?;
        self.emit_line("pop rax")?;

        match op {
            BinaryOp::Add => self.emit_line("add rax, rcx")?,
            BinaryOp::Subtract => self.emit_line("sub rax, rcx")?,
            BinaryOp::Multiply => self.emit_line("imul rax, rcx")?,
            BinaryOp::Divide => {
                self.emit_line("cqo")?;
                self.emit_line("idiv rcx")?;
            }
            BinaryOp::Modulo => {
                self.emit_line("cqo")?;
                self.emit_line("idiv rcx")?;
                self.emit_line("mov rax, rdx")?; // 余数在 rdx
            }
            BinaryOp::Equal => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("sete al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::NotEqual => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setne al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::LessThan => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setl al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::LessThanEqual => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setle al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::GreaterThan => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setg al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::GreaterThanEqual => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setge al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::BitAnd => self.emit_line("and rax, rcx")?,
            BinaryOp::BitOr => self.emit_line("or rax, rcx")?,
            BinaryOp::BitXor => self.emit_line("xor rax, rcx")?,
            BinaryOp::LeftShift => self.emit_line("shl rax, cl")?,
            BinaryOp::RightShift => self.emit_line("shr rax, cl")?,
            BinaryOp::RightShiftArithmetic => self.emit_line("sar rax, cl")?,
            BinaryOp::LogicalAnd => {
                let end_label = self.new_label("logical_and_end");
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", end_label))?;
                self.emit_line("mov rax, rcx")?;
                self.emit_line("test rax, rax")?;
                self.emit_raw(&format!("{}:", end_label))?;
            }
            BinaryOp::LogicalOr => {
                let end_label = self.new_label("logical_or_end");
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jnz {}", end_label))?;
                self.emit_line("mov rax, rcx")?;
                self.emit_raw(&format!("{}:", end_label))?;
            }
        }
        Ok(())
    }

    /// 生成函数调用
    fn emit_call(&mut self, func: &lir::Expression, args: &[lir::Expression]) -> NativeResult<()> {
        // 保存参数
        for arg in args.iter().rev() {
            self.emit_expr(arg)?;
            self.emit_line("push rax")?;
        }

        // 获取函数名
        if let lir::Expression::Variable(name) = func {
            // 恢复参数到寄存器
            let arg_regs = if self.os.uses_system_v_abi() {
                vec!["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
            } else {
                vec!["rcx", "rdx", "r8", "r9"]
            };

            for (i, _) in args.iter().enumerate().take(arg_regs.len()) {
                self.emit_line(&format!("pop {}", arg_regs[i]))?;
            }

            // 调整栈对齐
            self.emit_line(&format!("call {}", name))?;
        } else {
            // Indirect call - call via register
            self.emit_expr(func)?; // result goes to rax
            self.emit_line("call rax")?;
        }

        Ok(())
    }

    /// 获取类型大小
    fn type_size(&self, ty: &lir::Type) -> usize {
        use lir::Type;
        match ty {
            Type::Void => 0,
            Type::Bool => 1,
            Type::Char | Type::Schar | Type::Uchar => 1,
            Type::Short | Type::Ushort => 2,
            Type::Int | Type::Uint | Type::Float => 4,
            Type::Long | Type::Ulong | Type::Double | Type::Pointer(_) => 8,
            Type::LongLong | Type::UlongLong | Type::LongDouble => 16,
            _ => 8,
        }
    }

    /// 获取类型对齐
    fn type_align(&self, ty: &lir::Type) -> usize {
        self.type_size(ty).max(1)
    }
}

impl AssemblyGenerator for X86_64AssemblyGenerator {
    fn generate(&mut self, lir: &x_lir::Program) -> NativeResult<String> {
        self.clear();
        self.collect_literals_and_globals(lir)?;
        self.emit_header()?;
        self.emit_data_section()?;
        self.emit_text_section(lir)?;
        Ok(self.output.clone())
    }

    fn arch(&self) -> TargetArch {
        TargetArch::X86_64
    }
}

// ============================================================================
// 单元测试
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_creation() {
        let gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        assert_eq!(gen.arch(), TargetArch::X86_64);
    }

    #[test]
    fn test_simple_function() {
        let mut lir = lir::Program::new();
        let mut func = lir::Function::new("main", lir::Type::Int);
        func.body.statements.push(lir::Statement::Return(Some(
            lir::Expression::int(42),
        )));
        lir.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        let result = gen.generate(&lir).unwrap();

        assert!(result.contains("main:"));
        assert!(result.contains("mov rax, 42"));
        assert!(result.contains("ret"));
    }

    #[test]
    fn test_binary_add() {
        let mut lir = lir::Program::new();
        let mut func = lir::Function::new("test", lir::Type::Int);
        func.body.statements.push(lir::Statement::Return(Some(
            lir::Expression::int(10).add(lir::Expression::int(20)),
        )));
        lir.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        let result = gen.generate(&lir).unwrap();

        assert!(result.contains("add rax, rcx"));
    }

    #[test]
    fn test_windows_abi() {
        let mut lir = lir::Program::new();
        let mut func = lir::Function::new("test", lir::Type::Int);
        func.parameters.push(lir::Parameter { name: "x".to_string(), type_: lir::Type::Int });
        func.body.statements.push(lir::Statement::Return(Some(
            lir::Expression::var("x"),
        )));
        lir.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Windows);
        let result = gen.generate(&lir).unwrap();

        // Windows uses rcx for first argument (MASM uses qword ptr)
        assert!(result.contains("mov qword ptr [rbp-8], rcx"));
    }
}
