//! x86-64 汇编生成器
//!
//! 支持 NASM 语法（Linux/macOS）和 MASM 语法（Windows）。
//!
//! # 支持的 ABI
//!
//! - System V AMD64 ABI (Linux/macOS) - NASM 语法
//! - Microsoft x64 ABI (Windows) - MASM 语法 (ml64)
//!
//! # 示例输出 (NASM)
//!
//! ```nasm
//! global main
//! main:
//!     push rbp
//!     mov rbp, rsp
//!     sub rsp, 32
//!     ; ... function body ...
//!     mov rsp, rbp
//!     pop rbp
//!     ret
//! ```
//!
//! # 示例输出 (MASM)
//!
//! ```masm
//! .code
//! PUBLIC main
//! main:
//!     push rbp
//!     mov rbp, rsp
//!     sub rsp, 32
//!     ; ... function body ...
//!     mov rsp, rbp
//!     pop rbp
//!     ret
//! ```

use std::collections::HashMap;
use std::fmt::Write;

use crate::{escape_assembly_string, NativeError, NativeResult, TargetArch, TargetOS};
use x_lir as lir;

use super::{AssemblyGenerator, GlobalInfo};

/// 汇编语法类型
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum AssemblySyntax {
    /// NASM 语法（Linux/macOS）
    Nasm,
    /// MASM 语法（Windows/ml64）
    Masm,
}

/// x86-64 汇编生成器
pub struct X86_64AssemblyGenerator {
    /// 目标操作系统
    os: TargetOS,
    /// 汇编语法
    syntax: AssemblySyntax,
    /// 输出缓冲区
    output: String,
    /// 当前缩进级别
    indent: usize,
    /// 标签计数器
    label_counter: usize,
    /// 字符串字面量表
    string_literals: HashMap<String, String>,
    /// 全局变量表
    globals: HashMap<String, GlobalInfo>,
    /// 局部变量栈偏移
    local_offsets: HashMap<String, i32>,
    /// 当前栈帧大小
    stack_size: usize,
    /// 当前函数名
    current_function: String,
    /// 循环标签栈 - (continue_label, break_label) for each nested loop
    loop_labels: Vec<(String, String)>,
    /// 字段偏移：`StructName::field` -> 字节偏移
    field_offsets: HashMap<String, usize>,
    /// 当前函数参数与局部变量的静态类型（解析 Member / PointerMember）
    local_and_param_types: HashMap<String, lir::Type>,
}

impl X86_64AssemblyGenerator {
    /// 创建新的 x86-64 汇编生成器
    pub fn new(os: TargetOS) -> Self {
        let syntax = match os {
            TargetOS::Windows => AssemblySyntax::Masm,
            TargetOS::Linux | TargetOS::MacOS => AssemblySyntax::Nasm,
        };

        Self {
            os,
            syntax,
            output: String::new(),
            indent: 0,
            label_counter: 0,
            string_literals: HashMap::new(),
            globals: HashMap::new(),
            local_offsets: HashMap::new(),
            stack_size: 0,
            current_function: String::new(),
            loop_labels: Vec::new(),
            field_offsets: HashMap::new(),
            local_and_param_types: HashMap::new(),
        }
    }

    /// 清空生成器状态
    pub fn clear(&mut self) {
        self.output.clear();
        self.indent = 0;
        self.label_counter = 0;
        self.string_literals.clear();
        self.globals.clear();
        self.local_offsets.clear();
        self.stack_size = 0;
        self.current_function.clear();
        self.loop_labels.clear();
        self.field_offsets.clear();
        self.local_and_param_types.clear();
    }

    /// 生成唯一标签名
    fn new_label(&mut self, prefix: &str) -> String {
        let label = format!("L_{}_{}", prefix, self.label_counter);
        self.label_counter += 1;
        label
    }

    /// 输出一行汇编
    fn emit_line(&mut self, line: &str) -> NativeResult<()> {
        writeln!(self.output, "{}{}", "    ".repeat(self.indent), line)?;
        Ok(())
    }

    /// 输出原始文本（无缩进）
    fn emit_raw(&mut self, text: &str) -> NativeResult<()> {
        writeln!(self.output, "{}", text)?;
        Ok(())
    }

    /// 生成内存操作数语法
    /// MASM: qword ptr [rbp-8]
    /// NASM: qword [rbp-8]
    fn mem_operand(&self, size: &str, offset: i32) -> String {
        match self.syntax {
            AssemblySyntax::Masm => format!("{} ptr [rbp-{}]", size, offset),
            AssemblySyntax::Nasm => format!("{} [rbp-{}]", size, offset),
        }
    }

    /// 生成简单内存操作数语法（无大小前缀，用于寄存器操作）
    /// MASM: qword ptr [rbp-8]
    /// NASM: [rbp-8]
    fn mem_operand_simple(&self, offset: i32) -> String {
        match self.syntax {
            AssemblySyntax::Masm => format!("qword ptr [rbp-{}]", offset),
            AssemblySyntax::Nasm => format!("[rbp-{}]", offset),
        }
    }

    /// 生成汇编头部
    fn emit_header(&mut self) -> NativeResult<()> {
        self.emit_raw("; Generated by X Compiler Native Backend")?;
        match self.syntax {
            AssemblySyntax::Masm => {
                self.emit_raw("; Target: x86_64-pc-windows-msvc (MASM)")?;
            }
            AssemblySyntax::Nasm => {
                self.emit_raw("; Target: x86_64-unknown-linux-gnu (NASM)")?;
            }
        }
        self.emit_raw("")?;
        Ok(())
    }

    /// 生成数据段
    fn emit_data_section(&mut self) -> NativeResult<()> {
        if self.string_literals.is_empty() && self.globals.is_empty() {
            return Ok(());
        }

        // 克隆数据以避免借用冲突
        let string_literals: Vec<(String, String)> = self
            .string_literals
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        let globals: Vec<(String, GlobalInfo)> = self
            .globals
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();

        match self.syntax {
            AssemblySyntax::Nasm => {
                // NASM 语法
                self.emit_raw("section .rodata")?;
                for (literal, label) in &string_literals {
                    self.emit_raw(&format!("{}:", label))?;
                    self.emit_raw(&format!(
                        "    db \"{}\", 0",
                        escape_assembly_string(literal)
                    ))?;
                }
                self.emit_raw("")?;

                if !globals.is_empty() {
                    self.emit_raw("section .data")?;
                    for (name, info) in &globals {
                        self.emit_raw(&format!("{}:", name))?;
                        if info.initialized {
                            self.emit_raw(&format!("    times {} db 0", info.size))?;
                        } else {
                            self.emit_raw(&format!("    resb {}", info.size))?;
                        }
                    }
                    self.emit_raw("")?;
                }
            }
            AssemblySyntax::Masm => {
                // MASM 语法
                self.emit_raw(".const")?;
                for (literal, label) in &string_literals {
                    self.emit_raw(&format!(
                        "{} BYTE \"{}\", 0",
                        label,
                        escape_assembly_string(literal)
                    ))?;
                }
                self.emit_raw("")?;

                if !globals.is_empty() {
                    self.emit_raw(".data")?;
                    for (name, info) in &globals {
                        if info.initialized {
                            self.emit_raw(&format!("{} BYTE {} DUP (0)", name, info.size))?;
                        } else {
                            self.emit_raw(&format!("{} BYTE {} DUP (?)", name, info.size))?;
                        }
                    }
                    self.emit_raw("")?;
                }
            }
        }
        Ok(())
    }

    /// 收集字符串字面量和全局变量
    fn collect_literals_and_globals(&mut self, lir: &lir::Program) -> NativeResult<()> {
        for decl in &lir.declarations {
            match decl {
                lir::Declaration::Global(global) => {
                    let size = self.type_size(&global.type_);
                    self.globals.insert(
                        global.name.clone(),
                        GlobalInfo {
                            size,
                            initialized: global.initializer.is_some(),
                            align: self.type_align(&global.type_),
                            initializer: global.initializer.clone(),
                        },
                    );
                }
                lir::Declaration::Function(func) => {
                    self.collect_string_literals(&func.body)?;
                }
                lir::Declaration::Struct(strct) => {
                    // Calculate field offsets with proper alignment
                    let mut current_offset = 0;
                    let mut max_alignment = 1;

                    for field in &strct.fields {
                        let align = self.type_align(&field.type_);
                        max_alignment = max_alignment.max(align);

                        // Align current offset to field alignment requirement
                        if current_offset % align != 0 {
                            current_offset += align - (current_offset % align);
                        }

                        let size = self.type_size(&field.type_);
                        self.field_offsets.insert(
                            Self::layout_key(&strct.name, &field.name),
                            current_offset,
                        );
                        current_offset += size;
                    }

                    let _ = current_offset.next_multiple_of(max_alignment.max(1));
                }
                lir::Declaration::Class(cls) => {
                    // Calculate field offsets with proper alignment - same as struct
                    let mut current_offset = 0;
                    let mut max_alignment = 1;

                    for field in &cls.fields {
                        let align = self.type_align(&field.type_);
                        max_alignment = max_alignment.max(align);

                        // Align current offset to field alignment requirement
                        if current_offset % align != 0 {
                            current_offset += align - (current_offset % align);
                        }

                        let size = self.type_size(&field.type_);
                        self.field_offsets.insert(
                            Self::layout_key(&cls.name, &field.name),
                            current_offset,
                        );
                        current_offset += size;
                    }

                    let _ = current_offset.next_multiple_of(max_alignment.max(1));
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn layout_key(struct_name: &str, field: &str) -> String {
        format!("{}::{}", struct_name, field)
    }

    fn collect_var_types_stmt(stmt: &lir::Statement, types: &mut HashMap<String, lir::Type>) {
        match stmt {
            lir::Statement::Variable(var) => {
                types.insert(var.name.clone(), var.type_.clone());
            }
            lir::Statement::Compound(block) => {
                for s in &block.statements {
                    Self::collect_var_types_stmt(s, types);
                }
            }
            lir::Statement::If(if_stmt) => {
                Self::collect_var_types_stmt(&*if_stmt.then_branch, types);
                if let Some(else_branch) = &if_stmt.else_branch {
                    Self::collect_var_types_stmt(&**else_branch, types);
                }
            }
            lir::Statement::For(for_stmt) => {
                if let Some(init) = &for_stmt.initializer {
                    Self::collect_var_types_stmt(&**init, types);
                }
                Self::collect_var_types_stmt(&*for_stmt.body, types);
            }
            lir::Statement::While(while_stmt) => {
                Self::collect_var_types_stmt(&*while_stmt.body, types);
            }
            lir::Statement::DoWhile(do_while) => {
                Self::collect_var_types_stmt(&*do_while.body, types);
            }
            lir::Statement::Switch(sw) => {
                for c in &sw.cases {
                    Self::collect_var_types_stmt(&c.body, types);
                }
                if let Some(def) = &sw.default {
                    Self::collect_var_types_stmt(&**def, types);
                }
            }
            lir::Statement::Match(m) => {
                for case in &m.cases {
                    for s in &case.body.statements {
                        Self::collect_var_types_stmt(s, types);
                    }
                }
            }
            lir::Statement::Try(t) => {
                for s in &t.body.statements {
                    Self::collect_var_types_stmt(s, types);
                }
                for c in &t.catch_clauses {
                    for s in &c.body.statements {
                        Self::collect_var_types_stmt(s, types);
                    }
                }
                if let Some(fin) = &t.finally_block {
                    for s in &fin.statements {
                        Self::collect_var_types_stmt(s, types);
                    }
                }
            }
            lir::Statement::Declaration(lir::Declaration::Function(f)) => {
                for s in &f.body.statements {
                    Self::collect_var_types_stmt(s, types);
                }
            }
            _ => {}
        }
    }

    fn peel_qualified_ty(ty: &lir::Type) -> &lir::Type {
        match ty {
            lir::Type::Qualified(_, inner) => Self::peel_qualified_ty(inner),
            t => t,
        }
    }

    fn struct_name_from_pointer_type(ty: &lir::Type) -> Option<String> {
        let ty = Self::peel_qualified_ty(ty);
        match ty {
            lir::Type::Pointer(inner) => {
                let inner = Self::peel_qualified_ty(inner);
                if let lir::Type::Named(s) = inner {
                    Some(s.clone())
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    fn struct_name_from_aggregate_type(ty: &lir::Type) -> Option<String> {
        let ty = Self::peel_qualified_ty(ty);
        match ty {
            lir::Type::Named(s) => Some(s.clone()),
            _ => None,
        }
    }

    fn infer_pointee_struct_for_expr(&self, expr: &lir::Expression) -> Option<String> {
        match expr {
            lir::Expression::Variable(n) => self
                .local_and_param_types
                .get(n)
                .and_then(Self::struct_name_from_pointer_type),
            lir::Expression::Cast(ty, e) => Self::struct_name_from_pointer_type(ty)
                .or_else(|| self.infer_pointee_struct_for_expr(e)),
            lir::Expression::Parenthesized(e) => self.infer_pointee_struct_for_expr(e),
            _ => None,
        }
    }

    fn infer_aggregate_struct_for_expr(&self, expr: &lir::Expression) -> Option<String> {
        match expr {
            lir::Expression::Variable(n) => self
                .local_and_param_types
                .get(n)
                .and_then(Self::struct_name_from_aggregate_type),
            lir::Expression::Dereference(inner) => self.infer_pointee_struct_for_expr(inner),
            lir::Expression::Cast(ty, e) => Self::struct_name_from_aggregate_type(ty)
                .or_else(|| self.infer_aggregate_struct_for_expr(e)),
            lir::Expression::Parenthesized(e) => self.infer_aggregate_struct_for_expr(e),
            _ => None,
        }
    }

    fn unique_layout_field_offset(&self, field: &str) -> Option<usize> {
        let suffix = format!("::{}", field);
        let mut found: Option<usize> = None;
        for (k, &off) in &self.field_offsets {
            if k.ends_with(&suffix) {
                if found.is_some() {
                    return None;
                }
                found = Some(off);
            }
        }
        found.or_else(|| self.field_offsets.get(field).copied())
    }

    fn resolve_field_offset(
        &self,
        base: &lir::Expression,
        field: &str,
        pointer_member: bool,
    ) -> Option<usize> {
        let by_type = if pointer_member {
            self.infer_pointee_struct_for_expr(base)
        } else {
            self.infer_aggregate_struct_for_expr(base)
        };
        if let Some(s) = by_type {
            let key = Self::layout_key(&s, field);
            if let Some(&o) = self.field_offsets.get(&key) {
                return Some(o);
            }
        }
        self.unique_layout_field_offset(field)
    }

    /// 从语句块收集字符串字面量
    fn collect_string_literals(&mut self, block: &lir::Block) -> NativeResult<()> {
        for stmt in &block.statements {
            self.collect_stmt_strings(stmt)?;
        }
        Ok(())
    }

    fn collect_declaration_strings(&mut self, decl: &lir::Declaration) -> NativeResult<()> {
        match decl {
            lir::Declaration::Function(func) => self.collect_string_literals(&func.body),
            lir::Declaration::Global(g) => {
                if let Some(init) = &g.initializer {
                    self.collect_expr_strings(init)?;
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn collect_pattern_strings(&mut self, pat: &lir::Pattern) -> NativeResult<()> {
        use lir::{Literal, Pattern};
        match pat {
            Pattern::Literal(Literal::String(s)) => {
                if !self.string_literals.contains_key(s) {
                    let label = format!("LC{}", self.string_literals.len());
                    self.string_literals.insert(s.clone(), label);
                }
                Ok(())
            }
            Pattern::Literal(_) => Ok(()),
            Pattern::Constructor(_, ps) => {
                for p in ps {
                    self.collect_pattern_strings(p)?;
                }
                Ok(())
            }
            Pattern::Tuple(ps) => {
                for p in ps {
                    self.collect_pattern_strings(p)?;
                }
                Ok(())
            }
            Pattern::Record(_, fields) => {
                for (_, p) in fields {
                    self.collect_pattern_strings(p)?;
                }
                Ok(())
            }
            Pattern::Or(a, b) => {
                self.collect_pattern_strings(a)?;
                self.collect_pattern_strings(b)
            }
            Pattern::Wildcard | Pattern::Variable(_) => Ok(()),
        }
    }

    /// 从语句收集字符串字面量
    fn collect_stmt_strings(&mut self, stmt: &lir::Statement) -> NativeResult<()> {
        use lir::Statement;
        match stmt {
            Statement::Expression(expr) => self.collect_expr_strings(expr),
            Statement::Declaration(decl) => self.collect_declaration_strings(decl),
            Statement::Variable(var) => {
                if let Some(init) = &var.initializer {
                    self.collect_expr_strings(init)
                } else {
                    Ok(())
                }
            }
            Statement::If(if_stmt) => {
                self.collect_expr_strings(&if_stmt.condition)?;
                self.collect_stmt_strings(&if_stmt.then_branch)?;
                if let Some(else_branch) = &if_stmt.else_branch {
                    self.collect_stmt_strings(else_branch)?;
                }
                Ok(())
            }
            Statement::While(while_stmt) => {
                self.collect_expr_strings(&while_stmt.condition)?;
                self.collect_stmt_strings(&while_stmt.body)
            }
            Statement::DoWhile(do_while) => {
                self.collect_stmt_strings(&*do_while.body)?;
                self.collect_expr_strings(&do_while.condition)
            }
            Statement::For(for_stmt) => {
                if let Some(init) = &for_stmt.initializer {
                    self.collect_stmt_strings(init)?;
                }
                if let Some(cond) = &for_stmt.condition {
                    self.collect_expr_strings(cond)?;
                }
                if let Some(inc) = &for_stmt.increment {
                    self.collect_expr_strings(inc)?;
                }
                self.collect_stmt_strings(&for_stmt.body)
            }
            Statement::Switch(sw) => {
                self.collect_expr_strings(&sw.expression)?;
                for c in &sw.cases {
                    self.collect_expr_strings(&c.value)?;
                    self.collect_stmt_strings(&c.body)?;
                }
                if let Some(def) = &sw.default {
                    self.collect_stmt_strings(def)?;
                }
                Ok(())
            }
            Statement::Match(m) => {
                self.collect_expr_strings(&m.scrutinee)?;
                for case in &m.cases {
                    self.collect_pattern_strings(&case.pattern)?;
                    if let Some(g) = &case.guard {
                        self.collect_expr_strings(g)?;
                    }
                    self.collect_string_literals(&case.body)?;
                }
                Ok(())
            }
            Statement::Try(t) => {
                self.collect_string_literals(&t.body)?;
                for c in &t.catch_clauses {
                    self.collect_string_literals(&c.body)?;
                }
                if let Some(fin) = &t.finally_block {
                    self.collect_string_literals(fin)?;
                }
                Ok(())
            }
            Statement::Return(Some(expr)) => self.collect_expr_strings(expr),
            Statement::Compound(block) => self.collect_string_literals(block),
            _ => Ok(()),
        }
    }

    fn collect_initializer_strings(&mut self, init: &lir::Initializer) -> NativeResult<()> {
        match init {
            lir::Initializer::Expression(e) => self.collect_expr_strings(e),
            lir::Initializer::List(items) => {
                for i in items {
                    self.collect_initializer_strings(i)?;
                }
                Ok(())
            }
            lir::Initializer::Named(_, inner) => self.collect_initializer_strings(inner),
            lir::Initializer::Indexed(idx, inner) => {
                self.collect_expr_strings(idx)?;
                self.collect_initializer_strings(inner)
            }
        }
    }

    /// 从表达式收集字符串字面量
    fn collect_expr_strings(&mut self, expr: &lir::Expression) -> NativeResult<()> {
        use lir::{Expression, Literal};
        match expr {
            Expression::Literal(Literal::String(s)) => {
                if !self.string_literals.contains_key(s) {
                    let label = format!("LC{}", self.string_literals.len());
                    self.string_literals.insert(s.clone(), label);
                }
                Ok(())
            }
            Expression::Literal(_) | Expression::Variable(_) => Ok(()),
            Expression::Unary(_, e) => self.collect_expr_strings(e),
            Expression::Binary(_, left, right) => {
                self.collect_expr_strings(left)?;
                self.collect_expr_strings(right)
            }
            Expression::Ternary(c, t, e) => {
                self.collect_expr_strings(c)?;
                self.collect_expr_strings(t)?;
                self.collect_expr_strings(e)
            }
            Expression::Call(func, args) => {
                self.collect_expr_strings(func)?;
                for arg in args {
                    self.collect_expr_strings(arg)?;
                }
                Ok(())
            }
            Expression::Assign(t, v) => {
                self.collect_expr_strings(t)?;
                self.collect_expr_strings(v)
            }
            Expression::AssignOp(_, t, v) => {
                self.collect_expr_strings(t)?;
                self.collect_expr_strings(v)
            }
            Expression::Index(a, i) => {
                self.collect_expr_strings(a)?;
                self.collect_expr_strings(i)
            }
            Expression::Member(o, _) => self.collect_expr_strings(o),
            Expression::PointerMember(o, _) => self.collect_expr_strings(o),
            Expression::Dereference(e) => self.collect_expr_strings(e),
            Expression::AddressOf(e) => self.collect_expr_strings(e),
            Expression::Cast(_, e) => self.collect_expr_strings(e),
            Expression::Comma(exprs) => {
                for e in exprs {
                    self.collect_expr_strings(e)?;
                }
                Ok(())
            }
            Expression::Parenthesized(e) => self.collect_expr_strings(e),
            Expression::InitializerList(items) => {
                for item in items {
                    self.collect_initializer_strings(item)?;
                }
                Ok(())
            }
            Expression::CompoundLiteral(_, items) => {
                for item in items {
                    self.collect_initializer_strings(item)?;
                }
                Ok(())
            }
            Expression::SizeOf(_) | Expression::AlignOf(_) => Ok(()),
            Expression::SizeOfExpr(e) => self.collect_expr_strings(e),
        }
    }

    /// 生成代码段
    fn emit_text_section(&mut self, lir: &lir::Program) -> NativeResult<()> {
        // 收集本地定义的函数名
        let local_functions: std::collections::HashSet<&str> = lir
            .declarations
            .iter()
            .filter_map(|decl| {
                if let lir::Declaration::Function(func) = decl {
                    Some(func.name.as_str())
                } else {
                    None
                }
            })
            .collect();

        match self.syntax {
            AssemblySyntax::Nasm => {
                // NASM 语法 - 声明外部函数
                self.emit_raw("; External functions")?;
                if !local_functions.contains("printf") {
                    self.emit_raw("extern printf")?;
                }
                if !local_functions.contains("puts") {
                    self.emit_raw("extern puts")?;
                }
                if !local_functions.contains("malloc") {
                    self.emit_raw("extern malloc")?;
                }
                if !local_functions.contains("free") {
                    self.emit_raw("extern free")?;
                }
                if !local_functions.contains("println") {
                    self.emit_raw("extern println")?;
                }
                if !local_functions.contains("print") {
                    self.emit_raw("extern print")?;
                }
                if !local_functions.contains("exit") {
                    self.emit_raw("extern exit")?;
                }
                self.emit_raw("")?;
                self.emit_raw("section .text code")?;
            }
            AssemblySyntax::Masm => {
                // MASM 语法
                // 注意：External functions 在需要时由调用代码生成，不需要预声明
                self.emit_raw(".code")?;
            }
        }

        for decl in &lir.declarations {
            if let lir::Declaration::Function(func) = decl {
                self.emit_function(func)?;
            }
        }

        // MASM 需要结束代码段
        if self.syntax == AssemblySyntax::Masm {
            self.emit_raw("END")?;
        }

        Ok(())
    }

    /// 生成函数
    fn emit_function(&mut self, func: &lir::Function) -> NativeResult<()> {
        self.stack_size = 0;
        self.local_offsets.clear();
        self.current_function = func.name.clone();
        self.local_and_param_types.clear();
        for p in &func.parameters {
            self.local_and_param_types
                .insert(p.name.clone(), p.type_.clone());
        }
        for stmt in &func.body.statements {
            Self::collect_var_types_stmt(stmt, &mut self.local_and_param_types);
        }

        // 函数标签
        if func.name == "main" {
            match self.syntax {
                AssemblySyntax::Nasm => {
                    self.emit_raw(&format!("global {}", func.name))?;
                }
                AssemblySyntax::Masm => {
                    self.emit_raw(&format!("PUBLIC {}", func.name))?;
                }
            }
        }
        self.emit_raw(&format!("{}:", func.name))?;

        // 函数序言
        self.emit_line("push rbp")?;
        self.emit_line("mov rbp, rsp")?;

        // 分配栈空间
        let stack_alloc_label = self.new_label("stack_alloc");
        self.emit_line(&format!("sub rsp, 0  ; {}", stack_alloc_label))?;

        // 保存被调用者保存的寄存器
        let callee_saved = vec!["rbx", "r12", "r13", "r14", "r15"];
        for reg in &callee_saved {
            self.emit_line(&format!("push {}", reg))?;
        }

        // 处理参数
        let arg_regs = if self.os.uses_system_v_abi() {
            vec!["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
        } else {
            vec!["rcx", "rdx", "r8", "r9"]
        };

        for (i, param) in func.parameters.iter().enumerate() {
            if i < arg_regs.len() {
                self.local_offsets
                    .insert(param.name.clone(), ((i + 1) * 8) as i32);
                self.emit_line(&format!(
                    "mov {}, {}",
                    self.mem_operand_simple(((i + 1) * 8) as i32),
                    arg_regs[i]
                ))?;
            }
        }

        // 生成函数体
        self.emit_block(&func.body)?;

        // 函数尾声
        let epilogue_label = format!("L_{}_epilogue", func.name);
        self.emit_raw(&format!("{}:", epilogue_label))?;

        for reg in callee_saved.iter().rev() {
            self.emit_line(&format!("pop {}", reg))?;
        }

        self.emit_line("mov rsp, rbp")?;
        self.emit_line("pop rbp")?;
        self.emit_line("ret")?;
        self.emit_raw("")?;

        Ok(())
    }

    /// 生成语句块
    fn emit_block(&mut self, block: &lir::Block) -> NativeResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    /// 生成语句
    fn emit_statement(&mut self, stmt: &lir::Statement) -> NativeResult<()> {
        use lir::Statement;
        match stmt {
            Statement::Expression(expr) => {
                self.emit_expr(expr)?;
            }
            Statement::Variable(var) => {
                self.stack_size += 8;
                let offset = self.stack_size as i32;
                self.local_offsets.insert(var.name.clone(), offset);

                if let Some(init) = &var.initializer {
                    self.emit_expr(init)?;
                    self.emit_line(&format!("mov {}, rax", self.mem_operand_simple(offset)))?;
                } else {
                    self.emit_line(&format!("mov {}, 0", self.mem_operand("qword", offset)))?;
                }
            }
            Statement::Return(Some(expr)) => {
                self.emit_expr(expr)?;
                self.emit_line("mov rsp, rbp")?;
                self.emit_line("pop rbp")?;
                self.emit_line("ret")?;
            }
            Statement::Return(None) => {
                self.emit_line("xor rax, rax")?;
                self.emit_line("mov rsp, rbp")?;
                self.emit_line("pop rbp")?;
                self.emit_line("ret")?;
            }
            Statement::If(if_stmt) => {
                let else_label = self.new_label("else");
                let end_label = self.new_label("endif");

                self.emit_expr(&if_stmt.condition)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", else_label))?;

                self.emit_statement(&if_stmt.then_branch)?;
                self.emit_line(&format!("jmp {}", end_label))?;

                self.emit_raw(&format!("{}:", else_label))?;
                if let Some(else_branch) = &if_stmt.else_branch {
                    self.emit_statement(else_branch)?;
                }
                self.emit_raw(&format!("{}:", end_label))?;
            }
            Statement::While(while_stmt) => {
                let start_label = self.new_label("while_start"); // continue jumps here (recheck condition)
                let end_label = self.new_label("while_end"); // break jumps here

                // Push to label stack for break/continue
                self.loop_labels
                    .push((start_label.clone(), end_label.clone()));

                self.emit_raw(&format!("{}:", start_label))?;
                self.emit_expr(&while_stmt.condition)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", end_label))?;

                self.emit_statement(&while_stmt.body)?;
                self.emit_line(&format!("jmp {}", start_label))?;

                self.emit_raw(&format!("{}:", end_label))?;

                // Pop from stack
                self.loop_labels.pop();
            }
            Statement::DoWhile(do_while) => {
                let start_label = self.new_label("do_start");
                let cond_label = self.new_label("do_cond");
                let end_label = self.new_label("do_end");

                // continue -> go to condition check (then back to start if condition true)
                // break -> exit to end_label
                self.loop_labels
                    .push((cond_label.clone(), end_label.clone()));

                self.emit_raw(&format!("{}:", start_label))?;

                self.indent += 1;
                self.emit_statement(&do_while.body)?;
                self.emit_line(&format!("jmp {}", cond_label))?;
                self.indent -= 1;

                self.emit_raw(&format!("{}:", cond_label))?;
                self.emit_expr(&do_while.condition)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jnz {}", start_label))?;

                self.emit_raw(&format!("{}:", end_label))?;

                // Pop from stack
                self.loop_labels.pop();
            }
            Statement::For(for_stmt) => {
                let start_label = self.new_label("for_start");
                let end_label = self.new_label("for_end");
                // continue -> go to condition check (then loop if true)
                // break -> exit to end_label

                // initializer
                if let Some(init) = &for_stmt.initializer {
                    self.emit_statement(init)?;
                }

                // Push to label stack
                self.loop_labels
                    .push((start_label.clone(), end_label.clone()));

                self.emit_raw(&format!("{}:", start_label))?;

                // condition check
                self.indent += 1;
                if let Some(cond) = &for_stmt.condition {
                    self.emit_expr(cond)?;
                    self.emit_line("test rax, rax")?;
                    self.emit_line(&format!("jz {}", end_label))?;
                }

                // loop body
                self.emit_statement(&for_stmt.body)?;

                // increment
                if let Some(inc) = &for_stmt.increment {
                    self.emit_expr(inc)?;
                }

                self.emit_line(&format!("jmp {}", start_label))?;
                self.indent -= 1;

                self.emit_raw(&format!("{}:", end_label))?;

                // Pop from stack
                self.loop_labels.pop();
            }
            Statement::Compound(block) => {
                self.emit_block(block)?;
            }
            Statement::Break => {
                // break jumps to the current loop's break target
                if let Some((_continue_label, break_label)) = self.loop_labels.last() {
                    self.emit_line(&format!("jmp {}", break_label))?;
                } else {
                    self.emit_line("; TODO: break outside loop")?;
                }
            }
            Statement::Continue => {
                // continue jumps to the current loop's continue target (condition check / loop start)
                if let Some((continue_label, _break_label)) = self.loop_labels.last() {
                    self.emit_line(&format!("jmp {}", continue_label))?;
                } else {
                    self.emit_line("; TODO: continue outside loop")?;
                }
            }
            Statement::Empty => {}
            _ => {
                // 其他语句类型的简化处理
                self.emit_line(&format!("; TODO: {:?}", std::mem::discriminant(stmt)))?;
            }
        }
        Ok(())
    }

    /// 嵌套 `Initializer` 展平后的栈槽数（每项 8 字节，与遗留 NativeBackend 一致）。
    fn count_flat_initializer_slots(init: &lir::Initializer) -> usize {
        match init {
            lir::Initializer::Expression(_) => 1,
            lir::Initializer::List(list) => list.iter().map(Self::count_flat_initializer_slots).sum(),
            lir::Initializer::Named(_, inner) => Self::count_flat_initializer_slots(inner),
            lir::Initializer::Indexed(_, inner) => Self::count_flat_initializer_slots(inner),
        }
    }

    fn count_flat_initializer_list_slots(items: &[lir::Initializer]) -> usize {
        items.iter().map(Self::count_flat_initializer_slots).sum()
    }

    /// `Indexed` 先求下标（副作用），内层值写入下一槽位（非真实稀疏布局）。
    fn emit_flat_initializer_on_stack(
        &mut self,
        init: &lir::Initializer,
        slot: &mut usize,
    ) -> NativeResult<()> {
        match init {
            lir::Initializer::Expression(e) => {
                self.emit_expr(e)?;
                self.emit_line(&format!("mov [rsp+{}], rax", *slot * 8))?;
                *slot += 1;
            }
            lir::Initializer::List(list) => {
                for i in list {
                    self.emit_flat_initializer_on_stack(i, slot)?;
                }
            }
            lir::Initializer::Named(_, inner) => {
                self.emit_flat_initializer_on_stack(inner, slot)?;
            }
            lir::Initializer::Indexed(idx, inner) => {
                self.emit_expr(idx)?;
                self.emit_flat_initializer_on_stack(inner, slot)?;
            }
        }
        Ok(())
    }

    fn emit_initializer_list_on_stack(&mut self, items: &[lir::Initializer]) -> NativeResult<()> {
        let num_slots = Self::count_flat_initializer_list_slots(items);
        let size = num_slots * 8;
        self.emit_line(&format!("sub rsp, {}", size))?;
        let mut slot = 0usize;
        for item in items {
            self.emit_flat_initializer_on_stack(item, &mut slot)?;
        }
        debug_assert_eq!(slot, num_slots);
        self.emit_line("mov rax, rsp")?;
        Ok(())
    }

    /// 生成表达式
    fn emit_expr(&mut self, expr: &lir::Expression) -> NativeResult<()> {
        use lir::{BinaryOp, Expression, UnaryOp};
        match expr {
            Expression::Literal(lit) => self.emit_literal(lit)?,
            Expression::Variable(name) => {
                if let Some(offset) = self.local_offsets.get(name) {
                    self.emit_line(&format!("mov rax, {}", self.mem_operand_simple(*offset)))?;
                } else if self.globals.contains_key(name) {
                    self.emit_line(&format!("mov rax, [{}]", name))?;
                } else {
                    return Err(NativeError::CodegenError(format!(
                        "Undefined variable: {}",
                        name
                    )));
                }
            }
            Expression::Unary(op, e) => {
                self.emit_expr(e)?;
                match op {
                    UnaryOp::Minus => {
                        self.emit_line("neg rax")?;
                    }
                    UnaryOp::BitNot => {
                        self.emit_line("not rax")?;
                    }
                    UnaryOp::Not => {
                        self.emit_line("test rax, rax")?;
                        self.emit_line("setz al")?;
                        self.emit_line("movzx rax, al")?;
                    }
                    _ => {}
                }
            }
            Expression::Binary(op, left, right) => {
                self.emit_binary(*op, left, right)?;
            }
            Expression::Call(func, args) => {
                self.emit_call(func, args)?;
            }
            Expression::Assign(target, value) => {
                self.emit_expr(value)?;
                match target.as_ref() {
                    Expression::Variable(name) => {
                        if let Some(offset) = self.local_offsets.get(name) {
                            self.emit_line(&format!(
                                "mov {}, rax",
                                self.mem_operand_simple(*offset)
                            ))?;
                        } else if self.globals.contains_key(name) {
                            self.emit_line(&format!("mov [{}], rax", name))?;
                        }
                    }
                    Expression::Dereference(ptr) => {
                        self.emit_expr(ptr)?;
                        self.emit_line("mov [rax], rax")?;
                    }
                    Expression::Member(obj, field) => {
                        self.emit_expr(obj)?;
                        let offset = self.resolve_field_offset(obj, field, false).unwrap_or(0);
                        if offset > 0 {
                            self.emit_line(&format!("add rax, {}", offset))?;
                        }
                        self.emit_line("mov [rax], rax")?;
                    }
                    Expression::PointerMember(obj, field) => {
                        self.emit_expr(obj)?;
                        self.emit_line("mov rax, [rax]")?;
                        let offset = self.resolve_field_offset(obj, field, true).unwrap_or(0);
                        if offset > 0 {
                            self.emit_line(&format!("add rax, {}", offset))?;
                        }
                        self.emit_line("mov [rax], rax")?;
                    }
                    Expression::Index(arr, idx) => {
                        self.emit_expr(arr)?;
                        self.emit_line("mov rcx, rax")?;
                        self.emit_expr(idx)?;
                        self.emit_line("shl rax, 3")?; // 假设 8 字节元素
                        self.emit_line("add rcx, rax")?;
                        self.emit_line("mov [rcx], rax")?;
                    }
                    _ => {
                        self.emit_line("; TODO: complex assign target")?;
                    }
                }
            }
            Expression::AssignOp(op, target, value) => {
                // 处理如 +=, -= 等复合赋值
                self.emit_expr(target)?;
                self.emit_line("push rax")?;
                self.emit_expr(value)?;
                self.emit_line("mov rcx, rax")?;
                self.emit_line("pop rax")?;
                match op {
                    BinaryOp::Add => self.emit_line("add rax, rcx")?,
                    BinaryOp::Subtract => self.emit_line("sub rax, rcx")?,
                    BinaryOp::Multiply => self.emit_line("imul rax, rcx")?,
                    BinaryOp::Divide => {
                        self.emit_line("cqo")?;
                        self.emit_line("idiv rcx")?;
                    }
                    BinaryOp::Modulo => {
                        self.emit_line("cqo")?;
                        self.emit_line("idiv rcx")?;
                        self.emit_line("mov rax, rdx")?;
                    }
                    BinaryOp::BitAnd => self.emit_line("and rax, rcx")?,
                    BinaryOp::BitOr => self.emit_line("or rax, rcx")?,
                    BinaryOp::BitXor => self.emit_line("xor rax, rcx")?,
                    BinaryOp::LeftShift => self.emit_line("shl rax, cl")?,
                    BinaryOp::RightShift => self.emit_line("shr rax, cl")?,
                    BinaryOp::RightShiftArithmetic => self.emit_line("sar rax, cl")?,
                    _ => self.emit_line("; TODO: unsupported assign op")?,
                }
                // 存回目标
                match target.as_ref() {
                    Expression::Variable(name) => {
                        if let Some(offset) = self.local_offsets.get(name) {
                            self.emit_line(&format!(
                                "mov {}, rax",
                                self.mem_operand_simple(*offset)
                            ))?;
                        }
                    }
                    _ => {}
                }
            }
            Expression::SizeOf(ty) => {
                let size = self.type_size(ty);
                self.emit_line(&format!("mov rax, {}", size))?;
            }
            Expression::SizeOfExpr(expr) => {
                // SizeOfExpr - since LIR Expression doesn't carry type info,
                // we default to 8 bytes (pointer size on x86_64)
                let _ = expr;
                self.emit_line("mov rax, 8")?;
            }
            Expression::AlignOf(ty) => {
                let align = self.type_align(ty);
                self.emit_line(&format!("mov rax, {}", align))?;
            }
            Expression::Ternary(cond, then, else_) => {
                let else_label = self.new_label("ternary_else");
                let end_label = self.new_label("ternary_end");

                self.emit_expr(cond)?;
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", else_label))?;

                self.emit_expr(then)?;
                self.emit_line(&format!("jmp {}", end_label))?;

                self.emit_raw(&format!("{}:", else_label))?;
                self.emit_expr(else_)?;

                self.emit_raw(&format!("{}:", end_label))?;
            }
            Expression::Cast(ty, expr) => {
                self.emit_expr(expr)?;
                // Basic casting between integer types is handled implicitly
                // since everything is in rax as 64-bit. For floating point we'd need
                // proper instructions, but this handles the common case.
                let _ = ty;
            }
            Expression::AddressOf(expr) => match expr.as_ref() {
                Expression::Variable(name) => {
                    if let Some(offset) = self.local_offsets.get(name) {
                        self.emit_line(&format!("lea rax, [rbp-{}]", offset))?;
                    }
                }
                _ => self.emit_expr(expr)?,
            },
            Expression::Dereference(expr) => {
                self.emit_expr(expr)?;
                self.emit_line("mov rax, [rax]")?;
            }
            Expression::Index(arr, idx) => {
                self.emit_expr(arr)?;
                self.emit_line("push rax")?;
                self.emit_expr(idx)?;
                self.emit_line("mov rcx, rax")?;
                self.emit_line("pop rax")?;
                self.emit_line("shl rcx, 3")?; // 假设 8 字节元素
                self.emit_line("add rax, rcx")?;
                self.emit_line("mov rax, [rax]")?;
            }
            Expression::Member(obj, field) => {
                self.emit_expr(obj)?;
                let offset = self.resolve_field_offset(obj, field, false).unwrap_or(0);
                if offset > 0 {
                    self.emit_line(&format!("add rax, {}", offset))?;
                }
                self.emit_line("mov rax, [rax]")?;
            }
            Expression::PointerMember(obj, field) => {
                self.emit_expr(obj)?;
                self.emit_line("mov rax, [rax]")?;
                let offset = self.resolve_field_offset(obj, field, true).unwrap_or(0);
                if offset > 0 {
                    self.emit_line(&format!("add rax, {}", offset))?;
                }
                self.emit_line("mov rax, [rax]")?;
            }
            Expression::Comma(exprs) => {
                for expr in exprs.iter() {
                    self.emit_expr(expr)?;
                }
            }
            Expression::Parenthesized(expr) => {
                self.emit_expr(expr)?;
            }
            Expression::InitializerList(items) => {
                self.emit_initializer_list_on_stack(items)?;
            }
            Expression::CompoundLiteral(_, items) => {
                self.emit_initializer_list_on_stack(items)?;
            }
        }
        Ok(())
    }

    /// 生成字面量
    fn emit_literal(&mut self, lit: &lir::Literal) -> NativeResult<()> {
        use lir::Literal;
        match lit {
            Literal::Integer(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::UnsignedInteger(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::Long(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::UnsignedLong(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::LongLong(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::UnsignedLongLong(n) => {
                self.emit_line(&format!("mov rax, {}", n))?;
            }
            Literal::Bool(b) => {
                self.emit_line(&format!("mov rax, {}", if *b { 1 } else { 0 }))?;
            }
            Literal::Float(f) => {
                // 浮点数需要特殊处理，简化为整数
                self.emit_line(&format!("mov rax, {}", *f as i64))?;
            }
            Literal::Double(f) => {
                self.emit_line(&format!("mov rax, {}", *f as i64))?;
            }
            Literal::String(s) => {
                if let Some(label) = self.string_literals.get(s) {
                    self.emit_line(&format!("lea rax, [rel {}]", label))?;
                }
            }
            Literal::Char(c) => {
                self.emit_line(&format!("mov rax, {}", *c as i64))?;
            }
            Literal::NullPointer => {
                self.emit_line("xor rax, rax")?;
            }
        }
        Ok(())
    }

    /// 生成二元运算
    fn emit_binary(
        &mut self,
        op: lir::BinaryOp,
        left: &lir::Expression,
        right: &lir::Expression,
    ) -> NativeResult<()> {
        use lir::BinaryOp;

        self.emit_expr(left)?;
        self.emit_line("push rax")?;
        self.emit_expr(right)?;
        self.emit_line("mov rcx, rax")?;
        self.emit_line("pop rax")?;

        match op {
            BinaryOp::Add => self.emit_line("add rax, rcx")?,
            BinaryOp::Subtract => self.emit_line("sub rax, rcx")?,
            BinaryOp::Multiply => self.emit_line("imul rax, rcx")?,
            BinaryOp::Divide => {
                self.emit_line("cqo")?;
                self.emit_line("idiv rcx")?;
            }
            BinaryOp::Modulo => {
                self.emit_line("cqo")?;
                self.emit_line("idiv rcx")?;
                self.emit_line("mov rax, rdx")?; // 余数在 rdx
            }
            BinaryOp::Equal => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("sete al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::NotEqual => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setne al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::LessThan => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setl al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::LessThanEqual => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setle al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::GreaterThan => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setg al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::GreaterThanEqual => {
                self.emit_line("cmp rax, rcx")?;
                self.emit_line("setge al")?;
                self.emit_line("movzx rax, al")?;
            }
            BinaryOp::BitAnd => self.emit_line("and rax, rcx")?,
            BinaryOp::BitOr => self.emit_line("or rax, rcx")?,
            BinaryOp::BitXor => self.emit_line("xor rax, rcx")?,
            BinaryOp::LeftShift => self.emit_line("shl rax, cl")?,
            BinaryOp::RightShift => self.emit_line("shr rax, cl")?,
            BinaryOp::RightShiftArithmetic => self.emit_line("sar rax, cl")?,
            BinaryOp::LogicalAnd => {
                let end_label = self.new_label("logical_and_end");
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jz {}", end_label))?;
                self.emit_line("mov rax, rcx")?;
                self.emit_line("test rax, rax")?;
                self.emit_raw(&format!("{}:", end_label))?;
            }
            BinaryOp::LogicalOr => {
                let end_label = self.new_label("logical_or_end");
                self.emit_line("test rax, rax")?;
                self.emit_line(&format!("jnz {}", end_label))?;
                self.emit_line("mov rax, rcx")?;
                self.emit_raw(&format!("{}:", end_label))?;
            }
        }
        Ok(())
    }

    /// 生成函数调用
    fn emit_call(&mut self, func: &lir::Expression, args: &[lir::Expression]) -> NativeResult<()> {
        // 保存参数
        for arg in args.iter().rev() {
            self.emit_expr(arg)?;
            self.emit_line("push rax")?;
        }

        // 获取函数名
        if let lir::Expression::Variable(name) = func {
            // 恢复参数到寄存器
            let arg_regs = if self.os.uses_system_v_abi() {
                vec!["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
            } else {
                vec!["rcx", "rdx", "r8", "r9"]
            };

            for (i, _) in args.iter().enumerate().take(arg_regs.len()) {
                self.emit_line(&format!("pop {}", arg_regs[i]))?;
            }

            // 调整栈对齐
            self.emit_line(&format!("call {}", name))?;
        } else {
            // Indirect call - call via register
            self.emit_expr(func)?; // result goes to rax
            self.emit_line("call rax")?;
        }

        Ok(())
    }

    /// 获取类型大小
    fn type_size(&self, ty: &lir::Type) -> usize {
        use lir::Type;
        match ty {
            Type::Void => 0,
            Type::Bool => 1,
            Type::Char | Type::Schar | Type::Uchar => 1,
            Type::Short | Type::Ushort => 2,
            Type::Int | Type::Uint | Type::Float => 4,
            Type::Long | Type::Ulong | Type::Double | Type::Pointer(_) => 8,
            Type::LongLong | Type::UlongLong | Type::LongDouble => 16,
            _ => 8,
        }
    }

    /// 获取类型对齐
    fn type_align(&self, ty: &lir::Type) -> usize {
        self.type_size(ty).max(1)
    }
}

impl AssemblyGenerator for X86_64AssemblyGenerator {
    fn generate(&mut self, lir: &x_lir::Program) -> NativeResult<String> {
        self.clear();
        self.collect_literals_and_globals(lir)?;
        self.emit_header()?;
        self.emit_data_section()?;
        self.emit_text_section(lir)?;
        Ok(self.output.clone())
    }

    fn arch(&self) -> TargetArch {
        TargetArch::X86_64
    }
}

// ============================================================================
// 单元测试
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_creation() {
        let gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        assert_eq!(gen.arch(), TargetArch::X86_64);
    }

    #[test]
    fn test_simple_function() {
        let mut lir = lir::Program::new();
        let mut func = lir::Function::new("main", lir::Type::Int);
        func.body
            .statements
            .push(lir::Statement::Return(Some(lir::Expression::int(42))));
        lir.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        let result = gen.generate(&lir).unwrap();

        assert!(result.contains("main:"));
        assert!(result.contains("mov rax, 42"));
        assert!(result.contains("ret"));
    }

    #[test]
    fn test_binary_add() {
        let mut lir = lir::Program::new();
        let mut func = lir::Function::new("test", lir::Type::Int);
        func.body.statements.push(lir::Statement::Return(Some(
            lir::Expression::int(10).add(lir::Expression::int(20)),
        )));
        lir.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        let result = gen.generate(&lir).unwrap();

        assert!(result.contains("add rax, rcx"));
    }

    #[test]
    fn test_windows_abi() {
        let mut lir = lir::Program::new();
        let mut func = lir::Function::new("test", lir::Type::Int);
        func.parameters.push(lir::Parameter {
            name: "x".to_string(),
            type_: lir::Type::Int,
        });
        func.body
            .statements
            .push(lir::Statement::Return(Some(lir::Expression::var("x"))));
        lir.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Windows);
        let result = gen.generate(&lir).unwrap();

        // Windows uses rcx for first argument (MASM uses qword ptr)
        assert!(result.contains("mov qword ptr [rbp-8], rcx"));
    }

    #[test]
    fn test_two_structs_same_field_name_pointer_member() {
        let mut program = lir::Program::new();
        program.add(lir::Declaration::Struct(lir::Struct {
            name: "A".into(),
            fields: vec![lir::Field {
                name: "x".into(),
                type_: lir::Type::Int,
            }],
        }));
        program.add(lir::Declaration::Struct(lir::Struct {
            name: "B".into(),
            fields: vec![
                lir::Field {
                    name: "pad".into(),
                    type_: lir::Type::Int,
                },
                lir::Field {
                    name: "x".into(),
                    type_: lir::Type::Int,
                },
            ],
        }));
        let mut func = lir::Function::new("main", lir::Type::Int).param(
            "pb",
            lir::Type::Pointer(Box::new(lir::Type::Named("B".into()))),
        );
        func.body.statements.push(lir::Statement::Return(Some(
            lir::Expression::PointerMember(Box::new(lir::Expression::var("pb")), "x".into()),
        )));
        program.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        let asm = gen.generate(&program).unwrap();
        assert!(
            asm.contains("add rax, 4"),
            "应按 *B 使用 `B::x` 偏移 4，而非 `A::x` 的 0: {asm}"
        );
    }

    #[test]
    fn test_nested_initializer_list_string_in_rodata() {
        let mut program = lir::Program::new();
        let mut func = lir::Function::new("main", lir::Type::Int);
        func.body.statements.push(lir::Statement::Expression(
            lir::Expression::InitializerList(vec![lir::Initializer::List(vec![
                lir::Initializer::Expression(lir::Expression::Literal(lir::Literal::String(
                    "rodata_nested".into(),
                ))),
            ])]),
        ));
        func.body
            .statements
            .push(lir::Statement::Return(Some(lir::Expression::int(0))));
        program.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        let asm = gen.generate(&program).unwrap();
        assert!(
            asm.contains(r#"db "rodata_nested""#),
            "嵌套 Initializer::List 内的字符串须进入 .rodata: {asm}"
        );
    }

    #[test]
    fn test_emit_nested_initializer_list_allocates_flat_stack() {
        let mut program = lir::Program::new();
        let mut func = lir::Function::new("main", lir::Type::Int);
        func.body.statements.push(lir::Statement::Return(Some(
            lir::Expression::InitializerList(vec![lir::Initializer::List(vec![
                lir::Initializer::Expression(lir::Expression::int(1)),
                lir::Initializer::Expression(lir::Expression::int(2)),
            ])]),
        )));
        program.add(lir::Declaration::Function(func));

        let mut gen = X86_64AssemblyGenerator::new(TargetOS::Linux);
        let asm = gen.generate(&program).unwrap();
        assert!(
            asm.lines().any(|l| l.trim() == "sub rsp, 16"),
            "嵌套 List 应分配展平后的 16 字节: {asm}"
        );
        assert!(
            !asm.contains("TODO: initializer list") && !asm.contains("TODO: compound literal"),
            "不应再保留 initializer/compound 的 TODO 占位: {asm}"
        );
    }
}
