//! C# 后端 - 生成 C# 14 源代码
//!
//! 面向 .NET 10 平台，生成 C# 源代码
//!
//! ## C# 14 / .NET 10 特性支持 (2026年3月发布)
//! - Primary constructors（主构造函数）
//! - Collection expressions（集合表达式）
//! - Inline arrays（内联数组）
//! - Extended nameof scope
//! - Implicit span conversions
//! - Params Span/ReadOnlySpan
//! - Partial properties
//! - Field-backed properties
//! - Method group natural type improvements

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, ExpressionKind, StatementKind, Program as AstProgram};

/// C# 后端配置
#[derive(Debug, Clone)]
pub struct CSharpConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
    pub namespace: Option<String>,
}

impl Default for CSharpConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            namespace: None,
        }
    }
}

/// C# 后端
pub struct CSharpBackend {
    config: CSharpConfig,
    indent: usize,
    output: String,
    /// 当前正在生成的类名（用于实例方法生成）
    current_class: Option<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum CSharpError {
    #[error("C# 代码生成错误: {0}")]
    GenerationError(String),
    #[error("未实现: {0}")]
    Unimplemented(String),
    #[error("IO 错误: {0}")]
    IoError(#[from] std::io::Error),
    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("不支持的功能: {0}")]
    UnsupportedFeature(String),
}

pub type CSharpResult<T> = Result<T, CSharpError>;

impl CSharpBackend {
    pub fn new(config: CSharpConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            current_class: None,
        }
    }

    /// 从 AST 生成 C# 代码
    pub fn generate_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> CSharpResult<x_codegen::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;

        // 获取命名空间
        let namespace = self.config.namespace.clone().unwrap_or_else(|| "XLang".to_string());

        self.line(&format!("namespace {}", namespace))?;
        self.line("{")?;
        self.indent += 1;

        // 生成类定义
        for decl in &program.declarations {
            if let ast::Declaration::Class(class) = decl {
                self.emit_class(class)?;
            }
        }

        // 生成枚举
        for decl in &program.declarations {
            if let ast::Declaration::Enum(enum_decl) = decl {
                self.emit_enum(enum_decl)?;
            }
        }

        // 生成全局变量（作为静态字段）
        for decl in &program.declarations {
            if let ast::Declaration::Variable(v) = decl {
                self.emit_global_var(v)?;
            }
        }

        // 生成函数（作为静态方法）
        let mut has_main = false;
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                if f.name == "main" || f.name == "Main" {
                    has_main = true;
                }
                self.emit_function(f, None)?;
                self.line("")?;
            }
        }

        // 如果没有 Main 方法，生成一个默认的
        if !has_main {
            self.emit_default_main()?;
        }

        self.indent -= 1;
        self.line("}")?;

        // 创建输出文件
        let output_file = x_codegen::OutputFile {
            path: std::path::PathBuf::from("Program.cs"),
            content: self.output.as_bytes().to_vec(),
            file_type: x_codegen::FileType::CSharp,
        };

        Ok(x_codegen::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    /// 生成文件头部 (C# 14 / .NET 10)
    fn emit_header(&mut self) -> CSharpResult<()> {
        self.line("// Generated by X-Lang C# 14 backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("// Target: C# 14 / .NET 10 LTS (March 2026)")?;
        self.line("")?;
        self.line("using System;")?;
        self.line("using System.Collections.Generic;")?;
        self.line("using System.Threading.Tasks;")?;
        self.line("using System.Linq;")?;
        self.line("")?;
        Ok(())
    }

    /// 生成类定义 (C# 12: 支持主构造函数)
    fn emit_class(&mut self, class: &ast::ClassDecl) -> CSharpResult<()> {
        self.current_class = Some(class.name.clone());

        // 类修饰符
        let modifiers = if class.modifiers.is_abstract {
            "abstract "
        } else if class.modifiers.is_final {
            "sealed "
        } else {
            ""
        };

        // 继承
        let mut bases = Vec::new();
        if let Some(parent) = &class.extends {
            bases.push(parent.clone());
        }
        bases.extend(class.implements.clone());

        // C# 12: 检查是否有主构造函数参数
        let primary_ctor = if let Some(constructor) = class.members.iter()
            .find_map(|m| if let ast::ClassMember::Constructor(c) = m { Some(c) } else { None }) {
            if !constructor.parameters.is_empty() {
                let params: Vec<String> = constructor.parameters.iter()
                    .map(|p| {
                        let type_str = self.map_type_from_ast(p.type_annot.as_ref());
                        format!("{} {}", type_str, p.name)
                    })
                    .collect();
                format!("({})", params.join(", "))
            } else {
                String::new()
            }
        } else {
            String::new()
        };

        let base_str = if bases.is_empty() {
            String::new()
        } else {
            format!(" : {}", bases.join(", "))
        };

        self.line(&format!("{}public class {}{}{}", modifiers, class.name, primary_ctor, base_str))?;
        self.line("{")?;
        self.indent += 1;

        // 生成字段
        for member in &class.members {
            if let ast::ClassMember::Field(field) = member {
                self.emit_field(field)?;
            }
        }

        // 生成构造函数 (如果参数为空，不需要单独生成)
        for member in &class.members {
            if let ast::ClassMember::Constructor(constructor) = member {
                if constructor.parameters.is_empty() && !constructor.body.statements.is_empty() {
                    self.emit_constructor(class.name.as_str(), constructor)?;
                    self.line("")?;
                }
            }
        }

        // 生成方法
        for member in &class.members {
            if let ast::ClassMember::Method(method) = member {
                self.emit_method(method)?;
                self.line("")?;
            }
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;

        self.current_class = None;
        Ok(())
    }

    /// 生成字段
    fn emit_field(&mut self, field: &ast::VariableDecl) -> CSharpResult<()> {
        let visibility = self.map_visibility(field.visibility);
        let type_str = self.map_type_from_ast(field.type_annot.as_ref());
        let init = if let Some(expr) = &field.initializer {
            format!(" = {}", self.emit_expr(expr)?)
        } else {
            String::new()
        };
        self.line(&format!("{}{} {}{};", visibility, type_str, field.name, init))?;
        Ok(())
    }

    /// 生成构造函数
    fn emit_constructor(&mut self, class_name: &str, constructor: &ast::ConstructorDecl) -> CSharpResult<()> {
        let params: Vec<String> = constructor
            .parameters
            .iter()
            .map(|p| {
                let type_str = self.map_type_from_ast(p.type_annot.as_ref());
                format!("{} {}", type_str, p.name)
            })
            .collect();

        let visibility = self.map_visibility(constructor.visibility);
        self.line(&format!("{}{}({})", visibility, class_name, params.join(", ")))?;
        self.line("{")?;
        self.indent += 1;

        // 生成构造函数体
        for stmt in &constructor.body.statements {
            self.emit_stmt(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成方法
    fn emit_method(&mut self, method: &ast::FunctionDecl) -> CSharpResult<()> {
        let modifiers = self.map_method_modifiers(&method.modifiers);
        let return_type = self.map_type_from_ast(method.return_type.as_ref());
        let params: Vec<String> = method
            .parameters
            .iter()
            .map(|p| {
                let type_str = self.map_type_from_ast(p.type_annot.as_ref());
                format!("{} {}", type_str, p.name)
            })
            .collect();

        let async_keyword = if method.is_async { "async " } else { "" };
        self.line(&format!(
            "{}{}{} {}({})",
            modifiers, async_keyword, return_type, method.name, params.join(", ")
        ))?;
        self.line("{")?;
        self.indent += 1;

        self.emit_block(&method.body)?;

        // 如果有返回类型但块中没有显式 return，添加默认返回
        if method.return_type.is_some() {
            // 可以添加 return default; 但这通常是可选的
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成枚举
    fn emit_enum(&mut self, enum_decl: &ast::EnumDecl) -> CSharpResult<()> {
        // 检查是否是简单枚举（所有变体都是 Unit 类型）
        let is_simple_enum = enum_decl.variants.iter().all(|v| {
            matches!(v.data, ast::EnumVariantData::Unit)
        });

        if is_simple_enum {
            // 简单枚举：生成 C# enum
            self.line(&format!("public enum {}", enum_decl.name))?;
            self.line("{")?;
            self.indent += 1;

            for (i, variant) in enum_decl.variants.iter().enumerate() {
                if i > 0 {
                    self.line(",")?;
                }
                self.line(&variant.name)?;
            }

            self.indent -= 1;
            self.line("}")?;
        } else {
            // 复杂枚举：生成抽象类 + 子类
            self.line(&format!("public abstract class {}", enum_decl.name))?;
            self.line("{")?;
            self.indent += 1;

            // 为每个变体生成嵌套类
            for variant in &enum_decl.variants {
                match &variant.data {
                    ast::EnumVariantData::Unit => {
                        self.line(&format!("public class {} : {} {{}}", variant.name, enum_decl.name))?;
                    }
                    ast::EnumVariantData::Tuple(types) => {
                        self.line(&format!("public class {} : {}", variant.name, enum_decl.name))?;
                        self.line("{")?;
                        self.indent += 1;
                        for (i, ty) in types.iter().enumerate() {
                            let type_str = self.map_ast_type(ty);
                            self.line(&format!("public {} Item{};", type_str, i + 1))?;
                        }
                        self.indent -= 1;
                        self.line("}")?;
                    }
                    ast::EnumVariantData::Record(fields) => {
                        self.line(&format!("public class {} : {}", variant.name, enum_decl.name))?;
                        self.line("{")?;
                        self.indent += 1;
                        for (field_name, field_type) in fields {
                            let type_str = self.map_ast_type(field_type);
                            self.line(&format!("public {} {};", type_str, field_name))?;
                        }
                        self.indent -= 1;
                        self.line("}")?;
                    }
                }
            }

            self.indent -= 1;
            self.line("}")?;
        }
        self.line("")?;
        Ok(())
    }

    /// 生成全局变量（作为静态字段）
    fn emit_global_var(&mut self, v: &ast::VariableDecl) -> CSharpResult<()> {
        let type_str = self.map_type_from_ast(v.type_annot.as_ref());
        let init = if let Some(expr) = &v.initializer {
            format!(" = {}", self.emit_expr(expr)?)
        } else {
            String::new()
        };
        let mutable = if v.is_mutable { "" } else { "readonly " };
        self.line(&format!("public static {}{} {}{};", mutable, type_str, v.name, init))?;
        Ok(())
    }

    /// 生成函数（作为静态方法）
    fn emit_function(&mut self, f: &ast::FunctionDecl, class_name: Option<&str>) -> CSharpResult<()> {
        let return_type = self.map_type_from_ast(f.return_type.as_ref());
        let params: Vec<String> = f
            .parameters
            .iter()
            .map(|p| {
                let type_str = self.map_type_from_ast(p.type_annot.as_ref());
                format!("{} {}", type_str, p.name)
            })
            .collect();

        let async_keyword = if f.is_async { "async " } else { "" };
        let static_keyword = if class_name.is_none() { "static " } else { "" };
        self.line(&format!(
            "public {}{}{} {}({})",
            static_keyword, async_keyword, return_type, f.name, params.join(", ")
        ))?;
        self.line("{")?;
        self.indent += 1;

        self.emit_block(&f.body)?;

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成默认 Main 方法
    fn emit_default_main(&mut self) -> CSharpResult<()> {
        self.line("public static void Main(string[] args)")?;
        self.line("{")?;
        self.indent += 1;
        self.line("Console.WriteLine(\"Hello from C# backend!\");")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成语句块
    fn emit_block(&mut self, block: &ast::Block) -> CSharpResult<()> {
        for stmt in &block.statements {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    /// 生成语句
    fn emit_stmt(&mut self, stmt: &ast::Statement) -> CSharpResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            StatementKind::Variable(v) => {
                let type_str = self.map_type_from_ast(v.type_annot.as_ref());
                let init = if let Some(expr) = &v.initializer {
                    format!(" = {}", self.emit_expr(expr)?)
                } else {
                    String::new()
                };
                // C# doesn't have 'val', use readonly local variable pattern
                if v.is_mutable {
                    self.line(&format!("{} {}{};", type_str, v.name, init))?;
                } else {
                    // C# 7.2+ has readonly structs but not readonly locals
                    // We'll just use var for immutability hint
                    self.line(&format!("{} {}{}; // readonly", type_str, v.name, init))?;
                }
            }
            StatementKind::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            StatementKind::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while ({})", cond))?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::For(for_stmt) => {
                self.emit_for(for_stmt)?;
            }
            StatementKind::Match(match_stmt) => {
                self.emit_match(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try(try_stmt)?;
            }
            StatementKind::Break => {
                self.line("break;")?;
            }
            StatementKind::Continue => {
                self.line("continue;")?;
            }
            StatementKind::DoWhile(d) => {
                self.line("do")?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(&d.body)?;
                self.indent -= 1;
                self.line("}")?;
                let cond = self.emit_expr(&d.condition)?;
                self.line(&format!("while ({});", cond))?;
            }
            StatementKind::Unsafe(block) => {
                self.line("unsafe")?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(block)?;
                self.indent -= 1;
                self.line("}")?;
            }
        }
        Ok(())
    }

    /// 生成 if 语句
    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> CSharpResult<()> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if ({})", cond))?;
        self.line("{")?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;
        self.line("}")?;

        if let Some(else_block) = &if_stmt.else_block {
            self.line("else")?;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
            self.line("}")?;
        }
        Ok(())
    }

    /// 生成 for 语句
    fn emit_for(&mut self, for_stmt: &ast::ForStatement) -> CSharpResult<()> {
        let iter = self.emit_expr(&for_stmt.iterator)?;
        let var_name = self.emit_pattern_var(&for_stmt.pattern);

        self.line(&format!("foreach (var {} in {})", var_name, iter))?;
        self.line("{")?;
        self.indent += 1;
        self.emit_block(&for_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成模式变量名
    fn emit_pattern_var(&self, pattern: &ast::Pattern) -> String {
        match pattern {
            ast::Pattern::Wildcard => "_".to_string(),
            ast::Pattern::Variable(name) => name.clone(),
            ast::Pattern::Literal(lit) => self.emit_literal_for_pattern(lit),
            ast::Pattern::Array(elements) => {
                let vars: Vec<String> = elements.iter().map(|p| self.emit_pattern_var(p)).collect();
                format!("[{}]", vars.join(", "))
            }
            ast::Pattern::Tuple(elements) => {
                let vars: Vec<String> = elements.iter().map(|p| self.emit_pattern_var(p)).collect();
                format!("({})", vars.join(", "))
            }
            ast::Pattern::Or(left, _) => self.emit_pattern_var(left),
            ast::Pattern::Guard(inner, _) => self.emit_pattern_var(inner),
            ast::Pattern::Dictionary(entries) => {
                let vars: Vec<String> = entries
                    .iter()
                    .map(|(k, v)| format!("{}: {}", self.emit_pattern_var(k), self.emit_pattern_var(v)))
                    .collect();
                format!("{{{}}}", vars.join(", "))
            }
            ast::Pattern::Record(name, fields) => {
                let field_strs: Vec<String> = fields
                    .iter()
                    .map(|(k, v)| format!("{}={}", k, self.emit_pattern_var(v)))
                    .collect();
                format!("{}({})", name, field_strs.join(", "))
            }
            ast::Pattern::EnumConstructor(_type_name, variant_name, patterns) => {
                let pattern_strs: Vec<String> = patterns.iter().map(|p| self.emit_pattern_var(p)).collect();
                if patterns.is_empty() {
                    variant_name.clone()
                } else {
                    format!("{}({})", variant_name, pattern_strs.join(", "))
                }
            }
        }
    }

    /// 生成模式匹配中的字面量
    fn emit_literal_for_pattern(&self, lit: &ast::Literal) -> String {
        match lit {
            ast::Literal::Integer(n) => format!("{}", n),
            ast::Literal::Float(f) => format!("{}", f),
            ast::Literal::Boolean(b) => format!("{}", b),
            ast::Literal::String(s) => format!("\"{}\"", s),
            ast::Literal::Char(c) => format!("'{}'", c),
            ast::Literal::Null | ast::Literal::None | ast::Literal::Unit => "null".to_string(),
        }
    }

    /// 生成 match 语句（使用 if-else 链模拟）
    fn emit_match(&mut self, match_stmt: &ast::MatchStatement) -> CSharpResult<()> {
        let expr = self.emit_expr(&match_stmt.expression)?;

        // 存储表达式到临时变量
        let temp_var = "__match_val__";
        self.line(&format!("var {} = {};", temp_var, expr))?;

        for (i, case) in match_stmt.cases.iter().enumerate() {
            let condition = self.emit_match_condition(temp_var, &case.pattern, case.guard.as_ref())?;

            if i == 0 {
                self.line(&format!("if ({})", condition))?;
            } else {
                self.line(&format!("else if ({})", condition))?;
            }

            self.line("{")?;
            self.indent += 1;
            self.emit_pattern_bindings(temp_var, &case.pattern)?;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    /// 生成 match 条件
    fn emit_match_condition(
        &self,
        var: &str,
        pattern: &ast::Pattern,
        guard: Option<&ast::Expression>,
    ) -> CSharpResult<String> {
        let base_cond = match pattern {
            ast::Pattern::Wildcard => "true".to_string(),
            ast::Pattern::Variable(_) => "true".to_string(),
            ast::Pattern::Literal(lit) => {
                let lit_str = self.emit_literal_for_pattern(lit);
                format!("{} == {}", var, lit_str)
            }
            ast::Pattern::Or(left, right) => {
                let left_cond = self.emit_match_condition(var, left, None)?;
                let right_cond = self.emit_match_condition(var, right, None)?;
                format!("({}) || ({})", left_cond, right_cond)
            }
            ast::Pattern::Guard(inner, cond_expr) => {
                let inner_cond = self.emit_match_condition(var, inner, None)?;
                let guard_cond = self.emit_expr(cond_expr)?;
                format!("({}) && ({})", inner_cond, guard_cond)
            }
            ast::Pattern::Array(elements) => {
                let len_check = format!("{}.Length == {}", var, elements.len());
                let elem_checks: Vec<String> = elements
                    .iter()
                    .enumerate()
                    .map(|(i, p)| self.emit_match_condition(&format!("{}[{}]", var, i), p, None))
                    .collect::<CSharpResult<Vec<_>>>()?;
                if elem_checks.is_empty() {
                    format!("{}.Length == 0", var)
                } else {
                    format!("({}) && ({})", len_check, elem_checks.join(" && "))
                }
            }
            ast::Pattern::Tuple(elements) => {
                let elem_checks: Vec<String> = elements
                    .iter()
                    .enumerate()
                    .map(|(i, p)| self.emit_match_condition(&format!("Item{}({})", i + 1, var), p, None))
                    .collect::<CSharpResult<Vec<_>>>()?;
                elem_checks.join(" && ")
            }
            ast::Pattern::Dictionary(_) | ast::Pattern::Record(_, _) => {
                format!("true // pattern matching for records/dicts not fully implemented")
            }
            ast::Pattern::EnumConstructor(_type_name, variant_name, patterns) => {
                if patterns.is_empty() {
                    format!("{} == {}.{}", var, _type_name, variant_name)
                } else {
                    format!("{} is {} // enum constructor pattern", var, variant_name)
                }
            }
        };

        if let Some(guard_expr) = guard {
            let guard_str = self.emit_expr(guard_expr)?;
            Ok(format!("({}) && ({})", base_cond, guard_str))
        } else {
            Ok(base_cond)
        }
    }

    /// 生成模式绑定
    fn emit_pattern_bindings(&mut self, var: &str, pattern: &ast::Pattern) -> CSharpResult<()> {
        match pattern {
            ast::Pattern::Variable(name) => {
                self.line(&format!("var {} = {};", name, var))?;
            }
            ast::Pattern::Array(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_pattern_bindings(&format!("{}[{}]", var, i), elem)?;
                }
            }
            ast::Pattern::Tuple(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_pattern_bindings(&format!("Item{}({})", i + 1, var), elem)?;
                }
            }
            ast::Pattern::Or(left, _) => {
                self.emit_pattern_bindings(var, left)?;
            }
            ast::Pattern::Guard(inner, _) => {
                self.emit_pattern_bindings(var, inner)?;
            }
            ast::Pattern::Dictionary(entries) => {
                for (key, val_pattern) in entries {
                    let key_str = self.emit_pattern_var(key);
                    self.emit_pattern_bindings(&format!("{}.GetValueOrDefault({})", var, key_str), val_pattern)?;
                }
            }
            ast::Pattern::Record(_, fields) => {
                for (field, val_pattern) in fields {
                    self.emit_pattern_bindings(&format!("{}.{}", var, field), val_pattern)?;
                }
            }
            _ => {}
        }
        Ok(())
    }

    /// 生成 try 语句
    fn emit_try(&mut self, try_stmt: &ast::TryStatement) -> CSharpResult<()> {
        self.line("try")?;
        self.line("{")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;

        for catch in &try_stmt.catch_clauses {
            let catch_line = if let Some(var_name) = &catch.variable_name {
                if let Some(exc_type) = &catch.exception_type {
                    format!("catch ({} {})", exc_type, var_name)
                } else {
                    format!("catch (Exception {})", var_name)
                }
            } else if let Some(exc_type) = &catch.exception_type {
                format!("catch ({})", exc_type)
            } else {
                "catch (Exception)".to_string()
            };

            self.line(&catch_line)?;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(&catch.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("finally")?;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(finally)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    /// 生成表达式
    fn emit_expr(&self, expr: &ast::Expression) -> CSharpResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => self.emit_literal(lit),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ExpressionKind::Unary(op, expr) => {
                let e = self.emit_expr(expr)?;
                Ok(self.emit_unaryop(op, &e))
            }
            ExpressionKind::Call(callee, args) => self.emit_call(callee, args),
            ExpressionKind::Assign(target, value) => self.emit_assign(target, value),
            ExpressionKind::Array(elements) => self.emit_array_literal(elements),
            ExpressionKind::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            ExpressionKind::If(cond, then_e, else_e) => {
                let c = self.emit_expr(cond)?;
                let t = self.emit_expr(then_e)?;
                let e = self.emit_expr(else_e)?;
                Ok(format!("({} ? {} : {})", c, t, e))
            }
            ExpressionKind::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            ExpressionKind::Wait(wait_type, exprs) => self.emit_wait(wait_type, exprs),
            ExpressionKind::Dictionary(entries) => self.emit_dictionary_literal(entries),
            ExpressionKind::Record(name, fields) => self.emit_record_literal(name, fields),
            ExpressionKind::Lambda(params, body) => self.emit_lambda(params, body),
            ExpressionKind::Range(start, end, inclusive) => self.emit_range(start, end, *inclusive),
            ExpressionKind::Match(expr, cases) => self.emit_match_expr(expr, cases),
            _ => Err(CSharpError::UnsupportedFeature(format!("{:?}", expr.node))),
        }
    }

    /// 生成字面量
    fn emit_literal(&self, lit: &ast::Literal) -> CSharpResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(format!("{}L", n)),
            ast::Literal::Float(f) => Ok(format!("{}f", f)),
            ast::Literal::Boolean(b) => Ok(format!("{}", b).to_string()),
            ast::Literal::String(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null | ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("null".to_string()),
        }
    }

    /// 生成二元运算
    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("{} + {}", l, r),
            ast::BinaryOp::Sub => format!("{} - {}", l, r),
            ast::BinaryOp::Mul => format!("{} * {}", l, r),
            ast::BinaryOp::Div => format!("{} / {}", l, r),
            ast::BinaryOp::Mod => format!("{} % {}", l, r),
            ast::BinaryOp::Equal => format!("{} == {}", l, r),
            ast::BinaryOp::NotEqual => format!("{} != {}", l, r),
            ast::BinaryOp::Less => format!("{} < {}", l, r),
            ast::BinaryOp::LessEqual => format!("{} <= {}", l, r),
            ast::BinaryOp::Greater => format!("{} > {}", l, r),
            ast::BinaryOp::GreaterEqual => format!("{} >= {}", l, r),
            ast::BinaryOp::And => format!("{} && {}", l, r),
            ast::BinaryOp::Or => format!("{} || {}", l, r),
            ast::BinaryOp::Pow => format!("Math.Pow({}, {})", l, r),
            ast::BinaryOp::BitAnd => format!("{} & {}", l, r),
            ast::BinaryOp::BitOr => format!("{} | {}", l, r),
            ast::BinaryOp::BitXor => format!("{} ^ {}", l, r),
            ast::BinaryOp::LeftShift => format!("{} << {}", l, r),
            ast::BinaryOp::RightShift => format!("{} >> {}", l, r),
            ast::BinaryOp::Concat => format!("{} + {}", l, r),
            ast::BinaryOp::RangeExclusive => format!("Enumerable.Range({}, {} - {})", l, l, r),
            ast::BinaryOp::RangeInclusive => format!("Enumerable.Range({}, {} - {} + 1)", l, l, r),
        }
    }

    /// 生成一元运算
    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("-{}", e),
            ast::UnaryOp::Not => format!("!{}", e),
            ast::UnaryOp::BitNot => format!("~{}", e),
            ast::UnaryOp::Wait => format!("await {}", e),
        }
    }

    /// 生成函数调用
    fn emit_call(
        &self,
        callee: &ast::Expression,
        args: &[ast::Expression],
    ) -> CSharpResult<String> {
        let callee_str = self.emit_expr(callee)?;
        let arg_strs: Vec<String> = args
            .iter()
            .map(|a| self.emit_expr(a))
            .collect::<CSharpResult<Vec<_>>>()?;
        Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
    }

    /// 生成赋值表达式
    fn emit_assign(
        &self,
        target: &ast::Expression,
        value: &ast::Expression,
    ) -> CSharpResult<String> {
        let val = self.emit_expr(value)?;
        match &target.node {
            ExpressionKind::Variable(name) => Ok(format!("{} = {}", name, val)),
            ExpressionKind::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{} = {}", o, field, val))
            }
            _ => {
                let t = self.emit_expr(target)?;
                Ok(format!("{} = {}", t, val))
            }
        }
    }

    /// 生成数组字面量
    fn emit_array_literal(&self, elements: &[ast::Expression]) -> CSharpResult<String> {
        if elements.is_empty() {
            return Ok("new object[0]".to_string());
        }
        let elem_strs: Vec<String> = elements
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<CSharpResult<Vec<_>>>()?;
        Ok(format!("new object[] {{ {} }}", elem_strs.join(", ")))
    }

    /// 生成字典字面量
    fn emit_dictionary_literal(&self, entries: &[(ast::Expression, ast::Expression)]) -> CSharpResult<String> {
        if entries.is_empty() {
            return Ok("new Dictionary<object, object>()".to_string());
        }
        let entry_strs: Vec<String> = entries
            .iter()
            .map(|(k, v)| {
                let key = self.emit_expr(k)?;
                let val = self.emit_expr(v)?;
                Ok(format!("{{ {}, {} }}", key, val))
            })
            .collect::<CSharpResult<Vec<_>>>()?;
        Ok(format!("new Dictionary<object, object> {{ {} }}", entry_strs.join(", ")))
    }

    /// 生成记录字面量
    fn emit_record_literal(&self, name: &str, fields: &[(String, ast::Expression)]) -> CSharpResult<String> {
        let field_strs: Vec<String> = fields
            .iter()
            .map(|(k, v)| {
                let val = self.emit_expr(v)?;
                Ok(format!("{} = {}", k, val))
            })
            .collect::<CSharpResult<Vec<_>>>()?;
        Ok(format!("new {} {{ {} }}", name, field_strs.join(", ")))
    }

    /// 生成 Lambda 表达式
    fn emit_lambda(&self, params: &[ast::Parameter], body: &ast::Block) -> CSharpResult<String> {
        let param_strs: Vec<String> = params
            .iter()
            .map(|p| {
                let type_str = self.map_type_from_ast(p.type_annot.as_ref());
                format!("{} {}", type_str, p.name)
            })
            .collect();

        // 简单实现：假设 body 只有一个 return 语句
        if body.statements.len() == 1 {
            if let StatementKind::Return(Some(expr)) = &body.statements[0].node {
                let expr_str = self.emit_expr(expr)?;
                return Ok(format!("({}) => {}", param_strs.join(", "), expr_str));
            }
        }

        // 复杂情况：生成完整的方法体
        Ok(format!("({}) => {{ /* lambda body */ }}", param_strs.join(", ")))
    }

    /// 生成范围表达式
    fn emit_range(&self, start: &ast::Expression, end: &ast::Expression, inclusive: bool) -> CSharpResult<String> {
        let s = self.emit_expr(start)?;
        let e = self.emit_expr(end)?;
        if inclusive {
            Ok(format!("Enumerable.Range((int){}(, (int){} - (int){} + 1)", s, e, s))
        } else {
            Ok(format!("Enumerable.Range((int){}(, (int){} - (int){})", s, e, s))
        }
    }

    /// 生成 match 表达式
    fn emit_match_expr(&self, _expr: &ast::Expression, _cases: &[ast::MatchCase]) -> CSharpResult<String> {
        // C# 8.0+ has switch expressions, but we'll use a simpler approach
        Ok("/* match expression not fully implemented */ null".to_string())
    }

    /// 生成 wait 表达式
    fn emit_wait(&self, wait_type: &ast::WaitType, exprs: &[ast::Expression]) -> CSharpResult<String> {
        let expr_strs: Vec<String> = exprs
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<CSharpResult<Vec<_>>>()?;
        match wait_type {
            ast::WaitType::Single => {
                if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    let awaited: Vec<String> = expr_strs.iter().map(|e| format!("await {}", e)).collect();
                    Ok(format!("({})", awaited.join(", ")))
                }
            }
            ast::WaitType::Together => {
                if expr_strs.is_empty() {
                    Ok("Task.CompletedTask".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    Ok(format!("await Task.WhenAll({})", expr_strs.join(", ")))
                }
            }
            ast::WaitType::Race => {
                if expr_strs.is_empty() {
                    Ok("Task.CompletedTask".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    Ok(format!("await Task.WhenAny({})", expr_strs.join(", ")))
                }
            }
            ast::WaitType::Timeout(timeout_expr) => {
                let timeout = self.emit_expr(timeout_expr)?;
                if expr_strs.is_empty() {
                    Ok(format!("await Task.Delay({})", timeout))
                } else {
                    let expr = &expr_strs[0];
                    Ok(format!("await Task.WhenAny({}, Task.Delay({}{}))", expr, "TimeSpan.FromMilliseconds(", timeout))
                }
            }
        }
    }

    /// 从 AST 类型映射到 C# 类型
    fn map_type_from_ast(&self, ty: Option<&ast::Type>) -> String {
        match ty {
            Some(t) => self.map_ast_type(t),
            None => "void".to_string(),
        }
    }

    /// 映射 AST 类型
    fn map_ast_type(&self, ty: &ast::Type) -> String {
        match ty {
            ast::Type::Int => "long".to_string(),
            ast::Type::UnsignedInt => "ulong".to_string(),
            ast::Type::Float => "double".to_string(),
            ast::Type::Bool => "bool".to_string(),
            ast::Type::String => "string".to_string(),
            ast::Type::Char => "char".to_string(),
            ast::Type::Unit => "void".to_string(),
            ast::Type::Never => "void".to_string(),
            ast::Type::Array(inner) => format!("List<{}>", self.map_ast_type(inner)),
            ast::Type::Dictionary(key, value) => {
                format!("Dictionary<{}, {}>", self.map_ast_type(key), self.map_ast_type(value))
            }
            ast::Type::Option(inner) => format!("{}?", self.map_ast_type(inner)),
            ast::Type::Result(ok, err) => {
                format!("Result<{}, {}>", self.map_ast_type(ok), self.map_ast_type(err))
            }
            ast::Type::Function(params, ret) => {
                let param_types: Vec<String> = params.iter().map(|p| self.map_ast_type(p)).collect();
                let ret_type = self.map_ast_type(ret);
                format!("Func<{}, {}>", param_types.join(", "), ret_type)
            }
            ast::Type::Async(inner) => format!("Task<{}>", self.map_ast_type(inner)),
            ast::Type::Tuple(types) => {
                let type_strs: Vec<String> = types.iter().map(|t| self.map_ast_type(t)).collect();
                format!("Tuple<{}>", type_strs.join(", "))
            }
            ast::Type::Generic(name) => name.clone(),
            ast::Type::TypeParam(name) => name.clone(),
            ast::Type::TypeConstructor(name, args) => {
                let arg_strs: Vec<String> = args.iter().map(|t| self.map_ast_type(t)).collect();
                format!("{}<{}>", name, arg_strs.join(", "))
            }
            ast::Type::Var(name) => name.clone(),
            ast::Type::Dynamic => "object".to_string(),
            ast::Type::Void => "void".to_string(),
            ast::Type::Pointer(inner) => format!("{}*", self.map_ast_type(inner)),
            ast::Type::ConstPointer(inner) => format!("{}*", self.map_ast_type(inner)),
            // C FFI types
            ast::Type::CInt => "int".to_string(),
            ast::Type::CUInt => "uint".to_string(),
            ast::Type::CLong => "nint".to_string(),
            ast::Type::CULong => "nuint".to_string(),
            ast::Type::CLongLong => "long".to_string(),
            ast::Type::CULongLong => "ulong".to_string(),
            ast::Type::CFloat => "float".to_string(),
            ast::Type::CDouble => "double".to_string(),
            ast::Type::CChar => "byte".to_string(),
            ast::Type::CSize => "nuint".to_string(),
            ast::Type::CString => "IntPtr".to_string(),
            ast::Type::Record(name, _) => name.clone(),
            ast::Type::Union(name, _) => name.clone(),
        }
    }

    /// 映射访问修饰符
    fn map_visibility(&self, visibility: ast::Visibility) -> &'static str {
        match visibility {
            ast::Visibility::Private => "private ",
            ast::Visibility::Public => "public ",
            ast::Visibility::Protected => "protected ",
            ast::Visibility::Internal => "internal ",
        }
    }

    /// 映射方法修饰符
    fn map_method_modifiers(&self, modifiers: &ast::MethodModifiers) -> String {
        let mut result = String::new();

        result.push_str(self.map_visibility(modifiers.visibility));

        if modifiers.is_static {
            result.push_str("static ");
        }
        if modifiers.is_abstract {
            result.push_str("abstract ");
        }
        if modifiers.is_virtual {
            result.push_str("virtual ");
        }
        if modifiers.is_override {
            result.push_str("override ");
        }
        if modifiers.is_final {
            result.push_str("sealed ");
        }

        result
    }

    /// 输出一行代码（带缩进）
    fn line(&mut self, s: &str) -> CSharpResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

impl x_codegen::CodeGenerator for CSharpBackend {
    type Config = CSharpConfig;
    type Error = CSharpError;

    fn new(config: Self::Config) -> Self {
        Self::new(config)
    }

    fn generate_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> Result<x_codegen::CodegenOutput, Self::Error> {
        self.generate_from_ast(program)
    }

    fn generate_from_hir(&mut self, _hir: &x_hir::Hir) -> Result<x_codegen::CodegenOutput, Self::Error> {
        Err(CSharpError::Unimplemented("C# 后端 HIR 生成尚未实现".to_string()))
    }

    fn generate_from_lir(
        &mut self,
        _lir: &x_lir::Program,
    ) -> Result<x_codegen::CodegenOutput, Self::Error> {
        Err(CSharpError::Unimplemented("C# 后端 LIR 生成尚未实现".to_string()))
    }
}

// 保持向后兼容的别名
pub type DotNetCodeGenerator = CSharpBackend;
pub type DotNetConfig = CSharpConfig;
pub type DotNetCodeGenError = CSharpError;
pub type DotNetResult<T> = Result<T, CSharpError>;

#[cfg(test)]
mod tests {
    use super::*;
    use x_lexer::span::Span;
    use x_parser::ast::{Spanned, MethodModifiers};

    fn make_expr(kind: ExpressionKind) -> ast::Expression {
        Spanned::new(kind, Span::default())
    }

    fn make_stmt(kind: StatementKind) -> ast::Statement {
        Spanned::new(kind, Span::default())
    }

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
                span: Span::default(),
                name: "main".to_string(),
                type_parameters: vec![],
                parameters: vec![],
                effects: vec![],
                return_type: None,
                body: ast::Block {
                    statements: vec![make_stmt(StatementKind::Expression(make_expr(
                        ExpressionKind::Call(
                            Box::new(make_expr(ExpressionKind::Variable("Console.WriteLine".to_string()))),
                            vec![make_expr(ExpressionKind::Literal(ast::Literal::String(
                                "Hello, World!".to_string(),
                            )))],
                        ),
                    )))],
                },
                is_async: false,
                modifiers: MethodModifiers::default(),
            })],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("using System;"));
        assert!(csharp_code.contains("namespace XLang"));
        assert!(csharp_code.contains("public static void main()"));
        assert!(csharp_code.contains("Console.WriteLine(\"Hello, World!\")"));
    }

    #[test]
    fn test_empty_program_generates_default_main() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("public static void Main(string[] args)"));
        assert!(csharp_code.contains("Console.WriteLine(\"Hello from C# backend!\")"));
    }

    #[test]
    fn test_class_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![
                ast::Declaration::Class(ast::ClassDecl {
                    span: Span::default(),
                    name: "Person".to_string(),
                    type_parameters: vec![],
                    extends: None,
                    implements: vec![],
                    members: vec![
                        ast::ClassMember::Field(ast::VariableDecl {
                            name: "name".to_string(),
                            is_mutable: false,
                            type_annot: Some(ast::Type::String),
                            initializer: None,
                            visibility: ast::Visibility::Public,
                            span: Span::default(),
                        }),
                        ast::ClassMember::Method(ast::FunctionDecl {
                            span: Span::default(),
                            name: "greet".to_string(),
                            type_parameters: vec![],
                            parameters: vec![],
                            effects: vec![],
                            return_type: Some(ast::Type::String),
                            body: ast::Block {
                                statements: vec![make_stmt(StatementKind::Return(Some(make_expr(
                                    ExpressionKind::Literal(ast::Literal::String("Hello!".to_string()))
                                ))))],
                            },
                            is_async: false,
                            modifiers: MethodModifiers {
                                is_static: false,
                                visibility: ast::Visibility::Public,
                                ..Default::default()
                            },
                        }),
                    ],
                    modifiers: ast::ClassModifiers::default(),
                }),
            ],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("public class Person"));
        assert!(csharp_code.contains("public string name;"));
        assert!(csharp_code.contains("public string greet()"));
    }

    #[test]
    fn test_type_mapping() {
        let backend = CSharpBackend::new(CSharpConfig::default());

        // 基本类型
        assert_eq!(backend.map_ast_type(&ast::Type::Int), "long");
        assert_eq!(backend.map_ast_type(&ast::Type::Float), "double");
        assert_eq!(backend.map_ast_type(&ast::Type::Bool), "bool");
        assert_eq!(backend.map_ast_type(&ast::Type::String), "string");
        assert_eq!(backend.map_ast_type(&ast::Type::Char), "char");

        // 复合类型
        assert_eq!(backend.map_ast_type(&ast::Type::Array(Box::new(ast::Type::Int))), "List<long>");
        assert_eq!(
            backend.map_ast_type(&ast::Type::Option(Box::new(ast::Type::Int))),
            "long?"
        );
        assert_eq!(
            backend.map_ast_type(&ast::Type::Async(Box::new(ast::Type::Int))),
            "Task<long>"
        );
    }

    #[test]
    fn test_if_statement() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
                span: Span::default(),
                name: "test_if".to_string(),
                type_parameters: vec![],
                parameters: vec![],
                effects: vec![],
                return_type: None,
                body: ast::Block {
                    statements: vec![make_stmt(StatementKind::If(ast::IfStatement {
                        condition: make_expr(ExpressionKind::Literal(ast::Literal::Boolean(true))),
                        then_block: ast::Block {
                            statements: vec![make_stmt(StatementKind::Expression(make_expr(
                                ExpressionKind::Call(
                                    Box::new(make_expr(ExpressionKind::Variable(
                                        "Console.WriteLine".to_string(),
                                    ))),
                                    vec![make_expr(ExpressionKind::Literal(ast::Literal::String(
                                        "true".to_string(),
                                    )))],
                                ),
                            )))],
                        },
                        else_block: None,
                    }))],
                },
                is_async: false,
                modifiers: MethodModifiers::default(),
            })],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("if (true)"));
        assert!(csharp_code.contains("Console.WriteLine(\"true\")"));
    }

    #[test]
    fn test_while_loop() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
                span: Span::default(),
                name: "test_while".to_string(),
                type_parameters: vec![],
                parameters: vec![],
                effects: vec![],
                return_type: None,
                body: ast::Block {
                    statements: vec![make_stmt(StatementKind::While(ast::WhileStatement {
                        condition: make_expr(ExpressionKind::Literal(ast::Literal::Boolean(false))),
                        body: ast::Block { statements: vec![] },
                    }))],
                },
                is_async: false,
                modifiers: MethodModifiers::default(),
            })],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("while (false)"));
    }

    #[test]
    fn test_custom_namespace() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![],
            statements: vec![],
        };

        let config = CSharpConfig {
            namespace: Some("MyApp.Services".to_string()),
            ..Default::default()
        };
        let mut backend = CSharpBackend::new(config);
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("namespace MyApp.Services"));
    }

    #[test]
    fn test_enum_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Enum(ast::EnumDecl {
                span: Span::default(),
                name: "Color".to_string(),
                type_parameters: vec![],
                variants: vec![
                    ast::EnumVariant {
                        name: "Red".to_string(),
                        data: ast::EnumVariantData::Unit,
                        doc: None,
                        span: Span::default(),
                    },
                    ast::EnumVariant {
                        name: "Green".to_string(),
                        data: ast::EnumVariantData::Unit,
                        doc: None,
                        span: Span::default(),
                    },
                    ast::EnumVariant {
                        name: "Blue".to_string(),
                        data: ast::EnumVariantData::Unit,
                        doc: None,
                        span: Span::default(),
                    },
                ],
            })],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("public enum Color"));
        assert!(csharp_code.contains("Red"));
        assert!(csharp_code.contains("Green"));
        assert!(csharp_code.contains("Blue"));
    }

    #[test]
    fn test_binary_operations() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
                span: Span::default(),
                name: "test_ops".to_string(),
                type_parameters: vec![],
                parameters: vec![],
                effects: vec![],
                return_type: Some(ast::Type::Int),
                body: ast::Block {
                    statements: vec![make_stmt(StatementKind::Return(Some(make_expr(
                        ExpressionKind::Binary(
                            ast::BinaryOp::Add,
                            Box::new(make_expr(ExpressionKind::Literal(ast::Literal::Integer(1)))),
                            Box::new(make_expr(ExpressionKind::Literal(ast::Literal::Integer(2)))),
                        ),
                    ))))],
                },
                is_async: false,
                modifiers: MethodModifiers::default(),
            })],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(csharp_code.contains("return 1L + 2L;"));
    }
}
