//! C 后端 - 将 X IR 编译为 C23 代码
//!
//! 支持完整类型映射、声明、语句和表达式生成

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::Program as AstProgram;

use crate::{CodeGenerator, CodegenOutput, OutputFile, FileType};

/// C 标准版本
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CStandard {
    /// C99 标准
    C99,
    /// C11 标准
    C11,
    /// C23 标准（默认）
    #[default]
    C23,
}

impl CStandard {
    /// 获取标准的编译器标志
    pub fn flag(&self) -> &'static str {
        match self {
            CStandard::C99 => "-std=c99",
            CStandard::C11 => "-std=c11",
            CStandard::C23 => "-std=c23",
        }
    }

    /// 获取标准的字符串表示
    pub fn as_str(&self) -> &'static str {
        match self {
            CStandard::C99 => "c99",
            CStandard::C11 => "c11",
            CStandard::C23 => "c23",
        }
    }
}

/// C 后端配置
#[derive(Debug, Clone)]
pub struct CBackendConfig {
    /// 输出目录
    pub output_dir: Option<PathBuf>,
    /// 是否启用优化
    pub optimize: bool,
    /// 是否生成调试信息
    pub debug_info: bool,
    /// C 标准版本
    pub c_standard: CStandard,
    /// 是否生成头文件
    pub generate_header: bool,
}

impl Default for CBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            c_standard: CStandard::C23,
            generate_header: false,
        }
    }
}

/// C 后端错误类型
#[derive(Debug, thiserror::Error)]
pub enum CBackendError {
    #[error("代码生成错误: {0}")]
    GenerationError(String),
    #[error("I/O 错误: {0}")]
    IoError(#[from] std::io::Error),
    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("不支持的特性: {0}")]
    UnsupportedFeature(String),
    #[error("类型错误: {0}")]
    TypeError(String),
}

pub type CResult<T> = Result<T, CBackendError>;

/// C 后端
pub struct CBackend {
    config: CBackendConfig,
    /// 当前缩进级别
    indent: usize,
    /// 输出缓冲区
    output: String,
    /// 需要的头文件
    needs_stdbool: bool,
    needs_stdint: bool,
    needs_stddef: bool,
    needs_stdio: bool,
    needs_stdlib: bool,
    needs_string: bool,
    /// 用户定义的类型名称（用于生成前向声明）
    user_types: Vec<String>,
    /// 全局变量名称
    global_vars: Vec<String>,
}

impl CBackend {
    pub fn new(config: CBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            needs_stdbool: false,
            needs_stdint: false,
            needs_stddef: false,
            needs_stdio: false,
            needs_stdlib: false,
            needs_string: false,
            user_types: Vec::new(),
            global_vars: Vec::new(),
        }
    }

    /// 重置状态
    fn reset(&mut self) {
        self.indent = 0;
        self.output.clear();
        self.needs_stdbool = false;
        self.needs_stdint = false;
        self.needs_stddef = false;
        self.needs_stdio = false;
        self.needs_stdlib = false;
        self.needs_string = false;
        self.user_types.clear();
        self.global_vars.clear();
    }

    /// 输出一行代码
    fn line(&mut self, s: &str) -> CResult<()> {
        if s.is_empty() {
            writeln!(self.output)?;
        } else {
            for _ in 0..self.indent {
                write!(self.output, "    ")?;
            }
            writeln!(self.output, "{}", s)?;
        }
        Ok(())
    }

    /// 生成文件头部
    fn emit_header(&mut self) -> CResult<()> {
        self.line("/* Generated by X-Lang C backend */")?;
        self.line("/* DO NOT EDIT */")?;
        self.line("")?;

        // 根据需要的类型添加头文件
        if self.needs_stdbool {
            self.line("#include <stdbool.h>")?;
        }
        if self.needs_stdint {
            self.line("#include <stdint.h>")?;
        }
        if self.needs_stddef {
            self.line("#include <stddef.h>")?;
        }
        if self.needs_stdio {
            self.line("#include <stdio.h>")?;
        }
        if self.needs_stdlib {
            self.line("#include <stdlib.h>")?;
        }
        if self.needs_string {
            self.line("#include <string.h>")?;
        }

        if self.needs_stdbool || self.needs_stdint || self.needs_stddef
            || self.needs_stdio || self.needs_stdlib || self.needs_string {
            self.line("")?;
        }

        Ok(())
    }

    /// 生成 main 函数
    fn emit_main_function(&mut self, statements: &[x_parser::ast::Statement]) -> CResult<()> {
        self.line("int main(void) {")?;
        self.indent += 1;

        if statements.is_empty() {
            self.line("/* Empty program */")?;
            self.line("return 0;")?;
        } else {
            for stmt in statements {
                self.emit_statement(stmt)?;
            }
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成语句
    fn emit_statement(&mut self, _stmt: &x_parser::ast::Statement) -> CResult<()> {
        // TODO: 实现语句生成
        Ok(())
    }

    /// 从 AST 生成 C 代码
    fn generate_c_from_ast(&mut self, program: &AstProgram) -> CResult<String> {
        self.reset();

        // 预扫描以确定需要的头文件
        self.scan_program(program)?;

        // 生成头部
        self.emit_header()?;

        // 生成声明
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // 如果没有 main 函数，生成默认 main
        let has_main = program.declarations.iter().any(|d| {
            matches!(d, x_parser::ast::Declaration::Function(f) if f.name == "main")
        });

        if !has_main {
            self.line("")?;
            self.emit_main_function(&program.statements)?;
        }

        Ok(self.output.clone())
    }

    /// 预扫描程序以确定需要的头文件
    fn scan_program(&mut self, program: &AstProgram) -> CResult<()> {
        // 扫描声明
        for decl in &program.declarations {
            self.scan_declaration(decl)?;
        }

        // 扫描顶层语句
        for stmt in &program.statements {
            self.scan_statement(stmt)?;
        }

        Ok(())
    }

    /// 扫描声明
    fn scan_declaration(&mut self, decl: &x_parser::ast::Declaration) -> CResult<()> {
        match decl {
            x_parser::ast::Declaration::Function(f) => {
                // 检查返回类型和参数类型
                if let Some(ret_type) = &f.return_type {
                    self.scan_type(ret_type);
                }
                for param in &f.parameters {
                    if let Some(type_annot) = &param.type_annot {
                        self.scan_type(type_annot);
                    }
                }
                // 扫描函数体
                for stmt in &f.body.statements {
                    self.scan_statement(stmt)?;
                }
            }
            x_parser::ast::Declaration::Variable(v) => {
                if let Some(type_annot) = &v.type_annot {
                    self.scan_type(type_annot);
                }
                if let Some(init) = &v.initializer {
                    self.scan_expression(init)?;
                }
            }
            _ => {}
        }
        Ok(())
    }

    /// 扫描语句
    fn scan_statement(&mut self, stmt: &x_parser::ast::Statement) -> CResult<()> {
        match &stmt.node {
            x_parser::ast::StatementKind::Expression(expr) => {
                self.scan_expression(expr)?;
            }
            x_parser::ast::StatementKind::Variable(v) => {
                if let Some(type_annot) = &v.type_annot {
                    self.scan_type(type_annot);
                }
                if let Some(init) = &v.initializer {
                    self.scan_expression(init)?;
                }
            }
            x_parser::ast::StatementKind::Return(Some(expr)) => {
                self.scan_expression(expr)?;
            }
            _ => {}
        }
        Ok(())
    }

    /// 扫描表达式
    fn scan_expression(&mut self, expr: &x_parser::ast::Expression) -> CResult<()> {
        match &expr.node {
            x_parser::ast::ExpressionKind::Literal(lit) => {
                match lit {
                    x_parser::ast::Literal::Boolean(_) => self.needs_stdbool = true,
                    x_parser::ast::Literal::Integer(_) => self.needs_stdint = true,
                    x_parser::ast::Literal::String(_) => {
                        self.needs_stdio = true;
                        self.needs_stddef = true;
                    }
                    _ => {}
                }
            }
            x_parser::ast::ExpressionKind::Call(callee, args) => {
                self.scan_expression(callee)?;
                for arg in args {
                    self.scan_expression(arg)?;
                }
            }
            _ => {}
        }
        Ok(())
    }

    /// 扫描类型
    fn scan_type(&mut self, ty: &x_parser::ast::Type) {
        match ty {
            x_parser::ast::Type::Bool => self.needs_stdbool = true,
            x_parser::ast::Type::Int | x_parser::ast::Type::UnsignedInt => self.needs_stdint = true,
            x_parser::ast::Type::String => {
                self.needs_stddef = true; // for size_t
            }
            _ => {}
        }
    }

    /// 生成声明
    fn emit_declaration(&mut self, decl: &x_parser::ast::Declaration) -> CResult<()> {
        match decl {
            x_parser::ast::Declaration::Function(f) => self.emit_function(f),
            x_parser::ast::Declaration::Variable(v) => self.emit_global_variable(v),
            x_parser::ast::Declaration::ExternFunction(e) => self.emit_extern_function(e),
            x_parser::ast::Declaration::Class(c) => self.emit_class(c),
            x_parser::ast::Declaration::Trait(t) => self.emit_trait(t),
            x_parser::ast::Declaration::Enum(e) => self.emit_enum(e),
            x_parser::ast::Declaration::TypeAlias(t) => self.emit_type_alias(t),
            x_parser::ast::Declaration::Import(_) => Ok(()), // 忽略导入
            x_parser::ast::Declaration::Module(_) => Ok(()), // 忽略模块
            x_parser::ast::Declaration::Export(_) => Ok(()), // 忽略导出
        }
    }

    /// 生成函数
    fn emit_function(&mut self, f: &x_parser::ast::FunctionDecl) -> CResult<()> {
        // 生成返回类型
        let return_type = if let Some(ret_type) = &f.return_type {
            self.emit_type(ret_type)
        } else {
            "void".to_string()
        };

        // 生成参数列表
        let params = if f.parameters.is_empty() {
            "void".to_string()
        } else {
            f.parameters
                .iter()
                .map(|p| {
                    let ty = if let Some(type_annot) = &p.type_annot {
                        self.emit_type(type_annot)
                    } else {
                        "void*".to_string()
                    };
                    format!("{} {}", ty, p.name)
                })
                .collect::<Vec<_>>()
                .join(", ")
        };

        // 函数签名
        self.line(&format!("{} {}({}) {{", return_type, f.name, params))?;
        self.indent += 1;

        // 函数体
        for stmt in &f.body.statements {
            self.emit_statement(stmt)?;
        }

        // 如果没有显式返回，添加默认返回
        if f.return_type.is_none() {
            self.line("return;")?;
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;

        Ok(())
    }

    /// 生成全局变量
    fn emit_global_variable(&mut self, v: &x_parser::ast::VariableDecl) -> CResult<()> {
        let ty = if let Some(type_annot) = &v.type_annot {
            self.emit_type(type_annot)
        } else {
            "void*".to_string()
        };

        let init = if let Some(expr) = &v.initializer {
            let val = self.emit_expression(expr)?;
            format!(" = {}", val)
        } else {
            String::new()
        };

        let kw = if v.is_mutable { "" } else { "const " };
        self.line(&format!("{}{} {}{};", kw, ty, v.name, init))?;
        self.global_vars.push(v.name.clone());

        Ok(())
    }

    /// 生成外部函数声明
    fn emit_extern_function(&mut self, e: &x_parser::ast::ExternFunctionDecl) -> CResult<()> {
        let return_type = if let Some(ret_type) = &e.return_type {
            self.emit_type(ret_type)
        } else {
            "void".to_string()
        };

        let params = if e.parameters.is_empty() {
            "void".to_string()
        } else {
            e.parameters
                .iter()
                .map(|p| {
                    let ty = if let Some(type_annot) = &p.type_annot {
                        self.emit_type(type_annot)
                    } else {
                        "void*".to_string()
                    };
                    format!("{} {}", ty, p.name)
                })
                .collect::<Vec<_>>()
                .join(", ")
        };

        self.line(&format!("extern {} {}({});", return_type, e.name, params))?;
        self.line("")?;

        Ok(())
    }

    /// 生成类
    fn emit_class(&mut self, _c: &x_parser::ast::ClassDecl) -> CResult<()> {
        // TODO: 实现类生成
        Ok(())
    }

    /// 生成 Trait
    fn emit_trait(&mut self, _t: &x_parser::ast::TraitDecl) -> CResult<()> {
        // TODO: 实现 trait 生成
        Ok(())
    }

    /// 生成枚举
    fn emit_enum(&mut self, e: &x_parser::ast::EnumDecl) -> CResult<()> {
        self.line(&format!("typedef enum {{"))?;
        self.indent += 1;

        for (i, variant) in e.variants.iter().enumerate() {
            // 只支持 Unit 变体作为简单枚举
            let value = i.to_string();
            self.line(&format!("{}_{} = {},", e.name, variant.name, value))?;
        }

        self.indent -= 1;
        self.line(&format!("}} {};", e.name))?;
        self.line("")?;

        Ok(())
    }

    /// 生成类型别名
    fn emit_type_alias(&mut self, t: &x_parser::ast::TypeAlias) -> CResult<()> {
        let target = self.emit_type(&t.type_);
        self.line(&format!("typedef {} {};", target, t.name))?;
        self.line("")?;
        Ok(())
    }

    /// 生成类型字符串
    fn emit_type(&mut self, ty: &x_parser::ast::Type) -> String {
        match ty {
            x_parser::ast::Type::Bool => {
                self.needs_stdbool = true;
                "bool".to_string()
            }
            x_parser::ast::Type::Int => {
                self.needs_stdint = true;
                "int32_t".to_string()
            }
            x_parser::ast::Type::UnsignedInt => {
                self.needs_stdint = true;
                "uint32_t".to_string()
            }
            x_parser::ast::Type::Float => "double".to_string(),
            x_parser::ast::Type::String => {
                self.needs_stddef = true;
                "const char*".to_string()
            }
            x_parser::ast::Type::Char => "char32_t".to_string(),
            x_parser::ast::Type::Void => "void".to_string(),
            x_parser::ast::Type::Unit => "void".to_string(),
            x_parser::ast::Type::Never => "void".to_string(),
            x_parser::ast::Type::Option(inner) => {
                let inner_str = self.emit_type(inner);
                format!("{}*", inner_str) // 简化处理
            }
            x_parser::ast::Type::Array(inner) => {
                let inner_str = self.emit_type(inner);
                format!("{}*", inner_str) // 简化处理
            }
            x_parser::ast::Type::Pointer(inner) => {
                let inner_str = self.emit_type(inner);
                format!("{}*", inner_str)
            }
            x_parser::ast::Type::ConstPointer(inner) => {
                let inner_str = self.emit_type(inner);
                format!("const {}*", inner_str)
            }
            x_parser::ast::Type::Generic(name) => name.clone(),
            x_parser::ast::Type::TypeConstructor(name, _args) => {
                format!("{}_t", name.to_lowercase())
            }
            x_parser::ast::Type::TypeParam(name) => name.clone(),
            // C FFI 类型
            x_parser::ast::Type::CInt => "int".to_string(),
            x_parser::ast::Type::CUInt => "unsigned int".to_string(),
            x_parser::ast::Type::CLong => "long".to_string(),
            x_parser::ast::Type::CULong => "unsigned long".to_string(),
            x_parser::ast::Type::CLongLong => "long long".to_string(),
            x_parser::ast::Type::CULongLong => "unsigned long long".to_string(),
            x_parser::ast::Type::CFloat => "float".to_string(),
            x_parser::ast::Type::CDouble => "double".to_string(),
            x_parser::ast::Type::CChar => "char".to_string(),
            x_parser::ast::Type::CSize => {
                self.needs_stddef = true;
                "size_t".to_string()
            }
            x_parser::ast::Type::CString => "char*".to_string(),
            _ => "void*".to_string(), // 默认处理
        }
    }

    /// 生成表达式字符串
    fn emit_expression(&mut self, expr: &x_parser::ast::Expression) -> CResult<String> {
        match &expr.node {
            x_parser::ast::ExpressionKind::Literal(lit) => self.emit_literal(lit),
            x_parser::ast::ExpressionKind::Variable(name) => Ok(name.clone()),
            x_parser::ast::ExpressionKind::Binary(op, lhs, rhs) => {
                let l = self.emit_expression(lhs)?;
                let r = self.emit_expression(rhs)?;
                let op_str = self.emit_binary_op(op);
                Ok(format!("({} {} {})", l, op_str, r))
            }
            x_parser::ast::ExpressionKind::Unary(op, e) => {
                let operand = self.emit_expression(e)?;
                let op_str = match op {
                    x_parser::ast::UnaryOp::Negate => "-",
                    x_parser::ast::UnaryOp::Not => "!",
                    x_parser::ast::UnaryOp::BitNot => "~",
                    _ => "",
                };
                Ok(format!("({}{})", op_str, operand))
            }
            x_parser::ast::ExpressionKind::Call(callee, args) => {
                let func = self.emit_expression(callee)?;
                let args_str: Vec<String> = args
                    .iter()
                    .map(|a| self.emit_expression(a))
                    .collect::<CResult<Vec<_>>>()?;
                Ok(format!("{}({})", func, args_str.join(", ")))
            }
            x_parser::ast::ExpressionKind::Member(obj, field) => {
                let obj_str = self.emit_expression(obj)?;
                Ok(format!("{}.{}", obj_str, field))
            }
            _ => Ok("/* unsupported expression */".to_string()),
        }
    }

    /// 生成字面量
    fn emit_literal(&mut self, lit: &x_parser::ast::Literal) -> CResult<String> {
        match lit {
            x_parser::ast::Literal::Boolean(b) => {
                self.needs_stdbool = true;
                Ok(b.to_string())
            }
            x_parser::ast::Literal::Integer(n) => {
                self.needs_stdint = true;
                Ok(format!("{}i32", n))
            }
            x_parser::ast::Literal::Float(f) => Ok(format!("{}f", f)),
            x_parser::ast::Literal::String(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            x_parser::ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            x_parser::ast::Literal::Null => Ok("nullptr".to_string()),
            x_parser::ast::Literal::None => Ok("NULL".to_string()),
            x_parser::ast::Literal::Unit => Ok("0".to_string()),
        }
    }

    /// 生成二元运算符
    fn emit_binary_op(&mut self, op: &x_parser::ast::BinaryOp) -> &'static str {
        match op {
            x_parser::ast::BinaryOp::Add => "+",
            x_parser::ast::BinaryOp::Sub => "-",
            x_parser::ast::BinaryOp::Mul => "*",
            x_parser::ast::BinaryOp::Div => "/",
            x_parser::ast::BinaryOp::Mod => "%",
            x_parser::ast::BinaryOp::Equal => "==",
            x_parser::ast::BinaryOp::NotEqual => "!=",
            x_parser::ast::BinaryOp::Less => "<",
            x_parser::ast::BinaryOp::LessEqual => "<=",
            x_parser::ast::BinaryOp::Greater => ">",
            x_parser::ast::BinaryOp::GreaterEqual => ">=",
            x_parser::ast::BinaryOp::And => "&&",
            x_parser::ast::BinaryOp::Or => "||",
            x_parser::ast::BinaryOp::BitAnd => "&",
            x_parser::ast::BinaryOp::BitOr => "|",
            x_parser::ast::BinaryOp::BitXor => "^",
            x_parser::ast::BinaryOp::LeftShift => "<<",
            x_parser::ast::BinaryOp::RightShift => ">>",
            _ => "/* unknown op */",
        }
    }
}

/// 实现 CodeGenerator trait
impl CodeGenerator for CBackend {
    type Config = CBackendConfig;
    type Error = CBackendError;

    fn new(config: Self::Config) -> Self {
        Self::new(config)
    }

    fn generate_from_ast(&mut self, program: &AstProgram) -> Result<CodegenOutput, Self::Error> {
        let c_code = self.generate_c_from_ast(program)?;

        let output_file = OutputFile {
            path: PathBuf::from("output.c"),
            content: c_code.into_bytes(),
            file_type: FileType::C,
        };

        Ok(CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn generate_from_hir(&mut self, _hir: &x_hir::Hir) -> Result<CodegenOutput, Self::Error> {
        // TODO: 实现 HIR 到 C 的生成
        Err(CBackendError::UnsupportedFeature(
            "HIR generation not yet implemented".to_string(),
        ))
    }

    fn generate_from_lir(&mut self, _lir: &x_lir::Program) -> Result<CodegenOutput, Self::Error> {
        // TODO: 实现 LIR 到 C 的生成
        Err(CBackendError::UnsupportedFeature(
            "LIR generation not yet implemented".to_string(),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_c_standard_flags() {
        assert_eq!(CStandard::C99.flag(), "-std=c99");
        assert_eq!(CStandard::C11.flag(), "-std=c11");
        assert_eq!(CStandard::C23.flag(), "-std=c23");
    }

    #[test]
    fn test_default_config() {
        let config = CBackendConfig::default();
        assert_eq!(config.c_standard, CStandard::C23);
        assert!(!config.optimize);
        assert!(config.debug_info);
    }

    #[test]
    fn test_empty_program() {
        let mut backend = CBackend::new(CBackendConfig::default());
        // 使用 x_parser 解析空程序
        let program = x_parser::parse_program("").unwrap();
        let output = backend.generate_from_ast(&program).unwrap();
        assert_eq!(output.files.len(), 1);
        let content = String::from_utf8_lossy(&output.files[0].content);
        assert!(content.contains("int main(void)"));
    }

    #[test]
    fn test_type_mapping() {
        let mut backend = CBackend::new(CBackendConfig::default());

        assert_eq!(backend.emit_type(&x_parser::ast::Type::Bool), "bool");
        assert!(backend.needs_stdbool);

        assert_eq!(backend.emit_type(&x_parser::ast::Type::Int), "int32_t");
        assert!(backend.needs_stdint);

        assert_eq!(backend.emit_type(&x_parser::ast::Type::Float), "double");
    }
}
