//! C23 后端
//! 实现流水线：X → X IR → C23 → GCC/Clang → .o

use crate::xir::*;
use crate::lower::*;
use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::Program as AstProgram;

/// C 代码生成器配置
#[derive(Debug, Clone)]
pub struct CBackendConfig {
    /// 输出目录
    pub output_dir: Option<PathBuf>,
    /// 是否启用优化
    pub optimize: bool,
    /// 是否生成调试信息
    pub debug_info: bool,
    /// C 标准版本
    pub c_standard: CStandard,
    /// 编译器类型
    pub compiler: CCompiler,
}

/// C 标准版本
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CStandard {
    C89,
    C99,
    C11,
    C17,
    C23,
}

/// C 编译器类型
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CCompiler {
    Gcc,
    Clang,
    Msvc,
}

impl Default for CBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            c_standard: CStandard::C23,
            compiler: if cfg!(windows) {
                CCompiler::Msvc
            } else {
                CCompiler::Gcc
            },
        }
    }
}

/// C 代码生成器
pub struct CBackend {
    config: CBackendConfig,
}

impl CBackend {
    /// 创建新的 C 代码生成器
    pub fn new(config: CBackendConfig) -> Self {
        Self { config }
    }

    /// 从 AST 生成 C 代码
    pub fn generate_from_ast(&mut self, program: &AstProgram) -> CResult<String> {
        let xir_program = lower_program(program)?;
        self.generate_from_xir(&xir_program)
    }

    /// 从 X IR 生成 C 代码
    pub fn generate_from_xir(&mut self, program: &Program) -> CResult<String> {
        let mut output = String::new();

        // 生成文件头
        self.write_header(&mut output)?;

        // 生成包含的头文件
        self.write_includes(&mut output)?;

        // 生成前置声明
        self.write_forward_declarations(program, &mut output)?;

        // 生成类型定义
        self.write_type_definitions(program, &mut output)?;

        // 生成函数和全局变量
        self.write_declarations(program, &mut output)?;

        Ok(output)
    }

    /// 写入文件头
    fn write_header(&self, output: &mut String) -> CResult<()> {
        writeln!(output, "// Generated by X-Lang C23 backend")?;
        writeln!(output, "// DO NOT EDIT")?;
        writeln!(output)?;

        match self.config.c_standard {
            CStandard::C23 => writeln!(output, "#define __STDC_VERSION__ 202311L")?,
            CStandard::C17 => writeln!(output, "#define __STDC_VERSION__ 201710L")?,
            CStandard::C11 => writeln!(output, "#define __STDC_VERSION__ 201112L")?,
            _ => {}
        }
        writeln!(output)?;

        Ok(())
    }

    /// 写入头文件包含
    fn write_includes(&self, output: &mut String) -> CResult<()> {
        writeln!(output, "#include <stdio.h>")?;
        writeln!(output, "#include <stdlib.h>")?;
        writeln!(output, "#include <stdbool.h>")?;
        writeln!(output, "#include <stdint.h>")?;
        writeln!(output, "#include <stddef.h>")?;
        writeln!(output, "#include <string.h>")?;
        writeln!(output)?;
        Ok(())
    }

    /// 写入前置声明
    fn write_forward_declarations(
        &self,
        program: &Program,
        output: &mut String,
    ) -> CResult<()> {
        // 结构体前置声明
        for decl in &program.declarations {
            if let Declaration::Struct(s) = decl {
                writeln!(output, "struct {};", s.name)?;
            }
        }

        // 函数前置声明
        for decl in &program.declarations {
            if let Declaration::Function(f) = decl {
                write!(output, "{} {}(", f.return_type, f.name)?;
                if f.parameters.is_empty() {
                    write!(output, "void")?;
                } else {
                    for (i, param) in f.parameters.iter().enumerate() {
                        if i > 0 {
                            write!(output, ", ")?;
                        }
                        write!(output, "{}", param.type_)?;
                    }
                }
                writeln!(output, ");")?;
            }
        }

        writeln!(output)?;
        Ok(())
    }

    /// 写入类型定义
    fn write_type_definitions(&self, program: &Program, output: &mut String) -> CResult<()> {
        for decl in &program.declarations {
            match decl {
                Declaration::Struct(s) => {
                    writeln!(output, "{}", Declaration::Struct(s.clone()))?;
                    writeln!(output)?;
                }
                Declaration::Enum(e) => {
                    writeln!(output, "{}", Declaration::Enum(e.clone()))?;
                    writeln!(output)?;
                }
                Declaration::TypeAlias(t) => {
                    writeln!(output, "{}", Declaration::TypeAlias(t.clone()))?;
                    writeln!(output)?;
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// 写入声明
    fn write_declarations(&self, program: &Program, output: &mut String) -> CResult<()> {
        for decl in &program.declarations {
            match decl {
                Declaration::Function(f) => {
                    writeln!(output, "{}", f)?;
                    writeln!(output)?;
                }
                Declaration::Global(g) => {
                    writeln!(output, "{};", g)?;
                    writeln!(output)?;
                }
                Declaration::ExternFunction(e) => {
                    writeln!(output, "{};", e)?;
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// 编译生成的 C 代码
    pub fn compile_c_code(&self, c_code: &str, output_file: &PathBuf) -> CResult<()> {
        use std::process::Command;

        // 先保存 C 代码到临时文件
        let c_file = output_file.with_extension("c");
        std::fs::write(&c_file, c_code)?;

        // 构建编译器命令
        let mut cmd = match self.config.compiler {
            CCompiler::Gcc => Command::new("gcc"),
            CCompiler::Clang => Command::new("clang"),
            CCompiler::Msvc => Command::new("cl.exe"),
        };

        // 添加标准版本标志
        match self.config.compiler {
            CCompiler::Gcc | CCompiler::Clang => {
                match self.config.c_standard {
                    CStandard::C23 => cmd.arg("-std=c2x"),
                    CStandard::C17 => cmd.arg("-std=c17"),
                    CStandard::C11 => cmd.arg("-std=c11"),
                    CStandard::C99 => cmd.arg("-std=c99"),
                    CStandard::C89 => cmd.arg("-std=c89"),
                };
            }
            CCompiler::Msvc => {
                cmd.arg("/std:c17"); // MSVC 对 C23 支持有限
            }
        }

        // 添加优化标志
        if self.config.optimize {
            match self.config.compiler {
                CCompiler::Gcc | CCompiler::Clang => {
                    cmd.arg("-O2");
                }
                CCompiler::Msvc => {
                    cmd.arg("/O2");
                }
            }
        } else {
            match self.config.compiler {
                CCompiler::Gcc | CCompiler::Clang => {
                    cmd.arg("-O0");
                }
                CCompiler::Msvc => {
                    cmd.arg("/Od");
                }
            }
        }

        // 添加调试信息标志
        if self.config.debug_info {
            match self.config.compiler {
                CCompiler::Gcc | CCompiler::Clang => {
                    cmd.arg("-g");
                }
                CCompiler::Msvc => {
                    cmd.arg("/Zi");
                }
            }
        }

        // 添加警告标志
        match self.config.compiler {
            CCompiler::Gcc => {
                cmd.arg("-Wall").arg("-Wextra");
            }
            CCompiler::Clang => {
                cmd.arg("-Wall").arg("-Wextra");
            }
            CCompiler::Msvc => {
                cmd.arg("/W3");
            }
        }

        // 输出文件
        match self.config.compiler {
            CCompiler::Gcc | CCompiler::Clang => {
                cmd.arg("-o").arg(output_file);
                cmd.arg("-c").arg(&c_file);
            }
            CCompiler::Msvc => {
                cmd.arg(format!("/Fe:{}", output_file.to_string_lossy()));
                cmd.arg(format!("/Fo:{}", output_file.with_extension("obj").to_string_lossy()));
                cmd.arg("/c").arg(&c_file);
            }
        }

        // 执行编译
        let status = cmd.status()?;

        if !status.success() {
            return Err(CBackendError::CompilerError(
                format!("Compiler exited with status: {}", status)
            ));
        }

        Ok(())
    }
}

// ============================================================================
// Error handling
// ============================================================================

/// C 后端错误
#[derive(Debug, thiserror::Error)]
pub enum CBackendError {
    #[error("Lowering error: {0}")]
    LoweringError(#[from] LowerError),

    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),

    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),

    #[error("Compiler error: {0}")]
    CompilerError(String),
}

pub type CResult<T> = Result<T, CBackendError>;

// ============================================================================
// Helper utilities for simple programs
// ============================================================================

/// 创建一个简单的 "Hello, World!" 程序的 X IR
pub fn create_hello_world() -> Program {
    let mut program = Program::new();

    // printf 声明
    program.add(Declaration::ExternFunction(ExternFunction {
        name: "printf".to_string(),
        return_type: Type::Int,
        parameters: vec![Type::Pointer(Box::new(Type::Char))],
    }));

    // main 函数
    let mut main = Function::new("main", Type::Int);

    // printf("Hello, World!\n")
    let printf_call = Expression::Call(
        Box::new(Expression::Variable("printf".to_string())),
        vec![Expression::Literal(Literal::String("Hello, World!\\n".to_string()))],
    );

    main.add_stmt(Statement::Expression(printf_call));
    main.add_stmt(Statement::Return(Some(Expression::Literal(Literal::Integer(0)))));

    program.add(Declaration::Function(main));

    program
}

/// 创建一个简单的 Fibonacci 程序的 X IR
pub fn create_fibonacci() -> Program {
    let mut program = Program::new();

    // printf 声明
    program.add(Declaration::ExternFunction(ExternFunction {
        name: "printf".to_string(),
        return_type: Type::Int,
        parameters: vec![Type::Pointer(Box::new(Type::Char))],
    }));

    // fib(n) = n <= 1 ? n : fib(n-1) + fib(n-2)
    let mut fib = Function::new("fib", Type::Int);
    fib = fib.param("n", Type::Int);

    // n <= 1
    let cond = Expression::Binary(
        BinaryOp::LessThanEqual,
        Box::new(Expression::Variable("n".to_string())),
        Box::new(Expression::Literal(Literal::Integer(1))),
    );

    // n - 1
    let n_minus_1 = Expression::Binary(
        BinaryOp::Subtract,
        Box::new(Expression::Variable("n".to_string())),
        Box::new(Expression::Literal(Literal::Integer(1))),
    );

    // n - 2
    let n_minus_2 = Expression::Binary(
        BinaryOp::Subtract,
        Box::new(Expression::Variable("n".to_string())),
        Box::new(Expression::Literal(Literal::Integer(2))),
    );

    // fib(n-1)
    let fib_n_minus_1 = Expression::Call(
        Box::new(Expression::Variable("fib".to_string())),
        vec![n_minus_1],
    );

    // fib(n-2)
    let fib_n_minus_2 = Expression::Call(
        Box::new(Expression::Variable("fib".to_string())),
        vec![n_minus_2],
    );

    // fib(n-1) + fib(n-2)
    let sum = Expression::Binary(
        BinaryOp::Add,
        Box::new(fib_n_minus_1),
        Box::new(fib_n_minus_2),
    );

    // if (n <= 1) { return n; } else { return fib(n-1) + fib(n-2); }
    let mut then_block = Block::new();
    then_block.add(Statement::Return(Some(Expression::Variable("n".to_string()))));

    let mut else_block = Block::new();
    else_block.add(Statement::Return(Some(sum)));

    let if_stmt = Statement::If(IfStatement {
        condition: cond,
        then_branch: Box::new(Statement::Compound(then_block)),
        else_branch: Some(Box::new(Statement::Compound(else_block))),
    });

    fib.add_stmt(if_stmt);
    program.add(Declaration::Function(fib));

    // main 函数
    let mut main = Function::new("main", Type::Int);

    // for (int i = 0; i < 10; i++) printf("fib(%d) = %d\n", i, fib(i));
    let mut for_body = Block::new();

    let printf_call = Expression::Call(
        Box::new(Expression::Variable("printf".to_string())),
        vec![
            Expression::Literal(Literal::String("fib(%d) = %d\\n".to_string())),
            Expression::Variable("i".to_string()),
            Expression::Call(
                Box::new(Expression::Variable("fib".to_string())),
                vec![Expression::Variable("i".to_string())],
            ),
        ],
    );

    for_body.add(Statement::Expression(printf_call));

    let for_stmt = Statement::For(ForStatement {
        initializer: Some(Box::new(Statement::Variable(
            Variable::new("i", Type::Int).init(Expression::Literal(Literal::Integer(0)))
        ))),
        condition: Some(Expression::Binary(
            BinaryOp::LessThan,
            Box::new(Expression::Variable("i".to_string())),
            Box::new(Expression::Literal(Literal::Integer(10))),
        )),
        increment: Some(Expression::Unary(
            UnaryOp::PostIncrement,
            Box::new(Expression::Variable("i".to_string())),
        )),
        body: Box::new(Statement::Compound(for_body)),
    });

    main.add_stmt(for_stmt);
    main.add_stmt(Statement::Return(Some(Expression::Literal(Literal::Integer(0)))));

    program.add(Declaration::Function(main));

    program
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = create_hello_world();
        let mut backend = CBackend::new(CBackendConfig::default());
        let c_code = backend.generate_from_xir(&program).unwrap();
        assert!(c_code.contains("Hello, World!"));
        assert!(c_code.contains("int main()"));
    }

    #[test]
    fn test_fibonacci_generation() {
        let program = create_fibonacci();
        let mut backend = CBackend::new(CBackendConfig::default());
        let c_code = backend.generate_from_xir(&program).unwrap();
        assert!(c_code.contains("int fib("));
        assert!(c_code.contains("printf("));
    }
}
