//! C23 后端 - 动态类型版
//! 将 X AST 直接编译为使用 x_runtime.h 的 C 代码
//!
//! 所有 X 值映射到 `XValue`（tagged union），运算通过 runtime 函数完成。

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct CBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
    pub c_standard: CStandard,
    pub compiler: CCompiler,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CStandard { C89, C99, C11, C17, C23 }

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CCompiler { Gcc, Clang, Msvc }

impl Default for CBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            c_standard: CStandard::C23,
            compiler: if cfg!(windows) { CCompiler::Msvc } else { CCompiler::Gcc },
        }
    }
}

pub struct CBackend {
    config: CBackendConfig,
    indent: usize,
    output: String,
    /// Track global (top-level) variable declarations for forward decls
    global_vars: Vec<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum CBackendError {
    #[error("Lowering error: {0}")]
    LoweringError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Compiler error: {0}")]
    CompilerError(String),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type CResult<T> = Result<T, CBackendError>;

impl CBackend {
    pub fn new(config: CBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            global_vars: Vec::new(),
        }
    }

    pub fn generate_from_ast(&mut self, program: &AstProgram) -> CResult<String> {
        self.output.clear();
        self.indent = 0;
        self.global_vars.clear();

        self.emit_header()?;

        // Forward declare all user-defined functions
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                self.emit_forward_decl(f)?;
            }
        }
        self.line("")?;

        // Emit global variables
        for decl in &program.declarations {
            if let ast::Declaration::Variable(v) = decl {
                self.emit_global_var(v)?;
            }
        }

        // Emit functions
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                self.emit_function(f)?;
                self.line("")?;
            }
        }

        // If there's a user-defined main, wrap it
        let has_main = program.declarations.iter().any(|d| {
            matches!(d, ast::Declaration::Function(f) if f.name == "main")
        });

        if has_main {
            self.line("int main(int argc, char **argv) {")?;
            self.indent += 1;
            self.line("x_main();")?;
            self.line("return 0;")?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(self.output.clone())
    }

    fn emit_header(&mut self) -> CResult<()> {
        self.line("// Generated by X-Lang C23 backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        self.line("#include \"x_runtime.h\"")?;
        self.line("")?;
        Ok(())
    }

    fn emit_forward_decl(&mut self, f: &ast::FunctionDecl) -> CResult<()> {
        let cname = self.mangle_fn(&f.name);
        let params = if f.parameters.is_empty() {
            "void".to_string()
        } else {
            f.parameters.iter().map(|p| format!("XValue {}", p.name)).collect::<Vec<_>>().join(", ")
        };
        self.line(&format!("XValue {}({});", cname, params))?;
        Ok(())
    }

    fn emit_global_var(&mut self, v: &ast::VariableDecl) -> CResult<()> {
        let init = if let Some(expr) = &v.initializer {
            self.emit_global_init(expr)?
        } else {
            "{.tag = X_NULL, .as = {.i = 0}}".to_string()
        };
        self.line(&format!("XValue {} = {};", v.name, init))?;
        self.global_vars.push(v.name.clone());
        Ok(())
    }

    fn emit_global_init(&self, expr: &ast::Expression) -> CResult<String> {
        match expr {
            ast::Expression::Literal(ast::Literal::Integer(n)) => {
                Ok(format!("{{.tag = X_INT, .as = {{.i = {}LL}}}}", n))
            }
            ast::Expression::Literal(ast::Literal::Float(f)) => {
                Ok(format!("{{.tag = X_FLOAT, .as = {{.f = {:.17}}}}}", f))
            }
            ast::Expression::Literal(ast::Literal::Boolean(b)) => {
                Ok(format!("{{.tag = X_BOOL, .as = {{.b = {}}}}}", b))
            }
            ast::Expression::Literal(ast::Literal::Null) => {
                Ok("{.tag = X_NULL, .as = {.i = 0}}".to_string())
            }
            _ => {
                // For non-constant expressions, initialize to null and assign in x_main_init
                Ok("{.tag = X_NULL, .as = {.i = 0}}".to_string())
            }
        }
    }

    fn emit_function(&mut self, f: &ast::FunctionDecl) -> CResult<()> {
        let cname = self.mangle_fn(&f.name);
        let params = if f.parameters.is_empty() {
            "void".to_string()
        } else {
            f.parameters.iter().map(|p| format!("XValue {}", p.name)).collect::<Vec<_>>().join(", ")
        };
        self.line(&format!("XValue {}({}) {{", cname, params))?;
        self.indent += 1;
        self.emit_block(&f.body)?;
        self.line("return x_null();")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> CResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> CResult<()> {
        match stmt {
            ast::Statement::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            ast::Statement::Variable(v) => {
                let init = if let Some(expr) = &v.initializer {
                    self.emit_expr(expr)?
                } else {
                    "x_null()".to_string()
                };
                self.line(&format!("XValue {} = {};", v.name, init))?;
            }
            ast::Statement::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return x_null();")?;
                }
            }
            ast::Statement::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            ast::Statement::While(while_stmt) => {
                // Special case: `while true` → infinite loop
                if matches!(&while_stmt.condition, ast::Expression::Literal(ast::Literal::Boolean(true))) {
                    self.line("while (1) {")?;
                } else {
                    let cond = self.emit_expr(&while_stmt.condition)?;
                    self.line(&format!("while (x_as_bool({})) {{", cond))?;
                }
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            ast::Statement::For(_) => {
                self.line("/* TODO: for loop */")?;
            }
            ast::Statement::Match(_) => {
                self.line("/* TODO: match */")?;
            }
            ast::Statement::Try(_) => {
                self.line("/* TODO: try */")?;
            }
        }
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> CResult<()> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if (x_as_bool({})) {{", cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;
        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }
        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> CResult<String> {
        match expr {
            ast::Expression::Literal(lit) => self.emit_literal(lit),
            ast::Expression::Variable(name) => {
                Ok(name.clone())
            }
            ast::Expression::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ast::Expression::Unary(op, expr) => {
                let e = self.emit_expr(expr)?;
                Ok(self.emit_unaryop(op, &e))
            }
            ast::Expression::Call(callee, args) => {
                self.emit_call(callee, args)
            }
            ast::Expression::Assign(target, value) => {
                self.emit_assign(target, value)
            }
            ast::Expression::Array(elements) => {
                self.emit_array_literal(elements)
            }
            ast::Expression::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            ast::Expression::If(cond, then_e, else_e) => {
                let c = self.emit_expr(cond)?;
                let t = self.emit_expr(then_e)?;
                let e = self.emit_expr(else_e)?;
                Ok(format!("(x_as_bool({}) ? {} : {})", c, t, e))
            }
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("x_index_get({}, x_string(\"{}\"))", o, field))
            }
            _ => Err(CBackendError::UnsupportedFeature(format!("{:?}", expr))),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> CResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(format!("x_int({}LL)", n)),
            ast::Literal::Float(f) => {
                if f.is_infinite() || f.is_nan() {
                    Ok(format!("x_float({})", f))
                } else {
                    Ok(format!("x_float({:.17})", f))
                }
            }
            ast::Literal::Boolean(b) => Ok(format!("x_bool({})", b)),
            ast::Literal::String(s) => {
                let escaped = s.replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("x_string(\"{}\")", escaped))
            }
            ast::Literal::Char(c) => Ok(format!("x_string(\"{}\")", c)),
            ast::Literal::Null => Ok("x_null()".to_string()),
            ast::Literal::None => Ok("x_none()".to_string()),
            ast::Literal::Unit => Ok("x_null()".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("x_add({}, {})", l, r),
            ast::BinaryOp::Sub => format!("x_sub({}, {})", l, r),
            ast::BinaryOp::Mul => format!("x_mul({}, {})", l, r),
            ast::BinaryOp::Div => format!("x_div({}, {})", l, r),
            ast::BinaryOp::Mod => format!("x_mod({}, {})", l, r),
            ast::BinaryOp::Equal => format!("x_eq({}, {})", l, r),
            ast::BinaryOp::NotEqual => format!("x_neq({}, {})", l, r),
            ast::BinaryOp::Less => format!("x_lt({}, {})", l, r),
            ast::BinaryOp::LessEqual => format!("x_le({}, {})", l, r),
            ast::BinaryOp::Greater => format!("x_gt({}, {})", l, r),
            ast::BinaryOp::GreaterEqual => format!("x_ge({}, {})", l, r),
            ast::BinaryOp::And => format!("x_and({}, {})", l, r),
            ast::BinaryOp::Or => format!("x_or({}, {})", l, r),
            ast::BinaryOp::Pow => format!("x_pow({}, {})", l, r),
            _ => format!("/* unsupported binop {:?} */ x_null()", op),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("x_neg({})", e),
            ast::UnaryOp::Not => format!("x_not({})", e),
            _ => format!("/* unsupported unary {:?} */ x_null()", op),
        }
    }

    fn emit_call(&self, callee: &ast::Expression, args: &[ast::Expression]) -> CResult<String> {
        // Check for known builtins
        if let ast::Expression::Variable(name) = callee {
            let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect::<CResult<Vec<_>>>()?;
            return Ok(self.emit_builtin_or_call(name, &arg_strs));
        }
        // Generic call (shouldn't happen often)
        let callee_str = self.emit_expr(callee)?;
        let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect::<CResult<Vec<_>>>()?;
        Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
    }

    fn emit_builtin_or_call(&self, name: &str, args: &[String]) -> String {
        match name {
            "print" | "println" => {
                if args.len() == 1 { format!("x_print({})", args[0]) }
                else { "x_print(x_null())".to_string() }
            }
            "print_inline" => {
                if args.len() == 1 { format!("x_print_inline({})", args[0]) }
                else { "x_print_inline(x_null())".to_string() }
            }
            "concat" => {
                if args.len() == 2 { format!("x_concat({}, {})", args[0], args[1]) }
                else { "x_string(\"\")".to_string() }
            }
            "to_string" => format!("x_to_string({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "to_int" => format!("x_to_int({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "to_float" => format!("x_to_float({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "char_at" => {
                if args.len() == 2 { format!("x_char_at({}, {})", args[0], args[1]) }
                else { "x_string(\"\")".to_string() }
            }
            "substring" => {
                if args.len() == 3 { format!("x_substring({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_string(\"\")".to_string() }
            }
            "len" => format!("x_len({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_upper" => format!("x_str_upper({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_lower" => format!("x_str_lower({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_trim" => format!("x_str_trim({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_split" => {
                if args.len() == 2 { format!("x_str_split({}, {})", args[0], args[1]) }
                else { "x_array_val(x_array_new(0))".to_string() }
            }
            "str_starts_with" => {
                if args.len() == 2 { format!("x_str_starts_with({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "str_contains" => {
                if args.len() == 2 { format!("x_str_contains({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "str_find" => {
                if args.len() == 2 { format!("x_str_find({}, {})", args[0], args[1]) }
                else { "x_int(-1)".to_string() }
            }
            "str_replace" => {
                if args.len() == 3 { format!("x_str_replace({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_string(\"\")".to_string() }
            }
            // Arrays
            "new_array" => {
                if args.len() == 2 { format!("x_new_array({}, {})", args[0], args[1]) }
                else { "x_array_val(x_array_new(0))".to_string() }
            }
            "push" => {
                if args.len() == 2 { format!("x_push({}, {})", args[0], args[1]) }
                else { "x_null()".to_string() }
            }
            "copy_array" => format!("x_copy_array({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "swap" => {
                if args.len() == 3 { format!("x_swap({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_null()".to_string() }
            }
            "sort_by_value_desc" => format!("x_sort_by_value_desc({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            // Map
            "new_map" => "x_builtin_new_map()".to_string(),
            "map_set" => {
                if args.len() == 3 { format!("x_builtin_map_set({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_null()".to_string() }
            }
            "map_get" => {
                if args.len() == 2 { format!("x_builtin_map_get({}, {})", args[0], args[1]) }
                else { "x_null()".to_string() }
            }
            "map_contains" => {
                if args.len() == 2 { format!("x_builtin_map_contains({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "map_keys" => format!("x_builtin_map_keys({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            // Math
            "sqrt" => format!("x_sqrt({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "pow" => {
                if args.len() == 2 { format!("x_pow({}, {})", args[0], args[1]) }
                else { "x_float(0.0)".to_string() }
            }
            "abs" => format!("x_abs({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "sin" => format!("x_sin({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "cos" => format!("x_cos({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "floor" => format!("x_floor({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "ceil" => format!("x_ceil({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "round" => format!("x_round({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            // Type conversion
            "format_float" => {
                if args.len() == 2 { format!("x_format_float({}, {})", args[0], args[1]) }
                else { "x_string(\"0.0\")".to_string() }
            }
            "type_of" => format!("x_type_of({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            // Regex
            "regex_match_count" => {
                if args.len() == 2 { format!("x_regex_match_count({}, {})", args[0], args[1]) }
                else { "x_int(0)".to_string() }
            }
            // Pi digits
            "compute_pi_digits" => format!("x_compute_pi_digits({})", args.first().map(|s| s.as_str()).unwrap_or("x_int(0)")),
            // Array indexing (parser internal)
            "__index__" => {
                if args.len() == 2 { format!("x_index_get({}, {})", args[0], args[1]) }
                else { "x_null()".to_string() }
            }
            // User-defined function
            _ => {
                let cname = self.mangle_fn(name);
                format!("{}({})", cname, args.join(", "))
            }
        }
    }

    fn emit_assign(&self, target: &ast::Expression, value: &ast::Expression) -> CResult<String> {
        let val = self.emit_expr(value)?;
        match target {
            ast::Expression::Variable(name) => {
                Ok(format!("({} = {})", name, val))
            }
            // arr[i] is parsed as Call(Variable("__index__"), [arr, i])
            ast::Expression::Call(callee, args) if args.len() == 2 => {
                if let ast::Expression::Variable(name) = callee.as_ref() {
                    if name == "__index__" {
                        let arr = self.emit_expr(&args[0])?;
                        let idx = self.emit_expr(&args[1])?;
                        return Ok(format!("(x_index_set({}, {}, {}), x_null())", arr, idx, val));
                    }
                }
                let t = self.emit_expr(target)?;
                Ok(format!("({} = {})", t, val))
            }
            _ => {
                let t = self.emit_expr(target)?;
                Ok(format!("({} = {})", t, val))
            }
        }
    }

    fn emit_array_literal(&self, elements: &[ast::Expression]) -> CResult<String> {
        if elements.is_empty() {
            return Ok("x_array_val(x_array_new(0))".to_string());
        }
        // We need a compound expression to build the array
        let mut parts = Vec::new();
        parts.push("({ XArray *_a = x_array_new(".to_string());
        parts.push(format!("{}); ", elements.len()));
        for elem in elements {
            let e = self.emit_expr(elem)?;
            parts.push(format!("x_array_push(_a, {}); ", e));
        }
        parts.push("x_array_val(_a); })".to_string());
        Ok(parts.join(""))
    }

    fn mangle_fn(&self, name: &str) -> String {
        format!("x_{}", name)
    }

    fn line(&mut self, s: &str) -> CResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }

    /// Compile generated C code to executable
    pub fn compile_c_code(&self, c_code: &str, output_file: &PathBuf) -> CResult<()> {
        use std::process::Command;

        let c_file = output_file.with_extension("c");
        std::fs::write(&c_file, c_code)?;

        // Copy runtime header next to the C file
        let runtime_dir = c_file.parent().unwrap_or(std::path::Path::new("."));
        let runtime_path = runtime_dir.join("x_runtime.h");
        let runtime_src = include_str!("../runtime/x_runtime.h");
        std::fs::write(&runtime_path, runtime_src)?;

        let mut cmd = match self.config.compiler {
            CCompiler::Gcc => Command::new("gcc"),
            CCompiler::Clang => Command::new("clang"),
            CCompiler::Msvc => Command::new("cl.exe"),
        };

        match self.config.compiler {
            CCompiler::Gcc | CCompiler::Clang => {
                match self.config.c_standard {
                    CStandard::C23 => { cmd.arg("-std=c2x"); }
                    CStandard::C17 => { cmd.arg("-std=c17"); }
                    CStandard::C11 => { cmd.arg("-std=c11"); }
                    CStandard::C99 => { cmd.arg("-std=c99"); }
                    CStandard::C89 => { cmd.arg("-std=c89"); }
                }
                if self.config.optimize { cmd.arg("-O2"); } else { cmd.arg("-O0"); }
                if self.config.debug_info { cmd.arg("-g"); }
                cmd.arg("-lm");
                cmd.arg("-I").arg(runtime_dir);
                cmd.arg("-o").arg(output_file);
                cmd.arg(&c_file);
            }
            CCompiler::Msvc => {
                cmd.arg("/std:c17");
                if self.config.optimize { cmd.arg("/O2"); } else { cmd.arg("/Od"); }
                if self.config.debug_info { cmd.arg("/Zi"); }
                cmd.arg(format!("/I{}", runtime_dir.to_string_lossy()));
                cmd.arg(format!("/Fe:{}", output_file.to_string_lossy()));
                cmd.arg(&c_file);
            }
        }

        let output = cmd.output()?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(CBackendError::CompilerError(
                format!("C compiler failed:\n{}", stderr)
            ));
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            declarations: vec![
                ast::Declaration::Function(ast::FunctionDecl {
                    name: "main".to_string(),
                    parameters: vec![],
                    return_type: None,
                    body: ast::Block {
                        statements: vec![
                            ast::Statement::Expression(
                                ast::Expression::Call(
                                    Box::new(ast::Expression::Variable("print".to_string())),
                                    vec![ast::Expression::Literal(ast::Literal::String("Hello, World!".to_string()))],
                                )
                            ),
                        ],
                    },
                    is_async: false,
                }),
            ],
        };

        let mut backend = CBackend::new(CBackendConfig::default());
        let c_code = backend.generate_from_ast(&program).unwrap();
        assert!(c_code.contains("x_print"));
        assert!(c_code.contains("Hello, World!"));
        assert!(c_code.contains("int main("));
    }
}
