//! C# 后端 - 将 X AST 编译为 .NET 字节码
//!
//! 生成 C# 代码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, ExpressionKind, StatementKind, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct CSharpBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for CSharpBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct CSharpBackend {
    config: CSharpBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum CSharpBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type CSharpResult<T> = Result<T, CSharpBackendError>;

impl CSharpBackend {
    pub fn new(config: CSharpBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> CSharpResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_namespace()?;
        self.emit_class(program)?;

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("Program.cs"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::DotNetAssembly,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> CSharpResult<()> {
        self.line("// Generated by X-Lang C# backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_namespace(&mut self) -> CSharpResult<()> {
        self.line("namespace XLang")?;
        self.line("{")?;
        self.indent += 1;
        Ok(())
    }

    fn emit_class(&mut self, program: &AstProgram) -> CSharpResult<()> {
        self.line("using System;")?;
        self.line("")?;

        // Emit X classes as C# classes
        for decl in &program.declarations {
            if let ast::Declaration::Class(class) = decl {
                self.emit_x_class(class)?;
            }
        }

        // Emit X traits as C# interfaces
        for decl in &program.declarations {
            if let ast::Declaration::Trait(trait_decl) = decl {
                self.emit_x_trait(trait_decl)?;
            }
        }

        // Main Program class
        self.line("public class Program")?;
        self.line("{")?;
        self.indent += 1;

        // Emit all top-level variable declarations as static fields
        for decl in &program.declarations {
            if let ast::Declaration::Variable(var) = decl {
                let value_str = if let Some(init) = &var.initializer {
                    self.emit_expr(init)?
                } else {
                    "null".to_string()
                };
                self.line(&format!("public static var {} = {};", var.name, value_str))?;
            }
        }

        self.line("")?;

        // Emit all function declarations as static methods
        for decl in &program.declarations {
            if let ast::Declaration::Function(func) = decl {
                self.emit_function_as_method(func)?;
                self.line("")?;
            }
        }

        // Emit main method with program statements
        self.emit_main_method(&program.statements)?;

        self.indent -= 1;
        self.line("}")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// Emit an X class as a C# class
    fn emit_x_class(&mut self, class: &ast::ClassDecl) -> CSharpResult<()> {
        // Build class declaration
        let mut class_line = String::new();

        // Modifiers
        if class.modifiers.is_abstract {
            class_line.push_str("abstract ");
        }
        if class.modifiers.is_final {
            class_line.push_str("sealed ");
        }

        class_line.push_str(&format!("public class {}", class.name));

        // Extends (C# uses ':' for both inheritance and interface implementation)
        let mut inheritance = Vec::new();
        if let Some(parent) = &class.extends {
            inheritance.push(parent.clone());
        }
        inheritance.extend(class.implements.clone());

        if !inheritance.is_empty() {
            class_line.push_str(&format!(" : {}", inheritance.join(", ")));
        }

        class_line.push_str("\n{");

        self.line(&class_line)?;
        self.indent += 1;

        // Emit fields
        for member in &class.members {
            if let ast::ClassMember::Field(field) = member {
                let field_type = self.csharp_type(field.type_annot.as_ref());
                let visibility = self.visibility_str(field.visibility);
                self.line(&format!("{}{} {};", visibility, field_type, field.name))?;
            }
        }

        // Emit constructors
        for member in &class.members {
            if let ast::ClassMember::Constructor(constructor) = member {
                self.emit_constructor(&class.name, constructor)?;
            }
        }

        // Emit methods
        for member in &class.members {
            if let ast::ClassMember::Method(method) = member {
                self.emit_method(&class.name, method)?;
            }
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    /// Emit an X trait as a C# interface
    fn emit_x_trait(&mut self, trait_decl: &ast::TraitDecl) -> CSharpResult<()> {
        let mut interface_line = format!("public interface {}", trait_decl.name);

        // C# interfaces can extend multiple interfaces
        if !trait_decl.extends.is_empty() {
            interface_line.push_str(&format!(" : {}", trait_decl.extends.join(", ")));
        }

        interface_line.push_str("\n{");

        self.line(&interface_line)?;
        self.indent += 1;

        // Emit method signatures
        for method in &trait_decl.methods {
            let return_type = self.csharp_type(method.return_type.as_ref());
            let params: Vec<String> = method
                .parameters
                .iter()
                .map(|p| format!("{} {}", self.csharp_type(p.type_annot.as_ref()), p.name))
                .collect();

            self.line(&format!("{} {}({});", return_type, method.name, params.join(", ")))?;
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    /// Emit a C# constructor
    fn emit_constructor(&mut self, class_name: &str, constructor: &ast::ConstructorDecl) -> CSharpResult<()> {
        let params: Vec<String> = constructor
            .parameters
            .iter()
            .map(|p| format!("{} {}", self.csharp_type(p.type_annot.as_ref()), p.name))
            .collect();

        self.line(&format!("public {}({})", class_name, params.join(", ")))?;
        self.line("{")?;
        self.indent += 1;

        self.emit_block(&constructor.body)?;

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// Emit a C# method
    fn emit_method(&mut self, class_name: &str, method: &ast::FunctionDecl) -> CSharpResult<()> {
        let return_type = self.csharp_type(method.return_type.as_ref());

        let params: Vec<String> = method
            .parameters
            .iter()
            .map(|p| format!("{} {}", self.csharp_type(p.type_annot.as_ref()), p.name))
            .collect();

        // Modifiers
        let mut modifiers = String::new();
        if method.modifiers.is_static {
            modifiers.push_str("static ");
        }
        if method.modifiers.is_final {
            modifiers.push_str("sealed ");
        }
        if method.modifiers.is_abstract {
            modifiers.push_str("abstract ");
        }
        if method.modifiers.is_virtual {
            modifiers.push_str("virtual ");
        }
        if method.modifiers.is_override {
            modifiers.push_str("override ");
        }

        let visibility = self.visibility_str(method.modifiers.visibility);

        self.line(&format!(
            "{}{}{} {}({})",
            visibility, modifiers, return_type, method.name, params.join(", ")
        ))?;
        self.line("{")?;
        self.indent += 1;

        self.emit_block(&method.body)?;

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// Convert X type to C# type
    fn csharp_type(&self, type_annot: Option<&ast::Type>) -> String {
        match type_annot {
            Some(t) => match t {
                ast::Type::Int => "int".to_string(),
                ast::Type::Float => "double".to_string(),
                ast::Type::Bool => "bool".to_string(),
                ast::Type::String => "string".to_string(),
                ast::Type::Char => "char".to_string(),
                ast::Type::Unit => "void".to_string(),
                ast::Type::Option(inner) => format!("{}?", self.csharp_type(Some(inner))),
                ast::Type::Generic(name) | ast::Type::TypeParam(name) => name.clone(),
                _ => "object".to_string(),
            },
            None => "object".to_string(),
        }
    }

    /// Convert X visibility to C# visibility
    fn visibility_str(&self, visibility: ast::Visibility) -> &'static str {
        match visibility {
            ast::Visibility::Private => "private ",
            ast::Visibility::Public => "public ",
            ast::Visibility::Protected => "protected ",
            ast::Visibility::Internal => "internal ",
        }
    }

    fn emit_main_method(&mut self, statements: &[ast::Statement]) -> CSharpResult<()> {
        self.line("public static void Main(string[] args)")?;
        self.line("{")?;
        self.indent += 1;

        // Emit all program statements
        for stmt in statements {
            self.emit_statement(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_function_as_method(&mut self, func: &ast::FunctionDecl) -> CSharpResult<()> {
        // For now, return void, we'll add type support later
        let mut params = Vec::new();
        for param in &func.parameters {
            params.push(format!("object {}", param.name));
        }

        // Handle async functions - return Task<object>
        let (return_type, async_keyword) = if func.is_async {
            ("Task<object>", "async ")
        } else {
            ("object", "")
        };

        self.line(&format!(
            "public static {} {}{}({})",
            return_type,
            async_keyword,
            func.name,
            params.join(", ")
        ))?;
        self.line("{")?;
        self.indent += 1;

        self.emit_block(&func.body)?;

        // Add return statement
        if func.is_async {
            self.line("return Task.FromResult<object>(null);")?;
        } else {
            self.line("return null;")?;
        }
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn line(&mut self, s: &str) -> CSharpResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> CSharpResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let expr_str = self.emit_expr(expr)?;
                self.line(&format!("{};", expr_str))?;
            }
            StatementKind::Variable(decl) => {
                let value_str = if let Some(init) = &decl.initializer {
                    self.emit_expr(init)?
                } else {
                    "null".to_string()
                };
                self.line(&format!("var {} = {};", decl.name, value_str))?;
            }
            StatementKind::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            StatementKind::While(while_stmt) => {
                self.emit_while(while_stmt)?;
            }
            StatementKind::For(for_stmt) => {
                self.emit_for(for_stmt)?;
            }
            StatementKind::Match(match_stmt) => {
                self.emit_match(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try(try_stmt)?;
            }
            StatementKind::Return(ret) => {
                if let Some(expr) = ret {
                    let expr_str = self.emit_expr(expr)?;
                    self.line(&format!("return {};", expr_str))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::Break => {
                self.line("break;")?;
            }
            StatementKind::Continue => {
                self.line("continue;")?;
            }
            StatementKind::DoWhile(do_while) => {
                self.line("while (true)")?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(&do_while.body)?;
                let cond = self.emit_expr(&do_while.condition)?;
                self.line(&format!("if (!({})) break;", cond))?;
                self.indent -= 1;
                self.line("}")?;
            }
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> CSharpResult<()> {
        self.line("{")?;
        self.indent += 1;
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> CSharpResult<()> {
        let cond_str = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if ({})", cond_str))?;
        self.emit_block(&if_stmt.then_block)?;

        if let Some(else_block) = &if_stmt.else_block {
            self.line("else")?;
            self.emit_block(else_block)?;
        }

        Ok(())
    }

    fn emit_while(&mut self, while_stmt: &ast::WhileStatement) -> CSharpResult<()> {
        let cond_str = self.emit_expr(&while_stmt.condition)?;
        self.line(&format!("while ({})", cond_str))?;
        self.emit_block(&while_stmt.body)?;
        Ok(())
    }

    fn emit_for(&mut self, for_stmt: &ast::ForStatement) -> CSharpResult<()> {
        let iter = self.emit_expr(&for_stmt.iterator)?;
        let pattern_name = self.emit_pattern_var(&for_stmt.pattern);
        // C# foreach syntax
        self.line(&format!("foreach (var {} in {})", pattern_name, iter))?;
        self.emit_block(&for_stmt.body)?;
        Ok(())
    }

    fn emit_pattern_var(&self, pattern: &ast::Pattern) -> String {
        match pattern {
            ast::Pattern::Wildcard => "_".to_string(),
            ast::Pattern::Variable(name) => name.clone(),
            ast::Pattern::Or(left, _) => self.emit_pattern_var(left),
            ast::Pattern::Guard(inner, _) => self.emit_pattern_var(inner),
            _ => "item".to_string(),
        }
    }

    fn emit_match(&mut self, match_stmt: &ast::MatchStatement) -> CSharpResult<()> {
        let expr = self.emit_expr(&match_stmt.expression)?;
        // C# 7+ pattern matching with switch expression
        self.line(&format!("switch ({})", expr))?;
        self.line("{")?;
        self.indent += 1;

        for case in &match_stmt.cases {
            let pattern_str = self.emit_match_pattern(&case.pattern);
            let when_clause = if let Some(guard) = &case.guard {
                let guard_str = self.emit_expr(guard)?;
                format!(" when ({})", guard_str)
            } else {
                String::new()
            };
            self.line(&format!("{}{} =>", pattern_str, when_clause))?;
            self.indent += 1;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
            self.indent -= 1;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_match_pattern(&self, pattern: &ast::Pattern) -> String {
        match pattern {
            ast::Pattern::Wildcard => "_".to_string(),
            ast::Pattern::Variable(name) => name.clone(),
            ast::Pattern::Literal(lit) => self.emit_literal(lit).unwrap_or_else(|_| "_".to_string()),
            ast::Pattern::Or(left, right) => {
                format!("{} or {}", self.emit_match_pattern(left), self.emit_match_pattern(right))
            }
            ast::Pattern::Array(elements) => {
                let elem_strs: Vec<String> = elements.iter().map(|p| self.emit_match_pattern(p)).collect();
                format!("[{}]", elem_strs.join(", "))
            }
            ast::Pattern::Tuple(elements) => {
                let elem_strs: Vec<String> = elements.iter().map(|p| self.emit_match_pattern(p)).collect();
                format!("({})", elem_strs.join(", "))
            }
            _ => "_".to_string(),
        }
    }

    fn emit_try(&mut self, try_stmt: &ast::TryStatement) -> CSharpResult<()> {
        self.line("try")?;
        self.line("{")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;

        for catch in &try_stmt.catch_clauses {
            let catch_line = if let Some(var_name) = &catch.variable_name {
                if let Some(exc_type) = &catch.exception_type {
                    format!("catch ({} {})", exc_type, var_name)
                } else {
                    format!("catch (Exception {})", var_name)
                }
            } else {
                "catch".to_string()
            };
            self.line(&catch_line)?;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(&catch.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("finally")?;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(finally)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> CSharpResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => self.emit_literal(lit),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, lhs, rhs) => {
                let lhs_str = self.emit_expr(lhs)?;
                let rhs_str = self.emit_expr(rhs)?;
                match op {
                    ast::BinaryOp::Pow => {
                        // Pow is a function call in C#, not an operator
                        Ok(format!("Math.Pow({}, {})", lhs_str, rhs_str))
                    }
                    _ => Ok(format!("({} {} {})", lhs_str, self.emit_binop(op), rhs_str)),
                }
            }
            ExpressionKind::Unary(op, operand) => {
                let expr_str = self.emit_expr(operand)?;
                Ok(format!("({}{})", self.emit_unaryop(op), expr_str))
            }
            ExpressionKind::Call(callee, args) => {
                let mut arg_strs = Vec::new();
                for arg in args {
                    arg_strs.push(self.emit_expr(arg)?);
                }
                let callee_str = self.emit_expr(callee)?;
                self.emit_call(&callee_str, &arg_strs)
            }
            ExpressionKind::Parenthesized(expr) => {
                let inner = self.emit_expr(expr)?;
                Ok(format!("({})", inner))
            }
            ExpressionKind::Assign(lhs, rhs) => {
                let lhs_str = self.emit_expr(lhs)?;
                let rhs_str = self.emit_expr(rhs)?;
                Ok(format!("{} = {}", lhs_str, rhs_str))
            }
            ExpressionKind::Wait(wait_type, exprs) => {
                self.emit_wait(wait_type, exprs)
            }
            _ => Err(CSharpBackendError::UnsupportedFeature(format!(
                "Expression type not supported: {:?}",
                expr
            ))),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> CSharpResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(f.to_string()),
            ast::Literal::Boolean(b) => Ok(b.to_string().to_lowercase()),
            ast::Literal::String(s) => Ok(format!("\"{}\"", s)),
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null | ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("null".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp) -> &str {
        match op {
            ast::BinaryOp::Add => "+",
            ast::BinaryOp::Sub => "-",
            ast::BinaryOp::Mul => "*",
            ast::BinaryOp::Div => "/",
            ast::BinaryOp::Mod => "%",
            ast::BinaryOp::Pow => "Math.Pow", // Special case, will handle differently
            ast::BinaryOp::Equal => "==",
            ast::BinaryOp::NotEqual => "!=",
            ast::BinaryOp::Less => "<",
            ast::BinaryOp::LessEqual => "<=",
            ast::BinaryOp::Greater => ">",
            ast::BinaryOp::GreaterEqual => ">=",
            ast::BinaryOp::And => "&&",
            ast::BinaryOp::Or => "||",
            ast::BinaryOp::BitAnd => "&",
            ast::BinaryOp::BitOr => "|",
            ast::BinaryOp::BitXor => "^",
            ast::BinaryOp::LeftShift => "<<",
            ast::BinaryOp::RightShift => ">>",
            ast::BinaryOp::Concat => "+",
            _ => "+", // Default for unsupported ops
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp) -> &str {
        match op {
            ast::UnaryOp::Negate => "-",
            ast::UnaryOp::Not => "!",
            ast::UnaryOp::BitNot => "~",
            ast::UnaryOp::Wait => "await ", // Wait becomes await
            _ => "", // Ignore other ops for now
        }
    }

    fn emit_wait(&self, wait_type: &ast::WaitType, exprs: &[ast::Expression]) -> CSharpResult<String> {
        let expr_strs: Vec<String> = exprs
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<Result<Vec<_>, _>>()?;
        match wait_type {
            ast::WaitType::Single => {
                // Single await: await expr
                if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    // Multiple expressions - await each
                    let awaited: Vec<String> = expr_strs.iter().map(|e| format!("await {}", e)).collect();
                    Ok(format!("({})", awaited.join(", ")))
                }
            }
            ast::WaitType::Together => {
                // Parallel execution: Task.WhenAll
                if expr_strs.is_empty() {
                    Ok("Task.CompletedTask".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    Ok(format!("await Task.WhenAll({})", expr_strs.join(", ")))
                }
            }
            ast::WaitType::Race => {
                // Race: Task.WhenAny
                if expr_strs.is_empty() {
                    Ok("Task.CompletedTask".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    Ok(format!("await Task.WhenAny({})", expr_strs.join(", ")))
                }
            }
            ast::WaitType::Timeout(timeout_expr) => {
                // Timeout: Task.WhenAny with Task.Delay
                let timeout = self.emit_expr(timeout_expr)?;
                if expr_strs.is_empty() {
                    Ok(format!("await Task.Delay({})", timeout))
                } else {
                    let expr = &expr_strs[0];
                    Ok(format!(
                        "await Task.WhenAny({}, Task.Delay({}))",
                        expr, timeout
                    ))
                }
            }
        }
    }

    fn emit_call(&self, callee: &str, args: &[String]) -> CSharpResult<String> {
        match callee {
            "println" => Ok(format!("Console.WriteLine({})", args.join(", "))),
            "print" => Ok(format!("Console.Write({})", args.join(", "))),
            _ => Ok(format!("{}({})", callee, args.join(", "))),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_lexer::span::Span;
    use x_parser::ast::{Spanned, Literal};

    fn make_expr(kind: ExpressionKind) -> ast::Expression {
        Spanned::new(kind, Span::default())
    }

    fn make_stmt(kind: StatementKind) -> ast::Statement {
        Spanned::new(kind, Span::default())
    }

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![],
            statements: vec![make_stmt(StatementKind::Expression(make_expr(ExpressionKind::Call(
                Box::new(make_expr(ExpressionKind::Variable("println".to_string()))),
                vec![make_expr(ExpressionKind::Literal(Literal::String(
                    "Hello from X-Lang!".to_string(),
                )))],
            ))))],
        };

        let mut backend = CSharpBackend::new(CSharpBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(csharp_code.contains("namespace XLang"));
        assert!(csharp_code.contains("using System;"));
        assert!(csharp_code.contains("public class Program"));
        assert!(csharp_code.contains("public static void Main"));
        assert!(csharp_code.contains("Console.WriteLine(\"Hello from X-Lang!\");"));
    }
}
