//! C# 后端 - 将 X AST 编译为 .NET 字节码
//! 
//! 生成 C# 代码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct CSharpBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for CSharpBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct CSharpBackend {
    config: CSharpBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum CSharpBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type CSharpResult<T> = Result<T, CSharpBackendError>;

impl CSharpBackend {
    pub fn new(config: CSharpBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(&mut self, program: &AstProgram) -> CSharpResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_namespace()?;
        self.emit_class()?;

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("Program.cs"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::DotNetAssembly,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> CSharpResult<()> {
        self.line("// Generated by X-Lang C# backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_namespace(&mut self) -> CSharpResult<()> {
        self.line("namespace XLang")?;
        self.line("{")?;
        self.indent += 1;
        Ok(())
    }

    fn emit_class(&mut self) -> CSharpResult<()> {
        self.line("public class Program")?;
        self.line("{")?;
        self.indent += 1;
        self.emit_main_method()?;
        self.indent -= 1;
        self.line("}")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_main_method(&mut self) -> CSharpResult<()> {
        self.line("public static void Main(string[] args)")?;
        self.line("{")?;
        self.indent += 1;
        self.line("Console.WriteLine(\"Hello from C# backend!\");")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn line(&mut self, s: &str) -> CSharpResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            declarations: vec![],
            statements: vec![],
        };

        let mut backend = CSharpBackend::new(CSharpBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let csharp_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(csharp_code.contains("namespace XLang"));
        assert!(csharp_code.contains("public class Program"));
        assert!(csharp_code.contains("public static void Main"));
        assert!(csharp_code.contains("Console.WriteLine(\"Hello from C# backend!\");"));
    }
}
