//! Java 后端 - 将 X AST 编译为 Java 字节码
//! 
//! 生成 Java 字节码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct JavaBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for JavaBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct JavaBackend {
    config: JavaBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum JavaBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type JavaResult<T> = Result<T, JavaBackendError>;

impl JavaBackend {
    pub fn new(config: JavaBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(&mut self, program: &AstProgram) -> JavaResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_class()?;

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("Main.java"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::JvmBytecode,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> JavaResult<()> {
        self.line("// Generated by X-Lang Java backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_class(&mut self) -> JavaResult<()> {
        self.line("public class Main {")?;
        self.indent += 1;
        self.emit_main_method()?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_main_method(&mut self) -> JavaResult<()> {
        self.line("public static void main(String[] args) {")?;
        self.indent += 1;
        self.line("System.out.println(\"Hello from Java backend!\");")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn line(&mut self, s: &str) -> JavaResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            declarations: vec![],
            statements: vec![],
        };

        let mut backend = JavaBackend::new(JavaBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let java_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(java_code.contains("public class Main"));
        assert!(java_code.contains("public static void main"));
        assert!(java_code.contains("System.out.println(\"Hello from Java backend!\");"));
    }
}
