//! Java 后端 - 将 X AST 编译为 Java 字节码
//!
//! 生成 Java 字节码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, ExpressionKind, StatementKind, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct JavaBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for JavaBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct JavaBackend {
    config: JavaBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum JavaBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type JavaResult<T> = Result<T, JavaBackendError>;

impl JavaBackend {
    pub fn new(config: JavaBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(&mut self, program: &AstProgram) -> JavaResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_class(program)?;

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("Main.java"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::JvmBytecode,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> JavaResult<()> {
        self.line("// Generated by X-Lang Java backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_class(&mut self, program: &AstProgram) -> JavaResult<()> {
        // First, emit X class declarations as Java classes
        for decl in &program.declarations {
            if let ast::Declaration::Class(class_decl) = decl {
                self.emit_x_class(class_decl)?;
            }
        }

        // Emit trait declarations as Java interfaces
        for decl in &program.declarations {
            if let ast::Declaration::Trait(trait_decl) = decl {
                self.emit_x_trait(trait_decl)?;
            }
        }

        // Emit the Main class with top-level functions
        self.line("public class Main {")?;
        self.indent += 1;

        // Emit all function declarations as static methods
        for decl in &program.declarations {
            if let ast::Declaration::Function(func) = decl {
                self.emit_function_as_method(func)?;
            }
        }

        // Emit main method with top-level statements
        self.emit_main_method(&program.statements)?;

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// Emit an X class as a Java class
    fn emit_x_class(&mut self, class: &ast::ClassDecl) -> JavaResult<()> {
        // Build class declaration line
        let mut class_line = String::new();

        // Modifiers
        if class.modifiers.is_abstract {
            class_line.push_str("abstract ");
        }
        if class.modifiers.is_final {
            class_line.push_str("final ");
        }

        class_line.push_str(&format!("class {}", class.name));

        // Extends
        if let Some(parent) = &class.extends {
            class_line.push_str(&format!(" extends {}", parent));
        }

        // Implements
        if !class.implements.is_empty() {
            class_line.push_str(&format!(" implements {}", class.implements.join(", ")));
        }

        class_line.push_str(" {");

        self.line(&class_line)?;
        self.indent += 1;

        // Emit fields
        for member in &class.members {
            if let ast::ClassMember::Field(field) = member {
                let field_type = self.java_type(field.type_annot.as_ref());
                let visibility = self.visibility_str(field.visibility);
                self.line(&format!("{}{} {};", visibility, field_type, field.name))?;
            }
        }

        // Emit constructors
        for member in &class.members {
            if let ast::ClassMember::Constructor(constructor) = member {
                self.emit_constructor(&class.name, constructor)?;
            }
        }

        // Emit methods
        for member in &class.members {
            if let ast::ClassMember::Method(method) = member {
                self.emit_method(&class.name, method)?;
            }
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    /// Emit an X trait as a Java interface
    fn emit_x_trait(&mut self, trait_decl: &ast::TraitDecl) -> JavaResult<()> {
        let mut interface_line = format!("interface {}", trait_decl.name);

        // Trait extends (Java interfaces can extend multiple)
        if !trait_decl.extends.is_empty() {
            interface_line.push_str(&format!(" extends {}", trait_decl.extends.join(", ")));
        }

        interface_line.push_str(" {");

        self.line(&interface_line)?;
        self.indent += 1;

        // Emit method signatures
        for method in &trait_decl.methods {
            let return_type = self.java_type(method.return_type.as_ref());
            let params: Vec<String> = method
                .parameters
                .iter()
                .map(|p| format!("{} {}", self.java_type(p.type_annot.as_ref()), p.name))
                .collect();

            self.line(&format!("{} {}({});", return_type, method.name, params.join(", ")))?;
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    /// Emit a constructor
    fn emit_constructor(&mut self, class_name: &str, constructor: &ast::ConstructorDecl) -> JavaResult<()> {
        let params: Vec<String> = constructor
            .parameters
            .iter()
            .map(|p| format!("{} {}", self.java_type(p.type_annot.as_ref()), p.name))
            .collect();

        self.line(&format!("public {}({}) {{", class_name, params.join(", ")))?;
        self.indent += 1;

        self.emit_block(&constructor.body)?;

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// Emit a class method
    fn emit_method(&mut self, class_name: &str, method: &ast::FunctionDecl) -> JavaResult<()> {
        let return_type = self.java_type(method.return_type.as_ref());

        let params: Vec<String> = method
            .parameters
            .iter()
            .map(|p| format!("{} {}", self.java_type(p.type_annot.as_ref()), p.name))
            .collect();

        // Modifiers
        let mut modifiers = String::new();
        if method.modifiers.is_static {
            modifiers.push_str("static ");
        }
        if method.modifiers.is_final {
            modifiers.push_str("final ");
        }
        if method.modifiers.is_abstract {
            modifiers.push_str("abstract ");
        }

        let visibility = self.visibility_str(method.modifiers.visibility);

        self.line(&format!(
            "{}{}{} {}({}) {{",
            visibility, modifiers, return_type, method.name, params.join(", ")
        ))?;
        self.indent += 1;

        self.emit_block(&method.body)?;

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// Convert X type to Java type
    fn java_type(&self, type_annot: Option<&ast::Type>) -> String {
        match type_annot {
            Some(t) => match t {
                ast::Type::Int => "int".to_string(),
                ast::Type::Float => "double".to_string(),
                ast::Type::Bool => "boolean".to_string(),
                ast::Type::String => "String".to_string(),
                ast::Type::Char => "char".to_string(),
                ast::Type::Unit => "void".to_string(),
                ast::Type::Option(inner) => format!("java.util.Optional<{}>", self.java_type(Some(inner))),
                ast::Type::Generic(name) | ast::Type::TypeParam(name) => name.clone(),
                _ => "Object".to_string(),
            },
            None => "Object".to_string(),
        }
    }

    /// Convert X visibility to Java visibility
    fn visibility_str(&self, visibility: ast::Visibility) -> &'static str {
        match visibility {
            ast::Visibility::Private => "private ",
            ast::Visibility::Public => "public ",
            ast::Visibility::Protected => "protected ",
            ast::Visibility::Internal => "", // package-private
        }
    }

    fn emit_main_method(&mut self, statements: &[ast::Statement]) -> JavaResult<()> {
        self.line("public static void main(String[] args) {")?;
        self.indent += 1;

        // Emit all top-level statements
        for stmt in statements {
            self.emit_statement(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_function_as_method(&mut self, func_decl: &ast::FunctionDecl) -> JavaResult<()> {
        // For now, assume Object return type (we'll add proper type handling later)
        let params: Vec<String> = func_decl
            .parameters
            .iter()
            .map(|p| format!("Object {}", p.name))
            .collect();

        // Handle async functions - return CompletableFuture
        let (return_type, needs_completable_future) = if func_decl.is_async {
            ("java.util.concurrent.CompletableFuture<Object>".to_string(), true)
        } else {
            ("Object".to_string(), false)
        };

        self.line(&format!(
            "public static {} {}({}) {{",
            return_type,
            func_decl.name,
            params.join(", ")
        ))?;
        self.indent += 1;

        // For async functions, wrap the body in supplyAsync
        if needs_completable_future {
            self.line("return java.util.concurrent.CompletableFuture.supplyAsync(() -> {")?;
            self.indent += 1;
        }

        self.emit_block(&func_decl.body)?;

        if needs_completable_future {
            self.line("return null;")?;
            self.indent -= 1;
            self.line("});")?;
        } else {
            self.line("return null;")?;
        }
        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> JavaResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let expr_str = self.emit_expr(expr)?;
                self.line(&format!("{};", expr_str))?;
            }
            StatementKind::Variable(var_decl) => {
                if let Some(init) = &var_decl.initializer {
                    // Has initializer - can use var/final var
                    let var_type = if var_decl.is_mutable {
                        "var"
                    } else {
                        "final var"
                    };
                    let init_str = self.emit_expr(init)?;
                    self.line(&format!("{} {} = {};", var_type, var_decl.name, init_str))?;
                } else {
                    // No initializer - need explicit type annotation
                    let java_type = if let Some(type_annot) = &var_decl.type_annot {
                        self.type_to_java(type_annot)?
                    } else {
                        // Default to Object if no type annotation
                        "Object".to_string()
                    };

                    let modifier = if var_decl.is_mutable {
                        ""
                    } else {
                        "final "
                    };
                    self.line(&format!("{}{} {};", modifier, java_type, var_decl.name))?;
                }
            }
            StatementKind::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            StatementKind::While(while_stmt) => {
                self.emit_while(while_stmt)?;
            }
            StatementKind::Return(ret) => {
                if let Some(expr) = ret {
                    let expr_str = self.emit_expr(expr)?;
                    self.line(&format!("return {};", expr_str))?;
                } else {
                    self.line("return;")?;
                }
            }
            _ => {
                return Err(JavaBackendError::UnsupportedFeature(format!(
                    "Unsupported statement type: {:?}",
                    stmt
                )));
            }
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> JavaResult<()> {
        self.line("{")?;
        self.indent += 1;

        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> JavaResult<()> {
        let cond_str = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if ({}) {{", cond_str))?;
        self.indent += 1;

        self.emit_block(&if_stmt.then_block)?;

        self.indent -= 1;

        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;

            self.emit_block(else_block)?;

            self.indent -= 1;
        }

        self.line("}")?;
        Ok(())
    }

    fn emit_while(&mut self, while_stmt: &ast::WhileStatement) -> JavaResult<()> {
        let cond_str = self.emit_expr(&while_stmt.condition)?;
        self.line(&format!("while ({}) {{", cond_str))?;
        self.indent += 1;

        self.emit_block(&while_stmt.body)?;

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> JavaResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => Ok(self.emit_literal(lit)?),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, left, right) => {
                let lhs = self.emit_expr(left)?;
                let rhs = self.emit_expr(right)?;
                self.emit_binop(op, &lhs, &rhs)
            }
            ExpressionKind::Unary(op, operand) => {
                let expr_str = self.emit_expr(operand)?;
                self.emit_unaryop(op, &expr_str)
            }
            ExpressionKind::Call(callee, args) => {
                let callee_str = self.emit_expr(callee)?;
                let mut arg_strs = Vec::new();
                for arg in args {
                    arg_strs.push(self.emit_expr(arg)?);
                }
                Ok(self.emit_call(&callee_str, &arg_strs)?)
            }
            ExpressionKind::Assign(left, right) => {
                let lhs = self.emit_expr(left)?;
                let rhs = self.emit_expr(right)?;
                Ok(format!("{} = {}", lhs, rhs))
            }
            ExpressionKind::Parenthesized(expr) => {
                let inner = self.emit_expr(expr)?;
                Ok(format!("({})", inner))
            }
            ExpressionKind::Wait(wait_type, exprs) => {
                self.emit_wait(wait_type, exprs)
            }
            _ => Err(JavaBackendError::UnsupportedFeature(format!(
                "Unsupported expression type: {:?}",
                expr
            ))),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> JavaResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(f.to_string()),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => Ok(format!("\"{}\"", s.replace('"', "\\\""))),
            ast::Literal::Null => Ok("null".to_string()),
            _ => Err(JavaBackendError::UnsupportedFeature(format!(
                "Unsupported literal type: {:?}",
                lit
            ))),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, lhs: &str, rhs: &str) -> JavaResult<String> {
        let op_str = match op {
            ast::BinaryOp::Add => "+",
            ast::BinaryOp::Sub => "-",
            ast::BinaryOp::Mul => "*",
            ast::BinaryOp::Div => "/",
            ast::BinaryOp::Mod => "%",
            ast::BinaryOp::Equal => "==",
            ast::BinaryOp::NotEqual => "!=",
            ast::BinaryOp::Less => "<",
            ast::BinaryOp::LessEqual => "<=",
            ast::BinaryOp::Greater => ">",
            ast::BinaryOp::GreaterEqual => ">=",
            ast::BinaryOp::And => "&&",
            ast::BinaryOp::Or => "||",
            ast::BinaryOp::BitAnd => "&",
            ast::BinaryOp::BitOr => "|",
            ast::BinaryOp::BitXor => "^",
            ast::BinaryOp::LeftShift => "<<",
            ast::BinaryOp::RightShift => ">>",
            _ => {
                return Err(JavaBackendError::UnsupportedFeature(format!(
                    "Unsupported binary operator: {:?}",
                    op
                )));
            }
        };
        Ok(format!("{} {} {}", lhs, op_str, rhs))
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, expr: &str) -> JavaResult<String> {
        match op {
            ast::UnaryOp::Negate => Ok(format!("-{}", expr)),
            ast::UnaryOp::Not => Ok(format!("!{}", expr)),
            ast::UnaryOp::BitNot => Ok(format!("~{}", expr)),
            ast::UnaryOp::Wait => Ok(format!("{}.join()", expr)), // Wait for CompletableFuture
            _ => Err(JavaBackendError::UnsupportedFeature(format!(
                "Unsupported unary operator: {:?}",
                op
            ))),
        }
    }

    fn emit_wait(&self, wait_type: &ast::WaitType, exprs: &[ast::Expression]) -> JavaResult<String> {
        let expr_strs: Vec<String> = exprs
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<Result<Vec<_>, _>>()?;
        match wait_type {
            ast::WaitType::Single => {
                // Single await: future.join() or future.get()
                if expr_strs.len() == 1 {
                    Ok(format!("{}.join()", expr_strs[0]))
                } else {
                    // Multiple expressions - join each
                    let joined: Vec<String> = expr_strs.iter().map(|e| format!("{}.join()", e)).collect();
                    Ok(format!("java.util.Arrays.asList({})", joined.join(", ")))
                }
            }
            ast::WaitType::Together => {
                // Parallel execution: CompletableFuture.allOf
                if expr_strs.is_empty() {
                    Ok("java.util.concurrent.CompletableFuture.completedFuture(null)".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("{}.join()", expr_strs[0]))
                } else {
                    let futures = expr_strs.join(", ");
                    Ok(format!(
                        "java.util.concurrent.CompletableFuture.allOf({}).join()",
                        futures
                    ))
                }
            }
            ast::WaitType::Race => {
                // Race: CompletableFuture.anyOf
                if expr_strs.is_empty() {
                    Ok("java.util.concurrent.CompletableFuture.completedFuture(null)".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("{}.join()", expr_strs[0]))
                } else {
                    let futures = expr_strs.join(", ");
                    Ok(format!(
                        "java.util.concurrent.CompletableFuture.anyOf({}).join()",
                        futures
                    ))
                }
            }
            ast::WaitType::Timeout(timeout_expr) => {
                // Timeout: orTimeout
                let timeout = self.emit_expr(timeout_expr)?;
                if expr_strs.is_empty() {
                    Ok("java.util.concurrent.CompletableFuture.completedFuture(null)".to_string())
                } else {
                    let expr = &expr_strs[0];
                    Ok(format!(
                        "{}.orTimeout({}, java.util.concurrent.TimeUnit.MILLISECONDS).join()",
                        expr, timeout
                    ))
                }
            }
        }
    }

    fn emit_call(&self, callee: &str, args: &[String]) -> JavaResult<String> {
        // Map built-in functions
        match callee {
            "println" => Ok(format!("System.out.println({})", args.join(", "))),
            "print" => Ok(format!("System.out.print({})", args.join(", "))),
            _ => {
                // Regular function call
                Ok(format!("{}({})", callee, args.join(", ")))
            }
        }
    }

    /// Convert X language type to Java type
    fn type_to_java(&self, ty: &ast::Type) -> JavaResult<String> {
        match ty {
            ast::Type::Int => Ok("int".to_string()),
            ast::Type::Float => Ok("double".to_string()),
            ast::Type::Bool => Ok("boolean".to_string()),
            ast::Type::String => Ok("String".to_string()),
            ast::Type::Char => Ok("char".to_string()),
            ast::Type::Unit => Ok("void".to_string()),
            ast::Type::Never => Ok("void".to_string()),
            ast::Type::Generic(name) | ast::Type::TypeParam(name) | ast::Type::Var(name) => {
                Ok(name.clone())
            }
            ast::Type::Array(elem) => {
                let elem_type = self.type_to_java(elem)?;
                Ok(format!("{}[]", elem_type))
            }
            ast::Type::Dictionary(key, value) => {
                let _key_type = self.type_to_java(key)?;
                let value_type = self.type_to_java(value)?;
                Ok(format!("java.util.Map<String, {}>", value_type))
            }
            ast::Type::Record(name, _) => {
                Ok(name.clone())
            }
            ast::Type::Union(name, _) => {
                Ok(name.clone())
            }
            ast::Type::Option(inner) => {
                // Java doesn't have Option, use nullable type wrapper
                let inner_type = self.type_to_java(inner)?;
                Ok(format!("java.util.Optional<{}>", inner_type))
            }
            ast::Type::Result(ok_type, _) => {
                // Simplified: just use the Ok type wrapped
                let ok_java = self.type_to_java(ok_type)?;
                Ok(format!("java.util.Optional<{}>", ok_java))
            }
            ast::Type::Tuple(elements) => {
                // Tuples map to Object arrays or custom tuple classes
                if elements.is_empty() {
                    Ok("Object".to_string())
                } else {
                    Ok("Object[]".to_string())
                }
            }
            ast::Type::Function(params, ret) => {
                // Java functional interface
                let ret_type = self.type_to_java(ret)?;
                if params.is_empty() {
                    Ok(format!("java.util.function.Supplier<{}>", ret_type))
                } else {
                    Ok(format!("java.util.function.Function<Object, {}>", ret_type))
                }
            }
            ast::Type::Async(inner) => {
                let inner_type = self.type_to_java(inner)?;
                Ok(format!("java.util.concurrent.CompletableFuture<{}>", inner_type))
            }
            ast::Type::TypeConstructor(name, type_args) => {
                // Generic type application: List<Int> -> List<Integer>
                let args: Vec<String> = type_args.iter()
                    .map(|t| self.type_to_java(t))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(format!("{}<{}>", name, args.join(", ")))
            }
        }
    }

    fn line(&mut self, s: &str) -> JavaResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_parser::ast::*;
    use x_lexer::span::Span;

    fn make_expr(kind: ExpressionKind) -> Expression {
        Spanned::new(kind, Span::default())
    }

    fn make_stmt(kind: StatementKind) -> Statement {
        Spanned::new(kind, Span::default())
    }

    #[test]
    fn test_basic_generation() {
        let program = Program {
            span: Span::default(),
            declarations: vec![],
            statements: vec![make_stmt(StatementKind::Expression(make_expr(ExpressionKind::Call(
                Box::new(make_expr(ExpressionKind::Variable("println".to_string()))),
                vec![make_expr(ExpressionKind::Literal(Literal::String(
                    "Hello, X Language!".to_string(),
                )))],
            ))))],
        };

        let mut backend = JavaBackend::new(JavaBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let java_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(java_code.contains("public class Main"));
        assert!(java_code.contains("public static void main"));
        assert!(java_code.contains("System.out.println(\"Hello, X Language!\");"));
    }

    #[test]
    fn test_variables_and_expressions() {
        // let x = 5
        // let y = 10
        // println(x + y)
        let program = Program {
            span: Span::default(),
            declarations: vec![],
            statements: vec![
                make_stmt(StatementKind::Variable(VariableDecl {
                    span: Span::default(),
                    name: "x".to_string(),
                    is_mutable: false,
                    type_annot: None,
                    initializer: Some(make_expr(ExpressionKind::Literal(Literal::Integer(5)))),
                    visibility: Visibility::default(),
                })),
                make_stmt(StatementKind::Variable(VariableDecl {
                    span: Span::default(),
                    name: "y".to_string(),
                    is_mutable: false,
                    type_annot: None,
                    initializer: Some(make_expr(ExpressionKind::Literal(Literal::Integer(10)))),
                    visibility: Visibility::default(),
                })),
                make_stmt(StatementKind::Expression(make_expr(ExpressionKind::Call(
                    Box::new(make_expr(ExpressionKind::Variable("println".to_string()))),
                    vec![make_expr(ExpressionKind::Binary(
                        BinaryOp::Add,
                        Box::new(make_expr(ExpressionKind::Variable("x".to_string()))),
                        Box::new(make_expr(ExpressionKind::Variable("y".to_string()))),
                    ))],
                )))),
            ],
        };

        let mut backend = JavaBackend::new(JavaBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let java_code = String::from_utf8_lossy(&output.files[0].content);

        assert!(java_code.contains("final var x = 5;"));
        assert!(java_code.contains("final var y = 10;"));
        assert!(java_code.contains("System.out.println(x + y);"));
    }

    #[test]
    fn unsupported_operator_returns_error_instead_of_panicking() {
        // Use an operator that Java backend does not implement yet.
        let program = Program {
            span: Span::default(),
            declarations: vec![],
            statements: vec![make_stmt(StatementKind::Expression(make_expr(ExpressionKind::Binary(
                BinaryOp::Concat,
                Box::new(make_expr(ExpressionKind::Literal(Literal::String("a".to_string())))),
                Box::new(make_expr(ExpressionKind::Literal(Literal::String("b".to_string())))),
            ))))],
        };

        let mut backend = JavaBackend::new(JavaBackendConfig::default());
        let err = backend.generate_from_ast(&program).unwrap_err();
        match err {
            JavaBackendError::UnsupportedFeature(msg) => {
                assert!(msg.contains("Unsupported binary operator"));
            }
            other => panic!("expected UnsupportedFeature, got {other:?}"),
        }
    }
}
