//! Python 后端 - 将 X AST 编译为 Python 代码
//!
//! 生成清晰可读的 Python 源代码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_lexer::span::Span;
use x_parser::ast::{self, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct PythonBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for PythonBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct PythonBackend {
    config: PythonBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum PythonBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type PythonResult<T> = Result<T, PythonBackendError>;

impl PythonBackend {
    pub fn new(config: PythonBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> PythonResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;

        // Emit global variables
        for decl in &program.declarations {
            if let ast::Declaration::Variable(v) = decl {
                self.emit_global_var(v)?;
            }
        }

        // Emit functions
        let mut has_main = false;
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                self.emit_function(f)?;
                self.line("")?;
                if f.name == "main" {
                    has_main = true;
                }
            }
        }

        // Emit main function only if not already defined
        if !has_main {
            self.emit_main_function()?;
        }

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("output.py"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::Python,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> PythonResult<()> {
        self.line("# Generated by X-Lang Python backend")?;
        self.line("# DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_main_function(&mut self) -> PythonResult<()> {
        self.line("def main():")?;
        self.indent += 1;
        self.line("print('Hello from Python backend!')")?;
        self.indent -= 1;
        self.line("")?;
        self.line("if __name__ == '__main__':")?;
        self.indent += 1;
        self.line("main()")?;
        self.indent -= 1;
        Ok(())
    }

    fn emit_global_var(&mut self, v: &ast::VariableDecl) -> PythonResult<()> {
        let init = if let Some(expr) = &v.initializer {
            self.emit_expr(expr)?
        } else {
            "None".to_string()
        };
        self.line(&format!("{} = {}", v.name, init))?;
        Ok(())
    }

    fn emit_function(&mut self, f: &ast::FunctionDecl) -> PythonResult<()> {
        let params = if f.parameters.is_empty() {
            "".to_string()
        } else {
            f.parameters
                .iter()
                .map(|p| p.name.clone())
                .collect::<Vec<_>>()
                .join(", ")
        };
        self.line(&format!("def {}({}):", f.name, params))?;
        self.indent += 1;
        self.emit_block(&f.body)?;
        if f.return_type.is_some() {
            self.line("return None")?;
        }
        self.indent -= 1;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> PythonResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> PythonResult<()> {
        match stmt {
            ast::Statement::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&e)?;
            }
            ast::Statement::Variable(v) => {
                let init = if let Some(expr) = &v.initializer {
                    self.emit_expr(expr)?
                } else {
                    "None".to_string()
                };
                self.line(&format!("{} = {}", v.name, init))?;
            }
            ast::Statement::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {}", e))?;
                } else {
                    self.line("return")?;
                }
            }
            ast::Statement::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            ast::Statement::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while {}:", cond))?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
            }
            ast::Statement::For(_) => {
                self.line("# TODO: for loop")?;
            }
            ast::Statement::Match(_) => {
                self.line("# TODO: match")?;
            }
            ast::Statement::Try(_) => {
                self.line("# TODO: try")?;
            }
            ast::Statement::Break => {
                self.line("break")?;
            }
            ast::Statement::Continue => {
                self.line("continue")?;
            }
            ast::Statement::DoWhile(d) => {
                self.line("while True:")?;
                self.indent += 1;
                self.emit_block(&d.body)?;
                let cond = self.emit_expr(&d.condition)?;
                self.line(&format!("if not ({}):", cond))?;
                self.indent += 1;
                self.line("break")?;
                self.indent -= 1;
                self.indent -= 1;
            }
        }
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> PythonResult<()> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if {}:", cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;
        if let Some(else_block) = &if_stmt.else_block {
            self.line("else:")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> PythonResult<String> {
        match expr {
            ast::Expression::Literal(lit) => self.emit_literal(lit),
            ast::Expression::Variable(name) => Ok(name.clone()),
            ast::Expression::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ast::Expression::Unary(op, expr) => {
                let e = self.emit_expr(expr)?;
                Ok(self.emit_unaryop(op, &e))
            }
            ast::Expression::Call(callee, args) => self.emit_call(callee, args),
            ast::Expression::Assign(target, value) => self.emit_assign(target, value),
            ast::Expression::Array(elements) => self.emit_array_literal(elements),
            ast::Expression::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            ast::Expression::If(cond, then_e, else_e) => {
                let c = self.emit_expr(cond)?;
                let t = self.emit_expr(then_e)?;
                let e = self.emit_expr(else_e)?;
                Ok(format!("{} if {} else {}", t, c, e))
            }
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            _ => Err(PythonBackendError::UnsupportedFeature(format!(
                "{:?}",
                expr
            ))),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> PythonResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(format!("{}", n)),
            ast::Literal::Float(f) => Ok(format!("{}", f)),
            ast::Literal::Boolean(b) => Ok(format!("{}", b)),
            ast::Literal::String(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null => Ok("None".to_string()),
            ast::Literal::None => Ok("None".to_string()),
            ast::Literal::Unit => Ok("None".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("{} + {}", l, r),
            ast::BinaryOp::Sub => format!("{} - {}", l, r),
            ast::BinaryOp::Mul => format!("{} * {}", l, r),
            ast::BinaryOp::Div => format!("{} / {}", l, r),
            ast::BinaryOp::Mod => format!("{} % {}", l, r),
            ast::BinaryOp::Equal => format!("{} == {}", l, r),
            ast::BinaryOp::NotEqual => format!("{} != {}", l, r),
            ast::BinaryOp::Less => format!("{} < {}", l, r),
            ast::BinaryOp::LessEqual => format!("{} <= {}", l, r),
            ast::BinaryOp::Greater => format!("{} > {}", l, r),
            ast::BinaryOp::GreaterEqual => format!("{} >= {}", l, r),
            ast::BinaryOp::And => format!("{} and {}", l, r),
            ast::BinaryOp::Or => format!("{} or {}", l, r),
            ast::BinaryOp::Pow => format!("{} ** {}", l, r),
            _ => format!("# unsupported binop {:?} #", op),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("-{}", e),
            ast::UnaryOp::Not => format!("not {}", e),
            _ => format!("# unsupported unary {:?} #", op),
        }
    }

    fn emit_call(
        &self,
        callee: &ast::Expression,
        args: &[ast::Expression],
    ) -> PythonResult<String> {
        let callee_str = self.emit_expr(callee)?;
        let arg_strs: Vec<String> = args
            .iter()
            .map(|a| self.emit_expr(a))
            .collect::<PythonResult<Vec<_>>>()?;
        Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
    }

    fn emit_assign(
        &self,
        target: &ast::Expression,
        value: &ast::Expression,
    ) -> PythonResult<String> {
        let val = self.emit_expr(value)?;
        match target {
            ast::Expression::Variable(name) => Ok(format!("{} = {}", name, val)),
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{} = {}", o, field, val))
            }
            _ => {
                let t = self.emit_expr(target)?;
                Ok(format!("{} = {}", t, val))
            }
        }
    }

    fn emit_array_literal(&self, elements: &[ast::Expression]) -> PythonResult<String> {
        if elements.is_empty() {
            return Ok("[]".to_string());
        }
        let elem_strs: Vec<String> = elements
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<PythonResult<Vec<_>>>()?;
        Ok(format!("[{}]", elem_strs.join(", ")))
    }

    fn line(&mut self, s: &str) -> PythonResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
            span: Span::default(),
                name: "main".to_string(),
                parameters: vec![],
                return_type: None,
                body: ast::Block {
                    statements: vec![ast::Statement::Expression(ast::Expression::Call(
                        Box::new(ast::Expression::Variable("print".to_string())),
                        vec![ast::Expression::Literal(ast::Literal::String(
                            "Hello, World!".to_string(),
                        ))],
                    ))],
                },
                is_async: false,
            })],
            statements: vec![],
        };

        let mut backend = PythonBackend::new(PythonBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let python_code = String::from_utf8_lossy(&output.files[0].content);
        // The implementation uses double quotes for string literals
        assert!(python_code.contains("print(\"Hello, World!\")"));
        assert!(python_code.contains("def main():"));
    }

    #[test]
    fn test_empty_program_generates_default_main() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![],
            statements: vec![],
        };

        let mut backend = PythonBackend::new(PythonBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let python_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(python_code.contains("def main():"));
        assert!(python_code.contains("print('Hello from Python backend!')"));
        assert!(python_code.contains("if __name__ == '__main__':"));
        assert!(python_code.contains("main()"));
    }
}
