//! TypeScript 后端 - 将 X AST 编译为 TypeScript 代码
//!
//! 生成 TypeScript 源码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, ExpressionKind, StatementKind, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct TypeScriptBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for TypeScriptBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct TypeScriptBackend {
    config: TypeScriptBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum TypeScriptBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type TypeScriptResult<T> = Result<T, TypeScriptBackendError>;

impl TypeScriptBackend {
    pub fn new(config: TypeScriptBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> TypeScriptResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;

        // Emit all declarations first
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // Emit main function containing all top-level statements
        if !program.statements.is_empty() {
            self.line("function main(): void {")?;
            self.indent += 1;

            for stmt in &program.statements {
                self.emit_statement(stmt)?;
            }

            self.indent -= 1;
            self.line("}")?;
            self.line("")?;
            self.line("// Run the main function")?;
            self.line("main();")?;
        }

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("index.ts"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::TypeScript,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> TypeScriptResult<()> {
        self.line("// Generated by X-Lang TypeScript backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_declaration(&mut self, decl: &ast::Declaration) -> TypeScriptResult<()> {
        match decl {
            ast::Declaration::Variable(var_decl) => {
                self.emit_variable_decl(var_decl)?;
                self.line("")?;
            }
            ast::Declaration::Function(func_decl) => {
                self.emit_function_decl(func_decl)?;
                self.line("")?;
            }
            ast::Declaration::Class(class_decl) => {
                self.emit_class_decl(class_decl)?;
                self.line("")?;
            }
            ast::Declaration::Trait(trait_decl) => {
                self.emit_trait_decl(trait_decl)?;
                self.line("")?;
            }
            _ => {
                return Err(TypeScriptBackendError::UnsupportedFeature(format!(
                    "Declaration type {:?} is not yet supported in TypeScript backend",
                    decl
                )));
            }
        }
        Ok(())
    }

    fn emit_variable_decl(&mut self, var_decl: &ast::VariableDecl) -> TypeScriptResult<()> {
        let keyword = if var_decl.is_mutable { "let" } else { "const" };
        let name = &var_decl.name;

        if let Some(init) = &var_decl.initializer {
            let init_expr = self.emit_expr(init)?;
            self.line(&format!("{} {} = {};", keyword, name, init_expr))?;
        } else {
            self.line(&format!("{} {};", keyword, name))?;
        }

        Ok(())
    }

    fn emit_function_decl(&mut self, func_decl: &ast::FunctionDecl) -> TypeScriptResult<()> {
        let async_keyword = if func_decl.is_async { "async " } else { "" };
        let name = &func_decl.name;

        let params: Vec<String> = func_decl
            .parameters
            .iter()
            .map(|p| p.name.clone())
            .collect();

        self.line(&format!(
            "{}function {}({}): void {{",
            async_keyword,
            name,
            params.join(", ")
        ))?;
        self.indent += 1;

        self.emit_block(&func_decl.body)?;

        self.indent -= 1;
        self.line("}")?;

        Ok(())
    }

    fn emit_class_decl(&mut self, class_decl: &ast::ClassDecl) -> TypeScriptResult<()> {
        // Emit class header
        let extends_clause = if let Some(parent) = &class_decl.extends {
            format!(" extends {}", parent)
        } else {
            String::new()
        };

        let implements_clause = if !class_decl.implements.is_empty() {
            format!(" implements {}", class_decl.implements.join(", "))
        } else {
            String::new()
        };

        self.line(&format!(
            "class {}{}{} {{",
            class_decl.name, extends_clause, implements_clause
        ))?;
        self.indent += 1;

        // Emit members
        for member in &class_decl.members {
            match member {
                ast::ClassMember::Field(field) => {
                    let field_type = if let Some(type_annot) = &field.type_annot {
                        self.emit_type(type_annot)
                    } else {
                        "any".to_string()
                    };
                    let initializer = if let Some(init) = &field.initializer {
                        format!(" = {}", self.emit_expr(init)?)
                    } else {
                        String::new()
                    };
                    self.line(&format!(
                        "{}{}: {}{};",
                        if field.is_mutable { "" } else { "readonly " },
                        field.name,
                        field_type,
                        initializer
                    ))?;
                }
                ast::ClassMember::Method(method) => {
                    self.emit_method_decl(method)?;
                }
                ast::ClassMember::Constructor(constructor) => {
                    self.emit_constructor_decl(constructor)?;
                }
            }
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_method_decl(&mut self, method: &ast::FunctionDecl) -> TypeScriptResult<()> {
        let params: Vec<String> = method
            .parameters
            .iter()
            .map(|p| {
                let type_str = if let Some(type_annot) = &p.type_annot {
                    format!(": {}", self.emit_type(type_annot))
                } else {
                    String::new()
                };
                format!("{}{}", p.name, type_str)
            })
            .collect();

        let return_type = if let Some(ret) = &method.return_type {
            self.emit_type(ret)
        } else {
            "void".to_string()
        };

        self.line(&format!("{}({}): {} {{", method.name, params.join(", "), return_type))?;
        self.indent += 1;
        self.emit_block(&method.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_constructor_decl(&mut self, constructor: &ast::ConstructorDecl) -> TypeScriptResult<()> {
        let params: Vec<String> = constructor
            .parameters
            .iter()
            .map(|p| {
                let type_str = if let Some(type_annot) = &p.type_annot {
                    format!(": {}", self.emit_type(type_annot))
                } else {
                    String::new()
                };
                format!("{}{}", p.name, type_str)
            })
            .collect();

        self.line(&format!("constructor({}) {{", params.join(", ")))?;
        self.indent += 1;
        self.emit_block(&constructor.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_trait_decl(&mut self, trait_decl: &ast::TraitDecl) -> TypeScriptResult<()> {
        self.line(&format!("interface {} {{", trait_decl.name))?;
        self.indent += 1;

        for method in &trait_decl.methods {
            let params: Vec<String> = method
                .parameters
                .iter()
                .map(|p| {
                    let type_str = if let Some(type_annot) = &p.type_annot {
                        format!(": {}", self.emit_type(type_annot))
                    } else {
                        String::new()
                    };
                    format!("{}{}", p.name, type_str)
                })
                .collect();

            let return_type = if let Some(ret) = &method.return_type {
                self.emit_type(ret)
            } else {
                "void".to_string()
            };

            self.line(&format!("{}({}): {};", method.name, params.join(", "), return_type))?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_type(&self, ty: &ast::Type) -> String {
        match ty {
            ast::Type::Int => "number".to_string(),
            ast::Type::Float => "number".to_string(),
            ast::Type::Bool => "boolean".to_string(),
            ast::Type::String => "string".to_string(),
            ast::Type::Char => "string".to_string(),
            ast::Type::Unit => "void".to_string(),
            ast::Type::Never => "never".to_string(),
            ast::Type::Array(inner) => format!("{}[]", self.emit_type(inner)),
            ast::Type::Option(inner) => format!("{} | null", self.emit_type(inner)),
            ast::Type::Result(ok, _err) => self.emit_type(ok), // Simplified
            ast::Type::Tuple(types) => {
                let type_strs: Vec<String> = types.iter().map(|t| self.emit_type(t)).collect();
                format!("[{}]", type_strs.join(", "))
            }
            ast::Type::Function(params, ret) => {
                let param_strs: Vec<String> = params.iter().map(|t| self.emit_type(t)).collect();
                format!("({}) => {}", param_strs.join(", "), self.emit_type(ret))
            }
            ast::Type::Generic(name) | ast::Type::TypeParam(name) | ast::Type::Var(name) => {
                name.clone()
            }
            _ => "any".to_string(),
        }
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> TypeScriptResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let expr_str = self.emit_expr(expr)?;
                self.line(&format!("{};", expr_str))?;
            }
            StatementKind::Variable(var_decl) => {
                self.emit_variable_decl(var_decl)?;
            }
            StatementKind::Return(expr_opt) => {
                if let Some(expr) = expr_opt {
                    let expr_str = self.emit_expr(expr)?;
                    self.line(&format!("return {};", expr_str))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::If(if_stmt) => {
                self.emit_if_statement(if_stmt)?;
            }
            StatementKind::While(while_stmt) => {
                self.emit_while_statement(while_stmt)?;
            }
            StatementKind::For(for_stmt) => {
                self.emit_for_statement(for_stmt)?;
            }
            StatementKind::Match(match_stmt) => {
                self.emit_match_statement(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try_statement(try_stmt)?;
            }
            StatementKind::Break => {
                self.line("break;")?;
            }
            StatementKind::Continue => {
                self.line("continue;")?;
            }
            StatementKind::DoWhile(do_while) => {
                self.line("while (true) {")?;
                self.indent += 1;
                self.emit_block(&do_while.body)?;
                let cond = self.emit_expr(&do_while.condition)?;
                self.line(&format!("if (!({})) {{ break; }}", cond))?;
                self.indent -= 1;
                self.line("}")?;
            }
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> TypeScriptResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_if_statement(&mut self, if_stmt: &ast::IfStatement) -> TypeScriptResult<()> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if ({}) {{", cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;

        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }

        self.line("}")?;
        Ok(())
    }

    fn emit_while_statement(&mut self, while_stmt: &ast::WhileStatement) -> TypeScriptResult<()> {
        let cond = self.emit_expr(&while_stmt.condition)?;
        self.line(&format!("while ({}) {{", cond))?;
        self.indent += 1;
        self.emit_block(&while_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_for_statement(&mut self, for_stmt: &ast::ForStatement) -> TypeScriptResult<()> {
        let iter = self.emit_expr(&for_stmt.iterator)?;
        let pattern_name = self.emit_pattern_var(&for_stmt.pattern);
        self.line(&format!("for (const {} of {}) {{", pattern_name, iter))?;
        self.indent += 1;
        self.emit_block(&for_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_pattern_var(&self, pattern: &ast::Pattern) -> String {
        match pattern {
            ast::Pattern::Wildcard => "_".to_string(),
            ast::Pattern::Variable(name) => name.clone(),
            ast::Pattern::Array(elements) => {
                let vars: Vec<String> = elements.iter().map(|p| self.emit_pattern_var(p)).collect();
                format!("[{}]", vars.join(", "))
            }
            ast::Pattern::Tuple(elements) => {
                let vars: Vec<String> = elements.iter().map(|p| self.emit_pattern_var(p)).collect();
                format!("[{}]", vars.join(", "))
            }
            ast::Pattern::Or(left, _) => self.emit_pattern_var(left),
            ast::Pattern::Guard(inner, _) => self.emit_pattern_var(inner),
            _ => "_item".to_string(),
        }
    }

    fn emit_match_statement(&mut self, match_stmt: &ast::MatchStatement) -> TypeScriptResult<()> {
        let expr = self.emit_expr(&match_stmt.expression)?;
        // Use a temporary variable for the match value
        let temp_var = "__match_val__";
        self.line(&format!("const {} = {};", temp_var, expr))?;

        for (i, case) in match_stmt.cases.iter().enumerate() {
            let condition = self.emit_match_condition(temp_var, &case.pattern, case.guard.as_ref())?;

            if i == 0 {
                self.line(&format!("if ({}) {{", condition))?;
            } else {
                self.line(&format!("else if ({}) {{", condition))?;
            }

            self.indent += 1;
            self.emit_pattern_bindings(temp_var, &case.pattern)?;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_match_condition(&self, var: &str, pattern: &ast::Pattern, guard: Option<&ast::Expression>) -> TypeScriptResult<String> {
        let base_cond = match pattern {
            ast::Pattern::Wildcard => "true".to_string(),
            ast::Pattern::Variable(_) => "true".to_string(),
            ast::Pattern::Literal(lit) => {
                let lit_str = self.emit_literal(lit)?;
                format!("{} === {}", var, lit_str)
            }
            ast::Pattern::Or(left, right) => {
                let left_cond = self.emit_match_condition(var, left, None)?;
                let right_cond = self.emit_match_condition(var, right, None)?;
                format!("({}) || ({})", left_cond, right_cond)
            }
            ast::Pattern::Array(elements) => {
                let len_check = format!("Array.isArray({}) && {}.length === {}", var, var, elements.len());
                let elem_checks: Vec<String> = elements.iter().enumerate()
                    .map(|(i, p)| self.emit_match_condition(&format!("{}[{}]", var, i), p, None))
                    .collect::<TypeScriptResult<Vec<_>>>()?;
                if elem_checks.is_empty() {
                    format!("{}.length === 0", var)
                } else {
                    format!("({}) && {}", len_check, elem_checks.join(" && "))
                }
            }
            _ => format!("true /* pattern not fully supported */"),
        };

        if let Some(guard_expr) = guard {
            let guard_str = self.emit_expr(guard_expr)?;
            Ok(format!("({}) && ({})", base_cond, guard_str))
        } else {
            Ok(base_cond)
        }
    }

    fn emit_pattern_bindings(&mut self, var: &str, pattern: &ast::Pattern) -> TypeScriptResult<()> {
        match pattern {
            ast::Pattern::Variable(name) => {
                self.line(&format!("const {} = {};", name, var))?;
            }
            ast::Pattern::Array(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_pattern_bindings(&format!("{}[{}]", var, i), elem)?;
                }
            }
            ast::Pattern::Tuple(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_pattern_bindings(&format!("{}[{}]", var, i), elem)?;
                }
            }
            ast::Pattern::Or(left, _) => {
                self.emit_pattern_bindings(var, left)?;
            }
            ast::Pattern::Guard(inner, _) => {
                self.emit_pattern_bindings(var, inner)?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_try_statement(&mut self, try_stmt: &ast::TryStatement) -> TypeScriptResult<()> {
        self.line("try {")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.indent -= 1;

        for catch in &try_stmt.catch_clauses {
            let catch_line = if let Some(var_name) = &catch.variable_name {
                format!("catch ({}) {{", var_name)
            } else {
                "catch (error) {".to_string()
            };
            self.line(&catch_line)?;
            self.indent += 1;
            self.emit_block(&catch.body)?;
            self.indent -= 1;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("} finally {")?;
            self.indent += 1;
            self.emit_block(finally)?;
            self.indent -= 1;
        }

        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> TypeScriptResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => Ok(self.emit_literal(lit)?),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, lhs, rhs) => {
                let lhs_str = self.emit_expr(lhs)?;
                let rhs_str = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &lhs_str, &rhs_str))
            }
            ExpressionKind::Unary(op, expr) => {
                let expr_str = self.emit_expr(expr)?;
                Ok(self.emit_unaryop(op, &expr_str))
            }
            ExpressionKind::Call(callee, args) => {
                let callee_str = self.emit_expr(callee)?;
                let mut arg_strs = Vec::new();
                for arg in args {
                    arg_strs.push(self.emit_expr(arg)?);
                }

                // Map built-in functions
                if callee_str == "println" {
                    Ok(format!("console.log({})", arg_strs.join(", ")))
                } else {
                    Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
                }
            }
            ExpressionKind::Assign(lhs, rhs) => {
                let lhs_str = self.emit_expr(lhs)?;
                let rhs_str = self.emit_expr(rhs)?;
                Ok(format!("{} = {}", lhs_str, rhs_str))
            }
            ExpressionKind::Parenthesized(expr) => {
                let inner = self.emit_expr(expr)?;
                Ok(format!("({})", inner))
            }
            ExpressionKind::Wait(wait_type, exprs) => {
                self.emit_wait(wait_type, exprs)
            }
            _ => Err(TypeScriptBackendError::UnsupportedFeature(format!(
                "Expression type {:?} is not yet supported in TypeScript backend",
                expr
            ))),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> TypeScriptResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(f.to_string()),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => Ok(format!("\"{}\"", s.replace('"', "\\\""))),
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null => Ok("null".to_string()),
            ast::Literal::None => Ok("undefined".to_string()),
            ast::Literal::Unit => Ok("undefined".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, lhs: &str, rhs: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("{} + {}", lhs, rhs),
            ast::BinaryOp::Sub => format!("{} - {}", lhs, rhs),
            ast::BinaryOp::Mul => format!("{} * {}", lhs, rhs),
            ast::BinaryOp::Div => format!("{} / {}", lhs, rhs),
            ast::BinaryOp::Mod => format!("{} % {}", lhs, rhs),
            ast::BinaryOp::Pow => format!("Math.pow({}, {})", lhs, rhs),
            ast::BinaryOp::And => format!("{} && {}", lhs, rhs),
            ast::BinaryOp::Or => format!("{} || {}", lhs, rhs),
            ast::BinaryOp::Equal => format!("{} === {}", lhs, rhs),
            ast::BinaryOp::NotEqual => format!("{} !== {}", lhs, rhs),
            ast::BinaryOp::Less => format!("{} < {}", lhs, rhs),
            ast::BinaryOp::LessEqual => format!("{} <= {}", lhs, rhs),
            ast::BinaryOp::Greater => format!("{} > {}", lhs, rhs),
            ast::BinaryOp::GreaterEqual => format!("{} >= {}", lhs, rhs),
            ast::BinaryOp::BitAnd => format!("{} & {}", lhs, rhs),
            ast::BinaryOp::BitOr => format!("{} | {}", lhs, rhs),
            ast::BinaryOp::BitXor => format!("{} ^ {}", lhs, rhs),
            ast::BinaryOp::LeftShift => format!("{} << {}", lhs, rhs),
            ast::BinaryOp::RightShift => format!("{} >> {}", lhs, rhs),
            ast::BinaryOp::Concat => format!("{} + {}", lhs, rhs),
            _ => format!("/* unsupported op {:?} */ {} {}", op, lhs, rhs),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, expr: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("-{}", expr),
            ast::UnaryOp::Not => format!("!{}", expr),
            ast::UnaryOp::BitNot => format!("~{}", expr),
            ast::UnaryOp::Wait => format!("await {}", expr),
        }
    }

    fn emit_wait(&self, wait_type: &ast::WaitType, exprs: &[ast::Expression]) -> TypeScriptResult<String> {
        let expr_strs: Vec<String> = exprs
            .iter()
            .map(|e| self.emit_expr(e))
            .collect::<Result<Vec<_>, _>>()?;
        match wait_type {
            ast::WaitType::Single => {
                // Single await: await expr
                if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    // Multiple expressions - await each
                    let awaited: Vec<String> = expr_strs.iter().map(|e| format!("await {}", e)).collect();
                    Ok(format!("({})", awaited.join(", ")))
                }
            }
            ast::WaitType::Together => {
                // Parallel execution: Promise.all
                if expr_strs.is_empty() {
                    Ok("Promise.resolve()".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    Ok(format!("await Promise.all([{}])", expr_strs.join(", ")))
                }
            }
            ast::WaitType::Race => {
                // Race: Promise.race
                if expr_strs.is_empty() {
                    Ok("Promise.resolve()".to_string())
                } else if expr_strs.len() == 1 {
                    Ok(format!("await {}", expr_strs[0]))
                } else {
                    Ok(format!("await Promise.race([{}])", expr_strs.join(", ")))
                }
            }
            ast::WaitType::Timeout(timeout_expr) => {
                // Timeout: race between operation and timeout
                let timeout = self.emit_expr(timeout_expr)?;
                if expr_strs.is_empty() {
                    Ok(format!("new Promise(resolve => setTimeout(resolve, {}))", timeout))
                } else {
                    let expr = &expr_strs[0];
                    Ok(format!(
                        "await Promise.race([{}, new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), {}))])",
                        expr, timeout
                    ))
                }
            }
        }
    }

    fn line(&mut self, s: &str) -> TypeScriptResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_lexer::span::Span;
    use x_parser::ast::{Spanned, Literal, MethodModifiers};

    fn make_expr(kind: ExpressionKind) -> ast::Expression {
        Spanned::new(kind, Span::default())
    }

    fn make_stmt(kind: StatementKind) -> ast::Statement {
        Spanned::new(kind, Span::default())
    }

    #[test]
    fn test_empty_program_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![],
            statements: vec![],
        };

        let mut backend = TypeScriptBackend::new(TypeScriptBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let ts_code = String::from_utf8_lossy(&output.files[0].content);
        // With empty statements, no main function is generated
        assert!(ts_code.contains("// Generated by X-Lang TypeScript backend"));
    }

    #[test]
    fn test_program_with_statements_generates_main() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![],
            statements: vec![make_stmt(StatementKind::Expression(make_expr(ExpressionKind::Call(
                Box::new(make_expr(ExpressionKind::Variable("println".to_string()))),
                vec![make_expr(ExpressionKind::Literal(Literal::String(
                    "Hello, World!".to_string(),
                )))],
            ))))],
        };

        let mut backend = TypeScriptBackend::new(TypeScriptBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let ts_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(ts_code.contains("function main(): void"));
        assert!(ts_code.contains("console.log("));
        assert!(ts_code.contains("main();"));
    }

    #[test]
    fn test_async_function_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
                span: Span::default(),
                name: "fetch_data".to_string(),
                type_parameters: vec![],
                parameters: vec![],
                effects: vec![],
                return_type: Some(ast::Type::String),
                body: ast::Block {
                    statements: vec![make_stmt(StatementKind::Return(Some(make_expr(
                        ExpressionKind::Literal(Literal::String("data".to_string())),
                    ))))],
                },
                is_async: true,
                modifiers: MethodModifiers::default(),
            })],
            statements: vec![],
        };

        let mut backend = TypeScriptBackend::new(TypeScriptBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let ts_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(ts_code.contains("async function fetch_data"));
    }

    #[test]
    fn test_wait_together_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
                span: Span::default(),
                name: "main".to_string(),
                type_parameters: vec![],
                parameters: vec![],
                effects: vec![],
                return_type: None,
                body: ast::Block {
                    statements: vec![make_stmt(StatementKind::Expression(make_expr(
                        ExpressionKind::Wait(
                            ast::WaitType::Together,
                            vec![
                                make_expr(ExpressionKind::Variable("task1".to_string())),
                                make_expr(ExpressionKind::Variable("task2".to_string())),
                            ],
                        ),
                    )))],
                },
                is_async: true,
                modifiers: MethodModifiers::default(),
            })],
            statements: vec![],
        };

        let mut backend = TypeScriptBackend::new(TypeScriptBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let ts_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(ts_code.contains("async function main"));
        assert!(ts_code.contains("await Promise.all([task1, task2])"));
    }

    #[test]
    fn test_wait_race_generation() {
        let program = AstProgram {
            span: Span::default(),
            declarations: vec![ast::Declaration::Function(ast::FunctionDecl {
                span: Span::default(),
                name: "main".to_string(),
                type_parameters: vec![],
                parameters: vec![],
                effects: vec![],
                return_type: None,
                body: ast::Block {
                    statements: vec![make_stmt(StatementKind::Expression(make_expr(
                        ExpressionKind::Wait(
                            ast::WaitType::Race,
                            vec![
                                make_expr(ExpressionKind::Variable("task1".to_string())),
                                make_expr(ExpressionKind::Variable("task2".to_string())),
                            ],
                        ),
                    )))],
                },
                is_async: true,
                modifiers: MethodModifiers::default(),
            })],
            statements: vec![],
        };

        let mut backend = TypeScriptBackend::new(TypeScriptBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let ts_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(ts_code.contains("async function main"));
        assert!(ts_code.contains("await Promise.race([task1, task2])"));
    }
}
