//! TypeScript 后端 - 将 X AST 编译为 TypeScript 代码
//! 
//! 生成 TypeScript 源码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct TypeScriptBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for TypeScriptBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct TypeScriptBackend {
    config: TypeScriptBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum TypeScriptBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type TypeScriptResult<T> = Result<T, TypeScriptBackendError>;

impl TypeScriptBackend {
    pub fn new(config: TypeScriptBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(&mut self, program: &AstProgram) -> TypeScriptResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_main_function()?;

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("index.ts"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::TypeScript,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> TypeScriptResult<()> {
        self.line("// Generated by X-Lang TypeScript backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_main_function(&mut self) -> TypeScriptResult<()> {
        self.line("function main(): void {")?;
        self.indent += 1;
        self.line("console.log('Hello from TypeScript backend!');")?;
        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        self.line("// Run the main function")?;
        self.line("main();")?;
        Ok(())
    }

    fn line(&mut self, s: &str) -> TypeScriptResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            declarations: vec![],
            statements: vec![],
        };

        let mut backend = TypeScriptBackend::new(TypeScriptBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let ts_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(ts_code.contains("function main(): void"));
        assert!(ts_code.contains("console.log('Hello from TypeScript backend!');"));
        assert!(ts_code.contains("main();"));
    }
}
