//! Zig 后端 - 将 X AST 编译为 Zig 代码
//!
//! 利用 Zig 的内存管理和错误处理特性，提供高效的编译输出

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct ZigBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for ZigBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct ZigBackend {
    config: ZigBackendConfig,
    indent: usize,
    output: String,
    /// Track global (top-level) variable declarations for forward decls
    global_vars: Vec<String>,
    /// Track imported Zig modules
    imported_modules: Vec<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum ZigBackendError {
    #[error("Lowering error: {0}")]
    LoweringError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Compiler error: {0}")]
    CompilerError(String),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type ZigResult<T> = Result<T, ZigBackendError>;

impl ZigBackend {
    pub fn new(config: ZigBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            global_vars: Vec::new(),
            imported_modules: Vec::new(),
        }
    }

    pub fn generate_from_ast(&mut self, program: &AstProgram) -> ZigResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;
        self.global_vars.clear();
        self.imported_modules.clear();

        self.emit_header()?;

        // Emit imports
        for decl in &program.declarations {
            if let ast::Declaration::Import(import) = decl {
                self.emit_import(import)?;
            }
        }

        // Emit global variables
        for decl in &program.declarations {
            if let ast::Declaration::Variable(v) = decl {
                self.emit_global_var(v)?;
            }
        }

        // Emit functions
        let mut has_main = false;
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                self.emit_function(f)?;
                self.line("")?;
                if f.name == "main" {
                    has_main = true;
                }
            }
        }

        // Emit main function only if not already defined
        if !has_main {
            self.emit_main_function()?;
        }

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("output.zig"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::Zig,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_main_function(&mut self) -> ZigResult<()> {
        self.line("pub fn main() !void {")?;
        self.indent += 1;
        self.line("const std = @import(\"std\");")?;
        self.line("const stdout = std.io.getStdOut().writer();")?;
        self.line("")?;
        self.line("// Initialize runtime")?;
        self.line("try stdout.print(\"Hello from Zig backend!\n\", .{});")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_header(&mut self) -> ZigResult<()> {
        self.line("// Generated by X-Lang Zig backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;

        // 不总是导入std，而是在emit_import中处理

        Ok(())
    }

    fn emit_forward_decl(&mut self, _f: &ast::FunctionDecl) -> ZigResult<()> {
        // Zig不需要前向声明，所以这个函数为空
        Ok(())
    }

    fn emit_global_var(&mut self, v: &ast::VariableDecl) -> ZigResult<()> {
        let init = if let Some(expr) = &v.initializer {
            self.emit_expr(expr)?
        } else {
            "undefined".to_string()
        };
        let var_type = if let Some(type_annot) = &v.type_annot {
            format!(" : {}", self.emit_type(type_annot))
        } else {
            "".to_string()
        };
        self.line(&format!("var {}{} = {};", v.name, var_type, init))?;
        self.global_vars.push(v.name.clone());
        Ok(())
    }

    fn emit_function(&mut self, f: &ast::FunctionDecl) -> ZigResult<()> {
        let params = if f.parameters.is_empty() {
            "".to_string()
        } else {
            f.parameters.iter().map(|p| {
                let param_type = if let Some(type_annot) = &p.type_annot {
                    format!(" : {}", self.emit_type(type_annot))
                } else {
                    " : anytype".to_string()
                };
                format!("{} {}", p.name, param_type)
            }).collect::<Vec<_>>().join(", ")
        };
        let return_type = if let Some(return_type) = &f.return_type {
            format!(" -> {}", self.emit_type(return_type))
        } else {
            "".to_string()
        };
        self.line(&format!("fn {}{}({}){} {{" , f.name, "", params, return_type))?;
        self.indent += 1;
        self.emit_block(&f.body)?;
        if f.return_type.is_none() {
            self.line("return;")?;
        }
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> ZigResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> ZigResult<()> {
        match stmt {
            ast::Statement::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            ast::Statement::Variable(v) => {
                let init = if let Some(expr) = &v.initializer {
                    self.emit_expr(expr)?
                } else {
                    "undefined".to_string()
                };
                let var_type = if let Some(type_annot) = &v.type_annot {
                    format!(" : {}", self.emit_type(type_annot))
                } else {
                    "".to_string()
                };
                self.line(&format!("var {}{} = {};", v.name, var_type, init))?;
            }
            ast::Statement::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            ast::Statement::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            ast::Statement::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while ({}) {{" , cond))?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            ast::Statement::For(_) => {
                self.line("// TODO: for loop")?;
            }
            ast::Statement::Match(_) => {
                self.line("// TODO: match")?;
            }
            ast::Statement::Try(_) => {
                self.line("// TODO: try")?;
            }
        }
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> ZigResult<()> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if ({}) {{" , cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;
        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }
        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> ZigResult<String> {
        match expr {
            ast::Expression::Literal(lit) => self.emit_literal(lit),
            ast::Expression::Variable(name) => {
                Ok(name.clone())
            }
            ast::Expression::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ast::Expression::Unary(op, expr) => {
                let e = self.emit_expr(expr)?;
                Ok(self.emit_unaryop(op, &e))
            }
            ast::Expression::Call(callee, args) => {
                self.emit_call(callee, args)
            }
            ast::Expression::Assign(target, value) => {
                self.emit_assign(target, value)
            }
            ast::Expression::Array(elements) => {
                self.emit_array_literal(elements)
            }
            ast::Expression::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            ast::Expression::If(cond, then_e, else_e) => {
                let c = self.emit_expr(cond)?;
                let t = self.emit_expr(then_e)?;
                let e = self.emit_expr(else_e)?;
                Ok(format!("if ({}) {} else {}", c, t, e))
            }
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            _ => Err(ZigBackendError::UnsupportedFeature(format!("{:?}", expr))),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> ZigResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(format!("{}", n)),
            ast::Literal::Float(f) => {
                Ok(format!("{}", f))
            }
            ast::Literal::Boolean(b) => Ok(format!("{}", b)),
            ast::Literal::String(s) => {
                let escaped = s.replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null => Ok("null".to_string()),
            ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("void".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("{} + {}", l, r),
            ast::BinaryOp::Sub => format!("{} - {}", l, r),
            ast::BinaryOp::Mul => format!("{} * {}", l, r),
            ast::BinaryOp::Div => format!("{} / {}", l, r),
            ast::BinaryOp::Mod => format!("{} % {}", l, r),
            ast::BinaryOp::Equal => format!("{} == {}", l, r),
            ast::BinaryOp::NotEqual => format!("{} != {}", l, r),
            ast::BinaryOp::Less => format!("{} < {}", l, r),
            ast::BinaryOp::LessEqual => format!("{} <= {}", l, r),
            ast::BinaryOp::Greater => format!("{} > {}", l, r),
            ast::BinaryOp::GreaterEqual => format!("{} >= {}", l, r),
            ast::BinaryOp::And => format!("{} and {}", l, r),
            ast::BinaryOp::Or => format!("{} or {}", l, r),
            ast::BinaryOp::Pow => format!("@exp(@log({}) * {})", l, r),
            _ => format!("/* unsupported binop {:?} */ null", op),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("-{}", e),
            ast::UnaryOp::Not => format!("!{}", e),
            _ => format!("/* unsupported unary {:?} */ null", op),
        }
    }

    fn emit_call(&self, callee: &ast::Expression, args: &[ast::Expression]) -> ZigResult<String> {
        if let ast::Expression::Variable(name) = callee {
            let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect::<ZigResult<Vec<_>>>()?;
            return Ok(self.emit_builtin_or_call(name, &arg_strs));
        }
        let callee_str = self.emit_expr(callee)?;
        let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect::<ZigResult<Vec<_>>>()?;

        // 处理allocator.alloc等返回错误联合类型的函数
        if callee_str.ends_with(".alloc") {
            Ok(format!("{}({}, {}) catch unreachable", callee_str, arg_strs[0], arg_strs[1]))
        } else {
            Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
        }
    }

    fn emit_builtin_or_call(&self, name: &str, args: &[String]) -> String {
        match name {
            "print" | "println" => {
                if args.len() == 1 {
                    format!("std.debug.print(\"{{}}\n\", .{{{}}})", args[0])
                } else {
                    "std.debug.print(\"\n\", .{{}})".to_string()
                }
            }
            "print_inline" => {
                if args.len() == 1 {
                    format!("std.debug.print(\"{{}}\", .{{{}}})", args[0])
                } else {
                    "std.debug.print(\"\", .{{}})".to_string()
                }
            }
            "concat" => {
                if args.len() == 2 {
                    format!("std.mem.concat(u8, &[_][]const u8{{ {}, {} }})", args[0], args[1])
                } else {
                    "\"\"" .to_string()
                }
            }
            "to_string" => format!("std.fmt.allocPrint(std.heap.page_allocator, \"{{}}\", .{{{}}}) catch unreachable", args.first().unwrap_or(&"null".to_string())),
            "type_of" => format!("@typeName(@TypeOf({}))", args.first().unwrap_or(&"null".to_string())),
            "panic" => {
                if args.len() == 1 {
                    format!("std.debug.panic(\"{{}}\", .{{{}}})", args[0])
                } else {
                    "std.debug.panic(\"panic\", .{{}})".to_string()
                }
            }
            "len" => format!("{}.len", args.first().unwrap_or(&"null".to_string())),
            _ => {
                format!("{}({})", name, args.join(", "))
            }
        }
    }

    fn emit_assign(&self, target: &ast::Expression, value: &ast::Expression) -> ZigResult<String> {
        let val = self.emit_expr(value)?;
        match target {
            ast::Expression::Variable(name) => {
                Ok(format!("{} = {}", name, val))
            }
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{} = {}", o, field, val))
            }
            _ => {
                let t = self.emit_expr(target)?;
                Ok(format!("{} = {}", t, val))
            }
        }
    }

    fn emit_array_literal(&self, elements: &[ast::Expression]) -> ZigResult<String> {
        if elements.is_empty() {
            return Ok("[]anytype{}".to_string());
        }
        let elem_strs: Vec<String> = elements.iter().map(|e| self.emit_expr(e)).collect::<ZigResult<Vec<_>>>()?;
        Ok(format!("[_]anytype{{{}}}", elem_strs.join(", ")))
    }

    fn emit_type(&self, ty: &ast::Type) -> String {
        match ty {
            ast::Type::Int => "i32".to_string(),
            ast::Type::Float => "f64".to_string(),
            ast::Type::Bool => "bool".to_string(),
            ast::Type::String => "[]const u8".to_string(),
            ast::Type::Char => "u8".to_string(),
            ast::Type::Unit => "void".to_string(),
            ast::Type::Never => "noreturn".to_string(),
            ast::Type::Array(inner) => format!("[] {}", self.emit_type(inner)),
            ast::Type::Dictionary(key, value) => format!("std.AutoHashMap({}, {})", self.emit_type(key), self.emit_type(value)),
            ast::Type::Function(params, return_type) => {
                let param_types = params.iter().map(|p| self.emit_type(p)).collect::<Vec<_>>().join(", ");
                format!("fn({}) -> {}", param_types, self.emit_type(return_type))
            }
            _ => "anytype".to_string(),
        }
    }

    fn emit_import(&mut self, import: &ast::ImportDecl) -> ZigResult<()> {
        // 检查是否是Zig标准库导入
        if import.module_path.starts_with("zig::") {
            let zig_module = import.module_path.trim_start_matches("zig::");

            // 处理子模块导入，如 zig::std::math
            let zig_import_path = zig_module.replace("::", ".");

            // 处理导入符号
            if import.symbols.is_empty() || import.symbols.contains(&ast::ImportSymbol::All) {
                // 通配导入或无符号导入，导入整个模块
                let module_name = zig_module.split("::").last().unwrap_or(zig_module);
                let import_stmt = format!("const {} = @import(\"{}\");", module_name, zig_import_path);

                // 避免重复导入
                if !self.imported_modules.contains(&module_name.to_string()) {
                    self.line(&import_stmt)?;
                    self.imported_modules.push(module_name.to_string());
                }
            } else {
                // 命名导入
                for symbol in &import.symbols {
                    if let ast::ImportSymbol::Named(name, alias) = symbol {
                        let import_name = alias.as_ref().unwrap_or(name);
                        let import_stmt = format!("const {} = @import(\"{}\").{};", import_name, zig_import_path, name);

                        // 避免重复导入
                        if !self.imported_modules.contains(&import_name.to_string()) {
                            self.line(&import_stmt)?;
                            self.imported_modules.push(import_name.to_string());
                        }
                    }
                }
            }
        }
        Ok(())
    }

    fn line(&mut self, s: &str) -> ZigResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }

    /// Compile generated Zig code to executable
    pub fn compile_zig_code(&self, zig_code: &str, output_file: &PathBuf) -> ZigResult<()> {
        use std::process::Command;

        let zig_file = output_file.with_extension("zig");
        std::fs::write(&zig_file, zig_code)?;

        // Build zig command
        let mut cmd = Command::new("zig");
        cmd.arg("build-exe")
            .arg(zig_file)
            .arg("-O")
            .arg(if self.config.optimize { "ReleaseFast" } else { "Debug" });

        if self.config.debug_info {
            cmd.arg("-g");
        }

        // Execute compilation
        let output = cmd.output()?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            return Err(ZigBackendError::CompilerError(
                format!("Zig compiler failed:\nstdout: {}\nstderr: {}", stdout, stderr)
            ));
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            declarations: vec![
                ast::Declaration::Function(ast::FunctionDecl {
                    name: "main".to_string(),
                    parameters: vec![],
                    return_type: None,
                    body: ast::Block {
                        statements: vec![
                            ast::Statement::Expression(
                                ast::Expression::Call(
                                    Box::new(ast::Expression::Variable("print".to_string())),
                                    vec![ast::Expression::Literal(ast::Literal::String("Hello, World!".to_string()))],
                                )
                            ),
                        ],
                    },
                    is_async: false,
                }),
            ],
            statements: vec![]
        };

        let mut backend = ZigBackend::new(ZigBackendConfig::default());
        let output = backend.generate_from_ast(&program).unwrap();
        let zig_code = String::from_utf8_lossy(&output.files[0].content);
        assert!(zig_code.contains("std.debug.print"));
        assert!(zig_code.contains("Hello, World!"));
        assert!(zig_code.contains("fn main()"));
    }
}