// Zig 后端实现
// 将 X IR 编译为 Zig 代码，然后使用 Zig 编译器编译为 Native 或 Wasm

use std::path::PathBuf;
use std::process::Command;
use std::str;

use super::{CodegenOutput, OutputFile, FileType};
use super::{CodeGenError, CodeGenResult};
use super::xir::{Program, Declaration, Function, Statement, Expression, Type, BinaryOp, UnaryOp};

/// Zig 后端配置
#[derive(Debug, Clone)]
pub struct ZigBackendConfig {
    /// 目标平台
    pub target: ZigTarget,
    /// 输出目录
    pub output_dir: Option<PathBuf>,
    /// 是否启用优化
    pub optimize: bool,
    /// 是否生成调试信息
    pub debug_info: bool,
}

/// Zig 目标平台
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum ZigTarget {
    /// 本地机器码
    Native,
    /// WebAssembly
    Wasm,
}

/// Zig 后端
pub struct ZigBackend {
    config: ZigBackendConfig,
}

impl ZigBackend {
    /// 创建新的 Zig 后端
    pub fn new(config: ZigBackendConfig) -> Self {
        Self {
            config,
        }
    }

    /// 从 AST 生成代码（实现 DynamicCodeGenerator trait 所需）
    pub fn generate_from_ast(&mut self, program: &x_parser::ast::Program) -> CodeGenResult<CodegenOutput> {
        // 首先将 AST  lowering 到 XIR
        // TODO: 实现完整的 AST -> XIR lowering
        // 目前暂时返回占位符错误
        Err(CodeGenError::UnsupportedFeature(
            "AST to XIR lowering not fully implemented yet".to_string(),
        ))
    }

    /// 从 XIR 模块生成代码
    pub fn generate_from_xir(&self, program: &Program) -> CodeGenResult<CodegenOutput> {
        let mut output = CodegenOutput {
            files: Vec::new(),
            dependencies: Vec::new(),
        };

        // 生成 Zig 源码
        let zig_source = self.generate_zig_source(program)?;

        // 确定输出文件名
        let file_name = format!("output.zig");
        let output_path = self.config.output_dir
            .clone()
            .unwrap_or_else(|| PathBuf::from("."))
            .join(file_name);

        // 添加到输出文件列表
        output.files.push(OutputFile {
            path: output_path.clone(),
            content: zig_source.as_bytes().to_vec(),
            file_type: FileType::Zig, // Use Zig type for Zig source code
        });

        // 如果不需要链接，只返回源码
        if !self.config.debug_info { // 暂时用 debug_info 作为是否需要编译的标志，后续可以添加专门的 no_link 选项
            return Ok(output);
        }

        // 编译为目标格式
        self.compile_zig(&output_path)?;

        Ok(output)
    }

    /// 生成 Zig 源码
    fn generate_zig_source(&self, program: &Program) -> CodeGenResult<String> {
        let mut source = String::new();

        // 添加版权声明
        source.push_str("// Generated by X Language Zig Backend\n");
        source.push_str("\n");

        // 添加导入
        source.push_str("const std = @import(\"std\");\n");
        source.push_str("\n");

        // 生成所有声明
        for decl in &program.declarations {
            match decl {
                Declaration::Function(func) => {
                    source.push_str(&self.generate_function(func)?);
                    source.push_str("\n");
                }
                Declaration::Struct(strukt) => {
                    source.push_str(&self.generate_struct(strukt)?);
                    source.push_str("\n");
                }
                Declaration::Enum(enum_) => {
                    source.push_str(&self.generate_enum(enum_)?);
                    source.push_str("\n");
                }
                Declaration::TypeAlias(alias) => {
                    source.push_str(&self.generate_type_alias(alias)?);
                    source.push_str("\n");
                }
                Declaration::Global(global) => {
                    source.push_str(&self.generate_global(global)?);
                    source.push_str("\n");
                }
                Declaration::ExternFunction(ext_func) => {
                    source.push_str(&self.generate_extern_function(ext_func)?);
                    source.push_str("\n");
                }
            }
        }

        Ok(source)
    }

    /// 生成函数
    fn generate_function(&self, func: &Function) -> CodeGenResult<String> {
        let mut source = String::new();

        // 生成函数签名
        source.push_str(&format!("fn {}(", func.name));

        // 生成参数
        for (i, param) in func.parameters.iter().enumerate() {
            if i > 0 {
                source.push_str(", ");
            }
            source.push_str(&format!("{}: {}", param.name, self.generate_type(&param.type_)?));
        }

        // 生成返回类型
        source.push_str(&format!(" -> {}", self.generate_type(&func.return_type)?));

        source.push_str(" {\n");

        // 生成函数体
        for stmt in &func.body.statements {
            source.push_str(&self.generate_statement(stmt)?);
        }

        source.push_str("}\n");

        Ok(source)
    }

    /// 生成结构体定义
    fn generate_struct(&self, strukt: &super::xir::Struct) -> CodeGenResult<String> {
        let mut source = String::new();
        source.push_str(&format!("pub const {} = struct {{\n", strukt.name));

        for field in &strukt.fields {
            source.push_str(&format!("    {}: {},\n", field.name, self.generate_type(&field.type_)?));
        }

        source.push_str("};\n");
        Ok(source)
    }

    /// 生成枚举定义
    fn generate_enum(&self, enum_: &super::xir::Enum) -> CodeGenResult<String> {
        let mut source = String::new();

        if let Some(underlying_type) = &enum_.underlying_type {
            source.push_str(&format!("pub const {} = enum({}) {{\n", enum_.name, self.generate_type(underlying_type)?));
        } else {
            source.push_str(&format!("pub const {} = enum {{\n", enum_.name));
        }

        for (i, variant) in enum_.variants.iter().enumerate() {
            if let Some(value) = &variant.value {
                source.push_str(&format!("    {} = {},\n", variant.name, value));
            } else {
                source.push_str(&format!("    {} = {},\n", variant.name, i));
            }
        }

        source.push_str("};\n");
        Ok(source)
    }

    /// 生成类型别名
    fn generate_type_alias(&self, alias: &super::xir::TypeAlias) -> CodeGenResult<String> {
        let target_type = self.generate_type(&alias.target_type)?;
        Ok(format!("pub const {} = {};\n", alias.name, target_type))
    }

    /// 生成全局变量
    fn generate_global(&self, global: &super::xir::GlobalVar) -> CodeGenResult<String> {
        let type_str = self.generate_type(&global.type_)?;
        let mut source = String::new();

        if global.is_const {
            source.push_str("pub const ");
        } else {
            source.push_str("pub var ");
        }

        source.push_str(&format!("{}: {}", global.name, type_str));

        if let Some(init) = &global.initializer {
            let init_str = self.generate_expression(init)?;
            source.push_str(&format!(" = {}", init_str));
        }

        source.push_str(";\n");
        Ok(source)
    }

    /// 生成外部函数声明
    fn generate_extern_function(&self, ext_func: &super::xir::ExternFunction) -> CodeGenResult<String> {
        let mut source = String::new();
        source.push_str(&format!("extern \"{}\" fn {}(", ext_func.abi.as_deref().unwrap_or("C"), ext_func.name));

        for (i, param) in ext_func.parameters.iter().enumerate() {
            if i > 0 {
                source.push_str(", ");
            }
            source.push_str(&format!("{}: {}", param.name, self.generate_type(&param.type_)?));
        }

        source.push_str(&format!(") -> {};\n", self.generate_type(&ext_func.return_type)?));
        Ok(source)
    }

    /// 生成语句
    fn generate_statement(&self, stmt: &Statement) -> CodeGenResult<String> {
        match stmt {
            Statement::Expression(expr) => {
                let expr_str = self.generate_expression(expr)?;
                Ok(format!("    {};\n", expr_str))
            }
            Statement::Return(expr) => {
                if let Some(expr) = expr {
                    let expr_str = self.generate_expression(expr)?;
                    Ok(format!("    return {};\n", expr_str))
                } else {
                    Ok("    return;\n".to_string())
                }
            }
            Statement::Variable(var) => {
                let mut stmt_str = String::new();
                if var.is_static {
                    stmt_str.push_str("    comptime ");
                }
                if let Some(expr) = &var.initializer {
                    let expr_str = self.generate_expression(expr)?;
                    stmt_str.push_str(&format!("    var {}: {} = {};\n", var.name, self.generate_type(&var.type_)?, expr_str));
                } else {
                    stmt_str.push_str(&format!("    var {}: {};\n", var.name, self.generate_type(&var.type_)?));
                }
                Ok(stmt_str)
            }
            Statement::If(if_stmt) => {
                let cond_str = self.generate_expression(&if_stmt.condition)?;
                let then_str = self.generate_statement(&if_stmt.then_branch)?;
                let mut if_str = format!("    if ({}) {{\n{}", cond_str, then_str.trim_start_matches("    "));

                if let Some(else_branch) = &if_stmt.else_branch {
                    // Handle else if chains
                    if let Statement::If(_) = else_branch.as_ref() {
                        if_str.push_str("    } else ");
                        let else_str = self.generate_statement(else_branch)?;
                        if_str.push_str(&else_str.trim_start_matches("    "));
                    } else {
                        if_str.push_str("    } else {\n");
                        let else_str = self.generate_statement(else_branch)?;
                        if_str.push_str(&else_str.trim_start_matches("    "));
                        if_str.push_str("    }\n");
                    }
                } else {
                    if_str.push_str("    }\n");
                }

                Ok(if_str)
            }
            Statement::While(while_stmt) => {
                let cond_str = self.generate_expression(&while_stmt.condition)?;
                let body_str = self.generate_statement(&while_stmt.body)?;
                Ok(format!("    while ({}) {{\n{}    }}\n", cond_str, body_str.trim_start_matches("    ")))
            }
            Statement::Break => {
                Ok("    break;\n".to_string())
            }
            Statement::Continue => {
                Ok("    continue;\n".to_string())
            }
            Statement::Compound(block) => {
                let mut block_str = String::new();
                for stmt in &block.statements {
                    block_str.push_str(&self.generate_statement(stmt)?);
                }
                Ok(format!("{{\n{}    }}\n", block_str))
            }
            Statement::DoWhile(do_while) => {
                let body_str = self.generate_statement(&do_while.body)?;
                let cond_str = self.generate_expression(&do_while.condition)?;
                Ok(format!("    {{\n{}    }} while ({});\n", body_str.trim_start_matches("    "), cond_str))
            }
            Statement::For(for_stmt) => {
                let init_str = if let Some(init) = &for_stmt.init {
                    self.generate_statement(init)?
                } else {
                    String::new()
                };
                let cond_str = if let Some(cond) = &for_stmt.condition {
                    self.generate_expression(cond)?
                } else {
                    "true".to_string()
                };
                let update_str = if let Some(update) = &for_stmt.update {
                    self.generate_expression(update)?
                } else {
                    String::new()
                };
                let body_str = self.generate_statement(&for_stmt.body)?;

                Ok(format!(
                    "    for ({}; {}; {}) {{\n{}    }}\n",
                    init_str.trim().trim_end_matches(';'),
                    cond_str,
                    update_str,
                    body_str.trim_start_matches("    ")
                ))
            }
            Statement::Switch(switch) => {
                let cond_str = self.generate_expression(&switch.condition)?;
                let mut switch_str = format!("    switch ({}) {{\n", cond_str);

                for case in &switch.cases {
                    let value_str = self.generate_expression(&case.value)?;
                    switch_str.push_str(&format!("        {} => {{\n", value_str));

                    for stmt in &case.body.statements {
                        switch_str.push_str(&format!("            {}", self.generate_statement(stmt)?.trim_start_matches("    ")));
                    }

                    if case.fall_through {
                        switch_str.push_str("            // fallthrough\n");
                    } else {
                        switch_str.push_str("            break;\n");
                    }
                    switch_str.push_str("        },\n");
                }

                if let Some(default_case) = &switch.default_case {
                    switch_str.push_str("        else => {\n");
                    for stmt in &default_case.statements {
                        switch_str.push_str(&format!("            {}", self.generate_statement(stmt)?.trim_start_matches("    ")));
                    }
                    switch_str.push_str("        },\n");
                }

                switch_str.push_str("    }\n");
                Ok(switch_str)
            }
            _ => Err(CodeGenError::UnsupportedFeature(
                format!("Unsupported statement: {:?}", stmt),
            )),
        }
    }

    /// 生成表达式
    fn generate_expression(&self, expr: &Expression) -> CodeGenResult<String> {
        match expr {
            Expression::Literal(lit) => {
                Ok(format!("{:?}", lit))
            }
            Expression::Variable(name) => {
                Ok(name.clone())
            }
            Expression::Binary(op, left, right) => {
                let left_str = self.generate_expression(left)?;
                let right_str = self.generate_expression(right)?;
                let op_str = self.generate_operator(op);
                Ok(format!("({} {} {})", left_str, op_str, right_str))
            }
            Expression::Unary(op, inner) => {
                let inner_str = self.generate_expression(inner)?;
                let op_str = self.generate_unary_operator(op);
                Ok(format!("({}{})", op_str, inner_str))
            }
            Expression::Assign(left, right) => {
                let left_str = self.generate_expression(left)?;
                let right_str = self.generate_expression(right)?;
                Ok(format!("{} = {}", left_str, right_str))
            }
            Expression::AssignOp(op, left, right) => {
                let left_str = self.generate_expression(left)?;
                let right_str = self.generate_expression(right)?;
                let op_str = self.generate_operator(op);
                Ok(format!("{} {}= {}", left_str, op_str, right_str))
            }
            Expression::Call(func, args) => {
                let func_str = self.generate_expression(func)?;
                let mut args_str = String::new();
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        args_str.push_str(", ");
                    }
                    args_str.push_str(&self.generate_expression(arg)?);
                }
                Ok(format!("{}({})", func_str, args_str))
            }
            Expression::Ternary(cond, then_expr, else_expr) => {
                let cond_str = self.generate_expression(cond)?;
                let then_str = self.generate_expression(then_expr)?;
                let else_str = self.generate_expression(else_expr)?;
                Ok(format!("if ({}) {} else {}", cond_str, then_str, else_str))
            }
            Expression::Index(array, index) => {
                let array_str = self.generate_expression(array)?;
                let index_str = self.generate_expression(index)?;
                Ok(format!("{}[{}]", array_str, index_str))
            }
            Expression::Member(expr, member) => {
                let expr_str = self.generate_expression(expr)?;
                Ok(format!("{}.{}", expr_str, member))
            }
            Expression::PointerMember(expr, member) => {
                let expr_str = self.generate_expression(expr)?;
                Ok(format!("{}.{}.*", expr_str, member)) // Zig uses .* for pointer dereference followed by member access
            }
            Expression::AddressOf(expr) => {
                let expr_str = self.generate_expression(expr)?;
                Ok(format!("&{}", expr_str))
            }
            Expression::Dereference(expr) => {
                let expr_str = self.generate_expression(expr)?;
                Ok(format!("{}.*", expr_str))
            }
            Expression::Cast(target_type, expr) => {
                let type_str = self.generate_type(target_type)?;
                let expr_str = self.generate_expression(expr)?;
                Ok(format!("@as({}, {})", type_str, expr_str))
            }
            Expression::SizeOf(target_type) => {
                let type_str = self.generate_type(target_type)?;
                Ok(format!("@sizeOf({})", type_str))
            }
            _ => Err(CodeGenError::UnsupportedFeature(
                format!("Unsupported expression: {:?}", expr),
            )),
        }
    }

    /// 生成类型
    fn generate_type(&self, typ: &Type) -> CodeGenResult<String> {
        match typ {
            Type::Void => Ok("void".to_string()),
            Type::Bool => Ok("bool".to_string()),
            Type::Char => Ok("u8".to_string()),
            Type::Schar => Ok("i8".to_string()),
            Type::Uchar => Ok("u8".to_string()),
            Type::Short => Ok("i16".to_string()),
            Type::Ushort => Ok("u16".to_string()),
            Type::Int => Ok("i32".to_string()),
            Type::Uint => Ok("u32".to_string()),
            Type::Long => Ok("i64".to_string()),
            Type::Ulong => Ok("u64".to_string()),
            Type::LongLong => Ok("i64".to_string()),
            Type::UlongLong => Ok("u64".to_string()),
            Type::Float => Ok("f32".to_string()),
            Type::Double => Ok("f64".to_string()),
            Type::LongDouble => Ok("f128".to_string()),
            Type::Size => Ok("usize".to_string()),
            Type::Ptrdiff => Ok("isize".to_string()),
            Type::Intptr => Ok("isize".to_string()),
            Type::Uintptr => Ok("usize".to_string()),
            Type::Pointer(inner) => {
                let inner_str = self.generate_type(inner)?;
                Ok(format!("*{}", inner_str))
            }
            Type::Array(inner, size) => {
                let inner_str = self.generate_type(inner)?;
                if let Some(s) = size {
                    Ok(format!("[{}]{}", s, inner_str))
                } else {
                    Ok(format!("[]{}", inner_str))
                }
            }
            Type::Named(name) => Ok(name.clone()),
            _ => Err(CodeGenError::UnsupportedFeature(
                format!("Unsupported type: {:?}", typ),
            )),
        }
    }

    /// 生成二元运算符
    fn generate_operator(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Subtract => "-",
            BinaryOp::Multiply => "*",
            BinaryOp::Divide => "/",
            BinaryOp::Modulo => "%",
            BinaryOp::LessThan => "<",
            BinaryOp::LessThanEqual => "<=",
            BinaryOp::GreaterThan => ">",
            BinaryOp::GreaterThanEqual => ">=",
            BinaryOp::Equal => "==",
            BinaryOp::NotEqual => "!=",
            BinaryOp::LogicalAnd => "and",
            BinaryOp::LogicalOr => "or",
            BinaryOp::BitAnd => "&",
            BinaryOp::BitOr => "|",
            BinaryOp::BitXor => "^",
            BinaryOp::LeftShift => "<<",
            BinaryOp::RightShift => ">>",
        }
    }

    /// 生成一元运算符
    fn generate_unary_operator(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Plus => "+",
            UnaryOp::Minus => "-",
            UnaryOp::Not => "!",
            UnaryOp::BitNot => "~",
            UnaryOp::PreIncrement => "++",
            UnaryOp::PreDecrement => "--",
            UnaryOp::PostIncrement => "", // Postfix operators handled separately
            UnaryOp::PostDecrement => "", // Postfix operators handled separately
        }
    }

    /// 编译 Zig 代码
    fn compile_zig(&self, zig_file: &PathBuf) -> CodeGenResult<()> {
        // 构建 Zig 编译命令
        let mut cmd = Command::new("zig");
        
        match self.config.target {
            ZigTarget::Native => {
                cmd.args(&["build-exe"]);
            }
            ZigTarget::Wasm => {
                cmd.args(&["build-lib", "-target", "wasm32"]);
            }
        }
        
        // 添加优化选项
        if self.config.optimize {
            cmd.args(&["-O2"]);
        }
        
        // 添加调试信息选项
        if self.config.debug_info {
            cmd.args(&["-g"]);
        }
        
        // 添加输入文件
        cmd.arg(zig_file);
        
        // 执行命令
        let output = cmd.output()
            .map_err(|e| CodeGenError::IoError(e))?;
        
        // 检查执行结果
        if !output.status.success() {
            let stderr = str::from_utf8(&output.stderr)
                .unwrap_or("Failed to read stderr");
            return Err(CodeGenError::GenerationError(
                format!("Zig compilation failed: {}", stderr),
            ));
        }
        
        Ok(())
    }
}
