//! 代码生成器头部常量
//!
//! 统一定义各后端的生成文件头部注释

/// 生成器头部基础信息
pub const GENERATOR_NAME: &str = "X-Lang";

/// 各后端的头部注释
pub mod headers {
    /// Zig 后端头部
    pub const ZIG: &str = "// Generated by X-Lang Zig backend";

    /// C 后端头部
    pub const C: &str = "// Generated by X-Lang C backend";

    /// Rust 后端头部
    pub const RUST: &str = "// Generated by X-Lang Rust 1.94 backend";

    /// TypeScript 后端头部
    pub const TYPESCRIPT: &str = "// Generated by X-Lang TypeScript 6.0 backend";

    /// JavaScript 后端头部
    pub const JAVASCRIPT: &str = "// Generated by X-Lang JavaScript backend";

    /// Python 后端头部
    pub const PYTHON: &str = "# -*- coding: utf-8 -*-\n# Generated by X-Lang Python 3.14 backend";

    /// Java 后端头部
    pub const JAVA: &str = "// Generated by X-Lang Java 25 LTS backend";

    /// C# 后端头部
    pub const CSHARP: &str = "// Generated by X-Lang C# 14 backend";

    /// Erlang 后端头部
    pub const ERLANG: &str = "%%% Generated by X-Lang Erlang OTP 28 backend";

    /// Swift 后端头部
    pub const SWIFT: &str = "// Generated by X-Lang Swift 6.3 backend";

    /// LLVM IR 后端头部
    pub const LLVM: &str = "; Generated by X-Lang LLVM backend";

    /// .NET 后端头部
    pub const DOTNET: &str = "// Generated by X-Lang .NET backend";

    /// Native 后端头部
    pub const NATIVE: &str = "// Generated by X-Lang Native backend";
}

/// 生成带版本信息的头部注释
pub fn generate_header_with_version(backend: &str, version: Option<&str>) -> String {
    match version {
        Some(v) => format!(
            "// Generated by {} {} {} backend",
            GENERATOR_NAME, backend, v
        ),
        None => format!("// Generated by {} {} backend", GENERATOR_NAME, backend),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zig_header() {
        assert_eq!(headers::ZIG, "// Generated by X-Lang Zig backend");
    }

    #[test]
    fn test_python_header() {
        assert_eq!(headers::PYTHON, "# -*- coding: utf-8 -*-\n# Generated by X-Lang Python 3.14 backend");
    }

    #[test]
    fn test_generate_with_version() {
        let header = generate_header_with_version("Java", Some("25 LTS"));
        assert_eq!(header, "// Generated by X-Lang Java 25 LTS backend");
    }
}
