// .NET CIL生成器 - .NET后端
// 这个 crate 实现了 x-codegen 的 CodeGenerator trait
// 当前实现为生成 C# 源代码，后续可以升级为直接生成 CIL

use std::fmt::Write;
use std::path::PathBuf;
use x_codegen::{CodeGenerator, CodegenOutput};
use x_parser::ast::{self, ExpressionKind, Program, StatementKind};

/// .NET代码生成器配置
#[derive(Debug, Clone)]
pub struct DotNetConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for DotNetConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

/// .NET代码生成器
pub struct DotNetCodeGenerator {
    config: DotNetConfig,
    indent: usize,
    output: String,
    class_name: String,
}

/// .NET代码生成错误
#[derive(thiserror::Error, Debug)]
pub enum DotNetCodeGenError {
    #[error("代码生成错误: {0}")]
    GenerationError(String),

    #[error("未实现: {0}")]
    Unimplemented(String),

    #[error("IO错误: {0}")]
    IoError(#[from] std::io::Error),

    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
}

pub type DotNetResult<T> = Result<T, DotNetCodeGenError>;

impl DotNetCodeGenerator {
    pub fn new(config: DotNetConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            class_name: "Program".to_string(),
        }
    }

    /// Generate C# source code from AST
    pub fn generate_csharp_from_ast(&mut self, program: &Program) -> DotNetResult<String> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_namespace_start()?;
        self.emit_class_start()?;

        // Emit all declarations
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // Emit main method with top-level statements
        if !program.statements.is_empty() {
            self.emit_main_method(&program.statements)?;
        }

        self.emit_class_end()?;
        self.emit_namespace_end()?;

        Ok(self.output.clone())
    }

    fn emit_header(&mut self) -> DotNetResult<()> {
        self.line("// Generated by X-Lang .NET backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("using System;")?;
        self.line("")?;
        Ok(())
    }

    fn emit_namespace_start(&mut self) -> DotNetResult<()> {
        self.line("namespace XLang")?;
        self.line("{")?;
        self.indent += 1;
        Ok(())
    }

    fn emit_namespace_end(&mut self) -> DotNetResult<()> {
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_class_start(&mut self) -> DotNetResult<()> {
        self.line(&format!("public class {}", self.class_name))?;
        self.line("{")?;
        self.indent += 1;
        Ok(())
    }

    fn emit_class_end(&mut self) -> DotNetResult<()> {
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_declaration(&mut self, decl: &ast::Declaration) -> DotNetResult<()> {
        match decl {
            ast::Declaration::Variable(var) => {
                let csharp_type = if let Some(type_annot) = &var.type_annot {
                    self.type_to_csharp(type_annot)?
                } else if let Some(init) = &var.initializer {
                    self.infer_csharp_type(init)?
                } else {
                    "object".to_string()
                };

                let modifier = if var.is_mutable { "" } else { "readonly " };
                if let Some(init) = &var.initializer {
                    let init_str = self.emit_expr(init)?;
                    self.line(&format!("public static {}{} {} = {};", modifier, csharp_type, var.name, init_str))?;
                } else {
                    self.line(&format!("public static {}{} {};", modifier, csharp_type, var.name))?;
                }
            }
            ast::Declaration::Function(func) => {
                self.emit_function(func)?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_function(&mut self, func: &ast::FunctionDecl) -> DotNetResult<()> {
        let return_type = if let Some(ret_type) = &func.return_type {
            self.type_to_csharp(ret_type)?
        } else {
            "void".to_string()
        };

        let params: Vec<String> = func.parameters.iter()
            .map(|p| {
                let param_type = if let Some(t) = &p.type_annot {
                    self.type_to_csharp(t).unwrap_or_else(|_| "object".to_string())
                } else {
                    "object".to_string()
                };
                format!("{} {}", param_type, p.name)
            })
            .collect();

        let async_kw = if func.is_async { "async " } else { "" };
        self.line(&format!("public static {}{} {}({})", async_kw, return_type, func.name, params.join(", ")))?;
        self.line("{")?;
        self.indent += 1;
        self.emit_block(&func.body)?;
        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_main_method(&mut self, statements: &[ast::Statement]) -> DotNetResult<()> {
        self.line("public static void Main(string[] args)")?;
        self.line("{")?;
        self.indent += 1;

        for stmt in statements {
            self.emit_statement(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> DotNetResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> DotNetResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            StatementKind::Variable(var) => {
                if let Some(init) = &var.initializer {
                    let init_str = self.emit_expr(init)?;
                    let keyword = if var.is_mutable { "var" } else { "var" };
                    self.line(&format!("{} {} = {};", keyword, var.name, init_str))?;
                } else {
                    let csharp_type = if let Some(type_annot) = &var.type_annot {
                        self.type_to_csharp(type_annot)?
                    } else {
                        "object".to_string()
                    };
                    self.line(&format!("{} {};", csharp_type, var.name))?;
                }
            }
            StatementKind::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::If(if_stmt) => {
                let cond = self.emit_expr(&if_stmt.condition)?;
                self.line(&format!("if ({})", cond))?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(&if_stmt.then_block)?;
                self.indent -= 1;
                if let Some(else_block) = &if_stmt.else_block {
                    self.line("} else {")?;
                    self.indent += 1;
                    self.emit_block(else_block)?;
                    self.indent -= 1;
                }
                self.line("}")?;
            }
            StatementKind::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while ({})", cond))?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::For(for_stmt) => {
                let iter = self.emit_expr(&for_stmt.iterator)?;
                let pattern_name = match &for_stmt.pattern {
                    ast::Pattern::Variable(name) => name.clone(),
                    ast::Pattern::Wildcard => "_".to_string(),
                    _ => "item".to_string(),
                };
                self.line(&format!("foreach (var {} in {})", pattern_name, iter))?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(&for_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::Break => self.line("break;")?,
            StatementKind::Continue => self.line("continue;")?,
            StatementKind::Match(match_stmt) => {
                self.emit_match(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try(try_stmt)?;
            }
            StatementKind::DoWhile(do_while) => {
                self.line("while (true)")?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(&do_while.body)?;
                let cond = self.emit_expr(&do_while.condition)?;
                self.line(&format!("if (!({})) break;", cond))?;
                self.indent -= 1;
                self.line("}")?;
            }
        }
        Ok(())
    }

    fn emit_match(&mut self, match_stmt: &ast::MatchStatement) -> DotNetResult<()> {
        let expr = self.emit_expr(&match_stmt.expression)?;
        self.line(&format!("switch ({})", expr))?;
        self.line("{")?;
        self.indent += 1;

        for case in &match_stmt.cases {
            let pattern_str = self.emit_match_pattern(&case.pattern);
            let when_clause = if let Some(guard) = &case.guard {
                let guard_str = self.emit_expr(guard)?;
                format!(" when ({})", guard_str)
            } else {
                String::new()
            };
            self.line(&format!("{}{} =>", pattern_str, when_clause))?;
            self.indent += 1;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
            self.indent -= 1;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_match_pattern(&self, pattern: &ast::Pattern) -> String {
        match pattern {
            ast::Pattern::Wildcard => "_".to_string(),
            ast::Pattern::Variable(name) => name.clone(),
            ast::Pattern::Literal(lit) => self.emit_literal(lit).unwrap_or_else(|_| "_".to_string()),
            ast::Pattern::Or(left, right) => {
                format!("{} or {}", self.emit_match_pattern(left), self.emit_match_pattern(right))
            }
            ast::Pattern::Array(elements) => {
                let elem_strs: Vec<String> = elements.iter().map(|p| self.emit_match_pattern(p)).collect();
                format!("[{}]", elem_strs.join(", "))
            }
            ast::Pattern::Tuple(elements) => {
                let elem_strs: Vec<String> = elements.iter().map(|p| self.emit_match_pattern(p)).collect();
                format!("({})", elem_strs.join(", "))
            }
            _ => "_".to_string(),
        }
    }

    fn emit_try(&mut self, try_stmt: &ast::TryStatement) -> DotNetResult<()> {
        self.line("try")?;
        self.line("{")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;

        for catch in &try_stmt.catch_clauses {
            let catch_var = catch.variable_name.as_deref().unwrap_or("ex");
            if let Some(exc_type) = &catch.exception_type {
                self.line(&format!("catch ({} {})", exc_type, catch_var))?;
            } else {
                self.line(&format!("catch (Exception {})", catch_var))?;
            }
            self.line("{")?;
            self.indent += 1;
            self.emit_block(&catch.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("finally")?;
            self.line("{")?;
            self.indent += 1;
            self.emit_block(finally)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> DotNetResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => self.emit_literal(lit),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ExpressionKind::Unary(op, e) => {
                let inner = self.emit_expr(e)?;
                Ok(self.emit_unaryop(op, &inner))
            }
            ExpressionKind::Call(callee, args) => self.emit_call(callee, args),
            ExpressionKind::Assign(target, value) => {
                let val = self.emit_expr(value)?;
                let t = self.emit_expr(target)?;
                Ok(format!("{} = {}", t, val))
            }
            ExpressionKind::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            ExpressionKind::Array(elements) => {
                let elem_strs: Vec<String> = elements.iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<DotNetResult<Vec<_>>>()?;
                Ok(format!("new object[] {{{}}}", elem_strs.join(", ")))
            }
            ExpressionKind::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            _ => Ok("/* unsupported expression */ null".to_string()),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> DotNetResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(format!("{}", f)),
            ast::Literal::Boolean(b) => Ok(b.to_string().to_lowercase()),
            ast::Literal::String(s) => Ok(format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))),
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null | ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("null".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("({} + {})", l, r),
            ast::BinaryOp::Sub => format!("({} - {})", l, r),
            ast::BinaryOp::Mul => format!("({} * {})", l, r),
            ast::BinaryOp::Div => format!("({} / {})", l, r),
            ast::BinaryOp::Mod => format!("({} % {})", l, r),
            ast::BinaryOp::And => format!("({} && {})", l, r),
            ast::BinaryOp::Or => format!("({} || {})", l, r),
            ast::BinaryOp::Equal => format!("({} == {})", l, r),
            ast::BinaryOp::NotEqual => format!("({} != {})", l, r),
            ast::BinaryOp::Less => format!("({} < {})", l, r),
            ast::BinaryOp::LessEqual => format!("({} <= {})", l, r),
            ast::BinaryOp::Greater => format!("({} > {})", l, r),
            ast::BinaryOp::GreaterEqual => format!("({} >= {})", l, r),
            ast::BinaryOp::Pow => format!("Math.Pow({}, {})", l, r),
            _ => format!("({} /* op */ {})", l, r),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("(-{})", e),
            ast::UnaryOp::Not => format!("(!{})", e),
            ast::UnaryOp::BitNot => format!("(~{})", e),
            ast::UnaryOp::Wait => format!("({})", e),
        }
    }

    fn emit_call(&self, callee: &ast::Expression, args: &[ast::Expression]) -> DotNetResult<String> {
        let arg_strs: Vec<String> = args.iter()
            .map(|a| self.emit_expr(a))
            .collect::<DotNetResult<Vec<_>>>()?;

        if let ExpressionKind::Variable(name) = &callee.node {
            // Check for runtime primitives that should be inlined
            if name.starts_with("__rt_") {
                return self.emit_runtime_inline(name, &arg_strs);
            }

            match name.as_str() {
                "println" => Ok(format!("Console.WriteLine({})", arg_strs.join(", "))),
                "print" => Ok(format!("Console.Write({})", arg_strs.join(", "))),
                _ => Ok(format!("{}({})", name, arg_strs.join(", "))),
            }
        } else {
            let callee_str = self.emit_expr(callee)?;
            Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
        }
    }

    /// Emit inline code for runtime primitives (__rt_* functions)
    fn emit_runtime_inline(&self, name: &str, args: &[String]) -> DotNetResult<String> {
        let result = match name {
            // === File System (System.IO) ===
            "__rt_file_read" => format!("System.IO.File.ReadAllText({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_file_write" => format!("System.IO.File.WriteAllText({}, {})", args.get(0).map(|s| s.as_str()).unwrap_or(""), args.get(1).map(|s| s.as_str()).unwrap_or("")),
            "__rt_file_exists" => format!("System.IO.File.Exists({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_file_delete" => format!("System.IO.File.Delete({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_file_copy" => format!("System.IO.File.Copy({}, {})", args.get(0).map(|s| s.as_str()).unwrap_or(""), args.get(1).map(|s| s.as_str()).unwrap_or("")),
            "__rt_file_move" => format!("System.IO.File.Move({}, {})", args.get(0).map(|s| s.as_str()).unwrap_or(""), args.get(1).map(|s| s.as_str()).unwrap_or("")),
            "__rt_file_size" => format!("new long?(new System.IO.FileInfo({}).Length)", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_dir_create" => format!("System.IO.Directory.CreateDirectory({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_dir_list" => format!("System.IO.Directory.GetFiles({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_dir_exists" => format!("System.IO.Directory.Exists({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_dir_delete" => format!("System.IO.Directory.Delete({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),

            // === Console (Console) ===
            "__rt_print" => format!("Console.Write({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_println" => format!("Console.WriteLine({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_eprint" => format!("Console.Error.Write({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_eprintln" => format!("Console.Error.WriteLine({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_readline" => "Console.ReadLine()".to_string(),

            // === System (Environment) ===
            "__rt_get_env" => format!("Environment.GetEnvironmentVariable({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_args" => "Environment.GetCommandLineArgs()".to_string(),
            "__rt_cwd" => "Environment.CurrentDirectory".to_string(),
            "__rt_chdir" => format!("Directory.SetCurrentDirectory({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_exit" => format!("Environment.Exit({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_timestamp_ms" => "DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()".to_string(),
            "__rt_sleep" => format!("Thread.Sleep({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_getpid" => "System.Diagnostics.Process.GetCurrentProcess().Id".to_string(),

            // === Math (Math.*) ===
            "__rt_sqrt" => format!("Math.Sqrt({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_pow" => format!("Math.Pow({}, {})", args.get(0).map(|s| s.as_str()).unwrap_or(""), args.get(1).map(|s| s.as_str()).unwrap_or("")),
            "__rt_sin" => format!("Math.Sin({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_cos" => format!("Math.Cos({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_tan" => format!("Math.Tan({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_asin" => format!("Math.Asin({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_acos" => format!("Math.Acos({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_atan" => format!("Math.Atan({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_atan2" => format!("Math.Atan2({}, {})", args.get(0).map(|s| s.as_str()).unwrap_or(""), args.get(1).map(|s| s.as_str()).unwrap_or("")),
            "__rt_log" => format!("Math.Log({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_log2" => format!("Math.Log2({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_log10" => format!("Math.Log10({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_exp" => format!("Math.Exp({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_floor" => format!("Math.Floor({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_ceil" => format!("Math.Ceiling({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_round" => format!("Math.Round({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_trunc" => format!("Math.Truncate({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_abs_int" => format!("Math.Abs({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_abs_float" => format!("Math.Abs({})", args.get(0).map(|s| s.as_str()).unwrap_or("")),
            "__rt_min_int" => format!("Math.Min({}, {})", args.get(0).map(|s| s.as_str()).unwrap_or(""), args.get(1).map(|s| s.as_str()).unwrap_or("")),
            "__rt_max_int" => format!("Math.Max({}, {})", args.get(0).map(|s| s.as_str()).unwrap_or(""), args.get(1).map(|s| s.as_str()).unwrap_or("")),

            // Unknown runtime function - return placeholder comment
            _ => format!("/* unknown runtime function: {} */ null", name),
        };
        Ok(result)
    }

    fn type_to_csharp(&self, ty: &ast::Type) -> DotNetResult<String> {
        match ty {
            ast::Type::Int => Ok("int".to_string()),
            ast::Type::Float => Ok("double".to_string()),
            ast::Type::Bool => Ok("bool".to_string()),
            ast::Type::String => Ok("string".to_string()),
            ast::Type::Char => Ok("char".to_string()),
            ast::Type::Unit => Ok("void".to_string()),
            ast::Type::Array(elem) => {
                let elem_type = self.type_to_csharp(elem)?;
                Ok(format!("{}[]", elem_type))
            }
            ast::Type::Option(inner) => {
                // C# doesn't have Option, use nullable type
                self.type_to_csharp(inner)
            }
            ast::Type::Generic(name) | ast::Type::TypeParam(name) | ast::Type::Var(name) => {
                Ok(name.clone())
            }
            _ => Ok("object".to_string()),
        }
    }

    fn infer_csharp_type(&self, expr: &ast::Expression) -> DotNetResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => match lit {
                ast::Literal::Integer(_) => Ok("int".to_string()),
                ast::Literal::Float(_) => Ok("double".to_string()),
                ast::Literal::Boolean(_) => Ok("bool".to_string()),
                ast::Literal::String(_) => Ok("string".to_string()),
                ast::Literal::Char(_) => Ok("char".to_string()),
                _ => Ok("object".to_string()),
            },
            ExpressionKind::Array(_) => Ok("object[]".to_string()),
            _ => Ok("var".to_string()),
        }
    }

    fn line(&mut self, s: &str) -> DotNetResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

impl CodeGenerator for DotNetCodeGenerator {
    type Config = DotNetConfig;
    type Error = DotNetCodeGenError;

    fn new(config: Self::Config) -> Self {
        Self::new(config)
    }

    fn generate_from_ast(&mut self, program: &Program) -> Result<CodegenOutput, Self::Error> {
        let csharp_code = self.generate_csharp_from_ast(program)?;

        let output_file = x_codegen::OutputFile {
            path: std::path::PathBuf::from(format!("{}.cs", self.class_name)),
            content: csharp_code.as_bytes().to_vec(),
            file_type: x_codegen::FileType::DotNetAssembly,
        };

        Ok(CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn generate_from_hir(&mut self, _hir: &x_codegen::x_hir::Hir) -> Result<CodegenOutput, Self::Error> {
        Err(DotNetCodeGenError::Unimplemented(
            ".NET backend HIR generation not yet implemented".to_string(),
        ))
    }

    fn generate_from_pir(&mut self, _pir: &x_codegen::x_perceus::PerceusIR) -> Result<CodegenOutput, Self::Error> {
        Err(DotNetCodeGenError::Unimplemented(
            ".NET backend PIR generation not yet implemented".to_string(),
        ))
    }
}

impl From<x_codegen::CodeGenError> for DotNetCodeGenError {
    fn from(err: x_codegen::CodeGenError) -> Self {
        match err {
            x_codegen::CodeGenError::GenerationError(msg) => {
                DotNetCodeGenError::GenerationError(msg)
            }
            x_codegen::CodeGenError::IoError(e) => DotNetCodeGenError::IoError(e),
            _ => DotNetCodeGenError::GenerationError(format!("{:?}", err)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_codegen::CodeGenerator;
    use x_parser::parser::XParser;

    fn parse(source: &str) -> Program {
        XParser::new().parse(source).expect("parse")
    }

    #[test]
    fn test_config_default() {
        let config = DotNetConfig::default();
        assert!(config.output_dir.is_none());
        assert!(!config.optimize);
        assert!(config.debug_info);
    }

    #[test]
    fn test_config_custom() {
        let config = DotNetConfig {
            output_dir: Some(PathBuf::from("/tmp/output")),
            optimize: true,
            debug_info: false,
        };
        assert_eq!(config.output_dir, Some(PathBuf::from("/tmp/output")));
        assert!(config.optimize);
        assert!(!config.debug_info);
    }

    #[test]
    fn test_generator_new() {
        let config = DotNetConfig::default();
        let _generator = DotNetCodeGenerator::new(config);
    }

    #[test]
    fn test_basic_generation() {
        let program = parse("function main() { println(\"Hello\"); }");
        let mut gen = DotNetCodeGenerator::new(DotNetConfig::default());
        let output = gen.generate_from_ast(&program).expect("generate");
        assert!(!output.files.is_empty());
        let code = String::from_utf8_lossy(&output.files[0].content);
        assert!(code.contains("public class"));
        assert!(code.contains("Console.WriteLine"));
    }

    #[test]
    fn test_variable_generation() {
        let program = parse("function test() { let x = 42; }");
        let mut gen = DotNetCodeGenerator::new(DotNetConfig::default());
        let output = gen.generate_from_ast(&program).expect("generate");
        let code = String::from_utf8_lossy(&output.files[0].content);
        assert!(code.contains("var x = 42") || code.contains("public static"));
    }

    #[test]
    fn test_error_display() {
        let err = DotNetCodeGenError::GenerationError("test error".to_string());
        assert_eq!(err.to_string(), "代码生成错误: test error");

        let err = DotNetCodeGenError::Unimplemented("not implemented".to_string());
        assert_eq!(err.to_string(), "未实现: not implemented");
    }
}
