// Generated by X-Lang Zig backend
// DO NOT EDIT
// 学习 Zig 标准库：直接系统调用，零运行时依赖

const std = @import("std");
const builtin = @import("builtin");

const std = @import("std");
const builtin = @import("builtin");

fn test_math() void {
    // Block 0 (statements: [0])
    // Entry state: {}
    // Exit state: {"c": Moved, "a": Moved, "b": Moved}
}

fn main() void {
    var i_dup = try allocator.dupe(u8, i);
    var i_dup = try allocator.dupe(u8, i);
    var i_dup = try allocator.dupe(u8, i);
    // Block 0 (statements: [0])
    // Entry state: {}
    // Exit state: {"i": Moved}
}

