//! Emacs major mode syntax definition generator

use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::model::SyntaxModel;

/// Generate Emacs major mode syntax definition
pub fn generate(model: &SyntaxModel, output_dir: &Path) -> Result<()> {
    let syntax_content = generate_emacs_syntax(model);

    // Create output directory if it doesn't exist
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }

    let output_path = output_dir.join("x-mode.el");
    fs::write(&output_path, &syntax_content)?;

    Ok(())
}

/// Generate the Emacs Lisp file content
fn generate_emacs_syntax(model: &SyntaxModel) -> String {
    let mut output = String::new();

    // Header
    output.push_str(";;; x-mode.el --- Major mode for X language -*- lexical-binding: t -*-\n\n");
    output.push_str(";; Generated by X Language syntax generator\n");
    output.push_str(";; Version: 0.1.0\n\n");

    // Commentary
    output.push_str(";;; Commentary:\n");
    output.push_str(";; Major mode for editing X language source files.\n\n");

    // Code section
    output.push_str(";;; Code:\n\n");

    // Custom group
    output.push_str("(defgroup x nil\n");
    output.push_str("  \"Major mode for X language.\"\n");
    output.push_str("  :group 'languages)\n\n");

    // Syntax table
    output.push_str("(defvar x-syntax-table\n");
    output.push_str("  (let ((st (make-syntax-table)))\n");
    output.push_str("    ;; Comments\n");
    output.push_str("    (modify-syntax-entry ?/ \". 124\" st)\n");
    output.push_str("    (modify-syntax-entry ?* \". 23b\" st)\n");
    output.push_str("    (modify-syntax-entry ?\\n \">\" st)\n");
    output.push_str("    ;; Strings\n");
    output.push_str("    (modify-syntax-entry ?\\\" \"\\\"\" st)\n");
    output.push_str("    (modify-syntax-entry ?\\' \"\\\"\" st)\n");
    output.push_str("    ;; Operators\n");
    output.push_str("    (modify-syntax-entry ?+ \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?- \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?* \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?/ \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?% \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?< \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?> \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?= \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?! \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?& \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?| \".\" st)\n");
    output.push_str("    (modify-syntax-entry ?^ \".\" st)\n");
    output.push_str("    ;; Parentheses\n");
    output.push_str("    (modify-syntax-entry ?\\( \"()\" st)\n");
    output.push_str("    (modify-syntax-entry ?\\) \")(\" st)\n");
    output.push_str("    (modify-syntax-entry ?\\[ \"(]\" st)\n");
    output.push_str("    (modify-syntax-entry ?\\] \") [\" st)\n");
    output.push_str("    (modify-syntax-entry ?{ \"(}\" st)\n");
    output.push_str("    (modify-syntax-entry ?} \"){ \" st)\n");
    output.push_str("    st)\n");
    output.push_str("  \"Syntax table for X mode.\")\n\n");

    // Keywords
    output.push_str("(defvar x-keywords\n");
    output.push_str("  '(");
    if model.keywords.is_empty() {
        output.push_str("\n    \"needs\" \"given\" \"wait\" \"when\" \"is\" \"can\" \"atomic\"\n");
        output.push_str("    \"let\" \"mut\" \"val\" \"var\" \"const\" \"function\" \"async\"\n");
        output.push_str("    \"class\" \"trait\" \"if\" \"else\" \"while\" \"for\" \"match\"\n");
        output.push_str("    \"try\" \"catch\" \"finally\" \"return\" \"break\" \"continue\"\n");
        output.push_str("    \"import\" \"export\" \"module\"\n");
    } else {
        for keyword in &model.keywords {
            output.push_str(&format!("\n    \"{}\"", escape_elisp_string(keyword)));
        }
    }
    output.push_str(")\n");
    output.push_str("  \"X language keywords.\")\n\n");

    // Types
    output.push_str("(defvar x-types\n");
    output.push_str("  '(");
    if model.types.is_empty() {
        output.push_str("\n    \"Int\" \"Float\" \"Bool\" \"String\" \"Char\" \"Unit\"\n");
        output.push_str("    \"Option\" \"Result\" \"Array\"\n");
    } else {
        for t in &model.types {
            output.push_str(&format!("\n    \"{}\"", escape_elisp_string(t)));
        }
    }
    output.push_str(")\n");
    output.push_str("  \"X language built-in types.\")\n\n");

    // Builtins
    if !model.builtins.is_empty() {
        output.push_str("(defvar x-builtins\n");
        output.push_str("  '(");
        for builtin in &model.builtins {
            output.push_str(&format!("\n    \"{}\"", escape_elisp_string(builtin)));
        }
        output.push_str(")\n");
        output.push_str("  \"X language built-in functions.\")\n\n");
    }

    // Font lock
    output.push_str("(defvar x-font-lock-keywords\n");
    output.push_str("  `((,\"\\\\\\b\\\\w+\\\\b\\\\\");, 1 'font-lock-function-name-face)\n");
    output.push_str("    (,\"\\\\\\b\\\\([0-9]+\\\\(\\\\.[0-9]+\\\\)?\\\\)\\\\b\\\\, 1 'font-lock-constant-face)\n");
    output.push_str("    (, (regexp-opt x-keywords 'words) . font-lock-keyword-face)\n");
    output.push_str("    (, (regexp-opt x-types 'words) . font-lock-type-face)\n");
    if !model.builtins.is_empty() {
        output.push_str("    (, (regexp-opt x-builtins 'words) . font-lock-builtin-face)\n");
    }
    output.push_str(
        "    (,\"\\\\\\b\\\\(true\\\\|false\\\\)\\\\b\\\\, 1 'font-lock-constant-face)\n",
    );
    output.push_str(
        "    (,\"\\\\\\b\\\\([A-Z][a-zA-Z0-9_]*\\\\)\\\\b\\\\, 1 'font-lock-type-face)\n",
    );
    output.push_str("    (,\"\\\\\\b\\\\([a-z_][a-zA-Z0-9_]*\\\\)\\\\b\\\\, 1 'font-lock-variable-name-face))\n");
    output.push_str("  \"Font lock keywords for X mode.\")\n\n");

    // Indentation
    output.push_str("(defvar x-indent-offset 4\n");
    output.push_str("  \"Indentation offset for X mode.\")\n\n");

    output.push_str("(defun x-indent-line ()\n");
    output.push_str("  \"Indent current line for X mode.\"\n");
    output.push_str("  (let ((indent (calculate-x-indent)))\n");
    output.push_str("    (if (= (current-indentation) indent)\n");
    output.push_str("        (if (> (current-column) indent)\n");
    output.push_str("            (move-to-column indent))\n");
    output.push_str("      (beginning-of-line)\n");
    output.push_str("      (delete-horizontal-space)\n");
    output.push_str("      (indent-to indent))))\n\n");

    output.push_str("(defun calculate-x-indent ()\n");
    output.push_str("  \"Calculate indentation for current line.\"\n");
    output.push_str("  (save-excursion\n");
    output.push_str("    (beginning-of-line)\n");
    output.push_str("    (if (bobp) 0\n");
    output.push_str("      (let ((not-indented t) cur-indent)\n");
    output.push_str("        (forward-line -1)\n");
    output.push_str("        (setq cur-indent (current-indentation))\n");
    output.push_str("        (while not-indented\n");
    output.push_str("          (if (looking-at \"^[[:space:]]*\\\\}\")\n");
    output.push_str("              (progn\n");
    output.push_str("                (setq cur-indent (- cur-indent x-indent-offset))\n");
    output.push_str("                (setq not-indented nil))\n");
    output.push_str("            (if (looking-at \"^[[:space:]]*[{(]\")\n");
    output.push_str("                (progn\n");
    output.push_str("                  (setq cur-indent (+ cur-indent x-indent-offset))\n");
    output.push_str("                  (setq not-indented nil))\n");
    output.push_str("              (if (bobp)\n");
    output.push_str("                  (setq not-indented nil)\n");
    output.push_str("                (forward-line -1)))))\n");
    output.push_str("        cur-indent))))\n\n");

    // Mode definition
    output.push_str(";;;###autoload\n");
    output.push_str("(define-derived-mode x-mode prog-mode \"X\"\n");
    output.push_str("  \"Major mode for editing X language code.\"\n");
    output.push_str("  :syntax-table x-syntax-table\n");
    output.push_str("  (setq-local comment-start \"// \")\n");
    output.push_str("  (setq-local comment-end \"\")\n");
    output.push_str("  (setq-local indent-line-function #'x-indent-line)\n");
    output.push_str("  (setq font-lock-defaults '(x-font-lock-keywords)))\n\n");

    // Auto-mode
    output.push_str(";;;###autoload\n");
    output.push_str("(add-to-list 'auto-mode-alist '(\"\\\\\\.x\\\\\\'\" . x-mode))\n\n");

    // Provide
    output.push_str("(provide 'x-mode)\n\n");
    output.push_str(";;; x-mode.el ends here\n");

    output
}

/// Escape special characters for Emacs Lisp strings
fn escape_elisp_string(s: &str) -> &str {
    // For simplicity, we assume strings don't need escaping
    // In a full implementation, we'd handle " and \ characters
    s
}
