//! JetBrains IDE syntax definition generator

use std::path::Path;
use std::fs;

use anyhow::Result;

use crate::model::SyntaxModel;

/// Generate JetBrains IDE syntax definition
pub fn generate(model: &SyntaxModel, output_dir: &Path) -> Result<()> {
    let syntax_content = generate_jetbrains_syntax(model);

    // Create output directory if it doesn't exist
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }

    let output_path = output_dir.join(format!("{}.xml", model.language_name.to_lowercase()));
    fs::write(&output_path, &syntax_content)?;

    Ok(())
}

/// Generate the JetBrains XML file content
fn generate_jetbrains_syntax(model: &SyntaxModel) -> String {
    let mut output = String::new();

    // XML Header
    output.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    output.push_str("<!-- Generated by X Language syntax generator -->\n");
    output.push_str("<!-- JetBrains (IntelliJ IDEA) syntax definition -->\n\n");

    // File type definition
    output.push_str("<fileType name=\"");
    output.push_str(&model.language_name);
    output.push_str("\" language=\"");
    output.push_str(&model.language_name);
    output.push_str("\" extensions=\"");
    output.push_str(&model.file_extensions.join(";"));
    output.push_str("\">\n\n");

    // Syntax highlighter
    output.push_str("  <highlighter>\n");

    // Keywords
    output.push_str("    <keywords>\n");
    if model.keywords.is_empty() {
        output.push_str("      <keyword>needs</keyword>\n");
        output.push_str("      <keyword>given</keyword>\n");
        output.push_str("      <keyword>wait</keyword>\n");
        output.push_str("      <keyword>when</keyword>\n");
        output.push_str("      <keyword>is</keyword>\n");
        output.push_str("      <keyword>can</keyword>\n");
        output.push_str("      <keyword>atomic</keyword>\n");
        output.push_str("      <keyword>let</keyword>\n");
        output.push_str("      <keyword>mut</keyword>\n");
        output.push_str("      <keyword>val</keyword>\n");
        output.push_str("      <keyword>var</keyword>\n");
        output.push_str("      <keyword>const</keyword>\n");
        output.push_str("      <keyword>function</keyword>\n");
        output.push_str("      <keyword>async</keyword>\n");
        output.push_str("      <keyword>class</keyword>\n");
        output.push_str("      <keyword>trait</keyword>\n");
        output.push_str("      <keyword>if</keyword>\n");
        output.push_str("      <keyword>else</keyword>\n");
        output.push_str("      <keyword>while</keyword>\n");
        output.push_str("      <keyword>for</keyword>\n");
        output.push_str("      <keyword>match</keyword>\n");
        output.push_str("      <keyword>try</keyword>\n");
        output.push_str("      <keyword>catch</keyword>\n");
        output.push_str("      <keyword>finally</keyword>\n");
        output.push_str("      <keyword>return</keyword>\n");
        output.push_str("      <keyword>break</keyword>\n");
        output.push_str("      <keyword>continue</keyword>\n");
        output.push_str("      <keyword>import</keyword>\n");
        output.push_str("      <keyword>export</keyword>\n");
        output.push_str("      <keyword>module</keyword>\n");
    } else {
        for keyword in &model.keywords {
            output.push_str(&format!("      <keyword>{}</keyword>\n", escape_xml(keyword)));
        }
    }
    output.push_str("    </keywords>\n\n");

    // Types
    output.push_str("    <types>\n");
    if model.types.is_empty() {
        output.push_str("      <type>Int</type>\n");
        output.push_str("      <type>Float</type>\n");
        output.push_str("      <type>Bool</type>\n");
        output.push_str("      <type>String</type>\n");
        output.push_str("      <type>Char</type>\n");
        output.push_str("      <type>Unit</type>\n");
        output.push_str("      <type>Option</type>\n");
        output.push_str("      <type>Result</type>\n");
        output.push_str("      <type>Array</type>\n");
    } else {
        for t in &model.types {
            output.push_str(&format!("      <type>{}</type>\n", escape_xml(t)));
        }
    }
    output.push_str("    </types>\n\n");

    // Built-ins
    if !model.builtins.is_empty() {
        output.push_str("    <builtins>\n");
        for builtin in &model.builtins {
            output.push_str(&format!("      <builtin>{}</builtin>\n", escape_xml(builtin)));
        }
        output.push_str("    </builtins>\n\n");
    }

    // Operators
    output.push_str("    <operators>\n");
    if model.operators.is_empty() {
        output.push_str("      <operator>+</operator>\n");
        output.push_str("      <operator>-</operator>\n");
        output.push_str("      <operator>*</operator>\n");
        output.push_str("      <operator>/</operator>\n");
        output.push_str("      <operator>%</operator>\n");
        output.push_str("      <operator>==</operator>\n");
        output.push_str("      <operator>!=</operator>\n");
        output.push_str("      <operator>&lt;</operator>\n");
        output.push_str("      <operator>&gt;</operator>\n");
        output.push_str("      <operator>&lt;=</operator>\n");
        output.push_str("      <operator>&gt;=</operator>\n");
        output.push_str("      <operator>&amp;&amp;</operator>\n");
        output.push_str("      <operator>||</operator>\n");
        output.push_str("      <operator>!</operator>\n");
        output.push_str("      <operator>=&gt;</operator>\n");
        output.push_str("      <operator>-&gt;</operator>\n");
    } else {
        for op in &model.operators {
            output.push_str(&format!("      <operator>{}</operator>\n", escape_xml(op)));
        }
    }
    output.push_str("    </operators>\n\n");

    // Comments
    output.push_str("    <comments>\n");
    output.push_str(&format!("      <line>{}</line>\n", escape_xml(&model.comment.line)));
    output.push_str(&format!("      <blockStart>{}</blockStart>\n", escape_xml(&model.comment.block_start)));
    output.push_str(&format!("      <blockEnd>{}</blockEnd>\n", escape_xml(&model.comment.block_end)));
    output.push_str("    </comments>\n\n");

    // Strings
    output.push_str("    <strings>\n");
    output.push_str("      <string>\"</string>\n");
    output.push_str("      <char>'</char>\n");
    output.push_str("      <multiline>\"\"\"</multiline>\n");
    output.push_str("    </strings>\n");

    output.push_str("  </highlighter>\n");
    output.push_str("</fileType>\n");

    output
}

/// Escape special XML characters
fn escape_xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}
