//! Neovim Tree-sitter syntax definition generator

use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::model::SyntaxModel;

/// Generate Neovim Tree-sitter syntax definition
pub fn generate(model: &SyntaxModel, output_dir: &Path) -> Result<()> {
    // Create output directory if it doesn't exist
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }

    // Generate grammar.js for Tree-sitter
    let grammar_content = generate_grammar_js(model);
    let grammar_path = output_dir.join("grammar.js");
    fs::write(&grammar_path, &grammar_content)?;

    // Generate package.json
    let package_content = generate_package_json(model);
    let package_path = output_dir.join("package.json");
    fs::write(&package_path, &package_content)?;

    Ok(())
}

/// Generate the Tree-sitter grammar.js file
fn generate_grammar_js(model: &SyntaxModel) -> String {
    let mut output = String::new();

    output.push_str("// Tree-sitter grammar for X language\n");
    output.push_str("// Generated by X Language syntax generator\n\n");

    output.push_str("module.exports = grammar({\n");
    output.push_str("  name: 'x',\n\n");

    // Keywords
    output.push_str("  word: $ => $.identifier,\n\n");

    // Extras (whitespace and comments)
    output.push_str("  extras: $ => [\n");
    output.push_str("    /\\s/,\n");
    output.push_str("    $.comment,\n");
    output.push_str("  ],\n\n");

    // Rules
    output.push_str("  rules: {\n");

    // Program
    output.push_str("    source_file: $ => repeat($._definition),\n\n");

    // Definitions
    output.push_str("    _definition: $ => choice(\n");
    output.push_str("      $.function_definition,\n");
    output.push_str("      $.variable_declaration,\n");
    output.push_str("      $.class_definition,\n");
    output.push_str("      $.trait_definition,\n");
    output.push_str("      $.import_statement,\n");
    output.push_str("      $.export_statement,\n");
    output.push_str("    ),\n\n");

    // Function definition
    output.push_str("    function_definition: $ => seq(\n");
    output.push_str("      optional('async'),\n");
    output.push_str("      choice('fn', 'function'),\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      $.parameters,\n");
    output.push_str("      optional(seq('->', $._type)),\n");
    output.push_str("      $.block,\n");
    output.push_str("    ),\n\n");

    // Parameters
    output.push_str("    parameters: $ => seq(\n");
    output.push_str("      '(',\n");
    output.push_str("      commaSep($.parameter),\n");
    output.push_str("      ')',\n");
    output.push_str("    ),\n\n");

    output.push_str("    parameter: $ => seq(\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      optional(seq(':', $._type)),\n");
    output.push_str("    ),\n\n");

    // Variable declaration
    output.push_str("    variable_declaration: $ => seq(\n");
    output.push_str("      choice('let', 'var', 'const', 'val'),\n");
    output.push_str("      optional('mut'),\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      optional(seq(':', $._type)),\n");
    output.push_str("      optional(seq('=', $._expression)),\n");
    output.push_str("    ),\n\n");

    // Class definition
    output.push_str("    class_definition: $ => seq(\n");
    output.push_str("      'class',\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      optional($.type_parameters),\n");
    output.push_str("      optional(seq(':', commaSep1($.type_name))),\n");
    output.push_str("      $.class_body,\n");
    output.push_str("    ),\n\n");

    // Trait definition
    output.push_str("    trait_definition: $ => seq(\n");
    output.push_str("      'trait',\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      optional($.type_parameters),\n");
    output.push_str("      $.trait_body,\n");
    output.push_str("    ),\n\n");

    // Import statement
    output.push_str("    import_statement: $ => seq(\n");
    output.push_str("      'import',\n");
    output.push_str("      $.import_path,\n");
    output.push_str("    ),\n\n");

    output.push_str("    import_path: $ => seq(\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      repeat(seq('.', $.identifier)),\n");
    output.push_str("    ),\n\n");

    // Export statement
    output.push_str("    export_statement: $ => seq(\n");
    output.push_str("      'export',\n");
    output.push_str("      $._definition,\n");
    output.push_str("    ),\n\n");

    // Types
    output.push_str("    _type: $ => choice(\n");
    output.push_str("      $.primitive_type,\n");
    output.push_str("      $.type_name,\n");
    output.push_str("      $.generic_type,\n");
    output.push_str("      $.optional_type,\n");
    output.push_str("      $.result_type,\n");
    output.push_str("      $.function_type,\n");
    output.push_str("      $.tuple_type,\n");
    output.push_str("      $.array_type,\n");
    output.push_str("    ),\n\n");

    output.push_str("    primitive_type: $ => choice(\n");
    if model.types.is_empty() {
        output.push_str("      'Int', 'Float', 'Bool', 'String', 'Char', 'Unit', 'Never',\n");
    } else {
        output.push_str("      ");
        for (i, t) in model.types.iter().enumerate() {
            if i > 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("'{}'", t));
        }
        output.push_str(",\n");
    }
    output.push_str("    ),\n\n");

    output.push_str("    type_name: $ => $.identifier,\n\n");

    output.push_str("    generic_type: $ => seq(\n");
    output.push_str("      $.type_name,\n");
    output.push_str("      '<',\n");
    output.push_str("      commaSep1($._type),\n");
    output.push_str("      '>',\n");
    output.push_str("    ),\n\n");

    output.push_str("    optional_type: $ => seq(\n");
    output.push_str("      'Option',\n");
    output.push_str("      '<',\n");
    output.push_str("      $._type,\n");
    output.push_str("      '>',\n");
    output.push_str("    ),\n\n");

    output.push_str("    result_type: $ => seq(\n");
    output.push_str("      'Result',\n");
    output.push_str("      '<',\n");
    output.push_str("      $._type,\n");
    output.push_str("      ',',\n");
    output.push_str("      $._type,\n");
    output.push_str("      '>',\n");
    output.push_str("    ),\n\n");

    output.push_str("    function_type: $ => seq(\n");
    output.push_str("      $.parameters,\n");
    output.push_str("      '->',\n");
    output.push_str("      $._type,\n");
    output.push_str("    ),\n\n");

    output.push_str("    tuple_type: $ => seq(\n");
    output.push_str("      '(',\n");
    output.push_str("      commaSep1($._type),\n");
    output.push_str("      ')',\n");
    output.push_str("    ),\n\n");

    output.push_str("    array_type: $ => seq(\n");
    output.push_str("      '[',\n");
    output.push_str("      $._type,\n");
    output.push_str("      ';',\n");
    output.push_str("      optional($._expression),\n");
    output.push_str("      ']',\n");
    output.push_str("    ),\n\n");

    // Expressions
    output.push_str("    _expression: $ => choice(\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      $.literal,\n");
    output.push_str("      $.binary_expression,\n");
    output.push_str("      $.unary_expression,\n");
    output.push_str("      $.call_expression,\n");
    output.push_str("      $.member_expression,\n");
    output.push_str("      $.index_expression,\n");
    output.push_str("      $.lambda_expression,\n");
    output.push_str("      $.if_expression,\n");
    output.push_str("      $.match_expression,\n");
    output.push_str("      $.block,\n");
    output.push_str("    ),\n\n");

    output.push_str("    literal: $ => choice(\n");
    output.push_str("      $.integer_literal,\n");
    output.push_str("      $.float_literal,\n");
    output.push_str("      $.string_literal,\n");
    output.push_str("      $.char_literal,\n");
    output.push_str("      $.boolean_literal,\n");
    output.push_str("      $.null_literal,\n");
    output.push_str("    ),\n\n");

    output.push_str("    integer_literal: $ => /\\d[\\d_]*/,\n");
    output.push_str("    float_literal: $ => /\\d[\\d_]*\\.\\d[\\d_]*([eE][+-]?\\d+)?/,\n");
    output.push_str(
        "    string_literal: $ => seq('\"', repeat(choice(/[^\"\\\\]+/, /\\\\./)), '\"'),\n",
    );
    output.push_str("    char_literal: $ => seq(\"'\", choice(/[^'\\\\]/, /\\\\./), \"'\"),\n");
    output.push_str("    boolean_literal: $ => choice('true', 'false'),\n");
    output.push_str("    null_literal: $ => 'null',\n\n");

    output.push_str("    binary_expression: $ => choice(\n");
    output.push_str("      prec.left(2, seq($._expression, '*', $._expression)),\n");
    output.push_str("      prec.left(2, seq($._expression, '/', $._expression)),\n");
    output.push_str("      prec.left(2, seq($._expression, '%', $._expression)),\n");
    output.push_str("      prec.left(1, seq($._expression, '+', $._expression)),\n");
    output.push_str("      prec.left(1, seq($._expression, '-', $._expression)),\n");
    output.push_str("      prec.left(0, seq($._expression, '==', $._expression)),\n");
    output.push_str("      prec.left(0, seq($._expression, '!=', $._expression)),\n");
    output.push_str("      prec.left(0, seq($._expression, '<', $._expression)),\n");
    output.push_str("      prec.left(0, seq($._expression, '>', $._expression)),\n");
    output.push_str("      prec.left(0, seq($._expression, '<=', $._expression)),\n");
    output.push_str("      prec.left(0, seq($._expression, '>=', $._expression)),\n");
    output.push_str("      prec.left(-1, seq($._expression, '&&', $._expression)),\n");
    output.push_str("      prec.left(-2, seq($._expression, '||', $._expression)),\n");
    output.push_str("    ),\n\n");

    output.push_str("    unary_expression: $ => choice(\n");
    output.push_str("      seq('!', $._expression),\n");
    output.push_str("      seq('-', $._expression),\n");
    output.push_str("    ),\n\n");

    output.push_str("    call_expression: $ => seq(\n");
    output.push_str("      $._expression,\n");
    output.push_str("      $.arguments,\n");
    output.push_str("    ),\n\n");

    output.push_str("    arguments: $ => seq(\n");
    output.push_str("      '(',\n");
    output.push_str("      commaSep($._expression),\n");
    output.push_str("      ')',\n");
    output.push_str("    ),\n\n");

    output.push_str("    member_expression: $ => seq(\n");
    output.push_str("      $._expression,\n");
    output.push_str("      '.',\n");
    output.push_str("      $.identifier,\n");
    output.push_str("    ),\n\n");

    output.push_str("    index_expression: $ => seq(\n");
    output.push_str("      $._expression,\n");
    output.push_str("      '[',\n");
    output.push_str("      $._expression,\n");
    output.push_str("      ']',\n");
    output.push_str("    ),\n\n");

    output.push_str("    lambda_expression: $ => seq(\n");
    output.push_str("      optional('async'),\n");
    output.push_str("      $.parameters,\n");
    output.push_str("      optional(seq('->', $._type)),\n");
    output.push_str("      '=>',\n");
    output.push_str("      choice($.block, $._expression),\n");
    output.push_str("    ),\n\n");

    output.push_str("    if_expression: $ => seq(\n");
    output.push_str("      'if',\n");
    output.push_str("      $._expression,\n");
    output.push_str("      $.block,\n");
    output.push_str("      optional(seq('else', choice($.block, $.if_expression))),\n");
    output.push_str("    ),\n\n");

    output.push_str("    match_expression: $ => seq(\n");
    output.push_str("      'match',\n");
    output.push_str("      $._expression,\n");
    output.push_str("      $.match_body,\n");
    output.push_str("    ),\n\n");

    output.push_str("    match_body: $ => seq(\n");
    output.push_str("      '{',\n");
    output.push_str("      repeat($.match_arm),\n");
    output.push_str("      '}',\n");
    output.push_str("    ),\n\n");

    output.push_str("    match_arm: $ => seq(\n");
    output.push_str("      $._pattern,\n");
    output.push_str("      '=>',\n");
    output.push_str("      choice($._expression, $.block),\n");
    output.push_str("      optional(','),\n");
    output.push_str("    ),\n\n");

    // Patterns
    output.push_str("    _pattern: $ => choice(\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      $.literal,\n");
    output.push_str("      $.wildcard_pattern,\n");
    output.push_str("      $.tuple_pattern,\n");
    output.push_str("    ),\n\n");

    output.push_str("    wildcard_pattern: $ => '_',\n\n");

    output.push_str("    tuple_pattern: $ => seq(\n");
    output.push_str("      '(',\n");
    output.push_str("      commaSep1($._pattern),\n");
    output.push_str("      ')',\n");
    output.push_str("    ),\n\n");

    // Block
    output.push_str("    block: $ => seq(\n");
    output.push_str("      '{',\n");
    output.push_str("      repeat($._statement),\n");
    output.push_str("      '}',\n");
    output.push_str("    ),\n\n");

    // Statements
    output.push_str("    _statement: $ => choice(\n");
    output.push_str("      $.variable_declaration,\n");
    output.push_str("      $.expression_statement,\n");
    output.push_str("      $.if_expression,\n");
    output.push_str("      $.while_statement,\n");
    output.push_str("      $.for_statement,\n");
    output.push_str("      $.return_statement,\n");
    output.push_str("      $.break_statement,\n");
    output.push_str("      $.continue_statement,\n");
    output.push_str("    ),\n\n");

    output.push_str("    expression_statement: $ => seq(\n");
    output.push_str("      $._expression,\n");
    output.push_str("      optional(';'),\n");
    output.push_str("    ),\n\n");

    output.push_str("    while_statement: $ => seq(\n");
    output.push_str("      'while',\n");
    output.push_str("      $._expression,\n");
    output.push_str("      $.block,\n");
    output.push_str("    ),\n\n");

    output.push_str("    for_statement: $ => seq(\n");
    output.push_str("      'for',\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      'in',\n");
    output.push_str("      $._expression,\n");
    output.push_str("      $.block,\n");
    output.push_str("    ),\n\n");

    output.push_str("    return_statement: $ => seq(\n");
    output.push_str("      'return',\n");
    output.push_str("      optional($._expression),\n");
    output.push_str("    ),\n\n");

    output.push_str("    break_statement: $ => 'break',\n");
    output.push_str("    continue_statement: $ => 'continue',\n\n");

    // Comment
    output.push_str("    comment: $ => choice(\n");
    output.push_str("      seq('//', /.*/),\n");
    output.push_str("      seq('/*', /[^*]*\\*+([^/*][^*]*\\*+)*/),\n");
    output.push_str("    ),\n\n");

    // Identifier
    output.push_str("    identifier: $ => /[a-zA-Z_][a-zA-Z0-9_]*/,\n\n");

    // Type parameters
    output.push_str("    type_parameters: $ => seq(\n");
    output.push_str("      '<',\n");
    output.push_str("      commaSep1($.type_parameter),\n");
    output.push_str("      '>',\n");
    output.push_str("    ),\n\n");

    output.push_str("    type_parameter: $ => $.identifier,\n\n");

    // Class and trait bodies
    output.push_str("    class_body: $ => seq(\n");
    output.push_str("      '{',\n");
    output.push_str("      repeat($.class_member),\n");
    output.push_str("      '}',\n");
    output.push_str("    ),\n\n");

    output.push_str("    class_member: $ => choice(\n");
    output.push_str("      $.field_declaration,\n");
    output.push_str("      $.method_definition,\n");
    output.push_str("    ),\n\n");

    output.push_str("    field_declaration: $ => seq(\n");
    output.push_str("      optional('pub'),\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      ':',\n");
    output.push_str("      $._type,\n");
    output.push_str("      optional(seq('=', $._expression)),\n");
    output.push_str("    ),\n\n");

    output.push_str("    method_definition: $ => seq(\n");
    output.push_str("      optional('pub'),\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      $.parameters,\n");
    output.push_str("      optional(seq('->', $._type)),\n");
    output.push_str("      $.block,\n");
    output.push_str("    ),\n\n");

    output.push_str("    trait_body: $ => seq(\n");
    output.push_str("      '{',\n");
    output.push_str("      repeat($.trait_member),\n");
    output.push_str("      '}',\n");
    output.push_str("    ),\n\n");

    output.push_str("    trait_member: $ => choice(\n");
    output.push_str("      $.method_signature,\n");
    output.push_str("      $.method_definition,\n");
    output.push_str("    ),\n\n");

    output.push_str("    method_signature: $ => seq(\n");
    output.push_str("      $.identifier,\n");
    output.push_str("      $.parameters,\n");
    output.push_str("      optional(seq('->', $._type)),\n");
    output.push_str("    ),\n");

    output.push_str("  },\n");
    output.push_str("});\n\n");

    // Helper functions
    output.push_str("function commaSep(rule) {\n");
    output.push_str("  return optional(seq(rule, repeat(seq(',', rule))));\n");
    output.push_str("}\n\n");

    output.push_str("function commaSep1(rule) {\n");
    output.push_str("  return seq(rule, repeat(seq(',', rule)));\n");
    output.push_str("}\n");

    output
}

/// Generate the package.json file for Tree-sitter
fn generate_package_json(model: &SyntaxModel) -> String {
    let mut output = String::new();

    output.push_str("{\n");
    output.push_str("  \"name\": \"tree-sitter-x\",\n");
    output.push_str("  \"version\": \"0.1.0\",\n");
    output.push_str("  \"description\": \"Tree-sitter grammar for X language\",\n");
    output.push_str("  \"main\": \"bindings/node\",\n");
    output.push_str("  \"keywords\": [\n");
    output.push_str("    \"parser\",\n");
    output.push_str("    \"tree-sitter\",\n");
    output.push_str("    \"x-language\"\n");
    output.push_str("  ],\n");
    output.push_str("  \"author\": \"X Language Team\",\n");
    output.push_str("  \"license\": \"MIT\",\n");
    output.push_str("  \"dependencies\": {\n");
    output.push_str("    \"nan\": \"^2.18.0\"\n");
    output.push_str("  },\n");
    output.push_str("  \"devDependencies\": {\n");
    output.push_str("    \"tree-sitter-cli\": \"^0.20.8\"\n");
    output.push_str("  },\n");
    output.push_str("  \"tree-sitter\": [\n");
    output.push_str("    {\n");
    output.push_str("      \"scope\": \"source.x\",\n");
    output.push_str("      \"file-types\": [\n");

    if model.file_extensions.is_empty() {
        output.push_str("        \"x\"\n");
    } else {
        for (i, ext) in model.file_extensions.iter().enumerate() {
            if i > 0 {
                output.push_str(",\n");
            }
            output.push_str(&format!("        \"{}\"", ext));
        }
        output.push('\n');
    }

    output.push_str("      ],\n");
    output.push_str("      \"injection-regex\": \"^(x|X)$\"\n");
    output.push_str("    }\n");
    output.push_str("  ]\n");
    output.push_str("}\n");

    output
}
