//! Sublime Text syntax definition generator

use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::model::SyntaxModel;

/// Generate Sublime Text syntax definition
pub fn generate(model: &SyntaxModel, output_dir: &Path) -> Result<()> {
    let syntax_content = generate_sublime_syntax(model);

    // Create output directory if it doesn't exist
    if !output_dir.exists() {
        fs::create_dir_all(output_dir)?;
    }

    let output_path = output_dir.join(format!(
        "{}.sublime-syntax",
        model.language_name.to_lowercase()
    ));
    fs::write(&output_path, &syntax_content)?;

    Ok(())
}

/// Generate the .sublime-syntax file content
fn generate_sublime_syntax(model: &SyntaxModel) -> String {
    let mut output = String::new();

    // Header
    output.push_str("%YAML 1.2\n");
    output.push_str("---\n");
    output.push_str("# Generated by X Language syntax generator\n");
    output.push_str("# Sublime Text syntax definition\n\n");

    // Basic metadata
    output.push_str(&format!("name: {}\n", model.language_name));
    output.push_str(&format!(
        "file_extensions: [{}]\n",
        model.file_extensions.join(", ")
    ));
    output.push_str("scope: source.x\n");
    output.push_str("version: 2\n\n");

    // Contexts
    output.push_str("contexts:\n");
    output.push_str("  main:\n");

    // Include various contexts
    output.push_str("    - include: comments\n");
    output.push_str("    - include: strings\n");
    output.push_str("    - include: numbers\n");
    output.push_str("    - include: keywords\n");
    output.push_str("    - include: types\n");
    output.push_str("    - include: operators\n");
    output.push_str("    - include: identifiers\n");
    output.push_str("    - include: punctuation\n");
    output.push('\n');

    // Keywords context
    output.push_str("  keywords:\n");
    if !model.keywords.is_empty() {
        let keywords_pattern = model.keywords.join("|");
        output.push_str(&format!("    - match: '\\b({})\\b'\n", keywords_pattern));
        output.push_str("      scope: keyword.control.x\n");
    } else {
        output.push_str("    - match: '\\b(needs|given|wait|when|is|can|atomic|let|mut|val|var|const|function|async|class|trait|type|import|export|module|if|else|while|for|match|try|catch|finally|return|break|continue|do)\\b'\n");
        output.push_str("      scope: keyword.control.x\n");
    }
    output.push('\n');

    // Types context
    output.push_str("  types:\n");
    if !model.types.is_empty() {
        let types_pattern = model.types.join("|");
        output.push_str(&format!("    - match: '\\b({})\\b'\n", types_pattern));
        output.push_str("      scope: storage.type.x\n");
    } else {
        output.push_str("    - match: '\\b(Int|Float|Bool|String|Char|Unit|Never|Option|Result|Array|Dict|Set|Map)\\b'\n");
        output.push_str("      scope: storage.type.x\n");
    }
    output.push('\n');

    // Strings context
    output.push_str("  strings:\n");
    output.push_str("    - match: '\"'\n");
    output.push_str("      scope: punctuation.definition.string.begin.x\n");
    output.push_str("      push:\n");
    output.push_str("        - meta_scope: string.quoted.double.x\n");
    output.push_str("        - match: '\"'\n");
    output.push_str("          scope: punctuation.definition.string.end.x\n");
    output.push_str("          pop: true\n");
    output.push_str("        - match: '\\\\.'\n");
    output.push_str("          scope: constant.character.escape.x\n");
    output.push_str("    - match: \"'\"\n");
    output.push_str("      scope: punctuation.definition.string.begin.x\n");
    output.push_str("      push:\n");
    output.push_str("        - meta_scope: string.quoted.single.x\n");
    output.push_str("        - match: \"'\"\n");
    output.push_str("          scope: punctuation.definition.string.end.x\n");
    output.push_str("          pop: true\n");
    output.push_str("        - match: '\\\\.'\n");
    output.push_str("          scope: constant.character.escape.x\n");
    output.push_str("    # Multiline strings\n");
    output.push_str("    - match: '\"\"\"'\n");
    output.push_str("      scope: punctuation.definition.string.begin.x\n");
    output.push_str("      push:\n");
    output.push_str("        - meta_scope: string.quoted.triple.x\n");
    output.push_str("        - match: '\"\"\"'\n");
    output.push_str("          scope: punctuation.definition.string.end.x\n");
    output.push_str("          pop: true\n");
    output.push('\n');

    // Numbers context
    output.push_str("  numbers:\n");
    output.push_str("    - match: '\\b[0-9][0-9_]*\\.[0-9][0-9_]*( [eE][+-]?[0-9]+)?\\b'\n");
    output.push_str("      scope: constant.numeric.float.x\n");
    output.push_str("    - match: '\\b0[xX][0-9a-fA-F_]+\\b'\n");
    output.push_str("      scope: constant.numeric.hex.x\n");
    output.push_str("    - match: '\\b0[oO][0-7_]+\\b'\n");
    output.push_str("      scope: constant.numeric.octal.x\n");
    output.push_str("    - match: '\\b0[bB][01_]+\\b'\n");
    output.push_str("      scope: constant.numeric.binary.x\n");
    output.push_str("    - match: '\\b[0-9][0-9_]*\\b'\n");
    output.push_str("      scope: constant.numeric.integer.x\n");
    output.push('\n');

    // Comments context
    output.push_str("  comments:\n");
    output.push_str("    - match: '//.*$'\n");
    output.push_str("      scope: comment.line.double-slash.x\n");
    output.push_str("    - match: '/\\*'\n");
    output.push_str("      scope: punctuation.definition.comment.begin.x\n");
    output.push_str("      push:\n");
    output.push_str("        - meta_scope: comment.block.x\n");
    output.push_str("        - match: '\\*/'\n");
    output.push_str("          scope: punctuation.definition.comment.end.x\n");
    output.push_str("          pop: true\n");
    output.push('\n');

    // Operators context
    output.push_str("  operators:\n");
    if !model.operators.is_empty() {
        let escaped_operators: Vec<String> =
            model.operators.iter().map(|op| regex_escape(op)).collect();
        let operators_pattern = escaped_operators.join("|");
        output.push_str(&format!("    - match: '({})'\n", operators_pattern));
    } else {
        output.push_str("    - match: '(\\+|-|\\*|/|%|\\^|==|!=|<|>|<=|>=|&&|\\|\\||!|&|\\||<<|>>|\\+=|-=|\\*=|/=|=>|->|\\.\\.\\.?|::)'\n");
    }
    output.push_str("      scope: keyword.operator.x\n");
    output.push('\n');

    // Identifiers context
    output.push_str("  identifiers:\n");
    output.push_str("    - match: '\\b[A-Z][a-zA-Z0-9_]*\\b'\n");
    output.push_str("      scope: entity.name.type.x\n");
    output.push_str("    - match: '\\b[a-z_][a-zA-Z0-9_]*\\b'\n");
    output.push_str("      scope: variable.other.x\n");
    output.push('\n');

    // Punctuation context
    output.push_str("  punctuation:\n");
    output.push_str("    - match: '[{}()\\[\\];,.:]'\n");
    output.push_str("      scope: punctuation.x\n");

    output
}

/// Escape special regex characters
fn regex_escape(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '\\' | '.' | '+' | '*' | '?' | '(' | ')' | '[' | ']' | '{' | '}' | '^' | '$' | '|'
            | '/' => {
                result.push('\\');
                result.push(c);
            }
            _ => result.push(c),
        }
    }
    result
}
