[book]
title = "X 编程语言"
authors = ["X 语言团队"]
description = "X 编程语言的官方文档"

[output.html]
default-theme = "navy"
additional-css = ["assets/main.css"]
site-url = "https://x-lang.org/docs"
use-default-footer = true

[output.html.search]
enable = true
limit-results = 20
min-length = 2

[output.html.fold]
enable = true
level = 2